### ISSUE TITLE
How to have two values as a particular default

### ISSUE THREAD

**Issue by adarsh-kr** [facebookresearch/hydra#1016]
In my `config.yaml`, how to pass two datasets for e.g. cifar and cinic at once? Can I pass a multiple config groups to the defaults list? 

This is for the case when I want to train my model on a mix of datasets, but I do not want to create a config group for every possible combination. 
 
```
conf/
├── config.yaml
└── dataset
    ├──  cifar.yaml
    └── imagenet.yaml
    └── cinic.yaml
```

What I tried is as follows: 
```
dataset: 
  - cifar
  - cinic
```
which resulted in following error:

`Could not load train_dataset/['cifar', 'cinic']. Available options 'cifar ... '`

[Stackoverflow Link](https://stackoverflow.com/questions/64071955/passing-multiple-config-groups)

**Comment by omry** [comment]
Currently config groups are mutually exclusive.
Support for this is planned for Hydra 1.1. See #499.

**Comment by omry** [comment]
In the short term, you can try to use the OmegaConf merge API to do it yourself in your own code, but it will probably be a bit uncomfrotable.
