### ISSUE TITLE
Support not configuring Python the logging subsystem

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#1021]
Generic logging configuration  is hard and in some cases it's causing issues.
Currently Hydra always configures the logging subsystem. The idea is to allow disabling the configuration of the logging (as opposed to configuring the logging to be disabled).

**Comment by briankosw** [comment]
Hey @omry, I'd like to give a shot at this feature. Could you assign it to me? I have used Hydra before but I haven't contributed to Hydra yet, so I might need some guidance.

**Comment by shagunsodhani** [comment]
Hey @briankosw Feel free to start working on it. You can join the chat on [Zulip](https://hydra-framework.zulipchat.com/) and ask questions there.
