### ISSUE TITLE
[Feature Request] Access to config_path from user code

### ISSUE THREAD

**Issue by brainopia** [facebookresearch/hydra#1022]
Hello,

I need to get a `config_path` from inside the main method (in case it was overwritten from cli with `--config-path`).

I need it to resume a training from a checkpoint. To achieve this I currently do following:
- start training by pointing to a config path from previous run: `python scripts/train.py --config-path=../outputs/2020-09-28/11-02-22/.hydra`
- parse `--config-path` manually with ArgumentParser (I don't use hydra's `get_args_parser` since it's located in `_internal`).
- then I lookup a checkpoint in `output_dir` directory (e.g. `outputs/2020-09-28/11-02-22`) which I parse from `config_path`.

Initially, I thought the `config_path` would be present in HydraConfig.instance() but currently it's not stored anywhere.

**Comment by omry** [comment]
This seems a bit convoluted. You have the path `outputs/2020-09-28/11-02-22/`, you can pass it as a checkpoint directory to your own app which will just load the checkpoint from it.
You can load the config and replace the one Hydra is providing with something like:
```
$ python train.py resume_training=../outputs/2020-09-28/11-02-22
```

```python
if cfg.resume_training is not None:
  model = create_model_from_last_checkpoint(cfg.resume_training)
  cfg = OmegaConf.load(f"cfg.resume_training/.hydra/config.yaml")
else:
  model = create_new_model()
```

**Comment by brainopia** [comment]
In your example, I can't redefine arguments (e.g. learning rate) in config from output_dir with CLI.

**Comment by omry** [comment]
Take a look at the Compose API and see if it helps you here (The application overrides are in HydraConfig.instance()).

**Comment by brainopia** [comment]
Thank you, it helps.

I need to initialize hydra anew to add/change config_path, right?

```python
   from hydra.core.global_hydra import GlobalHydra
   from hydra.core.hydra_config import HydraConfig
   from hydra.experimental import compose, initialize

   if cfg.checkpoint:
        GlobalHydra.instance().clear()
        with initialize(config_path=checkpoint_dir + "/.hydra"):
            cfg = compose(config_name="config", overrides=HydraConfig.get()["overrides"]["task"])
```

**Comment by omry** [comment]
Ideally you would rely on the initialization from `@hydra.main()`.

One thing that might work to get easy access to the config is to load it and put it into the config store before you call compose.
See the Structured Configs tutorial for some background on the Config Store.

Site note:
```
HydraConfig.get()["overrides"]["task"]
```
can be
```
HydraConfig.get().overrides.task
```

**Comment by brainopia** [comment]
> One thing that might work to get easy access to the config is to load it and put it into the config store before you call compose.

Thank you for the pointer, but I'm not sure if I correctly undestand it.

Is it something like this?
```python
if cfg.checkpoint:
  dict_from_yaml = yaml.safe_load(open(cfg.checkpoint + '.hydra/config.yaml'))
  ConfigStore.instance().store('config', node=dict_from_yaml, package='_global_')
  cfg = compose(config_name="config", overrides=HydraConfig.get().overrides.task)
```

**Comment by omry** [comment]
Something like that.
Yes. You can also use a different name to avoid collisions with the already exist config.

1. Use OmegaConf.load() to load the config file (you are leaking a file object here).
2. no need to specify the package, since your group here is empty. if you store it in a group you will need `_global_`.
3. You can use a different name to avoid name collisions, say : `checkpoint_config`
```python
if cfg.checkpoint:
  checkpoint_cfg = OmegaConf.load(cfg.checkpoint + '.hydra/config.yaml')
  ConfigStore.instance().store('checkpoint_cfg', node=cfg)
  cfg = compose(config_name="checkpoint_cfg", overrides=HydraConfig.get().overrides.task)
```

**Comment by brainopia** [comment]
Yeah, much better. Thank you for your help!

**Comment by omry** [comment]
Thanks for trying out my suggestions, hopefully this will help others.
