### ISSUE TITLE
[Feature Request] [Hydra-Submitit-Launcher] Add support for passing `additional_parameters` as supported by Submititi

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#1036]
# 🚀 Feature Request

When calling [Submitit](https://github.com/facebookincubator/submitit) directly (not the plugin), one can pass an optional dictionary argument called [`additional_parameters`](https://github.com/facebookincubator/submitit/blob/e6fc6b2532a2ea480f08747816f14c53f526ef04/submitit/slurm/slurm.py#L432) to add parameters which are not currently available in submitit.

This argument can not be passed when using the submitit-plugin. Example error:

```
Key 'additional_parameters' not in 'SlurmQueueConf'
        full_key: hydra.launcher.additional_parameters
        reference_type=Optional[SlurmQueueConf]
        object_type=SlurmQueueConf
```

We should add support for passing this `additional_parameters` dict via the plugin aswell.

## Motivation

Same as above.

## Pitch

Add support for the dict in [SlurmQueueConf](https://github.com/facebookresearch/hydra/blob/master/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L31) and pass to submitit.AutoExecutor [here](https://github.com/facebookresearch/hydra/blob/dfbebc34020ad3d4bf1ab061565408740e62eb22/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py#L105)

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md)): Yes

## Additional context

Since this change is quite small, is there any reason it wasnt done in the first iteration of the plugin?

**Comment by omry** [comment]
I don't if there was a reason for leaving it out.
@jrapin?

**Comment by jrapin** [comment]
> I don't know if there was a reason for leaving it out.
> @jrapin?

Only historical reason, it did not exist when the first version was added, and I did not think about adding it later on :s

**Comment by shagunsodhani** [comment]
@omry @jrapin  should we add it now?

**Comment by jrapin** [comment]
> @omry @jrapin should we add it now?

definitely ;)
