### ISSUE TITLE
[Bug] tools/configen/README.md refers to configen.samples.user, but configen.samples.user is not a package

### ISSUE THREAD

**Issue by EspenHa** [facebookresearch/hydra#1045]
Like the title says. Instead of `configen.samples.user` it should refer to `configen.samples.my_module`.
This mistake is also present in `tools/configen/configen/templates/sample_config.yaml`

**Comment by omry** [comment]
Thanks for reporting, do you mind sending a PR to fix it?
You can base it on the actual example application in the project - I think it's covered by tests so it should be good.

By the way, are you planning on using configen? can you share some details on the use case?
keep in mind that it's still under active development and will likely continue to evolve in the near future.

**Comment by EspenHa** [comment]
I will send a PR.

Regarding configen, I am considering using it, but currently just testing it out. I am trying to create a highly configurable ML research application. I was looking at Structured Configs, but I would like to avoid having to "duplicate" a config class for every real class, which is why I started looking at configen.
The goal is to have all of my code to look as "normal" as possible, i.e. not having to carry around a config object through the whole code base, but still be highly configurable. The value of "normal" looking code is that it would be easier for other researchers to understand what is happening, without having to understand the semantics of my config setup.

**Comment by omry** [comment]
Cool. Will the framework be open sourced?
