### ISSUE TITLE
[Feature Request]  Schemas in hydra.main

### ISSUE THREAD

**Issue by tkornuta-nvidia** [facebookresearch/hydra#1048]
# 🚀  Schemas in hydra.main()

Add option to use schema based on a Structured Config to hydra.main decorator.

## Motivation

**Is your feature request related to a problem? Please describe.**

In the current "hydra flow" both yaml files and Structure Configs can be used as both sources of parameters and schemas for parameter/structure validation.

There are some cases when the one person (App Developer) develops the python code, whereas the other uses it and writes his config files (User). In one such a scenario:
 * The App Developer could write his python script and inject the schema/default param values using Structured Config for the whole application. 
 * When the User runs the application by providing his config (--config_name etc.) hydra could then catch all the errors by looking at the Structured Config first.

Code example:

```
@dataclass
class AppConfig:
    """
    This is structured config for this application, providing schema used for validation of user-written config files
    as well as default values of the selected parameters.
    """

   # Required section - with user defined content.
    important_section: Any = MISSING

   # Second Required section - with predefined content.
    predefined_section: SectionConfig = SectionConfig()

    # Name of the file to load. No default.
    restore_from: str = MISSING

    # Name of the file to save to - with default
    export_to: str = "export.chkpt"


# Load experiment specification, additionally using schema for validation/retrieving the default values.
@hydra.main(config_path="conf", config_name="my_app_config.yaml", schema=AppConfig)
def main(cfg: AppConfig) -> None:
```

## Pitch

**Describe alternatives you've considered**

One solution can be found in NVIDIA NeMo:
https://github.com/NVIDIA/NeMo/blob/main-vis-res/nemo/collections/vis/models/qtype.py

The solution is using the overloaded hydra_runner decorator:
https://github.com/NVIDIA/NeMo/blob/0c5573fd9ac4dff4797d1823e7ab36514164291b/nemo/core/config/hydra_runner.py#L26

Which internally registers the provided Structured Config type in the Config Store using the provided "config_name". This However, this solution will probably not work when one will change  config/path using --config_name/ --config_path

**Comment by omry** [comment]
Thanks for the feature request @tkornuta-nvidia.
I suspect recursive defaults would actually offer a good alternative solution.

In this scenario, the user would have to place AppConfig into the config store:
```
cs.store(group="schema", name="app_config", node=AppConfig)
```

And add the schema to the defaults list in the provided config:
user_config.yaml
```yaml
defaults:
  - schema/app_config
  - other: things
```

I am going to re-evaluate the fit once #171 is done.

**Comment by omry** [comment]
I believe the new Recursive Defaults List addresses this use case.

[Here](https://hydra.cc/docs/next/tutorials/structured_config/schema/) is an example of how to validate against a schema provided by someone else.
I recommend that you go over [The Defaults List](https://hydra.cc/docs/next/advanced/defaults_list) and [Extending Configs](https://hydra.cc/docs/next/patterns/extending_configs) as an introduction.
