### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by KamWithK** [facebookresearch/hydra#1051]
# 🐛 Bug
## Description
Can't use variable interpolation when using nested config.

## To reproduce
Create and load the following config:
```yaml
mode: "2d"
defaults:
       - modelling: ${mode}
```
This complains that `str interpolation key 'mode' not found`, even though the following does work fine:
```
       - ${mode}
```

I believe this is because of the `modelling` package, but how do I actually reference that `mode` parameter then?

## Expected Behavior
Should reference the config file "2d" (because it's the value in `mode`)...

## System information
- **Hydra Version** : 1.0.3  
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda
- **Operating system** : WSL running Ubuntu

## Additional context
I've also tried to create a second config file within the modelling directory and then interpolate like this `${defaults.mode}`, but it complains about mode not being an int.
If I then try `${defaults.0.mode}`, it also won't work (can't find it just like for `mode` by itself).

Any help will be greatly appreciated!!!

**Comment by omry** [comment]
Interpolation has very limited support in the defaults list.
Remember that while the defaults list is being processed, the config does not exist.

This is not a bug (and also has nothing at all to do with nested configs).

**Comment by omry** [comment]
Feel free to ask followup questions here or join the Hydra chat.

**Comment by KamWithK** [comment]
Why did the interpolation work previously when there wasn't a `modelling` folder/package then though?

**Comment by KamWithK** [comment]
Is there any alternative way you'd be able to suggest such that I'd be able to load the relevent file easily?
The reason I ask is that in my code I have 2d and 3d modelling config code which is split up into multiple files. When loading them it'd be extremely annoying to have to change 10 lines to/from 2d <-> 3d.

**Comment by KamWithK** [comment]
By the way @omry, I've sent a message into your zulipchat about this. Feel free to replly there instead if that's easier for you.
