### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by CatOfTheCannals** [facebookresearch/hydra#1065]
# 🚀 Feature Request

When using initialize(), I want to be able to pass an absolute path.

## Motivation

I always prefer to avoid hardcode and depending on the script that is calling the initialize method, the relative path will vary. Furthermore, if one moves the script to another location, then the relative path will potentially have to be modified.

## Pitch

Being that the source code of the initialize method explicitly asks for relative path using, I assume there must have been good reasons to set it that way.

However I think that an approach such as the one described in the following link allows for both portability and flexibility in the path definitions:
https://stackoverflow.com/a/25389715

I'm sure there was more to the thought process behind this design so I'll be really glad to understand it!!

**Comment by omry** [comment]
Did you look at the documentation of initialize?
https://hydra.cc/docs/experimental/compose_api#initialization-methods

**Comment by omry** [comment]
By the way, please set a title to your question.
