### ISSUE TITLE
Update Documentation for development and usage of plug-ins

### ISSUE THREAD

**Issue by pafi-code** [facebookresearch/hydra#1068]
# 🚀 Update Documentation for development and usage of plug-ins

It would be really cool if there could be more explanation/tutorial regarding "how to write and use your own hydra plug-in".
It took us some days to figure out that it needs to be an extra namespace package that needs to be installed in the environment that you are also using for your project.
You can somehow get this information by having a look at the source code of the example, but I feel like actual source code is not really a nice form of documentation. In the actual documentation there is only written that there are plug-ins, that you can use them and also develop your own ones, but not really how.

Thanks in advance! :v:

**Comment by omry** [comment]
Thanks, will look into improving the docs for plugin development.
