### ISSUE TITLE
[Bug][Configen] Generating from untyped signatures results in `str` default values without quotes

### ISSUE THREAD

**Issue by romesco** [facebookresearch/hydra#1071]
# 🐛 Bug
## Description
Configen will create fields typed as `Any` if there is no type in the signature, but if there's a default value which is a `str` type, it will not include it in quotes. Here's an example: https://github.com/pytorch/hydra-torch/blob/master/config/torch/optim/lr_scheduler.py#L74

## To reproduce
```
git clone https://github.com/pytorch/hydra-torch/
configen --config-dir=conf
```
Check output `/config/torch/optim/lr_scheduler.py` for example @
https://github.com/pytorch/hydra-torch/blob/master/config/torch/optim/lr_scheduler.py#L74

## System information
- **Hydra/configen Version** : https://github.com/facebookresearch/hydra/tree/1.1_dev_branch
- **Python version** : 3.8.6
- **Virtual environment type and version** : pyenv-virtualenv 1.2.20
- **Operating system** : Ubuntu 18.04

**Comment by omry** [comment]
PR Welcome :)
