### ISSUE TITLE
[Bug] Cannot use overrides containing '@' character

### ISSUE THREAD

**Issue by pringshia** [facebookresearch/hydra#1074]
# 🐛 Bug
## Description
I am unable to override a value that contains the '@' character, e.g. in the case of providing email addresses

## To reproduce

Borrowed from #962:

** Minimal Code/Config snippet to reproduce **

```
# test.py

import hydra

@hydra.main()
def foo(*args, **kargs):
    pass

foo()
```

```
$ python test.py +bar=example@example.com
```

** Stack trace/error message **

```
LexerNoViableAltException: +bar=example@example.com
                                       ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior

No error and bar's value should be set to "example@example.com".

## System information
- **Hydra Version** :  1.0.0
- **Python version** : 3.7.4
- **Virtual environment type and version** :
- **Operating system** : 

## Additional context

Similar to #962

**Comment by omry** [comment]
This should be doable, but as a temporary solution you can quote the value for Hydra.
Since the shell will interpret your quotes, you need to quote for it as well.

```
$ python test.py '+bar="example@example.com"'
```
