### ISSUE TITLE
[question] How to select a whole config group by a parameter in other group?

### ISSUE THREAD

**Issue by czrcbl** [facebookresearch/hydra#1079]
Hi, I am working in a project with configs in the following layout:

```
config/
    config.yaml
    model/
        model1.yaml
        model2.yaml
    dataset/
        dataset1.yaml
        dataset2
    experiment/
        exp1.yaml
        exp2.yaml
```

Each experiment will define a specific set of parameters including a specific dataset and a specific model.
I would like to call `python train.py experiment=exp2` and automatically select the specified dataset and model and load their params. Is there a way of doing that? In the documentation it has Specializing configuration, but it  only shows how to change a parameters instead of the whole config group.

If it is not possible, what would be the recommended alternative workflow?

**Comment by omry** [comment]
Hi, thanks for the question.
Recursive defaults list (#171) will be the solution for this and many other related problems.
This is not supported in Hydra 1.0 but is coming in 1.1 (Under active development in #1044).

In 1.0, you can only define the defaults list in your primary config.
Your alternatives are for now:
1. Use command line overrides to override the config group.
2. Use --config-name to override the primary config to one that has the defaults list you want.

There could be other alternatives I am not thinking of right now.
