### ISSUE TITLE
[Feature Request] Python Config

### ISSUE THREAD

**Issue by ferrine** [facebookresearch/hydra#1086]
# 🚀 Feature Request

A new feature in analog to `hydra.utils.instantiate` that reads a python file and returns objects created inside.

## Motivation

Writing configs in yaml is great and I really love the way it is done with the `instantiate` feature. But in most cases, I get frustrated when I try to write some more complicated things and experimenting with architectures, data pipelines. 

### A use case
For example, you may want to write tweaks in your neural network. These tweaks are just drafts and it is not practical to put the code into any library, just too much effort compared to the hypothesis tested.

## Pitch

**Describe the solution you'd like**
I have designed a solution for my daily use and is now something like

### Researcher API
```
cfg/arch
cfg/arch/resnet1.yaml
cfg/arch/resnet2.yaml

pycfg/arch
pycfg/arch/resnet1.py
pycfg/arch/resnet2.py
```

I store python files in the same way as config. In the `cfg/arch/resnet1.yaml` file I write

```
# @package group
_py_: arch/resnet1.py
layers: 10
blocks: 4
```
In the `py` file `pycfg/arch/resnet1.py` I have

```python
class Resnet:
    ... # implementation

def __load__(layers, blocks):
    return Resnet(layers=layers, blocks=blocks)
``` 

In experiment code I write:

```
net = hydrapy.instantiate(cfg.arch.resnet1)
```
Under the hood, it 
1. creates a module in 
```
~/.cache/hydrapy/_hydrapy/resnet1_6c6d16f65dca5c454aab19d03fba1b02.py
```
so that the content becomes picklable.
2. imports a new module and fetches `__load__` function. 
3. Executes, `__load__` with user-provided arguments (similar to `instantiate`), and returns the result to the user.

So finally, the result of `net = hydrapy.instantiate(cfg.arch.resnet1)` will be `Resnet(layers=10, blocks=4)`

**Describe alternatives you've considered**
I've iterated over a couple of alternatives to cure my pain in fast iteration over python files. 

* I've tried to force me and collaborators to write code into the repository (so that `_target_` can be used). But the repo is well maintained and the test suit is heavy. It became a high bar to directly contribute to test a tiny idea.
* I've also tried to mess with architectures inside the `train.py`, but only once and it was a mess.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes, why not. I know that the current state of this feature request is raw and requires discussion. In meanwhile I have this extension working in the private repo that I can't really share. So far this is not urgent as it is suited well for our small team, but if this feature gets enough attention and interest I can contribute.

** Another way to contribute**
An alternative way to contribute would be to create a python library with a single purpose, "import me a file as robust as possible". Later on, we continue on the feature request so you'll get a new dependency once it sustains. I think that will be the best way to do that so even more people can enjoy importing files or spot some problems that I missed.

## Additional context
Picking was really hard to achieve. I spent 2 weeks testing and trying a lot of things. For a month my implementation was not really picklable. But it was fine, most cases we used it for, assumed that we use library classes and there was no trouble.

In the proposed feature request, the content of the file is picklable. Any class created inside can survive under `ddp_spawn`.

**Comment by omry** [comment]
> A new feature in analog to hydra.utils.instantiate that reads a python file and returns objects created inside.

Any particular reason why you can't create a one-off class or function and use it as the `_target_`?

Here are some additional points worth mentioning:

1. Structured Configs can already allow you to define configs in code and use it in Hydra transparently. 
You can define your Structured Configs dynamically, register them in a config group and use them to instantiate the object normally.
Refer to the Structured Configs tutorial.

2. Another thing that can be interesting to you is the upcoming support for recursive instantiation (see [this](https://hydra.cc/docs/next/patterns/instantiate_objects/overview)).

3. Finally, take note of [configen](https://github.com/facebookresearch/hydra/tree/master/tools/configen) which is an experimental tool to generate the Structured Configs from code. It will initially be used to generate [PyTorch configs](https://github.com/pytorch/hydra-torch).

Generally, there is nothing wrong with you experimenting with your own instantiation strategies.
I think the points above will make the core offering from Hydra much more attractive in the long term.
At this point I am not convinced that the approach you are proposing lines up well with all the work that have went and still going into this area.

I am closing this for now, but please feel free to continue discussing here.
