### ISSUE TITLE
[Bug] Recursive default list + Package overrides

### ISSUE THREAD

**Issue by ppwwyyxx** [facebookresearch/hydra#1102]
# 🐛 Bug
## Description
Recursive default List + Package overrides not working. A continuation of https://github.com/facebookresearch/hydra/issues/171#issuecomment-719106222

## To reproduce

Configs:
```
# model/maskrcnn.yaml:
# @package _group_
a: 1
b: 2

# model/maskrcnn2.yaml:
# @package _group_
b: 3
c: 4

defaults:
  - model/maskrcnn   # ??
  - _self_

# main.yaml:
defaults:
  - model@model.submodule: maskrcnn2
```
Code:
```
@hydra.main(config_name="main")
def my_app(cfg: DictConfig) -> None:
    print(cfg)

if __name__ == "__main__":
    my_app()
```

It gives me:
```
{'model': {'a': 1, 'b': 2, 'submodule': {'b': 3, 'c': 4}}}
```

## Expected Behavior
I expect to get an equivalent of
```
model:
  submodule:
    a: 1
    b: 3
    c: 4
```

## System information
- **Hydra Version** :  master
- **Python version** :  3.8.6

**Comment by omry** [comment]
Thanks, something is off here, will take a look.

**Comment by omry** [comment]
This is a design issue with the current implementation.
I started to think about a design that switches addressing to be relative.
this is a very big change in how the recursive defaults will work.
Please check the design doc [here](https://docs.google.com/document/d/15z3IPmTOS4E6Xxv8RUFExuXi1WXjQs0DqF-39dnN_kc/edit#heading=h.janzbxaxlbff) and provide feedback.
