### ISSUE TITLE
group config delete gets IndexError:list index out of range

### ISSUE THREAD

**Issue by Hussni-V** [facebookresearch/hydra#1107]
Hello,

I have the following file structure 
```
├── conf
│   └── models
│         ├── faster.yaml
│   └── datasets
│         ├── coco.yaml
│   └── runtimes
│         ├── default.yaml
│└── config.yaml
└── main.py
```
config.yaml has defaults as such 
```
defaults:
    - models: faster
    - datasets: coco
    - runtimes: default
```
each .yaml file except config.yaml has the `# @package _group_` header and some other stuff
my main.py is 
```
@hydra.main(config_path = 'conf', config_name ="config")
def main(cfg:DictConfig) -> None:
    cfg = do_stuff(cfg)
    print('done')
```
I'm trying to delete some defaults through the command line however I came across a strange problem

if I run `python main.py ~runtimes ~models` it works fine
but if I run `python main.py ~models ~runtimes`
I get the following error

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/utils.py", line 350, in <lambda>
    overrides=args.overrides,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 104, in run
    run_mode=RunMode.RUN,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/hydra.py", line 512, in compose_config
    from_shell=from_shell,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 252, in _load_configuration
    ConfigLoaderImpl._apply_overrides_to_defaults(config_group_overrides, defaults)
  File "/opt/conda/lib/python3.6/site-packages/hydra/_internal/config_loader_impl.py", line 413, in _apply_overrides_to_defaults
    if value is not None and value != defaults[pair.idx].config_name:
IndexError: list index out of range

any help is appreciated

**Comment by omry** [comment]
This looks like a bug in 1.0.
Since this is an edge case, I would suggest that you just wait for 1.1, which will have a total rewrite of the config composition logic - including deletions.

**Comment by omry** [comment]
It would be great if you can try your use case on master. While the defaults list logic is still under development, it's already went through some massive changes and it's very likely that this is no longer a problem there.

(Even if it's the case, I suggest that you do not depend on master for anything serious, but it would be good to know).

**Comment by omry** [comment]
@Hussni-V , I am likely completely remove support for deletion from the defaults list as it becomes extremely complicated once recursive defaults are introduced.

Can you share some information about your use case for this feature?

**Comment by Hussni-V** [comment]
My use case is to create model configs in a modular manner and sometimes some config modules require the deletion of the defaults. However, I have made a workaround where the default would just point to a 'None' config and I can just ignore the part using logic.

**Comment by omry** [comment]
To clarify, you mean you have null in the defaults list or in the config itself?

**Comment by Hussni-V** [comment]
In the config itself.
If I don't want to use default I would do something

` python main.py models=none +custom=new_stuff`

none.yaml
```
# @package _group_
model: 'None'
method: 'None'
norm_cfg: 'None'
```

**Comment by omry** [comment]
I see.

fyi: you can use null in yaml to get Python None.
```yaml
foo: null
```
would become:
`{"foo": None}` once parsed.

**Comment by Hussni-V** [comment]
Noted, Thanks
