### ISSUE TITLE
[Feature Request] [non verbose launcher config]

### ISSUE THREAD

**Issue by emilemathieu** [facebookresearch/hydra#1113]
# 🚀 Feature Request 🚀

Hi all, thanks a lot for your great package!

I have different config files for different launchers, that I load through `defaults:` in `conf.yaml`. The issue being that when I select `hydra/launcher=submitit_local` I get the following error `Key 'partition' not in 'LocalQueueConf'` since the `partition` argument is set in my `submitit_slurm.yaml`.
One way to fix this is by only loading the proper config `submitit_local.yaml` with `hydra/launcher=submitit_local launcher=submitit_local`. Yet this is obviously verbose. Would there be another way to manage these situations? Ideally I would specify in the configs `launcher/submitit_*.yaml`  the launcher with `defaults: -hydra/launcher=submitit_*` but that's not possible I believe.

Cheers,
Emile

**Comment by jieru-hu** [comment]
Hi @emilemathieu,

I believe recursive defaults is the answer to this :) here is the master issue https://github.com/facebookresearch/hydra/issues/171
here is the latest design doc https://docs.google.com/document/d/15z3IPmTOS4E6Xxv8RUFExuXi1WXjQs0DqF-39dnN_kc/edit#heading=h.lbmvds7wtf23

this is planning for Hydra 1.1, the next major release.

**Comment by omry** [comment]
Yup, I think recursive defaults would offer a great solution for this.
Closing for now.
