### ISSUE TITLE
Struct Config with optional field.

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#1120]
I'm working with a API that expect a dict of extra args for config (boto3's `create_launch_template(**kwargs)`)
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_launch_template

I'm trying to figure out how to best create a struct config for the function's arguments.
for example I may have something like the following
```
@dataclass
class RayNodeConf:
    """
    Refer to boto3 doc for more information on each field
    https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html
    """
    InstanceType: str = "m5.large",
    ImageId: str = "ami-008d8ed4bd7dc2485",
    SubnetId: Optional[str] = None,
    SecurityGroupIds: Optional[str] = None,
```
But in my `config.yaml`
I only want to include the configs for `ImageId`  and `InstanceType`, since most of the times user don't really need to worry about what to pass in for `SubnetId` and `SecurityGroupIds`

as a result I will get a DictConfig of 
```
worker_nodes:
  InstanceType: m5.large
  ImageId: ami-008d8ed4bd7dc2485
  SubnetId: null
  SecurityGroupIds: null
  IamInstanceProfile: null
```

I cannot pass this in to the boto3 API (with the `null` value). I also tried to overwrite the Conf object but that doesn't work either (which makes sense cause it violates the StructConfig syntax)
```
    with read_write(cluster_cfg):
        cluster_cfg.head_node = {k for k in cluster_cfg.head_node if k[1]}
 ```
error 
```
omegaconf.errors.ValidationError: Invalid type assigned : set is not a subclass of RayNodeConf. value: {('InstanceType', 'm5.large'), ('ImageId', 'ami-008d8ed4bd7dc2485')}
        full_key: hydra.launcher.ray_cluster_cfg.head_node
        reference_type=RayClusterConf
        object_type=RayClusterConf
```

Would it be possible to have a config object that only contains fields that's not `null` instead of having certain fields as `foo=null`?

**Comment by omry** [comment]
The error is saying you are using a Python set.
are you sure you intended to do that and not use a dictionary?

**Comment by jieru-hu** [comment]
Sorry I pasted the wrong trial

```
    with read_write(cluster_cfg):
        cluster_cfg.setup_commands = setup_commands
        cluster_cfg.head_node = OmegaConf.create({k:v for k, v in cluster_cfg.head_node.items() if v})
```

error
```
omegaconf.errors.ValidationError: Invalid type assigned : dict is not a subclass of RayNodeConf. value: {'InstanceType': 'm5.large', 'ImageId': 'ami-008d8ed4bd7dc2485'}
        full_key: hydra.launcher.ray_cluster_cfg.head_node
        reference_type=RayClusterConf
        object_type=RayClusterConf

```

**Comment by omry** [comment]
Can you use Hydra compose API instead of using OmegaConf directly?

**Comment by omry** [comment]
It will be easier if you explain what you are trying to do face to face.

**Comment by jieru-hu** [comment]
> It will be easier if you explain what you are trying to do face to face.

sounds good, i was gonna suggest the same thing :)

**Comment by omry** [comment]
Is this still relevant?

**Comment by jieru-hu** [comment]
I think we got this resolved. closing
