### ISSUE TITLE
[Feature Request] [Submitit] [array_parallelism]

### ISSUE THREAD

**Issue by emilemathieu** [facebookresearch/hydra#1135]
# 🚀 Feature Request

Hi all!

Would there be a way to limit the number of map tasks that can be executed in parallel?

In `submitit` one can use the parameter `slurm_array_parallelism` as in the[ job array example](https://github.com/facebookincubator/submitit/blob/master/docs/examples.md#job-arrays).
Passing `additional_parameters: {"array_parallelism": 2}` does not work since it's not a `slurm` argument.

Cheers,
Emile

**Comment by omry** [comment]
This sounds like a nice addition, want to try to put out a pull request?

**Comment by emilemathieu** [comment]
Would the idea to add in [SlurmQueueConf](https://github.com/facebookresearch/hydra/blob/master/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L31) a [parameter `array_parallelism: int = 256`](https://github.com/facebookincubator/submitit/blob/master/submitit/slurm/slurm.py#L410)?

**Comment by jieru-hu** [comment]
> Would the idea to add in [SlurmQueueConf](https://github.com/facebookresearch/hydra/blob/master/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L31) a [parameter `array_parallelism: int = 256`](https://github.com/facebookincubator/submitit/blob/master/submitit/slurm/slurm.py#L410)?

Yes, looks like a good place to add the config :)

**Comment by shagunsodhani** [comment]
Closed via https://github.com/facebookresearch/hydra/pull/1137
