### ISSUE TITLE
[Feature Request] [skip existing config]

### ISSUE THREAD

**Issue by emilemathieu** [facebookresearch/hydra#1136]
# 🚀 Feature Request

Hi all!

I am interesting in avoiding to run experiments that have already been ran, i.e. similar `.hydra/config.yaml`.

The slightly dirty way I've been doing so far is by overriding the output directory name with `dir: ./experiments/${hydra.job.override_dirname}` and then at the beginning of my python script I check whether the same folder exists (and that training as been successful): `os.path.isfile(os.path.join(os.getcwd(), "successful.txt"))`.

Would there be a supported way to achieve this? :)

Cheers,
Emile

**Comment by jieru-hu** [comment]
thx for the feature request!  As far as I know, Hydra doesn't have support this so your solution probably makes the most sense at the moment. I think this is a low pri item for us for now.   

cc @omry

**Comment by omry** [comment]
Thanks for the suggestion.
This seems like something like this can be implemented in the basic sweeper but it also looks like it opens up many many questions as to how this will work.
I don't think it's worth the added complexity, so I am closing this.
If this is very important for you, you could try to implement your own sweeper plugin similar to the basic built in sweeper to see if you can get something reasonable.

Closing. feel free to continue discussing here.
