### ISSUE TITLE
[Feature Request] Log configuration in distributed processes

### ISSUE THREAD

**Issue by briankosw** [facebookresearch/hydra#1148]
# 🚀 Feature Request

Automatically configure the logging in spawned subprocesses.

## Motivation

**Is your feature request related to a problem? Please describe.**

As discussed in #1126 and #1004, the logging is not configured by Hydra in certain subprocesses that are created. I believe this happens because of lower-level implementation differences and its implications:
- Logging is "Hydra-configured" when subprocesses are created by `multiprocessing.fork`
  - `fork` copies over the parent's program state to the child process, so it makes sense that the logging configuration is identical.
- Logging is not "Hydra-configured" when subprocesses are created by `multiprocessing.spawn` or `torch.multiprocessing.spawn`
  - `spawn` creates a fresh Python interpreter process, so it makes sense that Hydra's logging configuration didn't copy over.

The solution proposed in #1126 was to create a helper function `get_logger` that loads the Hydra configuration and setups the logger manually, but this is obviously extra mental overhead.

## Pitch

**Describe the solution you'd like**

I really only see what solution, but I'd love to hear other people's suggestions. Since the subprocess-creating process cannot be overloaded by Hydra, I think the only way to automatically configure logging in any process is to configure the logging when `import hydra` is called.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by omry** [comment]
I don't see how configuring the logging during import is a solution:
The logging configuration is determined by the user based on the parameters to `@hydra.main()` and the user config files.

**Comment by briankosw** [comment]
If the logging is to be configured automatically in the sub-process that was created by spawn, I think it should be configured during import by including some conditional logic in `__init__.py`. The logging configuration is setup initially by the user setting some parameters and running `@hydra.main()`, and then the logging can be configured in each subprocess the user creates by loading up the previous set configuration.

**Comment by omry** [comment]
This sounds very hacky.
Also, Hydra sweepers may override the logging configuraiton.

I think the user will need to serialize the required state. logging is not the only thing that is not being initialized magically in spawned subprocesses.
There should probably be a cleaner API to obtain and restore the state though.

**Comment by briankosw** [comment]
I think you're right that the user probably needs to serialize the state of Hydra and pass it in as an argument for the subprocesses. Would it be good enough to create a method that takes in Hydra's state and restores that in the new subprocess?

**Comment by omry** [comment]
Try something along these lines
```
# on parent process
state = Singleton.get_state()

# serialize state to child process somehow (cloudpickle?).

# on child process
Singleton.set_state(state)

# use the configure_log() function in Hydra to configure the logging based the logging config in the HydraConfig singleton.

```

**Comment by alexeib** [comment]
+1 on this, would be great if we can get logging working well with DDP (very common usecase in fairseq and prob other frameworkds)

**Comment by omry** [comment]
The feature request is to "Automatically configure the logging in spawned subprocesses".
I don't think doing it automatically is possible so I am closing this feature request.

#1005 shows how to do it with a simple process pool (this may now work in Pytorch if it's spawning a new process).

Happy to look at this if someone produces a minimal example using DDP with Hydra that suffers from logging issues.
It should be minimal (a file or two, see the example in #1005 for a good minimal repro).
If you can produce it, please file a new issue.
