### ISSUE TITLE
[Feature Request] Clear output directory if it already exists

### ISSUE THREAD

**Issue by obust** [facebookresearch/hydra#1149]
# 🚀 Feature Request
Ability to clear the output directory if it already exists.

## Motivation

When I have 2 consecutive runs with the same output directory. The first one creates the directory and stdout file. The second run just adds to the artifacts (in particular, the stdout file is appended).
This means that the artifacts from the 1st and 2nd run are mixed in the same output directory.

## Pitch

I would like a hydra option to clear the output directory if it already exists.

**Comment by jieru-hu** [comment]
Thanks for your issue.

I'm not sure if Hydra core should be in the business of managing the logs in this case. But it sounds like this is something you can implement for your application.

We can better help you if you can provide a minimal repro here. 

cc @omry this sounds like a good use case for custom callback? :)

**Comment by omry** [comment]
This is actually intentional, there are use cases like resuming training where you want to read artifacts from the previous run.
If your problem is that the logging is appended, I think you can configure it to not do it.

Try this:
```
# run app twice:
~/dev/hydra$ python examples/tutorials/basic/running_your_hydra_app/4_logging/my_app.py hydra.run.dir=fixed 
[2020-11-17 15:25:43,078][__main__][INFO] - Info level message
~/dev/hydra$ python examples/tutorials/basic/running_your_hydra_app/4_logging/my_app.py hydra.run.dir=fixed 
[2020-11-17 15:25:44,020][__main__][INFO] - Info level message

# observe log is appended:
~/dev/hydra$ cat fixed/my_app.log 
[2020-11-17 15:25:43,078][__main__][INFO] - Info level message
[2020-11-17 15:25:44,020][__main__][INFO] - Info level message

# override file appender mode to w, run twice:
~/dev/hydra$ python examples/tutorials/basic/running_your_hydra_app/4_logging/my_app.py hydra.run.dir=fixed +hydra.job_logging.handlers.file.mode=w
2020-11-17 15:25:53,621][__main__][INFO] - Info level message
~/dev/hydra$ python examples/tutorials/basic/running_your_hydra_app/4_logging/my_app.py hydra.run.dir=fixed +hydra.job_logging.handlers.file.mode=w
[2020-11-17 15:25:55,629][__main__][INFO] - Info level message

# observe that log file is not appended.
omry@Coronadev:~/dev/hydra$ cat fixed/my_app.log 
[2020-11-17 15:25:55,629][__main__][INFO] - Info level message
```
And observe that the output log is not being appended after a second run.

Note that the + is needed because the default logging config does not specify the mode so it needed to be forced in.
