### ISSUE TITLE
How to change value of placeholder

### ISSUE THREAD

**Issue by Podidiving** [facebookresearch/hydra#1167]
Hi! I've started using hydra recently, and faced a problem. 
In my `config.yaml` I have a placeholder for `size` variable
```
size: &size 10  

key:
  x: *size
```
Suppose, I have next script:
```
import hydra
from omegaconf import DictConfig, OmegaConf

@hydra.main(config_name="config")
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```
When I run script with the following command `python3 test.py size=224` I expect to have `cfg["key"]["x"] == 224`, but it is equal to `10`. 
How should I deal with this problem?

**Comment by jieru-hu** [comment]
Instead of screenshot, could you paste the code instead? This will be easier for us to reproduce. thanks.

**Comment by Podidiving** [comment]
Good point, sorry

**Comment by jieru-hu** [comment]
Pls read omegaconf's wiki on this
https://omegaconf.readthedocs.io/en/latest/usage.html#config-node-interpolation

in your case, config.yaml would look like
```
size: 10

key:
  x: ${size}
```


```
import hydra
from omegaconf import DictConfig, OmegaConf

@hydra.main(config_name="config")
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg, resolve=True))

if __name__ == "__main__":
    my_app()
```

```
$ python myapp.py size=42
size: 42
key:
  x: 42
```

**Comment by Podidiving** [comment]
Yes, thank you, this works just fine. But still: is there any chance to make this work without changing the syntactic of `.yaml` file? I use this config in other scripts, and they will fall if I change it

**Comment by jieru-hu** [comment]
I think it is recommended not to use yaml anchors with Omegaconf: see this issue https://github.com/omry/omegaconf/issues/38

cc @omry in case that has changed.

**Comment by Podidiving** [comment]
Ok, got it
Thank you!

**Comment by omry** [comment]
All yaml implementation are resolving the anchors on load time.
The composition of the config object is obviously done after load time. at that time it's impossible to tell that size and x.size are linked.
It gets even worse, for example you may want to link two things that are in different config files. Standard YAML just can't deal with it.

Use OmegaConf  interpolations as @jieru-hu  suggested, this is why they exist.
