### ISSUE TITLE
[Feature Request] Extend list of supported primitives (like DateTime)

### ISSUE THREAD

**Issue by sxooler** [facebookresearch/hydra#1175]
# 🚀 Feature Request

I would like to use other data types in structured configs or in validating schema. These primitive types (`int`, `bool`, `float`, `str`, `Enums`) are supported and I would like to add `datetime` (or even also custom types). 

## Motivation

I am thinking about switching to Hydra. I love the features, especially structured configs is the one I would really like to use and would be very helpful for my ML tasks, but I'm coming from "Click world" where it's possible to define almost any type including custom ones with following validation (and it's clear that Hydra and Click are not supposed to work together - https://github.com/facebookresearch/hydra/issues/409). I do not expect the same set of feature, those are different projects with different purpose, but support of something primitive like `datetime` seems reasonable to me to have it here.

## Pitch

I would prefer to enable `datetime` in config definitions (`dataclasses`) so it would be able to work with following example:
```python
import hydra
from omegaconf import OmegaConf, MISSING
from hydra.core.config_store import ConfigStore
from dataclasses import dataclass

@dataclass
class Config:
    date_str: str = MISSING
    date: datetime = MISSING

cs = ConfigStore.instance()
cs.store(name="config", node=Config)

@hydra.main(config_name="config")
def my_app(cfg: Config) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```

This example is only for structured configs but could work in a same way for validating schemas.

I would also prefer to be able to parse datetime directly from YAML config without necessity to define custom dataclass and ConfigStore, but it seems this will not be supported (https://github.com/omry/omegaconf/issues/446). Thus, I would be really happy to have this functionality with dataclass validation.

Other option would be to use custom parser for Config (in my example), so dates would be loaded as strings and there would be some additional definition of parses (not sure where), but this does not sound much straightforward as Config class would suggest `str` type but it would be finally converted to another type `datetime`.

Thank you for your great work! I would like to hear your opinions or whether you have already some option how to deal with this types of data types handling.

**Comment by omry** [comment]
Hi again, @sxooler.
Dataclass validation is [coming from OmegaConf](https://omegaconf.readthedocs.io/en/latest/structured_config.html), not from Hydra.
As I said (I may have not been clear) - OmegaConf is the place to discuss this feature - not Hydra.

This is the wrong place to ask for this. I don't mind keeping https://github.com/omry/omegaconf/issues/446 as a wish-list enhancement request but it will be a while. There are much higher priorities and as I said the surface area of additional types is high. In addition this does not seem like a much requested feature (You are the first one to ask for it).
