### ISSUE TITLE
[Proposal] Separate news directory for each plugin

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#1177]
**Context**: This is a follow up to the offline conversation with Omry.

**Proposal**: Plugins are released independent of Hydra. It will be helpful to have a separate news directory for each plugin.

Each plugin will have a towncrier config, one new dependency (towncrier) and new `news` directory. Documentation will be updated to reflect these changes.

**Questions**: Do we have to move the old new entries to the new directories?

**Comment by shagunsodhani** [comment]
cc @omry @jieru-hu

**Comment by omry** [comment]
news entries are deleted after every release (when the changelog is created in Hydra). do you wouldn't find many.
There there are news entries for unreleased plugin changes they can be moved.

**Comment by shagunsodhani** [comment]
I thought some more and probably adding `towncrier` to each plugin is not a good idea. The plugin developer is anyways expected to have installed hydra.

**Comment by omry** [comment]
For the plugins developed in Hydra, I think we can use the towncrier from Hydra.
Plugins developed in other repos can do whatever they want.
