### ISSUE TITLE
[documentation] better configen example

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#1189]
A working demonstration of configen actually resides in here
`https://github.com/facebookresearch/hydra/tree/master/tools/configen/configen/samples`

and the examples here is the output of configen https://github.com/facebookresearch/hydra/tree/master/tools/configen/example

I found it a bit confusing when reading the documentation, at first I went straight ahead to `examples` to try out `configen` from the commandline (which is how other examples in Hydra works.)

Suggested we move `/configen/configen/samples` to examples or have a similar examples for users to try out configen, and also update the README to reflect the change.

**Comment by jieru-hu** [comment]
cc @omry 
Happy to do the changes but wanted to see what you think

**Comment by omry** [comment]
modules used to generate configs should be installed.
I thought it was easier to include a few simple things with configen.
also because it enables out-of-the box configs that works with configen as a demo once it's installed.

If you want to try to make the example more self contained, go for it.
