### ISSUE TITLE
[Feature Request] let instantiate() not deepcopy the values

### ISSUE THREAD

**Issue by ppwwyyxx** [facebookresearch/hydra#1199]
# 🚀 Feature Request

Now `hydra.utils.instantiate()` requires all values to be deepcopy-able. This is not friendly to configs that contains arbitrary objects.

## Motivation

```python
from torch import nn
from omegaconf import OmegaConf
from hydra.utils import instantiate

class A():
    def __init__(self, p):
        self.p = p

class M(nn.Module):
    def __init__(self):
        super().__init__()
        self.m = nn.Linear(10,10)

model = M()

cfg = OmegaConf.create({
        "_target_": "__main__.A",
        "p": model.parameters()
    }, flags={"allow_objects": True})
print(instantiate(cfg))
```
prints:
```
omegaconf.errors.ConfigTypeError: cannot pickle 'generator' object
        full_key: _target_
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```
It cannot pickle the value of "cfg.p" (although the error message is misleading on that).

`instantiate(cfg, p=model.parameters())` also fails (although just putting `p` in `cfg` as it's a much simpler interface)

An alternative to deepcopy can be to recursively copy all the structures (DictConfig/ListConfig) but not the leaf values.

**Comment by omry** [comment]
I merged a fix in OmegaConf, please install it from master and try.
Let me know if you hit anything else.

**Comment by ppwwyyxx** [comment]
Thanks for the quick fix! the issue is resolved

**Comment by omry** [comment]
Awesome.
