### ISSUE TITLE
[Optuna-Plugin] Add support for Python 3.9

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#1204]
Python 3.9 support depends on https://github.com/optuna/optuna/issues/2034

Related to #1062

**Comment by crcrpar** [comment]
Hi @shagunsodhani Optuna itself is installable on Python3.9. ref: https://github.com/optuna/optuna/pull/1908

**Comment by shagunsodhani** [comment]
You are right! thank you for the note. I have enabled the support again and will close this when #1197 lands.

**Comment by shagunsodhani** [comment]
Closed in https://github.com/facebookresearch/hydra/pull/1197
