### ISSUE TITLE
[Feature Request] Import config from another config

### ISSUE THREAD

**Issue by yartem** [facebookresearch/hydra#1214]
# 🚀 Feature Request

Hi!
First of all, thanks for such a simple yet functional instrument! :heart: At my work, I am doing MLOps, where I need to run multiple codebases in different environments (docker images) with different parameters (say, version of code and model), and I find hydra to fit this use-case very easily! 

But one feature I really lack: the possibility to share a common configuration via importing a config file in other config files. This common config file can contain a similar tree structure that can be used in other configs, for example:
```
├── conf
│   ├── constants.yaml
│   └── train
│       ├── mode.yaml
│       └── postgresql.yaml
└── my_app.py
```

```
conf/constants.yaml
--
# @package _global_
const:
  images: 
    simple_ubuntu: ubuntu:latest
    torch_with_some_perks: pytorch/pytorch
  ...
# (free format)
```

```
conf/model/object_detection.yaml
--
# @package _group_
# @import ../constants.yaml
name: object_detection
image: ${const.images.torch_with_some_perks}  # use the `const` tree
...
```

```
conf/model/object_classification.yaml
--
# @package _group_
# @import ../constants.yaml
name: object_detection
image: ${const.images.simple_ubuntu}
...
```

Now, I need to hack (wrap with my own code) `@hydra.main` to achieve this. 
1. Can this already be supported natively Hydra?
2. If not, is this feature liveable? if so, I'd be happy to work on it.

**Comment by jieru-hu** [comment]
Hi @yartem ! 

it seems like recursive defaults ([WIP PR here](https://github.com/facebookresearch/hydra/pull/1170), [Design Doc here](https://docs.google.com/document/d/1k3dgaWkH_7wLx6gI84GSkoi8rocJ6NRhaVok7Zr_62k/edit#heading=h.lbmvds7wtf23)) is what are you asking for.

The feature is planned for Hydra 1.1
Please feel free to check out the PR and try it (I believe it's ready for dogfooding now :) )

**Comment by omry** [comment]
Yup, I believe the use case you are after is covered well by the new recursive defaults.
It's getting ready to hit master, but as Jieru said it's in good enough shape for you to play with it from #1170).

I am going to close this, but feel free to continue the discussion here.

**Comment by omry** [comment]
By the way, I am always happy to see new use cases for Hydra! thanks for sharing!
