### ISSUE TITLE
[Optuna-Plugin] Enable testing on windows

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#1218]
Running test on windows + 3.7/3.8 throws the warning ```DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working on windows + Python 3.7 and 3.8```. The tests are run with `pytest -Werror tests` and ignoring warnings via pytest still cause the error.

Relevant CI run:

https://app.circleci.com/pipelines/github/facebookresearch/hydra/5418/workflows/52f8552a-3e49-4909-b2a5-8a2d4cb99bed/jobs/39570

**Comment by omry** [comment]
Please add more context to help understand the problem (while you still remember it).

**Comment by omry** [comment]
Closing based on your merged PR.
