### ISSUE TITLE
[Bug] Submitit Handling of ListConfigs

### ISSUE THREAD

**Issue by jgbos** [facebookresearch/hydra#1227]
# 🐛 Bug
## Description

I'm currently using your master branch (love the direction this is going) and have found a bug that may exist for your released version as well.  If I add the following parameter to my `SlurmLauncher` config:

```yaml
setup:
  - export MASTER_ADDR=$(hostname -s)
  - export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
```

I get the following error:

```
Traceback (most recent call last):
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/hydra/_internal/utils.py", line 196, in run_and_report
    return func()
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/hydra/_internal/utils.py", line 356, in <lambda>
    overrides=args.overrides,
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 137, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 154, in sweep
    results = self.launcher.launch(batch, initial_job_idx=initial_job_idx)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 122, in launch
    executor.update_parameters(**params)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/submitit/core/core.py", line 638, in update_parameters
    self._internal_update_parameters(**kwargs)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/submitit/auto/auto.py", line 197, in _internal_update_parameters
    self._executor._internal_update_parameters(**parameters)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/submitit/slurm/slurm.py", line 307, in _internal_update_parameters
    _make_sbatch_string(command="nothing to do", folder=self.folder, **kwargs)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/submitit/slurm/slurm.py", line 490, in _make_sbatch_string
    lines += ["", "# setup"] + setup
TypeError: can only concatenate list (not "ListConfig") to list
```

I tried adding `_convert_: all` to the config, but get the following error:

```
Traceback (most recent call last):
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/hydra/utils.py", line 99, in instantiate
    convert = _pop_convert_mode(final_kwargs)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/hydra/_internal/utils.py", line 631, in _pop_convert_mode
    convert = d.pop("_convert_")
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/omegaconf/dictconfig.py", line 453, in pop
    self._format_and_raise(key=key, value=None, cause=e)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/omegaconf/base.py", line 113, in _format_and_raise
    type_override=type_override,
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/omegaconf/_utils.py", line 678, in format_and_raise
    _raise(ex, cause)
  File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/omegaconf/_utils.py", line 588, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.ReadonlyConfigError: Cannot pop from read-only node
        full_key: hydra._convert_
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro

## System information
- **Hydra Version** :  latest master
- **Python version** :  3.7
- **Virtual environment type and version** :  conda
- **Operating system** :  Linux

**Comment by omry** [comment]
Thanks @jgbos , can you create a minimal repro for this? I am guessing it has nothing to do with opening and closing sockets.
Also, as this is likely a bug in 1.0, can you also test there?

**Comment by omry** [comment]
what is the setup node? is this a documented feature of Slurm or the plugin?

**Comment by omry** [comment]
Out of curiosity, what in the master branch are you relying on?
Recursive defaults are going to go through a major change soon.

**Comment by jgbos** [comment]
Yeah this is a general issue with Hydra and Submitit (not just master branch) because of the line

```
File "/home/gridsan/JU17693/.conda/envs/raiden-release/lib/python3.7/site-packages/submitit/slurm/slurm.py", line 490, in _make_sbatch_string
    lines += ["", "# setup"] + setup
```

If I edit those lines in submitit to `lines += ["", "# setup"] + list(setup)` it works fine.

The `setup` option allows the user to define additional code for the `sbatch` script, see here:

https://github.com/facebookincubator/submitit/blob/master/submitit/slurm/slurm.py#L400

My example above is for setting environment variables for distributed runs.

For you last comment, I am using your recursive instantiate.  Nothing is complex in my configs so I don't expect to do much refactoring if you end up doing major changes.  Completely aware this isn't stable yet.

**Comment by jgbos** [comment]
Does this help as a way to reproduce?  Everyone's slurm config is different!

```python
from dataclasses import dataclass, field
from typing import Any, List

from hydra.core.config_store import ConfigStore
from hydra_plugins.hydra_submitit_launcher.config import SlurmQueueConf


@dataclass
class ClusterConf(SlurmQueueConf):
    setup: List[Any] = field(default_factory=lambda: [
        "export MASTER_ADDR=$(hostname -s)",
        """export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')"""
    ])


ConfigStore.instance().store(
    group="hydra/launcher",
    name="my_cluster",
    node=ClusterConf(),
    provider="test",
)

```

**Comment by omry** [comment]
I see, so firstly - setup is not a supported field right now (as you have discovered trying to add it): the SlurmQueue conf does not have that field.

A fix can be two fold:
1. add setup support, something like this in the submitit plugin config:
```
@dataclass
class SlurmQueueConf(BaseQueueConf):
  ...
  setup: Optional[List[str]] = None
```

2. convert setup to a primitive list before passing it to submitit,
something like:
```
setup = OmegaConf.to_container(cfg.setup)
```

Do you want to give it a try?

**Comment by jgbos** [comment]
Sure, I can take a crack at creating a pull request.  

Strangely adding the `setup` field to the YAML file does not cause Hydra to crash even though it's not supported in the structured config.  I only just made the structured config above today.  Is that expected?

**Comment by omry** [comment]
> Sure, I can take a crack at creating a pull request.
> 
> Strangely adding the `setup` field to the YAML file does not cause Hydra to crash even though it's not supported in the structured config. I only just made the structured config above today. Is that expected?

Looking more closely:
I am assuming you added setup under additional_parameters?
This is a dictionary and can take any value.

@jrapin, any reason why setup should not be a member of SlurmQueueConf in the plugin?

**Comment by jgbos** [comment]
Sorry, I did not see this.  `additional_parameters` are parameters for the command line options where `setup` is used for additional lines of code for the sbatch script.  There are many possible things that can be added via setup to setup the srun environment.

Here's an example script (I've annotated where `setup` and `additional_parameters` differ)

```bash
#!/bin/bash

# Parameters
#SBATCH --array=0-1%2
#SBATCH --constraint=xeon-g6
#SBATCH --cpus-per-task=20
#SBATCH --error=submitit/%A_%a/%A_%a_0_log.err
#SBATCH --job-name=test_slurm
#SBATCH --mem=64GB
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=2
#SBATCH --open-mode=append
#SBATCH --output=submitit/%A_%a/%A_%a_0_log.out
#SBATCH --partition=gaia
#SBATCH --signal=USR1@120
#SBATCH --time=6000
#SBATCH --wckey=submitit
#SBATCH --gres=gpu:volta:2

####### Additional Parameters does this
# SBATCH <provided via additional parameters>

###### setup does this:
# setup
export MASTER_ADDR=$(hostname -s)
export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')

# command
export SUBMITIT_EXECUTOR=slurm
srun --output 'submitit/%A_%a/%A_%a_%t_log.out' --error 'submitit/%A_%a/%A_%a_%t_log.err' --unbuffered python -u -m submitit.core._submit 'submitit/%j'

```

**Comment by jgbos** [comment]
Here's the output of `--cfg all -p hydra.launcher`

```bash
# @package hydra.launcher
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
name: test_slurm
nodes: ${nodes}
timeout_min: 6000
cpus_per_task: 20
additional_parameters:
  gres: gpu:volta:2
tasks_per_node: 2
mem_gb: 64
partition: gaia
constraint: xeon-g6
setup:
- export MASTER_ADDR=$(hostname -s)
- export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0));
  print(s.getsockname()[1]); s.close()')
```

**Comment by omry** [comment]
I see.
The fact that you setup did what you wanted is a lucky coincidence.

Regardless
I am still not sure how you added it without code changes.
When I try the following in the example it fails to compose the config:
```diff
$ git diff
diff --git a/plugins/hydra_submitit_launcher/example/config.yaml b/plugins/hydra_submitit_launcher/example/config.yaml
index abb6cb85f..fcc74f99b 100644
--- a/plugins/hydra_submitit_launcher/example/config.yaml
+++ b/plugins/hydra_submitit_launcher/example/config.yaml
@@ -1,4 +1,7 @@
 defaults:
   - hydra/launcher: submitit_slurm
 
+hydra:
+  launcher:
+    setup: [ a,b,c ]
 task: 1
```

Output:
```
omry@Coronadev:~/dev/hydra/plugins/hydra_submitit_launcher/example$ python my_app.py 

Key 'setup' not in 'SlurmQueueConf'
        full_key: hydra.launcher.setup
        reference_type=Optional[SlurmQueueConf]
        object_type=SlurmQueueConf

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by jgbos** [comment]
I have a config in `hydra/launcher` directory:

```yaml
# @package _group_

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
name: test_slurm
mem_gb: 64
nodes: ${nodes}
timeout_min: 6000
cpus_per_task: 20
tasks_per_node: ${gpu}
partition: gaia
constraint: xeon-g6

additional_parameters:
  gres: gpu:volta:2

setup:
  - export MASTER_ADDR=$(hostname -s)
  - export MASTER_PORT=$(python -c 'import socket; s=socket.socket(); s.bind(("", 0)); print(s.getsockname()[1]); s.close()')
```

When I load it this way it does not get passed through the schema check.

**Comment by omry** [comment]
Gotcha. the name of your config should match the name of the base schema for it to get validated.
You will also not need to repeat so many things (like the target class and things that has the same value as those in the schema).

In Hydra 1.1, you will also be able to do something like:
```yaml
defaults:
  - submitit_slurm

name: test_slurm
mem_gb: 64
nodes: ${nodes}
timeout_min: 6000
cpus_per_task: 20
tasks_per_node: ${gpu}
partition: gaia
constraint: xeon-g6

additional_parameters:
  gres: gpu:volta:2
```

**Comment by jgbos** [comment]
awesome! yeah, this config was written before 1.0 :) 

I've recently started using the structured configs as schemas (so still learning) and discovering all the benefits.

What are you thoughts on the pull request?  Still need to add `setup` and convert to primitive. You can close it if there is a better direction to go.

**Comment by omry** [comment]
> I've recently started using the structured configs as schemas (so still learning) and discovering all the benefits.

Me too! :)

> What are you thoughts on the pull request? Still need to add setup and convert to primitive. You can close it if there is a better direction to go.

I still think it makes sense to add proper support to setup.
I made a suggestion there on how to simplify the change a little.

**Comment by jrapin** [comment]
> @jrapin, any reason why setup should not be a member of SlurmQueueConf in the plugin?

Just that I've never used it so didn't consider it, but if it's useful, no reason not to

**Comment by omry** [comment]
Thanks, we have a PR to add it (#1230).
