### ISSUE TITLE
[Bug] Error when merging configs

### ISSUE THREAD

**Issue by normster** [facebookresearch/hydra#1229]
# 🐛 Bug
## Description
Merging sub-configs within a config tries to access non-existent fields on the sub-configs and fails.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce

```
import hydra
from omegaconf import OmegaConf

@hydra.main(config_path='config', config_name='test.yaml')
def launch(cfg):
    cfg = OmegaConf.set_struct(cfg, False)
    merged = OmegaConf.merge(cfg.net, cfg.trainer)
    print(OmegaConf.to_yaml(merged))

if __name__ == '__main__':
    launch()

```

and run with `python launch.py -m` yields:

```
Traceback (most recent call last):
  File "launch.py", line 19, in launch
    merged = OmegaConf.merge(cfg.net, cfg.trainer)
AttributeError: 'NoneType' object has no attribute 'net'
```

If I set the struct flag to True instead it gives this error instead:

```
Traceback (most recent call last):
  File "launch.py", line 18, in launch
    merged = OmegaConf.merge(cfg.net, cfg.trainer)
omegaconf.errors.ConfigKeyError: Key 'data' is not in struct
	full_key: net.data
	reference_type=Any
	object_type=dict
```

If I load the config from file with OmegaConf.load() or from string with OmegaConf.create() there are no issues.

## Expected Behavior
Expect hydra to return the correct merged config:

```
data: /path/to/data
arch: resnet50
```

## System information
- **Hydra Version** :  1.0.4
- **Python version** : 3.8.5
- **Operating system** : Linux

**Comment by omry** [comment]
Can you add the content of config.yaml?

**Comment by omry** [comment]
This is wrong.
```
cfg = OmegaConf.set_struct(cfg, False)
```

Try:
```
OmegaConf.set_struct(cfg, False)
```

**Comment by normster** [comment]
Thanks! That fixed it.
