### ISSUE TITLE
Release new version of Hydra

### ISSUE THREAD

**Issue by noChamp** [facebookresearch/hydra#1234]
# 🚀 Feature Request

I would like you to release Hydra that includes this PR: https://github.com/facebookresearch/hydra/pull/1197

## Motivation

currently I am using python 3.9 and I can't run Hydra due to a bug that is solved in above PR

**Comment by omry** [comment]
Thanks. A new version of Hydra 1.0 is planned in a few weeks (to address some other needs).
In the mean time, you can install Hydra 1.0 with Python 3.9 support from the [1.0 branch](https://github.com/facebookresearch/hydra/tree/1.0_branch).
