### ISSUE TITLE
Ray Launcher CI fails

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#1238]
Example:

https://app.circleci.com/pipelines/github/facebookresearch/hydra/5707/workflows/7c5dbe70-f340-40f7-9c9d-0216f88932e0/jobs/42402

> ValueError: lib version not matching, local_version: ray==1.1.0

Probably related to the release of the latest Ray version.

**Comment by jieru-hu** [comment]
This particular issue was fixed.
