### ISSUE TITLE
[Configen][Bug] Configs for classes that inherit from abstract class

### ISSUE THREAD

**Issue by romesco** [facebookresearch/hydra#1242]
# 🐛 Bug
## Description
These two classes inherit from the Dataset abstract class referenced in issue #1241 :
https://github.com/romesco/configen-tests/blob/ae774572a5a541ea34b46590d0c18ef1c3230efe/configen_tests/utils/data/dataset.py#L36-L41
```python
class IterableDataset(Dataset[T_co]):
    def __iter__(self) -> Iterator[T_co]:
        raise NotImplementedError

    def __add__(self, other: Dataset[T_co]):
        return ChainDataset([self, other])
```

and
https://github.com/romesco/configen-tests/blob/ae774572a5a541ea34b46590d0c18ef1c3230efe/configen_tests/utils/data/dataset.py#L67-L116
```python
#class ConcatDataset(Dataset[T_co]):
class ConcatDataset(Dataset):
    r"""Dataset as a concatenation of multiple datasets.

    This class is useful to assemble different existing datasets.

    Arguments:
        datasets (sequence): List of datasets to be concatenated
    """
    datasets: List[Dataset[T_co]]
    cumulative_sizes: List[int]

...
    def __init__(self, datasets: Iterable[Dataset]) -> None:
        super(ConcatDataset, self).__init__()
        # Cannot verify that datasets is Sized
        assert len(datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore
        self.datasets = list(datasets)
        for d in self.datasets:
            assert not isinstance(d, IterableDataset), "ConcatDataset does not support IterableDataset"
        self.cumulative_sizes = self.cumsum(self.datasets)
```

Notice they have different characteristics. `IterableDataset` is again abstract in that it doesn't have its own `__init__` whereas `ConcatDataset` can actually be instnatiated. I needed to change the parent type of `ConcatDataset` to `Dataset` to get it to generate something.

When generating, both yield the same problematic conf as `Dataset`:
https://github.com/romesco/configen-tests/blob/ae774572a5a541ea34b46590d0c18ef1c3230efe/gen/configen_tests/utils/data/dataset.py#L33-L37
```python
@dataclass
class IterableDatasetConf:
    _target_: str = "configen_tests.utils.data.dataset.IterableDataset"
    args: Any = MISSING
    kwds: Any = MISSING
```

and

https://github.com/romesco/configen-tests/blob/ae774572a5a541ea34b46590d0c18ef1c3230efe/gen/configen_tests/utils/data/dataset.py#L46-L50
```python
@dataclass
class ConcatDatasetConf:
    _target_: str = "configen_tests.utils.data.dataset.ConcatDataset"
    args: Any = MISSING
    kwds: Any = MISSING
```
## Expected Behavior
I would expect to see:
```python
@dataclass
class IterableDatasetConf:
    _target_: str = "configen_tests.utils.data.dataset.IterableDataset"
```

and
```python
@dataclass
class ConcatDatasetConf:
    _target_: str = "configen_tests.utils.data.dataset.ConcatDataset"
    datasets: Any = MISSING
#eventually datasets: List = []
```

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce
```bash
git clone https://github.com/romesco/configen-tests
pip install -r requirements.txt
pip install .
configen --config-dir conf
```

## System information
- **Hydra Version** :  master
- **Python version** : 3.8
- **Virtual environment type and version** : pyenv-virtualenv 1.2.21
- **Operating system** : Ubuntu 18.04

**Comment by omry** [comment]
Please create a new issue for a feature request. 
The feature here is complicated and we should probably create a design doc for it. (followup for our chat).

**Comment by romesco** [comment]
Sounds good! There's definitely a lot to unpack.
