### ISSUE TITLE
Instantiating objects that include asterisk in signature

### ISSUE THREAD

**Issue by romesco** [facebookresearch/hydra#1243]
## Description
The `TensorDataset` class: https://github.com/romesco/configen-tests/blob/ae774572a5a541ea34b46590d0c18ef1c3230efe/configen_tests/utils/data/dataset.py#L45-L64
```python
#class TensorDataset(Dataset[Tuple[Tensor, ...]]):
class TensorDataset(object): #using type 'Dataset' still fails to gen signature
    r"""Dataset wrapping tensors.
    Each sample will be retrieved by indexing tensors along the first dimension.
    Arguments:
        *tensors (Tensor): tensors that have the same size of the first dimension.
    """
    tensors: Tuple[Tensor, ...]

    def __init__(self, *tensors: Tensor) -> None:
        assert all(tensors[0].size(0) == tensor.size(0) for tensor in tensors), "Size mismatch between tensors"
        self.tensors = tensors

    def __getitem__(self, index):
        return tuple(tensor[index] for tensor in self.tensors)

    def __len__(self):
        return self.tensors[0].size(0)
```

includes a `*tensors` in its signature.

Calling `hydra.utils.instantiate()`: https://github.com/romesco/configen-tests/blob/ae774572a5a541ea34b46590d0c18ef1c3230efe/configen_tests/test_instantiate.py#L7-L10
```python
full_class = f"gen.configen_tests.utils.data.dataset.TensorDatasetConf"
schema = OmegaConf.structured(get_class(full_class))
cfg = OmegaConf.merge(schema, cfg)
obj = instantiate(cfg, tensors=(Tensor([1])))
```

does not work because it currently only supports passthroughs by keyword, not positional (e.g. unpacking a tuple).

Running `pytest test_instantiate.py` gives the error:
```
 TypeError: Error instantiating/calling 'configen_tests.utils.data.dataset.TensorDataset' : __init__() got an unexpected keyword argument 'tensors'
```

## Expected Behavior
Need to be able to pass the tuple `tensors` (positionally) and get a successfully instantiated object.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce
```bash
git clone https://github.com/romesco/configen-tests
pip install -r requirements.txt
pip install .
configen --config-dir conf
```

## System information
- **Hydra Version** :  master
- **Python version** : 3.8
- **Virtual environment type and version** : pyenv-virtualenv 1.2.21
- **Operating system** : Ubuntu 18.04

**Comment by omry** [comment]
Please create a minimal repro. See [this](https://stackoverflow.com/help/minimal-reproducible-example) to understand what I mean. (Edit your question to the minimal repro once you have one).

**Comment by omry** [comment]
This is not a supported feature at the moment and is unlikely to be supported in the near future (recursive defaults is already a massive change for instantiation and I want things to settle down before I add additional features).

In the mean time, you can create an alternative factory method that will translate parameters in a supported forms to what the underlying `_init_()` function expects.

**Comment by romesco** [comment]
^ I'll give this a shot in `hydra-torch` as a one-off fix for signatures with this issue.

**Comment by thomkeh** [comment]
Just to one more data point: this would also be useful for instantiating `pathlib.Path`, whose constructor has the signature `Path(*pathsegments)`. What I would often like to do is

```python
@dataclass
class Path_:
    _target_: str = "pathlib.Path"
    path: str = MISSING

@dataclass
class Config:
    data_dir: Path_ = MISSING
    output_dir: Path_ = MISSING
```
and then use recursive instantiation to construct the Path object from `data_dir.path="/my/path"`. There are definitely work-arounds for this, but they are a quite verbose.

**Comment by omry** [comment]
I think this should now work with positional arguments support.
See [this](https://hydra.cc/docs/next/advanced/instantiate_objects/overview#simple-usage).
Something like this should work:
```
_target_: a.b.c
_args_:
 - param1
 - param2
```
Can you give it a try and report?

**Comment by omry** [comment]
Yeah, it works:
```python
from hydra.utils import instantiate

def foo(*items):
    return sum(items)


ret = instantiate(
    config={
        "_target_": "__main__.foo",
        "_args_": [1, 2, 3],
    }
)
print(ret) # 6
```
