### ISSUE TITLE
Change default sweep subdir to hydra.job.num

### ISSUE THREAD

**Issue by bamos** [facebookresearch/hydra#125]
Forking from #108:

Let's start with the same MWE and modify the `6_sweep` to have `import time; time.sleep(1e6)` in `experiment.py`, and also something like this in `conf/config.yaml`:

```
hydra:
  run:
    dir: ./exps/local
  sweep:
    dir: ./exps/sweep
    subdir: ${hydra.job.num}_${hydra.job.id}
```

We can then run `./experiment.py -m` and see this job on the cluster:

```
 22   267168    5053900 lea experimen    bda  R 2019-09-03T14:52       0:16 3-00:00:00     1       22       gpu:1 10  64G learnfair059
```

We can also see the output dir:

```
6_sweep(master*)$ tree exps/sweep
exps/sweep
└── 0_5053900
    ├── config.yaml
    ├── hydra.yaml
    ├── overrides.yaml
    └── UNKNOWN_NAME.log

1 directory, 4 files
```

Let's trigger a pre-emption for this job with `scancel --signal=USR1 5053900`. A new job will come back online (if you have the dask*/distributed libraries, otherwise see #108) with a new PID

```
 2   267168    5053930 lea experimen    bda  R 2019-09-03T14:53       0:19 3-00:00:00     1        2       gpu:1 10  64G learnfair041
```

This also creates a new directory for the experiment:

```
6_sweep(master*)$ tree exps/sweep
exps/sweep
├── 0_5053900
│   ├── config.yaml
│   ├── hydra.yaml
│   ├── overrides.yaml
│   └── UNKNOWN_NAME.log
└── 0_5053930
    ├── config.yaml
    ├── hydra.yaml
    ├── overrides.yaml
    └── UNKNOWN_NAME.log

2 directories, 8 files
```

Perhaps one solution here is not use `hydra.job.id` in the directory name and only `hydra.job.num`?

**Comment by omry** [comment]
fixed in 0.10.0
