### ISSUE TITLE
[Feature Request] Multirun of all experiments from the folder

### ISSUE THREAD

**Issue by hobogalaxy** [facebookresearch/hydra#1261]
# 🚀 Feature Request

So I'm not sure if this feature doesn't already exists so please let me know.

I want to group my experiments in folders:
```
- experiment
    - exp_group1
        - exp1.yaml
        - exp2.yaml
        - ...
    - exp_group2
    - exp_group3
```

And then I want to run the whole group as a multirun.

Can I do this from the command line level with only specifying name of the group folder? 
like this:
`python file.py --multirun +experiment=exp_group1`
instead of this:
`python file.py --multirun +experiment=exp_group1/exp1,exp_group1/exp2,... `

**Comment by omry** [comment]
try this:
```
$ python file.py --multirun '+experiment/exp_group1=glob(*)'
```

**Comment by hobogalaxy** [comment]
Thanks @omry! This solves my problem.
