### ISSUE TITLE
[Bug] jobs launched by submitit plugin cannot access hydra.job.id and hydra.job.num 

### ISSUE THREAD

**Issue by shubham-goel** [facebookresearch/hydra#1278]
# 🐛 Bug
## Description
`hydra.job.id` and `hydra.job.num` cannot be accessed using `HydraConfig.get()` for jobs launched by the submitit plugin.

## Checklist
- [ ] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
**test.py**
```python
import hydra
from hydra.core.hydra_config import HydraConfig
@hydra.main()
def main(cfg):
    print(
        HydraConfig.get().job.get('id', None),
        HydraConfig.get().job.get('num', None),
        cfg.a
    )
main()
```

**Terminal:**
```
$ python test.py +a=0,1
[2021-01-05 12:57:30,599][HYDRA] Launching 2 jobs locally
[2021-01-05 12:57:30,599][HYDRA]        #0 : +a=0
0 0 0
[2021-01-05 12:57:30,781][HYDRA]        #1 : +a=1
1 1 1

$ python test.py +a=0,1 hydra/launcher=submitit_slurm  -m
...
$ cat /checkpoint/shubhamgoel/outputs/2021-01-05/12-35-21/.submitit/*/*.out | grep -v INFO
None None 0
None None 1
```

## Expected Behavior
Expected behaviour is for hydra.job.id and hydra.job.num to be set by submitit and be accessible from the application.

## System information
- **Hydra Version** : 1.1.0dev1
- **Python version** : 3.8.5
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Ubuntu 20.04.1 LTS

**Comment by jieru-hu** [comment]
Thanks for the issue. I believe this was addressed in https://github.com/facebookresearch/hydra/issues/1270

It will be release in the next Hydra version 1.0.5
