### ISSUE TITLE
[Bug] utils.call forwarding behavior of ListConfig changes based on other types present

### ISSUE THREAD

**Issue by monney** [facebookresearch/hydra#1295]
# 🐛 Bug
## Description

I'm not sure if this is a bug or intended behavior but the forwarding behavior of `call` and  `instantiate` of a `ListConfig` object changes depending on the surrounding types. If a generator is passed in any surrounding arguments, the `ListConfig` becomes a generator. Otherwise it is not.

If this is intended how can I disable this?

## Checklist
- [x] I checked on the latest version of Hydra 
- [x] I created a minimal repro 

## To reproduce

```python
import pickle
from hydra.utils import call

def example(foo, bar):
    return foo


def pickle_test():
    foo = call({'_target_': f'{__file__[:-3]}.example', 'foo': [1, 2, 3]}, bar=[i for i in range(10)])
    pickle.dumps(foo) #this line succeeds

    foo = call({'_target_': f'{__file__[:-3]}.example', 'foo': [1, 2, 3]}, bar=(i for i in range(10)))
    pickle.dumps(foo) #this line fails -- TypeError: cannot pickle 'generator' object


if __name__=='__main__':
    pickle_test()
```

** Stack trace/error message **
```bash
Traceback (most recent call last):
  File "example_script.py", line 17, in <module>
    pickle_test()
  File "example_script.py", line 13, in pickle_test
    pickle.dumps(foo) #this line fails -- TypeError: cannot pickle 'generator' object
TypeError: cannot pickle 'generator' object
```

## Expected Behavior
Both instances of foo should be picklable (or not picklable but the former is preferred)

## System information
- **Hydra Version** :  1.1.0.dev2
- **Python version** :  3.8.6
- **Virtual environment type and version** : conda 4.8.5
- **Operating system** :  macOS and Ubuntu 18

## Additional context
- I don't think this happens in Hydra 1.0
- An actual typing test to see if it's a generator returns false for some reason. Only pickling fails.

**Comment by omry** [comment]
Thanks for reporting, this is rather odd. We will take a look.

**Comment by monney** [comment]
Thank you! Quite a strange bug indeed.

**Comment by monney** [comment]
I’m not actually sure there’s a way to fix this. The problem comes from the fact that OmegaConf objects need to keep track of their parent. So pickle tries to pickle the parent which contains the generator. The easiest workaround is probably to set the _convert_ parameter in instantiate. 

But I don’t see a direct fix without rewriting OmegaConf to not use parent refs.

Thoughts?

**Comment by omry** [comment]
Thanks for digging.

OmegaConf objects needs a reference to the parents for various reasons, the primary being interpolation support.

Normally, OmegaConf objects would reject anything that is not a supported type (like generator):
```python
In [12]: OmegaConf.create({"a" : [1,2,3], "b": (i for i in range(3))})
...
UnsupportedValueType: Value 'generator' is not a supported primitive type
        full_key: b
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```

There is a special internal mode that is only used with instantiate that allows arbitrary objects:
```python
In [13]: cfg = OmegaConf.create({"a" : [1,2,3], "b": (i for i in range(3))}, flags={"allow_objects": True})
In [14]: cfg
Out[14]: {'a': [1, 2, 3], 'b': <generator object <genexpr> at 0x7ff5304a2820>}
```

The reason this is not a normal part of the API is exactly things like this: serializing arbitrary objects is really really hard.

One workaround is to convert the cfg object to a primitive container:
```python
In [18]: pickle.dumps(OmegaConf.to_container(cfg)["a"])
Out[18]: b'\x80\x04\x95\x0b\x00\x00\x00\x00\x00\x00\x00]\x94(K\x01K\x02K\x03e.'
```

This can happen manually before you save like in the example above, or by using the `_convert_=all|partial`  flag as you suggested.

**Comment by monney** [comment]
For context, the use case I encountered this is in is passing params into an optimizer. I needed pickling for checkpointing. I think a small note in the docs about pickling would be good? Either way this can probably closed. Thank you for your help.

**Comment by omry** [comment]
Specifically, for pytorch classes (including optimizers), I recommend setting using `_convert_=all`.
FYI: The upcoming project [hydra-torch](https://github.com/pytorch/hydra-torch) will provide Structured Configs to use when instantiating Pytorch classes.
The default convert mode for all of those will be `all`.

cc @romesco.

**Comment by omry** [comment]
>  I think a small note in the docs about pickling would be good? Either way this can probably closed. Thank you for your help.

This is a pretty extreme corner case, it's probably does not justify it.
Once we standard classes to instantiate Pytorch classes this issue will become even less likely.

Closing. Thanks for reporting and digging.

**Comment by omry** [comment]
On second thought, I am keeping this open until I get a chance to take a closer look.

@guillaumegenthial, take a look at this. 
This looks like another reason to drop support for live (post instantiation) interpolation:
One solution for this is to detach OmegaConf containers from their parent before passing to the function. This will break live interpolation though.

**Comment by romesco** [comment]
Hey @monney, if your main goal is to configure optimizers, take a look at the repo omry mentioned: specifically here: https://github.com/pytorch/hydra-torch/blob/master/examples/mnist_00.md

Hopefully this is helpful to your project!

**Comment by omry** [comment]
Got a closer look.
This is unfortunately needed to support interpolation, which is a core functionality of the instantiate function.

I think it's reasonable to use `_convert="all"` here.

Closing.

**Comment by omry** [comment]
#1483 will fix it properly. This depends on `OmegaConf.resolve()` which is new in OmegaConf 2.1.0dev23.
