### ISSUE TITLE
[Bug] Configen does not support `Callable` types

### ISSUE THREAD

**Issue by piraka9011** [facebookresearch/hydra#1299]
# 🐛 Bug
## Description

When attempting to use configen to generate a [`Callable`](https://docs.python.org/3/library/typing.html#typing.Callable) type, a `TypeError` is thrown [here](https://github.com/facebookresearch/hydra/blob/dbe1e6882386fd1c1b721992542844e58bf0722a/tools/configen/configen/configen.py#L118).

See example config below.

## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
configen --config-dir conf --config-name pytorch_lightning
```

Example config from lightning

```yaml
# pytorch_lightning.yaml
defaults:
  - configen_schema

configen:
    output_dir: ${hydra:runtime.cwd}

    header: |
        # Autogenerated by configen, do not edit.
        # If encountering an error, please file an issue @
        # https://github.com/romesco/hydra-lightning
        # fmt: off
        # isort: skip_file
        # flake8: noqa
        # Hydra + Lightning

    module_path_pattern: 'hydra_configs/{{module_path}}.py'

    modules:
        - name: pytorch_lightning.metrics.classification
          classes:
            - Accuracy
            - Fbeta
            - Precision
```

** Stack trace/error message **

```sh
Traceback (most recent call last):
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 364, in _run_hydra
    run_and_report(
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 215, in run_and_report
    raise ex
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/utils.py", line 365, in <lambda>
    lambda: hydra.run(
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 109, in run
    return run_job(
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/hydra/core/utils.py", line 129, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/configen/configen.py", line 263, in main
    code = generate_module(cfg=cfg.configen, module=module)
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/configen/configen.py", line 182, in generate_module
    not missing_annotation_type and is_incompatible(type_)
  File "/home/allabana/.virtualenvs/light-ws/lib/python3.8/site-packages/configen/configen.py", line 118, in is_incompatible
    if type_ is Any or issubclass(type_, (int, float, str, bool, Enum)):
TypeError: issubclass() arg 1 must be a class
python-BaseException
```

## Expected Behavior

Config should be generated normally

## System information
- **Hydra Version** :  1.1.0dev5
- **Python version** : 3.8
- **Virtual environment type and version** : virtualenv
- **Operating system** : Ubuntu 20.04

## Additional context

If I attempt to wrap the failing `if` statement with a try catch like below, I get another error [here](https://github.com/facebookresearch/hydra/blob/dbe1e6882386fd1c1b721992542844e58bf0722a/tools/configen/configen/utils.py#L87)

```python
    try:
        if type_ is Any or issubclass(type_, (int, float, str, bool, Enum)):
            return False
    except TypeError:
        return False
```

And so I wrapped that failing block with another try/catch:

```
                try:
                    classname = t.__name__
                except AttributeError:
                    classname = t._name
```

And now configen works.

This is a hacky approach IMO, and a better solution could be proposed.

I'm not too familiar with the internals of configen, so I don't know what the best way is to check for subclasses or check for names. (Maybe there are other helper methods somewhere?)

I can open a PR if this is fine.

**Comment by piraka9011** [comment]
Also, when I generated the config, the `Dict` class was not imported automagically for one of the fields I generated:

```yaml
# pytorch_lightning.yaml
...
        - name: pytorch_lightning.loggers
          classes:
            - CometLogger
            - MLFlowLogger
            - NeptuneLogger
            - TestTubeLogger
            - WandbLogger
```
...

```python
# loggers.py

# No `from typing import Dict` at the top
@dataclass
class MLFlowLoggerConf:
    _target_: str = "pytorch_lightning.loggers.MLFlowLogger"
    experiment_name: str = "default"
    tracking_uri: Optional[str] = None
    tags: Optional[Dict[str, Any]] = None
    save_dir: Optional[str] = "./mlruns"
    prefix: str = ""
```

**Comment by omry** [comment]
Thanks for reporting.
Feel free to submit pull requests with fixes. we can discuss the actual fix over the pull requests.

**Comment by romesco** [comment]
Alright, I verified this bug as well.

I think the path forward is to create the PR with this bug fix (thank you @piraka9011 !), and then we can discuss the expected functionality and if there is a way to make configen more robust.

I encountered the missing import once before and started working on a fix for that. I can finish that up and make a PR to address that issue. :+1:
