### ISSUE TITLE
[Bug] Cannot find configuration file if the file suffix is `.yml` instead of `.yaml`

### ISSUE THREAD

**Issue by binh-vu** [facebookresearch/hydra#1308]
# 🐛 Bug
## Description

`.yml` is also a popular suffix for YAML file. However, the code doesn't handle it correctly and assumes that people will use `.yaml` suffix. Either this needs to be mentioned explicitly in the documentation to avoid confusion or the code has to be fixed. This is an excerpt from `hydra/plugins/config_source.py` showing how this currently is handled.

```python
@staticmethod
def _normalize_file_name(filename: str) -> str:
    if not any(filename.endswith(ext) for ext in [".yaml", ".yml"]):
        filename += ".yaml"
    return filename
```

The code above seems recognize that people use `.yml` suffix but assuming people will always use `.yaml` by appending to it? The [documentation](https://hydra.cc/docs/next/tutorials/basic/your_first_app/config_file) suggests that the users should omit the suffix.

## Checklist
- [x] I checked on the latest version of Hydra

## System information
- **Hydra Version** :  1.0.5
- **Python version** : 3.7.5

**Comment by omry** [comment]
Supported config file extention is only .yaml.
The docs tells you that you should omit the suffix when referencing configs (config can be files, structured configs and other things).

The .yml is only supported for the primary config file, but to avoid confusion I am probably going to remove this support.

**Comment by binh-vu** [comment]
I think for new users like me that go through the docs in this flow: Tutorial -> Basic Tutorial -> Your first Hydra app -> Specifying a config file. They won't know that `.yaml` is the only supported extension as the docs doesn't say that. What I got from the docs so far is that hydra supports YAML file, as a habit, I use `.yml` and get the error.

I think one line in the docs mentioning about the config file should ended with `.yaml` extension will probably help lots of new users out there.

**Comment by jieru-hu** [comment]
> I think for new users like me that go through the docs in this flow: Tutorial -> Basic Tutorial -> Your first Hydra app -> Specifying a config file. They won't know that `.yaml` is the only supported extension as the docs doesn't say that. What I got from the docs so far is that hydra supports YAML file, as a habit, I use `.yml` and get the error.
> 
> I think one line in the docs mentioning about the config file should ended with `.yaml` extension will probably help lots of new users out there.

Thank you for the suggestion! I will update our doc accordingly.
