### ISSUE TITLE
[Bug] Dot Syntax doesn't work for nested default overrides

### ISSUE THREAD

**Issue by monney** [facebookresearch/hydra#1321]
# 🐛 Bug
## Description
When trying of override a nested default something like the following doesn't work:

`foo.bar=baz`
but this does
`foo/bar=baz`

the dot syntax works for defaults in the main defaults list.
## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
In the nested defaults example:
https://github.com/facebookresearch/hydra/tree/master/examples/advanced/nested_defaults_list

run this from the terminal
```bash
python my_app.py server.db=sqlite
```

** Stack trace/error message **
```bash
Error merging override server.db=sqlite
Unsupported value type : sqlite
	full_key: server.db
	reference_type=Any
	object_type=dict
```

## Expected Behavior
The property should be changed to the alternate config in the group.
Same behavior as 
`python my_app.py server/db=sqlite`

## System information
- **Hydra Version** :  1.1.0.dev2
- **Python version** : Python 3.8.6 and 3.7.3
- **Virtual environment type and version** : conda 4.8.5
- **Operating system** : Ubuntu 18 and MacOS Catalina

## Additional context
Note that in this case the nested default the property is set using / syntax. This happens even it is originally set using the dot syntax.

**Comment by omry** [comment]
This is by design. why do you think this is a bug?

**Comment by monney** [comment]
I think I understand the difference. One involves explicitly saying to parse an alternate yaml file. I thought this was a bug because it work on the main defaults list

**Comment by monney** [comment]
Sorry I just realized you wouldn't need a dot on the main list, which is why I didn't encounter it there. I apologize. Closing.

**Comment by omry** [comment]
Config groups can be merged into different packages (package overrides).

This means that we can't just assume that `server/db` is always in the package `server.db`.

**Comment by monney** [comment]
I understand. Dumb error on my part. Thank you for taking the time to review

**Comment by omry** [comment]
It's a common mistake, don't feel bad about it :).

**Comment by omry** [comment]
The error message doesn't make sense though, looks like you did find some bug :).

filed #1322 to check it later.

**Comment by monney** [comment]
At least some good came out of it lol
