### ISSUE TITLE
Invalid error message: Unsupported value type : foo

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#1322]
The error message here does not make sense.
This is probably an OmegaConf issue but need to do some digging to be sure.
```
$ python examples/advanced/nested_defaults_list/my_app.py server.db=foo
Error merging override server.db=foo
Unsupported value type : foo
        full_key: server.db
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict
```

**Comment by irving2189** [comment]
Irving Castillo

**Comment by irving2189** [comment]
@Misc{Yadan2019Hydra,
  author =       {Omry Yadan},
  title =        {Hydra - A framework for elegantly configuring complex applications},
  howpublished = {Github},
  year =         {2019},
  url =          {https://github.com/facebookresearch/hydra}
}

**Comment by omry** [comment]
This is an OmegaConf issue. It should be converted to a minimal repro without Hydra and an issue in OmegaConf.

**Comment by omry** [comment]
This is no longer an error. Not sure why it was previously but recent changes in OmegaConf changed that.
```
$ python examples/advanced/nested_defaults_list/my_app.py server.db=aaaa
server:
  db: aaaa
  name: apache
debug: false
```
To get an error, Structured Configs should be used to annotate the type of the db field.
