### ISSUE TITLE
[Question] Hydra 1.0 Inheritance doesn't work for static schema multiple configs? Any workaround?

### ISSUE THREAD

**Issue by hoangthienan95** [facebookresearch/hydra#1333]
When there are too many configs to list in `myapp.py` (https://hydra.cc/docs/tutorials/structured_config/static_schema) , it seems like you cannot use the config inheritance showcased earlier in the Docs: (https://hydra.cc/docs/tutorials/structured_config/config_groups#config-inheritance)

How can we get type inheritance to recognize classes that inherit from the class listed in the main `Config` dataclass?

Reproducible example, modified from `/hydra/examples/tutorials/structured_configs/6_static_schema_many_configs` 1.0_branch:

```
.
├── conf
│   ├── config.yaml
│   ├── db
│   │   ├── prod.yaml
│   │   ├── qa.yaml
│   │   └── staging.yaml
│   └── __init__.py
└── my_app.py
```

** modified conf/db/staging.yaml** 

```yaml
# @package _group_
driver: mysql
host: mysql001.staging
user: root
password: root
new_field: test
```

**modified `myapp.py`**

```python
from dataclasses import dataclass

from omegaconf import MISSING, OmegaConf

import hydra
from hydra.core.config_store import ConfigStore


@dataclass
class DBConfig:
    driver: str = MISSING
    host: str = MISSING
    user: str = MISSING
    password: str = MISSING

@dataclass
class StagingConfig(DBConfig):
    new_field: str = MISSING

@dataclass
class Config:
    db: DBConfig = MISSING


cs = ConfigStore.instance()
cs.store(name="config", node=Config)


@hydra.main(config_path="conf", config_name="config")
def my_app(cfg: Config) -> None:
    print(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    my_app()
```

**Error**

```python
Error merging db=staging
Key 'new_field' not in 'DBConfig'
	full_key: db.new_field
	reference_type=DBConfig
	object_type=DBConfig
```

**Comment by omry** [comment]
Why do you expect StagingConfig to be used at all in your example?
You are just declaring it and not using it for anything.
