### ISSUE TITLE
How to use environment variables to yaml config

### ISSUE THREAD

**Issue by davidnvq** [facebookresearch/hydra#1334]
So far I can add the variable appearing somewhere in the config (e.g., `home: /home/user/`) using the syntax `${variable}` (e.g., `${home}`. Is it possible to use environment variables of the running system (e.g., `HOME`)? I tried to use `$HOME` and `${HOME}` but all failed.

Many thanks.

**Comment by davidnvq** [comment]
I found in the [documentation](https://hydra.cc/docs/configure_hydra/job/#hydrajobenv_set) about setting the environment variables as follows:
```
hydra:
  job:
    env_set:
      HOME: /home/user1
```

Does it mean I have to change `HOME` manually when I run the script `python train.py` in different machines? And also how can I reuse the `HOME` variable in other places of the config, e.g., `dataset: $HOME/dataset/example`?

**Comment by omry** [comment]
set_env is for setting an environment variable for your process.
to to access an env variable from config use the env resolver. check the OmegaConf docs.

**Comment by davidnvq** [comment]
Thank you for your pointer. I've just figured it out.

**Comment by jgc128** [comment]
For reference, this is how to do it:

```yaml
user:
  name: ${oc.env:USER}
  home: /home/${oc.env:USER}
```

https://omegaconf.readthedocs.io/en/2.2_branch/custom_resolvers.html#oc-env

**Comment by djstrong** [comment]
Why this is not working with basic example: https://hydra.cc/docs/intro/ ?
