### ISSUE TITLE
[Feature Request] make hydra._internal.utils._locate public

### ISSUE THREAD

**Issue by ppwwyyxx** [facebookresearch/hydra#1339]
# 🚀 Feature Request

## Motivation
The function `hydra._internal.utils._locate` is a great utility with many use. 
In addition to how it's used in hydra, the function can be useful for documentation (as in pydoc), serializing objects, or any configuration system. Making it a public function would be very helpful

## Pitch

**Describe the solution you'd like**
Just expose a non-internal importable path 

**Describe alternatives you've considered**
`pydoc.locate` doesn't work for some cases like `torch.optim.SGD`.

**Comment by omry** [comment]
Have you tried `hydra.utils.get_class()` ?

**Comment by ppwwyyxx** [comment]
Thanks that's perfect. Didn't notice there is already an API
