### ISSUE TITLE
[Bug] Inconsistent behaviour of `hydra:job.override_dirname` across different launchers

### ISSUE THREAD

**Issue by shubham-goel** [facebookresearch/hydra#1344]
# 🐛 Bug
## Description
`job.override_dirname` is evaluated differently, depending on (a) Launcher being used; and (b) whether the interpolation is done as ${hydra:job.override_dirname} or ${hydra.job.override_dirname}.

I'm using `job.override_dirname` in `sweep.subdir`. There are 2 possible interpolation behaviors when running, say, `python test.py -m a=0,1`:
Behaviour 1: `job.override_dirname` evaluates to `a=0,1` for both runs (`a=0` and `a=1`)
Behaviour 2: `job.override_dirname` evaluates to `a=0` and `a=1` for the two runs.

The default launcher exhibits Behaviour2 irrespective of whether the variable is interpolated as `${hydra.job.override_dirname}` or `${hydra:job.override_dirname}`.
The submitit launchers (local and slurm) exhibit Behaviour2 with  `${hydra.job.override_dirname}` but Behaviour1 with `${hydra:job.override_dirname}`

If I'm not mistaken, `${hydra:job.override_dirname}` should exhibit Behaviour2 with the submitit launchers also?

## Checklist
- [ ] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
test.py
```python
import hydra
@hydra.main(config_name="test")
def main(cfg):
    print(cfg.a)
main()
```
test.yaml (Change `hydra:job.override_dirname` to `hydra.job.override_dirname` depending on what you're testing)
```yaml
a: 0
hydra:
  sweep:
    dir: ${hydra:runtime.cwd}/outputs/sweep/${hydra:job.id}/
    subdir: ${hydra:runtime.cwd}/outputs/${hydra:job.override_dirname}/${hydra.job.num}
```
Running `python test.py -m a=0,1` with different launchers exhibits the behaviour mentioned above.

## System information
- **Hydra Version** :  1.1.0dev3
- **Python version** : 3.8.5
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Ubuntu 20.04.1 LTS

**Comment by omry** [comment]
override_diranme is not documented very well.

It should generally be used in the hydra.sweep.subdir.

It's not clear to me what you are trying to achieve by specifying it twice.

**Comment by omry** [comment]
Also, the documentation shows that you should use the form `hydra.job.override_dirname` and not `hydra:job.override_dirname`.

**Comment by shubham-goel** [comment]
Ah! I think using override_dirname in sweep.dir is causing come confusion. I changed it to clarify. Note that the `sweep.subdir` has an absolute path in my example and isn't a subdirectory of sweep.dir.

So I'm actually trying to setup hydra s.t. `run.dir` and `sweep.subdir` are the same folder. That ensures that `python test.py a=0` (which uses run.dir) gets the same CWD as the `a=0` run from `python test.py -m a=0,1` (which uses sweep.subdir). This as you can guess, relies on Behaviour2!

**Comment by shubham-goel** [comment]
Can you please point me to some explanation on the difference between `hydra.` and `hydra:`? 

I'm trying to use a config like this:

```yaml
exp_id: ${hydra:job.override_dirname}
hydra:
  sweep:
    subdir: ${hydra:runtime.cwd}/outputs/${exp_id}/
```

I use the `hydra:` resolver so that I can access the `exp_id` variable inside my app as well. That's not possible if I set `exp_id: ${hydra.job.override_dirname}`.

**Comment by omry** [comment]
The Hydra config node is not available as a part of the config object you are getting, if it was - you would be able to use interpolation in the normal form `${hydra.job.name}`.
To allow the app config to access the Hydra config node anyway, I added the hydra resolver. (See custom resolvers).
In the examples for override_dirname, the hydra.job.override_dirname node is accessed from the hydra config itself, so it is accessible in that form.

In fact, depending on exactly when the config node is evaluated - using the hydra resolver (`${hydra:job.name}`) may fail from the hydra config and you should not depend on it from there.

The two behaviors you are seeing *probably* boils down to the to exactly when the config node is evaluated.
There is a lot of special behavior to the override_dirname config and you are trying to use it in a rather unique way.
I am not at all surprised you are not having a good time. This is not your average config variable.

**Comment by omry** [comment]
In multirun, override dirname should be evaluated as a part of hydra.sweep.subdir.
Try this, seems to be working correctly for both run and multirun. (and for submitit too):
```
exp_id: ${hydra:job.override_dirname}
hydra:
  run:
    dir: ${hydra.runtime.cwd}/outputs/${exp_id}
  sweep:
    dir: ${hydra.runtime.cwd}/outputs/ 
    subdir: ${exp_id}
```
I am a bit confused about what you are trying to achieve by overiding the dirs in that way, but I kept it as is.

**Comment by shubham-goel** [comment]
Thanks a ton for the explanation and the snippet, @omry! This works!!

On why I'm doing this: It's an attempt to ensure that the directory structure created when you run `python test.py -m a=0,1` is the same as that from running `python test.py a=0` and `python test.py a=1` separately :). This makes it easier for me to find old experiments - as directories are invariant to whether or not the experiment was a part of a bigger sweep.
