### ISSUE TITLE
[Feature Request] Scoped variable interpolation

### ISSUE THREAD

**Issue by lematt1991** [facebookresearch/hydra#1347]
# 🚀 Feature Request

Currently, it seems that variable interpolation only works relative to the top level config.  It would be awesome, if we could have scoped variable interpolation.

## Motivation

Let's say I have a nested config:

```Python
from dataclasses import dataclass
from hydra.core.config_store import ConfigStore
import hydra

@dataclass
class Inner:
    x: str = "test"
    y: str = "this is a ${inner.x}"
    #  y: str = "this is a ${x}"  # <---- this would be ideal

@dataclass
class Outer:
    inner: Inner = Inner()
    a: str = "test"

cs = ConfigStore.instance()
cs.store(name="config", node=Outer)

@hydra.main(config_path=".", config_name="config")
def main(cfg):
    print(cfg.a)
    print(cfg.inner.y)
    
main()
```

The way it's done now, `Inner` needs to know what configs it may be nested inside of.  For example, if I wanted to add a second config, and wanted to reuse `Inner`

```Python
@dataclass
class Outer2:
    inner_field: Inner = Inner()
```

Now, the `"this is a ${inner.x}"` interpolation is broken, because the field it is nested inside of changed.

## Pitch

**Describe the solution you'd like**

Allow for scoped variable interpolation, so that we could just write:

```Python
@dataclass
class Inner:
    x: str = "test"
    y: str = "this is a ${x}" 
```

And not worry about what configs it might be nested inside of.

**Comment by jieru-hu** [comment]
Thanks Matt for the feature request.

for this particular usecase with strict config we probably do not need interpolation since we are working with dataclasses. The following works for me
```
from dataclasses import dataclass
from hydra.core.config_store import ConfigStore
import hydra


@dataclass
class Inner:
    x: str = "test"
    y: str = f"this is a ${x}"


@dataclass
class Outer:
    inner: Inner = Inner()
    a: str = "test"


cs = ConfigStore.instance()
cs.store( name="config", node=Outer )


@hydra.main( config_path=".", config_name="config" )
def main(cfg):
    print( cfg.a )
    print( cfg.inner.y )


main()
```

```
$ python my_app.py
test
this is a test
```

I don't think it works for yaml files though. 

cc @omry

**Comment by lematt1991** [comment]
This will only work for plugging the current static value of `x` into `y`, though.  If I ran `python main.py inner.x="not a test"`, then I would expect `cfg.inner.y` to be `this is not a test`, however, it still uses the static value for `x`

**Comment by omry** [comment]
OmegaConf 2.1 will support relative interpolation (https://github.com/omry/omegaconf/issues/48).
You can gain access to it by installing Hydra 1.1 dev release.

**Comment by omry** [comment]
Closing, feel free to continue the discussion if you have followup questions or comments.

**Comment by lematt1991** [comment]
Thanks @omry, exactly what I was looking for!
