### ISSUE TITLE
[plugins] Proposing change in how plugin versions are tracked

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#1359]
Currently plugin versions are only tracked in setup.py files. I am proposing to track the plugin version in __init__.py files like [hydra-core does](https://github.com/facebookresearch/hydra/blob/master/hydra/__init__.py#L3) and . An additional benefit is that we do not need to provide the version manually to town-crier.

The downside is, hydra-core uses [`find_version`](https://github.com/facebookresearch/hydra/blob/master/build_helpers/build_helpers.py#L16) function to read the version information. We will have to setup an ugly relative import to access this function. Duplicating this function across all the plugins wont be good. Another option can be to just import the __init__.py file from the package (in setup.py)

**Comment by shagunsodhani** [comment]
cc @omry @jieru-hu

**Comment by jieru-hu** [comment]
@shagunsodhani I'm not familiar with how towncrier works, could you provide more information on how it works now in Plugin vs hydra-core (since this seems to be the main motivation :) )

**Comment by shagunsodhani** [comment]
There are two ways to tell towncrier about the version:

1. a __version__ in the top level package. This can be either a string literal, a tuple, or an Incremental version.
2. Manually passing --version=<myversionhere> when interacting with towncrier.

Hydra core uses the first option.

For plugins, we are using the second option right now but would want to move to the first option.

**Comment by omry** [comment]
Hydra is big enough to justify some build related logic.
plugins, not so much (and I would definitely not want to replicate some functions into each plugin for that purpose).
There are some libraries that can help with module versioning.
[This](https://pypi.org/project/setuptools-git-versioning/) is pretty feature rich but not very popular (seems rather new).

The overhead of maintaining a proper release process for plugins can become too much. At this point I am not convinced using towncrier to plugin is worth it but I am willing to give it a try.
If you want to try to improve the process make a concrete proposal and we can discuss it.

**Comment by omry** [comment]
I already fixed this. Plugins version is now obtained from `__version__` in `hydra_plugins.XYZ_plugin.__init__.py`.
