### ISSUE TITLE
Confusing error message when overriding hydra/launcher from a nested defaults list without absolute and global package

### ISSUE THREAD

**Issue by Queuecumber** [facebookresearch/hydra#1365]
# 🐛 Bug
## Description

I have a config file which, among other things, is supposed to turn on the "submitit_slurm" launcher. This is not the "main" config for the python file, it's another config which I add in using the command line. When I add this config, I get the following error:

```
/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:394: UserWarning: In cluster/slurm_fair: Invalid overriding of hydra/launcher:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/defaults_list_override for more information.

  warnings.warn(msg, UserWarning)
In 'cluster/slurm_fair': Could not override 'hydra/launcher'. No match in the defaults list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

but I'm not trying to override hydra/launcher I'm trying to add it so I think it should work and changing the config to `override hydra/launcher: submitit_slurm` throws the same error. See minimal repro.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

**code** 

minimal.py:

```
import hydra
from omegaconf import DictConfig


@hydra.main(config_name="minimal", config_path="configs")
def main(cfg: DictConfig):
    return


if __name__ == "__main__":
    main()
```

**configs**, place in a folder named `configs`

minimal.yaml:

```
defaults:
  - hydra/launcher: submitit_slurm
```

Note: This file can be empty and it won't change the behavior at all

slurm.yaml, place in `configs/launcher`

```
defaults:
  - hydra/launcher: submitit_slurm
```

**run** 

`python minimal.py` this will work fine
`python minimal.py +launcher=slurm` this will crash with the stated error. Again this happens regardless of the contents of `minimal.yaml` and adding `override` in `slurm.yaml` also doesn't help.

**Stack trace/error message**
```
/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/defaults_list.py:394: UserWarning: In cluster/slurm_fair: Invalid overriding of hydra/launcher:
Default list overrides requires 'override' keyword.
See https://hydra.cc/docs/next/upgrades/1.0_to_1.1/defaults_list_override for more information.

  warnings.warn(msg, UserWarning)
In 'cluster/slurm_fair': Could not override 'hydra/launcher'. No match in the defaults list.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
No error.

## System information
- **Hydra Version** :  1.1.0.dev3
- **Python version** : 3.7.7
- **Virtual environment type and version** : 
- **Operating system** :

**Comment by omry** [comment]
> but I'm not trying to override hydra/launcher I'm trying to add it so I think it should work and changing the config to override hydra/launcher: submitit_slurm throws the same error. See minimal repro.

You can't add it because Hydra is adding it automatically.
You need to override it.

To make it easier to help you, can you provide a small zip file containing your directory structure (code and config of the repro) that results in that error?

**Comment by omry** [comment]
The problem is PROBABLY is:

> slurm.yaml, place in configs/launcher

Placing it in a config group launcher has implications. Defaults list elements are relative to the config group the file is in (as of Hydra 1.1). This probably means that Hydra is looking for a config group launcher/hydra/launcher.

In any case, I am guessing., provide a runnable example and I can help you without guessing.

**Comment by Queuecumber** [comment]
[minimal.zip](https://github.com/facebookresearch/hydra/files/5901323/minimal.zip)

Attached, I think this one describes exactly the scenario you mentioned (the "you need to override it" part)

Running with `HYDRA_FULL_ERROR=1`:

```
Traceback (most recent call last):
  File "minimal.py", line 11, in <module>
    main()
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/main.py", line 38, in decorated_main
    strict=strict,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 365, in _run_hydra
    lambda: hydra.run(
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 215, in run_and_report
    raise ex
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 212, in run_and_report
    return func()
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/utils.py", line 368, in <lambda>
    overrides=args.overrides,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 105, in run
    run_mode=RunMode.RUN,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 547, in compose_config
    from_shell=from_shell,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 156, in load_configuration
    from_shell=from_shell,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/config_loader_impl.py", line 187, in _load_configuration_impl
    skip_missing=run_mode == RunMode.MULTIRUN,
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 727, in create_defaults_list
    overrides.ensure_overrides_used()
  File "/private/home/mehrlich/.conda/envs/qgac/lib/python3.7/site-packages/hydra/_internal/defaults_list.py", line 162, in ensure_overrides_used
    raise ConfigCompositionException(msg)
hydra.errors.ConfigCompositionException: In 'launcher/slurm': Could not override 'hydra/launcher'. No match in the defaults list.
```

I agree with your most recent comment, it's probably something to do with that

BTW one thing that might help resolve via a workaround: is there a way to include a default on the command line that doesn't have a package? I remember reading in the docs that you can have something in your defaults list lie:

```
defaults:
  - something
```

and it will include the contents of `something.yaml` from the root of the config path, is there a way to use the command line to do that? I tried `python whatever.py ... +something` and got a parse error for missing `=`

**Comment by omry** [comment]
Add a global package header to your  your launcher/slurm.yaml and use absolute addressing:
```
# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm
```
This is documented in [configuring experiments](https://hydra.cc/docs/next/patterns/configuring_experiments).
The error is definitely confusing and I will take a look see how it can be improved.

**Comment by Queuecumber** [comment]
Yeah thats perfect, I didn't know you could do an absolute path like that, I actually need to go over the 1.1 docs in more details because I know a lot of stuff changed

**Comment by omry** [comment]
With #1372, you get this output when you make this mistake.
```
minimal$ python minimal.py +launcher=slurm
In 'launcher/slurm': Could not override 'launcher/hydra/launcher'. No match in the defaults list.
```

Hopefully it's enough to put you on the right track.
