### ISSUE TITLE
docusaurus immer dependency need to be updated 

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#1379]
This is blocked  for now, once the following is resolved we can update to get rid of the security warning
https://github.com/facebook/docusaurus/discussions/4093 
https://github.com/facebook/create-react-app/pull/10412

**Comment by omry** [comment]
Please use issue labels :)

**Comment by jieru-hu** [comment]
Still waiting for a new Docusaurus release.

**Comment by omry** [comment]
I think the new release is out.

**Comment by omry** [comment]
Is this done?
