### ISSUE TITLE
[Bug] Mandatory values parsed as strings

### ISSUE THREAD

**Issue by czrcbl** [facebookresearch/hydra#1382]
# 🐛 Bug
## Description
The mandatory values (???) are being parsed as strings.

## Checklist
- [ x] I checked on the latest version of Hydra
- [ x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

``` yaml
# config.yaml
PROJECT_DIR: ../../root
expname: ???
type: xxxx
```

``` python
# main.py
import hydra
from omegaconf import DictConfig

@hydra.main(config_path=".", config_name="config")
def main(cfg: DictConfig):
    print(cfg)
    
if __name__ == '__main__':
    main()
```

Then `python main.py`
```
{'PROJECT_DIR': '../../root', 'expname': '???', 'type': 'xxxx'}
```

## Expected Behavior
A error indicating that the `expname` parameter was not set on command line.

## System information
- **Hydra Version** :  1.0.6
- **Python version** : 3.9.1
- **Virtual environment type and version** : conda 4.9.2
- **Operating system** : Pop OS 20.10

**Comment by jieru-hu** [comment]
Thanks for the issue. 

- This is a [`omegaconf`](https://omegaconf.readthedocs.io/en/latest/usage.html#mandatory-values) behavior so better belong to the omegaconf repo.
- I think this is expected - accordingly to Omegaconf's doc
```
Use the value ??? to indicate parameters that need to be set prior to access

```

in your case if you try to do `cfg.expname` the exception will be thrown.


```
>>> from omegaconf import OmegaConf
>>> cfg=OmegaConf.create({"exp": "???"})
>>> cfg
{'exp': '???'}
>>> cfg.exp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jieru/opt/anaconda3/envs/pytest38/lib/python3.8/site-packages/omegaconf/dictconfig.py", line 305, in __getattr__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/Users/jieru/opt/anaconda3/envs/pytest38/lib/python3.8/site-packages/omegaconf/base.py", line 95, in _format_and_raise
    format_and_raise(
  File "/Users/jieru/opt/anaconda3/envs/pytest38/lib/python3.8/site-packages/omegaconf/_utils.py", line 694, in format_and_raise
    _raise(ex, cause)
  File "/Users/jieru/opt/anaconda3/envs/pytest38/lib/python3.8/site-packages/omegaconf/_utils.py", line 610, in _raise
    raise ex  # set end OC_CAUSE=1 for full backtrace
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: exp
        full_key: exp
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=dict

```

**Comment by omry** [comment]
This is not a bug, but maybe a missing feature.
Missing fields a legal part of the config. in fact you can populate them later in code.
As pointed out in both the [OmegaConf docs](https://omegaconf.readthedocs.io/en/latest/usage.html#mandatory-values) and the [Hydra basic tutorial](https://hydra.cc/docs/tutorials/basic/your_first_app/using_config), accessing missing fields raises an exception.

Feel free to submit a feature request to support eager evaluation of missing fields and failing if any are present in the config.
