### ISSUE TITLE
Ability to check invariants across parameters in the structured config

### ISSUE THREAD

**Issue by lminer** [facebookresearch/hydra#1398]
Once you start getting into complex applications, it is very possible that one parameter will depend on the value of another parameter.

Here's a simple deep learning example. Let's say I have a parameter that is a list corresponding to the dropout rate you want to use on each layer, and I also have a parameter that determines the number of layers in the network. It would be nice to have a check built into the structured config schema that would throw an error if the number of layers != the length of the list.

It seems like you could use a mechanism similar to custom variable interpolations for this.

**Comment by omry** [comment]
Hi @lminer.
Tanks for the feature request. Something like this belongs in OmegaConf.
There are already a couple of enhancement requests covering this to a large extent
- https://github.com/omry/omegaconf/issues/131
- https://github.com/omry/omegaconf/issues/91

For now you can do your the checks in your own code.
Closing as this is not a feature request for Hydra.
