### ISSUE TITLE
[config revolver]

### ISSUE THREAD

**Issue by emilemathieu** [facebookresearch/hydra#1400]
# 🚀 Feature Request

Hi! Is it possible to perform simple calculation in the `config.yaml` file? For instance would like to compute `mem_gb: ${126 / 8 * ${num_gpus}}` ion my `slurm.yaml`.

Best,
Emile

**Comment by YannDubs** [comment]
I think it's not yet possible by default (you could define your own resolvers), but hopefully soon : https://github.com/omry/omegaconf/issues/91

**Comment by YannDubs** [comment]
Just in case for resolvers you can find an example here : https://stackoverflow.com/questions/61714759/how-can-i-use-omegaconf-custom-interpolation-with-hydra/61736674#61736674 

@omry I would consider adding that to the advanced doc :)
