### ISSUE TITLE
[Bug] --hydra-help hangs/crashes running in home directory

### ISSUE THREAD

**Issue by laughingrice** [facebookresearch/hydra#1411]
# 🐛 Bug
## Description
It looks like --hydra-help tries to scan the entire subdirectory tree making it hang or crash if run in home directory or high up in the hierarchy.

Running the attached minimal example in it's own directory works fine, but trying to do the same in the home directory on a mac (`python ./hydra_test.py --hydra-help`) first complained on no access to .Trash (default security setting on modern osx), then when that was "fixed" it ran for several minutes, finally crashing apparently going into some link tracking loop (error message attached)

## Checklist
- [v ] I checked on the latest version of Hydra
- [v ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
 import omegaconf as oc
 import hydra

 @hydra.main()
 def app(cfg: oc.DictConfig) -> None:
     print(oc.OmegaConf.to_yaml(cfg))

 if __name__ == '__main__':
     app()
```

** Stack trace/error message **

```
OSError: [Errno 63] File name too long: '/Users/micha/opt/miniconda3/lib/python3.8/site-packages/hydra/conf/Library/Caches/org.videolan.vlc/org.sparkle-project.Sparkle/VLC 3.0.12/Applications/Microsoft Teams.app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/Microsoft Teams Helper (GPU).app/Contents/Frameworks/ADAL.framework/Versions/A/_CodeSignature'
```

## Expected Behavior

Return a help message without scanning recursively through the entire directory structure

## System information
- **Hydra Version** :   1.0.6
- **Python version** :  3.8.8
- **Virtual environment type and version** :  none
- **Operating system** : osx big sur (11.2.1)

all installed via anaconda

**Comment by omry** [comment]
This is not a bug, please provide a config directory.
The if not specified, the config directory is cwd. Hydra --help scans for config groups which is what taking forever in this case.

```
 import omegaconf as oc
 import hydra

@hydra.main(config_path="conf")
 def app(cfg: oc.DictConfig) -> None:
     print(oc.OmegaConf.to_yaml(cfg))
```
