### ISSUE TITLE
[Not Instantiating objects but get class]

### ISSUE THREAD

**Issue by emilemathieu** [facebookresearch/hydra#1412]
# 🚀 Feature Request

Hi all !

Really love the `Instantiating objects` feature. Was wondering whether it's possible to not instantiate the object, but still to get the python class / function from the string parameter. As `my_class = eval(cfg.parameter)` with `cfg.parameter = MyClass` would do.

Best,
Emile

**Comment by omry** [comment]
You can use hydra.utils.get_class().

**Comment by emilemathieu** [comment]
@omry Thanks!
Is there a way to do this in within a recursive `net = hydra.utils.instantiate(cfg.arch)`? As in having a config like `conf/arch/resnet50.yaml` looking like
```
_target_: architecture.ResNet
layers: [3, 4, 6, 3]
block:
  _target_: torchvision.models.resnet.Bottleneck 
```
but only want the `block` to be a class, not be instantiated.

**Comment by omry** [comment]
You can have your target points to a function that will return the class instead of instantiating it :).

**Comment by omry** [comment]
Maybe something like this:
```python
block:
  _target_: hydra.utils.get_class
  path: torchvision.models.resnet.Bottleneck
```
