### ISSUE TITLE
Config variable interpolation with custom resolver doesn't call the resolver

### ISSUE THREAD

**Issue by mfuntowicz** [facebookresearch/hydra#1415]
Using the following configuration:

_foo.yaml_
```yaml
num_threads: 0
```

_main.py_
```python
if __name__ == '__main__':
    # Custom resolver to fill empty env variable
    OmegaConf.register_resolver("plus_10", lambda x: str(int(x) + 10))
    run()
```

When using value interpolation, the resolver is not being called while statically setting the value correctly calls the resolver.

**Static Value**

_openmp.yaml_
```yaml
# @package hydra.job.env_set
OMP_NUM_THREADS: ${plus_10:0}
```

Result: 
```python
>>> OMP_NUM_THREADS: 10
```

**Dynamic Value**

_openmp.yaml_
```yaml
# @package hydra.job.env_set
OMP_NUM_THREADS: ${plus_10:${num_threads}}
```

Result: 
```python
>>> OMP_NUM_THREADS: ${plus_10:0}
```

**I'm using Hydra v1.1-pre3**

**Comment by omry** [comment]
I can't understand your report.
Please create a complete minimal runnable example reproducing the problem.

**Comment by omry** [comment]
Also, nested interpolations requires OmegaConf 2.1dev20. Please upgrade to Hydra 1.1.0dev4 and to the latest OmegaConf.
Closing, if you still have an issue please provide a complete runnable example.
