### ISSUE TITLE
Sub-config Interpolation

### ISSUE THREAD

**Issue by benjamindkilleen** [facebookresearch/hydra#1419]
# 🚀 Feature Request

Interpolation is a great feature. Is it possible to interpolate sub-configs as well as single values?

## Motivation

**Is your feature request related to a problem? Please describe.**

I'm frustrated when I have to copy-paste entire portions of my config file because the code is structured in such a way that different objects need access to the same config objects.

## Pitch

Copy-pasting config variables is a headache and liable to create errors.

**Describe the feature.**

Copy a sub-config when that's the value being interpolated.

For example, imagine I had a computer vision dataset that internally generated images with a certain shape, and then I wanted my model to know that input shape (to configure layer input). I might write

```yaml
dataset:
  name: my_dataset
  image_config:
    channels: 3
    height: 224
    width: 224

model:
  name: my_model
  image_config: ${dataset.image_config}
```

and expect the interpolated output to look like:

```yaml
dataset:
  name: my_dataset
  image_config:
    channels: 3
    height: 224
    width: 224

model:
  name: my_model
  image_config:
    channels: 3
    height: 224
    width: 224
```

but instead, `model.image_config` contains the un-interpolated string "${dataset.image_config}".

**Describe alternatives you've considered**

There are two alternatives:
1. Copy-paste the source sub-config and its values.
2. Copy-paste the source sub-config, but use interpolation for the values. This is obviously better, since at least the values are stored in only one place, but what if I want the dataset to have a new parameter?
3. Handle the copying in the user's code. But this is basically offloading the interpolation to the user in a not-very-configurable way.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes, but it would take a while...

**Comment by omry** [comment]
Interpolation is a feature of OmegaConf. I suggest you read the docs of OmegaConf.
Yes, you can interpolate into config nodes, not just config values.
Interpolations are evaluated lazily.
```python
In [1]: from omegaconf import OmegaConf

In [2]: cfg = OmegaConf.create("""\
   ...: dataset:
   ...:   name: my_dataset
   ...:   image_config:
   ...:     channels: 3
   ...:     height: 224
   ...:     width: 224
   ...: 
   ...: model:
   ...:   name: my_model
   ...:   image_config: ${dataset.image_config}
   ...:   """)

In [3]: print(OmegaConf.to_yaml(cfg))
dataset:
  name: my_dataset
  image_config:
    channels: 3
    height: 224
    width: 224
model:
  name: my_model
  image_config: ${dataset.image_config}


In [4]: print(OmegaConf.to_yaml(cfg, resolve=True))
dataset:
  name: my_dataset
  image_config:
    channels: 3
    height: 224
    width: 224
model:
  name: my_model
  image_config:
    channels: 3
    height: 224
    width: 224


In [5]: cfg.model.image_config
Out[5]: {'channels': 3, 'height': 224, 'width': 224}
```

**Comment by alexcoca** [comment]
> Interpolation is a feature of OmegaConf. I suggest you read the docs of OmegaConf. Yes, you can interpolate into config nodes, not just config values. Interpolations are evaluated lazily.
> 
> ```python
> In [1]: from omegaconf import OmegaConf
> 
> In [2]: cfg = OmegaConf.create("""\
>    ...: dataset:
>    ...:   name: my_dataset
>    ...:   image_config:
>    ...:     channels: 3
>    ...:     height: 224
>    ...:     width: 224
>    ...: 
>    ...: model:
>    ...:   name: my_model
>    ...:   image_config: ${dataset.image_config}
>    ...:   """)
> 
> In [3]: print(OmegaConf.to_yaml(cfg))
> dataset:
>   name: my_dataset
>   image_config:
>     channels: 3
>     height: 224
>     width: 224
> model:
>   name: my_model
>   image_config: ${dataset.image_config}
> 
> 
> In [4]: print(OmegaConf.to_yaml(cfg, resolve=True))
> dataset:
>   name: my_dataset
>   image_config:
>     channels: 3
>     height: 224
>     width: 224
> model:
>   name: my_model
>   image_config:
>     channels: 3
>     height: 224
>     width: 224
> 
> 
> In [5]: cfg.model.image_config
> Out[5]: {'channels': 3, 'height': 224, 'width': 224}
> ```

Would it be possible to somehow interpolate such that the `image_config` node itself is replaced by the contents of `dataset.image_config`?. In other words, the resolved `model` node would have keys `name`, `channels`, `height`, `width`.

**Comment by odelalleau** [comment]
> Would it be possible to somehow interpolate such that the `image_config` node itself is replaced by the contents of `dataset.image_config`?. In other words, the resolved `model` node would have keys `name`, `channels`, `height`, `width`.

As I mentioned in https://github.com/facebookresearch/hydra/issues/1286#issuecomment-1542274440 this is best done through Hydra's config composition features from the defaults list.

If you want to do it purely with OmegaConf you could do something like this:

```yaml
dataset:
  name: my_dataset
  image_config:
    channels: 3
    height: 224
    width: 224

model_base:
  name: my_model

model: ${merge:${model_base},${dataset.image_config}}
```
where you would need to implement your own `merge` resolver:
```python
OmegaConf.register_new_resolver("merge", lambda *configs: OmegaConf.merge(*configs))
```

There are some drawbacks to this approach though: config access is slower, and you can't modify `cfg.model.*` since it will be dynamically re-generated on each access. This could be solved by resolving the config before using it, but overall using Hydra's defaults list is cleaner IMO.

**Comment by alexcoca** [comment]
This is a fantastic reply - I will look into both options. Thanks so much for helping.
