### ISSUE TITLE
[Bug] Cannot Instantiate a nested interpolated target multiple times

### ISSUE THREAD

**Issue by mantaco1** [facebookresearch/hydra#1430]
# 🐛 Bug
## Description
The recent push to master fixed the original bug referenced in #1410 and #1420. This is essentially the same, but attempting it twice. If the interpolation is instantiated more than once, it doesn't work
## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

#### config_test.yaml
```yaml
child:
    _target_: config_test.Child
parent:
    _target_: config_test.Parent
    child: ${child}
```

##### config_test.py
```python
import hydra
from hydra.utils import instantiate


class Child:
    pass

class Parent:
    def __init__(self, child):
        self.child = child

@hydra.main(config_name="config_test")
def run(cfg):
    parent = instantiate(cfg.parent)
    parent = instantiate(cfg.parent)

    print(parent.child)


if __name__ == "__main__":
    run()
```

```
{}
```

## Expected Behavior
The child object should be correctly instantiated both times.
## System information
- **Hydra Version** :  master (1.1.dev4)
- **Python version** :  3.8
- **Operating system** :  Ubuntu 20.04

## Additional context
Deep copying the dict object allows this to work

**Comment by omry** [comment]
#1433 should fix it.
