### ISSUE TITLE
[Bug] Fish shell tests are broken with fish 3.2.0

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#1442]
There are a few expected outputs from fish 3.2.0 that seems to be breaking the tests.

@binshengliu - mind taking a look?
It looks like the trick to start fish without configuration no longer works as it was in previous versions:
```
 # Start fish without user configuration
 set env(HOME) /dev/null
```

This is example output:
```
omry@Coronadev:~/dev/hydra$ HOME=/dev/null fish;
error: Your history will not be saved.
warning-path: Unable to locate data directory derived from $HOME: '/dev/null/.local/share/fish'.
warning-path: The error was 'Not a directory'.
warning-path: Please set $HOME to a directory where you have write access.

error: Your personal settings will not be saved.
warning-path: Unable to locate config directory derived from $HOME: '/dev/null/.config/fish'.
warning-path: The error was 'Not a directory'.
warning-path: Please set $HOME to a directory where you have write access.

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
omry@Coronadev /h/o/d/hydra (fish)> 
```

Even providing a clean home dir does not achieve the required behavior:
```
omry@Coronadev:~/dev/hydra$ HOME=/tmp/3231232 fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
omry@Coronadev /h/o/d/hydra (fish)> 
```

As a temp workaround I am disabling fish shell tests.

**Comment by binshengliu** [comment]
Sure. I can have a look.

**Comment by omry** [comment]
Great, thanks.

**Comment by omry** [comment]
Possibly way to handle it:
Allocate a temp directory as test home dir and place a `~/.config/fish/config.fish` inside.
Content can customize the prompt similarly to how we are customizing the prompt in bash.
(Check the corresponding bash expect script).

```fish
function fish_prompt
    echo -n '>> '
end
```

I think this logic should be a part of the fish expect script and not a part of the Python test (to make it easier to test the expect script manually).

**Comment by binshengliu** [comment]
It seems the tests had been off before 3.2.0 due to the version check. I haven't been following fish's releases but it seems 3.2.0 was just released a few days ago, which switched on the tests. Not only the HOME trick but some test cases also seem problematic. I'll try to fix them together.
