### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by miraodasilva** [facebookresearch/hydra#1453]
# 🐛 Bug
## Description

Nested defaults don't seem to be working for me.
## Checklist
- [ X ] I checked on the latest version of Hydra
- [ X ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
I just used the example under examples/advanced/nested_defaults_list
** Stack trace/error message **
```
debug: false
name: apache
```

## Expected Behavior
It is missing "name: mysql", which would have been imported in the defaults on apache.yaml.

I suppose maybe this example is outdated? If so, how would one update it to produce the expected result on 1.0.6? I am asking because I am trying nested defaults in my own project using the same logic as this example, and it does not work. Defaults work fine for config.yaml, but any defaults on nested config files don't work. I looked through the docs for quite a while but maybe I missed something.

## System information
- **Hydra Version** :  1.0.6
- **Python version** : Python 3.7.6
- **Virtual environment type and version** : conda 4.8.2
- **Operating system** :  Ubuntu 18.04

**Comment by jieru-hu** [comment]
Recursive defaults is introduced in Hydra 1.1. Could you try this on 1.1 instead?
Also the example is only availble on the master branch (Hydra 1.1)  not on the 1.0_branch.

**Comment by miraodasilva** [comment]
You responded in 5 minutes and instantly fixed all my issues. All I can say is:
![image](https://user-images.githubusercontent.com/17463598/110049128-1f87a500-7d49-11eb-94a9-1357b8ec671b.png)
