### ISSUE TITLE
[Bug] Custom resolver interpolation with interpolated parameters does not work

### ISSUE THREAD

**Issue by kdonbekci** [facebookresearch/hydra#1455]
# 🐛 Bug
## Description
Nested custom resolver interpolations do not work as expected. Specifically when registering a custom resolver whose parameters are themselves variable interpolations, the custom resolver is treated as a string.

## To reproduce
If we have a `config.yaml` file as follows: 
```
a: 10
b: 10
c: "${add:${a},${b}}"
d: "${add:10,10}"
```
and a `main.py` file as follows:
```
from omegaconf import OmegaConf
import hydra
OmegaConf.register_resolver("add", lambda x, y: int(x) + int(y))

@hydra.main(config_name='config')
def main(cfg):
    print(cfg.c) # WRONG >> ${add:10,10}
    print(cfg.d) # CORRECT >> 20 

if __name__ == '__main__':
    main()
```

## Expected Behavior
We would expect first output to be the addition of `a` and `b` = 20. This is said to be supported at the OmegaConf documentation [here](https://omegaconf.readthedocs.io/en/latest/usage.html#custom-interpolations).

## System information
- **Hydra Version** :  1.0.6
- **Python version** : 3.6.9
- **Operating system** :  Ubuntu 18.04

**Comment by omry** [comment]
Why are you expecting it to work? is this a feature request?

**Comment by omry** [comment]
Ah, okay - you are pointing to the docs of the next OmegaConf version.

This is coming in Hydra 1.1 which is not released yet. OmegaConf 2.1 (which contains that feature is also not released yet).
You can experiment with both through the dev release of Hydra 1.1. See primary project readme for how to install it.

**Comment by kdonbekci** [comment]
Ah, thanks for the clarification and feel free to close the issue!
