### ISSUE TITLE
[Hydra Docs] Undocumented use of `debug = False` / `debug = True`

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1459]
In the Hydra docs (on master branch) there is undocumented use of a `debug` key.

For example, in https://hydra.cc/docs/next/tutorials/structured_config/schema we have
```yaml title="config.yaml" {2}
defaults:
  - base_config
  - db: mysql

debug: true
```
and
```python
@dataclass
class Config:
    db: DBConfig = MISSING
    debug: bool = False
```

As a new user, I wonder, "how does the `debug` key affect hydra's behavior"?

Here are the places where the `debug` is used in the docs:
- advanced/overriding_packages.md
- advanced/defaults_list.md
- tutorials/structured_config/5_schema.md

**Comment by omry** [comment]
This is an example of a generic field the user might be using for their own app.
Hydra does not care at all about that field.

**Comment by Jasha10** [comment]
Got it. Thanks.
