### ISSUE TITLE
[Question] is there a way to perform inheritance directly in hydra's configuration files? 

### ISSUE THREAD

**Issue by kwanUm** [facebookresearch/hydra#1460]
I often have the following configuration in my projects:

- config.yaml
- model/model1.yaml
- model/model1_with_slight_variation1.yaml 
- model/model1_with_slight_variation2.yaml 
- model/model2.yaml
- model/model2_with_slight_variation1.yaml 
- ...

Where the "*with_slight_variation*.yaml" files copy the same config from the model*.yaml files, and perform certain changes in some of the config specified at the latter.

How can I use hydra to reduce boilerplate copying in this case? I was thinking a simple inheritance direction in the config file can solve this in the future, and not sure what is the best practice for v1.0.

**Comment by jieru-hu** [comment]
Hi!

This is better supported in Hydra 1.1  - https://hydra.cc/docs/next/patterns/extending_configs/

In 1.0, you will have to separate the configs that has slight variations into their own config groups or override from the command-line.

**Comment by kwanUm** [comment]
Amazing. 1.1 rocks!
