### ISSUE TITLE
[Feature Request] Fault tolerance option for sweeps

### ISSUE THREAD

**Issue by hobogalaxy** [facebookresearch/hydra#1462]
# 🚀 Feature Request

Provide flags in Hydra config, that allow user to make sweeps fault tolerant.

## Motivation

When doing sweeps, e.g. hyperparameter search, some of the jobs might crash unexpectedly. For instance one of the experiments might run with batch size so high that gpu runs out of memory and cuda throws exception.
Currently any exception crashes the whole sweep.

It would be great if we could make Hydra ignore such exceptions and just run the next job.
It would be evern better if we could specify how many times Hydra should retry running the same job until moving on to the next one.

## Pitch
```yaml
hydra:
    launcher:
        fault_tolerance: True
        max_failures: 3
```

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Potentially. Seems not that hard to implement so I can try.

**Comment by omry** [comment]
This is a dup of #1377.
Retries is something that can be handled by individual sweeper plugins. (Each one may have a different policy about how to handle failures).
