### ISSUE TITLE
[Feature Request] Access overridden params from main.hydra

### ISSUE THREAD

**Issue by gianscarpe** [facebookresearch/hydra#1466]
# 🚀 Feature Request

 I was wondering if one can access overridden params from the main DictConfig. 

## Motivation

**Is your feature request related to a problem? Please describe.**

Could be useful to consider only overridden parameters, e.g., when one is loading a deep learning model and want to apply only some specific parameters 
## Pitch

**Describe the solution you'd like**

I thing we could have an argument for DictConfig that repliacates the Dict while having only overridden parameters
**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes if this feature is interesting! :)

**Comment by omry** [comment]
You can fine it in the Hydra config singleton.

https://hydra.cc/docs/next/configure_hydra/intro#in-your-code-using-the-hydraconfig-singleton
