### ISSUE TITLE
[Feature Request] Additional Configuration for Optuna plugin

### ISSUE THREAD

**Issue by monney** [facebookresearch/hydra#1472]
# 🚀 Feature Request

Hi I would like to be able to change the sampler settings from default.
## Motivation

Currently we can only pass what sampler to use but not any settings.

## Pitch

**Describe the solution you'd like**
It would be nice if we could pass in arbitrary sampler configs to be instantiated internally.

**Describe alternatives you've considered**
There are only a couple  hot settings I really care about, I imagine most people only change a few things, you could selectively support just a few options.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by omry** [comment]
cc @toshihikoyanase

Hi @monney,
Yes, this makes sense. 

I think we can leverage the new 1.1 support for nested defaults list for this.
It would be great if you initially try to make it without guidance, just based on the 1.1 docs.
[Here](https://hydra.cc/docs/next/advanced/defaults_list) is the doc for the new Defaults List.

**Comment by monney** [comment]
Closed by #1503
