### ISSUE TITLE
[Bug] None is evaluated as a string

### ISSUE THREAD

**Issue by marksibrahim** [facebookresearch/hydra#1473]
# 🐛 Bug
## Description

Python users would expect `None` to be evaluated the same as `null`, but `None` in a `config.yaml` is evaluated as a string. 

## Checklist
- [x] I checked on the latest version of Hydra

## To reproduce

** Minimal Code/Config snippet to reproduce **

`config.yaml`

```
name: None
```

`hydra_app.py`

```
from omegaconf import DictConfig
import hydra


@hydra.main(config_name="config")
def my_app(cfg: DictConfig) -> None:
    print(f"{cfg.name=}")
    if cfg.name is None:
        print("all good")


if __name__ == "__main__":
    my_app()
```

## Expected Behavior

Expect `None` to be evaluated as None, not a string following Python's convention. 

## System information
- **Hydra Version** :  `1.1.0.dev3`
- **Python version** : 3.8 
- **Virtual environment type and version** : 
- **Operating system** : Mac OS

**Comment by marksibrahim** [comment]
Closing, since this seems to be a standard for `yaml` files

**Comment by omry** [comment]
Correct. this is defined by YAML.

**Comment by Keiku** [comment]
If you want to read it as `None` in Python, specify `null`.

```
name: null
```
See also. https://stackoverflow.com/questions/30134110/how-can-i-output-blank-value-in-python-yaml-file/37445121
