### ISSUE TITLE
[List of configs from command line]

### ISSUE THREAD

**Issue by emilemathieu** [facebookresearch/hydra#1474]
# 🚀 Feature Request

Hi all!
I was wondering whether there would be a way to `set a list of configs from the command line` (but not in a sweep manner).

For instance I would like to specify `logger=[csv,wandb]` instead of defined a [`many_loggers.yaml`](https://github.com/hobogalaxy/lightning-hydra-template/blob/main/configs/logger/many_loggers.yaml) file that loads them
```
defaults:
    - csv.yaml
    - wandb.yaml
```

That would also be very convenient to specify a list of custom callbacks for debugging for instance!

Best,
Emile

@YannDubs

**Comment by omry** [comment]
This is coming in Hydra 1.1.
[doc](https://hydra.cc/docs/next/patterns/select_multiple_configs_from_config_group).

You can try it now by installing the dev release (see primary readme).
