### ISSUE TITLE
[Bug] module 'hydra.core' has no attribute 'global_hydra'

### ISSUE THREAD

**Issue by RamanHacks** [facebookresearch/hydra#1475]
# 🐛 Bug
## Description

module 'hydra.core' has no attribute 'global_hydra'
## Checklist
- [ ] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
import hydra
hydra.core.global_hydra.GlobalHydra().clear()
```
** Stack trace/error message **
```
AttributeError: module 'hydra.core' has no attribute 'global_hydra'
```

## Expected Behavior

Expected no error to pop.
## System information
- **Hydra Version** :  1.0.6
- **Python version** : 3.8
- **Virtual environment type and version** : conda 
- **Operating system** : linux

**Comment by omry** [comment]
This is not a documented public API.

What documented API or process are you using to get this error?

**Comment by omry** [comment]
This is the proper way to use the GlobalHydra singleton:
```python
from hydra.core.global_hydra import GlobalHydra
GlobalHydra.instance().clear()
```
