### ISSUE TITLE
[Bug] Cannot write to file with h5py inside main function

### ISSUE THREAD

**Issue by davidcian** [facebookresearch/hydra#1481]
# 🐛 Bug
## Description

For some reason, opening an HDF5 file in write mode with h5py, inside the Hydra main function, does not create a file.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
import h5py

from omegaconf import DictConfig
import hydra

@hydra.main(config_path='ds_conf', config_name='config')
def main_func(cfg: DictConfig) -> None:
  hdf5()

def hdf5():
  hdf_file = h5py.File("test_hdf.hdf5", 'w')
  hdf_file.close()

if __name__ == '__main__':
  main_func()
```

** Stack trace/error message **
```
// Paste the bad output here!
```

## Expected Behavior

I expected a file called `test_hdf.hdf5` to be created at the root directory of my project.

## System information
- **Hydra Version** :  1.0.6
- **Python version** : 3.7.8
- **Virtual environment type and version** : conda
- **Operating system** : Windows 10

## Additional context

Using a context manager changes nothing.

**Comment by jieru-hu** [comment]
Hi,

Hydra manages the apps working dir by default. 

Please check the doc for more info:
https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory
https://hydra.cc/docs/configure_hydra/workdir

for example, as  a workaround, if you do not want to configure the workingdir,  you can potentially create your file with the path
```
hdf_file = h5py.File(hydra.utils.get_original_cwd()/"test_hdf.hdf5", 'w')
```

Please feel free to reopen if you are still experiencing issues. :)
