### ISSUE TITLE
[Bug] [configen] configen fails on modules with `from __future__ import annotations` (default in python 3.10)

### ISSUE THREAD

**Issue by thomkeh** [facebookresearch/hydra#1484]
# 🐛 Bug
## Description
This is the same issue as in omry/omegaconf#303 for which I provided a fix in omry/omegaconf#424. The behavior that will become default in python 3.10, and which can be activated since python 3.7 with `from __future__ import annotations`, breaks configen, because it causes the type annotations to be stored as strings, so it is required to use `get_type_hints()` to parse them.

Python 3.10 is currently only in [alpha 6](https://www.python.org/downloads/release/python-3100a6/), but it's always good to prepare early, I think.

I'm willing to send a pull request!

## Checklist
- [x] I checked on the latest version of Hydra

## To reproduce

```python
from __future__ import annotations


class User:
    def __init__(self, age: int, name: str):
        self.age = age
        self.name = name

    def __repr__(self):
        return f"User: name={self.name}, age={self.age}"


class Admin(User):
    def __init__(self, private_key: str, age: int, name: str) -> None:
        super().__init__(age, name)
        self.private_key = private_key

    def __repr__(self):
        return (
            f"Admin: name={self.name}, age={self.age}, private_key={self.private_key}"
        )
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/Users/tk324/dev/python/hydra/tools/configen/configen/configen.py", line 263, in main
    code = generate_module(cfg=cfg.configen, module=module)
  File "/Users/tk324/dev/python/hydra/tools/configen/configen/configen.py", line 182, in generate_module
    not missing_annotation_type and is_incompatible(type_)
  File "/Users/tk324/dev/python/hydra/tools/configen/configen/configen.py", line 118, in is_incompatible
    if type_ is Any or issubclass(type_, (int, float, str, bool, Enum)):
TypeError: issubclass() arg 1 must be a class

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
configen should work in this case as well.

## System information
- **Hydra Version** :  master
- **Python version** : 3.8.5
- **Virtual environment type and version** : conda 4.8.3
- **Operating system** : MacOS

## Additional context
(In case you're wondering why I would care about this. I usually use `from __future__ import annotations` in my code, because it allows me to use newer type annotation syntax like lowercase `list` instead of `typing.List`, and the new union syntax `str | int` instead of `Union[str, int]`.)

**Comment by omry** [comment]
Thanks @thomkeh, PR welcome :)
