### ISSUE TITLE
[Bug] initializing wandb run prevents hydra logs on dev version

### ISSUE THREAD

**Issue by hobogalaxy** [facebookresearch/hydra#1486]
# 🐛 Bug
## Description
When wandb run is instantiated, hydra logs disappear.
This works incorrectly only on hydra dev version (1.1.0.dev4).

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```python
import hydra
import wandb

from hydra.utils import log


@hydra.main(config_name="config", config_path=".")
def main(config):    
    # this message shows up correctly
    log.info("First message.")

    wandb.init(project="test")
    
    # this message doesn't show up at all
    log.info("Second message.")


main()
```
On hydra 1.0.6 the second message shows up correctly.

## System information
- **Hydra Version** :  1.1.0.dev4
- **Python version** :  3.8.8
- **Virtual environment type and version** : conda
- **Operating system** : Ubuntu 20.04

**Comment by omry** [comment]
```
from hydra.utils import log
```

Why are you reusing the log from hydra.utils?
Check the documentation, you should define your own log instance.
If you do that, do you still have the problem?

**Comment by omry** [comment]
If you use your own logger it works as expected:

```
import hydra
import wandb
import logging

log = logging.getLogger(__name__) 

@hydra.main()
def main(config):
    # this message shows up correctly
    from hydra.utils import log
    log.info("First message.")

    wandb.init(project="test")

    # this message doesn't show up at all
    log.info("Second message.")


main()
```

I am going to close it as invalid, but feel free to continue discussing if you think there is a use case for reusing the internal Hydra logger.
If this is a way to reproduce some other issue, please try to demonstrate it directly.

**Comment by hobogalaxy** [comment]
@omry My bad, I somehow missed that part of documentation. Thank you for the example.

But I still believe something works wrong here, even when using the correct logger. It's actually a weird edge case, so maybe it's not worth investigating, but if you're curious here's what I found out.

There is a problem with running hydra sweeps when using wandb, it can be fixed with setting env variable `WANDB_START_METHOD=thread`, as I found out in this issue: https://github.com/wandb/client/issues/1314


If we set this variable:
```bash
export WANDB_START_METHOD="thread"
```
and run your example then the second message doesn't show up.

As I stated, I only experience it on dev version, hydra 1.0.6 seems to work correctly.

**Comment by omry** [comment]
This seems like a question to wandb, I have no idea what could be happening here.
At this point, Hydra has already configured the logger and is no longer doing anything to it.
My suggestion is that you find a way to tell wandb to not interact with the logging and use Hydra to configure it appropriately.

About threads: Generally speaking the OmegaConf config object is not thread safe. 
I am not expecting anything weird from wandb using threads but just as an FYI.

**Comment by omry** [comment]
[Here](https://hydra.cc/docs/configure_hydra/logging) is an example of how to fully customize the logging with Hydra.
