### ISSUE TITLE
Try to optimize performance of tab completion

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#149]
Determine what takes a long time during tab completion and try to make it faster.

**Comment by omry** [comment]
This is better now.

**Comment by greaber** [comment]
I'm finding that tab completion takes about three seconds, which seems quite slow.  Is this normal?

**Comment by omry** [comment]
No, it is not normal.
tab completion is composing the full config. does it also take you 3 second to compose the config (time between calling the `@hydra.main` function and entering the function?
If so, you either have some very large config or possibly your IO is very slow. (are you running on an NFS mount?).

**Comment by greaber** [comment]
I'm running on an SSD on bare metal.  I just measure composing the config as you suggested, and it takes about 0.6 seconds.  I also tried without loading my normal `.bash_profile`, but that didn't help.

**Comment by omry** [comment]
Please open a new issue and provide details about your hardware, software setup as well as the output of --info.
