### ISSUE TITLE
[Question] how can I load dynamically a configuration from file

### ISSUE THREAD

**Issue by kwanUm** [facebookresearch/hydra#1494]
Using the @hydra.main(config_name="config", config_path="conf") decorator to load the configuration in main is the standard way of working with hydra. But let's say I want to load another configuration file dynamically within the code, is there an easy way of doing it? 

I could try using the ConfigLoader class internally used by hydra, but it doesn't seem to be intended for this type of use.

**Comment by jieru-hu** [comment]
If you are on Hydra 1.1, this [doc](https://hydra.cc/docs/next/advanced/search_path/#internaldocs-banner) might help.

You can also check out the [compose API](https://hydra.cc/docs/experimental/compose_api/)

**Comment by omry** [comment]
Depending on what you do exactly, you may use [OmegaConf APIs](https://omegaconf.readthedocs.io/en/2.0_branch/) directly or use the [Compose API](https://hydra.cc/docs/experimental/compose_api/) Jieru mentioned.
I recommend using the compose API as it supports The Default Lists and overrides much like `@hydra.main()`.
