### ISSUE TITLE
[Feature Request] Interpolation across files

### ISSUE THREAD

**Issue by Waerden001** [facebookresearch/hydra#1504]
# 🚀 Feature Request: Interpolation across ```yaml``` files

Thanks for creating hydra, it really simplifies my ML workflow a lot! 

I would like the ability to reference (relatively)
- to another ```yaml``` file
- to certain values in another ```yaml``` file

## Motivation

Similar to the problem [here](https://github.com/facebookresearch/hydra/issues/1286). I have a PyTorch Project like the following

```
conf
├── config.yaml
├── data
│   └── dataset.yaml
├── architecture
│   ├── component_1.yaml
|   ├── component_2.yaml
│   └── model.yaml
│  
└── trainer
    ├── distributed.yaml
    └── multiple_gpu.yaml
```
component_1 and component_2 are used to assemble the final model. So I'd like to reference to ```component_1.yaml```, ```component_2.yaml``` inside ```model.yaml``` without defining all the parameters of component_1 and component_2 all again in ```model.yaml```. 

## Pitch

Maybe with something like the following

```model.yaml```
```
component_1: ${./architecture/component_1}
component_2: ${./architecture/component_2}
```

Even better, if ```component_1.yaml``` looks like

```
# something configurations
hidden_dim: 10
# some other configurations
```

I'd like to reference to it in ```model.yaml``` with 
```hidden_dim: ${./architecture/component_1:hidden_dim}```

**Comment by omry** [comment]
> Thanks for creating hydra, it really simplifies my ML workflow a lot!

Glad to hear it!

This is already possible by using existing features of Hydra.
Hydra enables you to compose a config object from config files.
Interpolations operating on the config object (composed from your input config files) and are evaluated when you access them.

OmegaConf 2.1 (that comes with Hydra 1.1) will also support relative interpolations.
```
a:
  b: 10
  b2: ${.b}  # relative, 10
  b3: ${a.b}  # absolute, 10
  z1: ${..z} # relative, 20
  z1: ${z} # absolute, 20
 z: 20
```
See my last comment on the issue you linked to for more information.

**Comment by alexcoca** [comment]
@Waerden001 I was wondering if you managed to understand how to do this?

**Comment by Waerden001** [comment]
> 



> @Waerden001 I was wondering if you managed to understand how to do this?

Sorry for the very late reply, it works smoothly for me now.
