### ISSUE TITLE
[Feature Request] String formatting Resolver

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#1505]
# 🚀 Feature Request

It would be nice to have the ability to use numbers -> string formatting like in python. 

## Motivation

When using hyperparameter sweepers the float values that you can get are very ugly e.g. `lbeta=8.472431893578286e-08`. If you use such interpolated values for your directory structure you ned up with directory names like `exp_ince/data_mnist/optfeat_AdamW/lr_0.002193088108976422/wdec_0.002193088108976422/sched_plateau/beta_8.472431893578286e-08/`. It would be much nicer to be able to format those values instead.

## Pitch

**Describe the solution you'd like**

A resolver that allows you to do ssmething like :
```yaml
to_format: 0.00838549
formatted: ${format:${to_format},.1e} # 8.3e-03
```

**Describe alternatives you've considered**
I'm currently using the following code (I think that this should work well for all use cases):
```python
def format_resolver(x, pattern):
    return f"{x:{pattern}}"

OmegaConf.register_new_resolver("format", format_resolver)
```

There are two questions / issues I see (assuming you like the idea):
1/  should it be in Omegaconf or hydra ?
2/ is the (very  hydra-esq) notation `${format:${to_format},.1e}` ok ? or should it by a more pythonesq notation `${format:${to_format}:.1e}`. The former seems simpler to deal with in hydra and probably makes more sense. In the former case I think that the simple resolver I wrote above should be quite general.

**Are you willing to open a pull request?** 
Not in the short term

**Comment by omry** [comment]
This is a nice solution.

```yaml
# careful with the .1e here, I am not sure if it's interpreted as a float or as a string.
formatted: ${format:${to_format},.1e}
```

> 1/ should it be in Omegaconf or hydra ?

At this time, I think not. OmegaConf 2.1 nested interpolations and other new capabilities are opening up a whole possible universe of new resolvers.
I don't think we should strive to include any useful one in the core though. The surface area and the maintenance burden will be very large over time.
You are welcome to use it in your own project.

> 2/ is the (very hydra-esq) notation ${format:${to_format},.1e} ok ? or should it by a more pythonesq notation ${format:${to_format}:.1e}. The former seems simpler to deal with in hydra and probably makes more sense. In the former case I think that the simple resolver I wrote above should be quite general.

This is more of an API design question, right?
I think in principle both can be made to work, but it may be trickier with the second form. (what would the Python code taking a single string look like?).

You can also use str.format directly, but it takes some escaping to pass the braces to it but it's as flexible as str.format (cc @odelalleau, escaping { and }, forgot about those.) :

```python
In [31]: OmegaConf.register_new_resolver("str.format", str.format, replace=True)

In [32]: OmegaConf.create({"a": '${str.format:aa \{:.2\} \{\}, 3.14, "foo bar"}'}).a
Out[32]: 'aa 3.1 foo bar'
```

**Comment by YannDubs** [comment]
Ok I understand that you don't want to add this in hydra in omegaconf. I thought you maybe wanted to have it as there is already the question of adding resolvers for + / - * (https://github.com/omry/omegaconf/issues/91 ) but I agree there should be a limit to what hydra does out of the box.

I'll keep using that in my code, and in case someone else wants something similar they can see how to do it here. I''ll close the issue for now, you can always reconsider if many people ask it :) 

PS: `.1e` actually gets interpreted as a string because of `{pattern}` in the python function which automatically does string conversion.

**Comment by omry** [comment]
> `.1e` actually gets interpreted as a string because of {pattern} in the python function which automatically does string conversion.

By the interpretation I mean how it's interpreted by OmegaConf (what object type your function is getting for the second parameter).

`{pattern}` may be converting the float to a string, but you know that converting floats is a risky business.
