### ISSUE TITLE
[Feature Request] Consistent argument name in compose API

### ISSUE THREAD

**Issue by jsyoo61** [facebookresearch/hydra#1510]
# 🚀 Feature Request

Hi I have a request regarding argument name in compose API

## Motivation

from `initialize` function, the argument for configuration path is `config_path`,
whereas from `initialize_config_dir` function, the argument for the same thing is `config_dir`

>def initialize(
    config_path: Optional[str] = None,
    job_name: Optional[str] = "app",
    caller_stack_depth: int = 1,
) -> None:

>def initialize_config_dir(config_dir: str, job_name: str = "app") -> None:
## Pitch

I thought consistent argument name for the same thing would be convenient.
Thanks in advance!

**Comment by jieru-hu** [comment]
hi @jsyoo61 

The naming is different on purpose.
In particular, `config_path` takes in relative while `config_dir` takes in absolute path. Please check the doc for more info. 
https://hydra.cc/docs/experimental/compose_api
