### ISSUE TITLE
[Bug] Basic tutorial is missing `# @package _group_` directive

### ISSUE THREAD

**Issue by tomsercu** [facebookresearch/hydra#1524]
# 🐛 Bug
## Description
The examples in the Basic tutorial are not up to date; they seem to need a `# @package _group_
` directive to behave as expected; following [these instructions](https://hydra.cc/docs/upgrades/0.11_to_1.0/adding_a_package_directive).

## Checklist
- [x] I checked on the latest version of Hydra : `1.0.6`
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
cd hydra-src/examples/tutorials/basic/your_first_hydra_app/4_config_groups/
python my_app.py +db=mysql
cd ../5_defaults/
python my_app.py
```

Observed output:
```
$ python my_app.py +db=postgresql
driver: mysql
user: omry
pass: secret
```

## Expected Behavior
Matching the [tutorial page](https://hydra.cc/docs/next/tutorials/basic/your_first_app/config_groups), so under package `db`
```
$ python my_app.py +db=postgresql
db:
  driver: postgresql
  pass: drowssap
  timeout: 10
  user: postgres_user
```
## System information
- **Hydra Version** : tried both 1.0.5 and   1.0.6

**Comment by omry** [comment]
There is a big yellow box at the top of the tutorial page you linked:
![image](https://user-images.githubusercontent.com/376455/113238521-cb93b180-925d-11eb-9cc1-5340fa2fdb55.png)

It looks like you are looking at the tutorial for Hydra 1.1 (not yet released).
If you want to try it, you can install the dev release (follow instructions in primary readme).

**Comment by tomsercu** [comment]
AH! yes the directive is there for the `1.0` version! ~~not up to date~~ -> "too up to date" 😅
 sorry for the noise.
And I'd looked at the <=0.11 version in the past, which didn't actually specify the content of the yaml file; but presumably needed to explicitly have `db:` in yaml

**Comment by omry** [comment]
Yeah, the box is something Docusaurus puts there automatically, I don't think I customize it.
Yes, 0.11 is effectively always using _global_ package.
