### ISSUE TITLE
[Feature Request] Print complete prompts when config has more than one missing group configs.

### ISSUE THREAD

**Issue by npuichigo** [facebookresearch/hydra#1525]
Usually, users don't want to specify the default config groups in config.yaml and expect output with full available options.

For example, the config file has three group config fields with missing field.
```yaml
defaults:
    - dataset: ???
    - model: ???
    - trainer: ???
```

Currently, the output would be like:
```
You must specify 'dataset', e.g, dataset=<OPTION>
Available options:
        cifar10
        fastspeech
```
Then, the program just exits.

The feature I request is to show all the options to the users in order to give them some tips:
```
You must specify 'dataset', e.g, dataset=<OPTION>
Available options:
        cifar10
        fastspeech

You must specify 'model', e.g, model=<OPTION>
Available options:
        alexnet
        resnet

You must specify 'trainer', e.g, trainer=<OPTION>
Available options:
        basic_cv_trainer
```

**Comment by jieru-hu** [comment]
Hi @npuichigo 

Thanks for reaching out. This is not something we plan to support at the moment. Please checkout [tab-completion](https://hydra.cc/docs/next/tutorials/basic/running_your_app/tab_completion), which is  could be an alternative to what you are suggesting this.
