### ISSUE TITLE
[Bug] Many calls to deepcopy slow down creating a large number of configs.

### ISSUE THREAD

**Issue by adefossez** [facebookresearch/hydra#1543]
# 🐛 Bug
## Description

As part of an experiment management tool, I typically have to create up to 100 configurations with Hydra, roughly from scratch, using the `compose` API. It seems for a moderately complex config up (around 100 lines), each call to create the Hydra config takes about 0.5 seconds.

While in itself it is not much, when multiplied by the number of XP, this quickly adds up. After running some profiling, it seems about 75% of the time is spent in the `__deepcopy__` method in OmegaConf `DictConfig` (let me know if I should rather open my issue there). For creating one config, there are about 50,000 calls to it.

It would be really helpful to have a way to reduce that number of calls and time spent in creating the config for my usecase.

## Checklist
- [ ] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

I don't have a minimum viable example at the moment but I can work on one.

## System information
- **Hydra Version** :  1.0.4
- **Python version** : 3.8
- **Virtual environment type and version** : virtual env
- **Operating system** : Mac OS X, Linux

**Comment by omry** [comment]
Please try to upgrade to hydra 1.1.

**Comment by adefossez** [comment]
It is solved in hydra 1.1, sorry for not trying that earlier :)

**Comment by omry** [comment]
Awesome.
