### ISSUE TITLE
Overwrite parameters lists from terminal

### ISSUE THREAD

**Issue by soupault** [facebookresearch/hydra#1544]
Hi, thank you for the great tool!

I have not find certain functionality covered in the docs in any form (see below). Thus, I am assuming that it is not currently possibly and might be considered for addition.

# 🚀 Feature Request / Inquiry

I have a parameter block similar to this in the config file:
```python
datasets:
  - name: private_A
    fraction_to_select: 0.2
  - name: public_B
    fraction_to_select: 0.3
```
Then, in the code, I implement a support for arbitrary number of entries in `datasets`:
```python
for d in config.datasets:
  if d.name.startswith("private"):
    dss.append(get_fraction(data[d.name], d.fraction_to_select))
...
```

I have not found much info in the documentation on interacting with this pattern from terminal, I would like to ask the following questions:
1. Is it possible to overwrite from terminal the whole `datasets` block such that the structure in similar and my code will still work?
2. Is it possible to keep the default values as above, but overwrite from the terminal, let's say, `fraction_to_select` for dataset `private_A`?
3. Is it possible to add entries to `datasets` from terminal in addition to `private_A` and `public_B`, e.g. `private_C`?
4. If none of the above is possible, could you, please, recommend an alternative implementation?

## Pitch

**Describe the solution you'd like**
Any implementation would be fine.

**Are you willing to open a pull request?**
Potentially, yes.

**Comment by omry** [comment]
> Hi, thank you for the great tool!
> 
> I have not find certain functionality covered in the docs in any form (see below). Thus, I am assuming that it is not currently possibly and might be considered for addition.
> 
> #  Feature Request / Inquiry
> I have a parameter block similar to this in the config file:
> 
> ```python
> datasets:
>   - name: private_A
>     fraction_to_select: 0.2
>   - name: public_B
>     fraction_to_select: 0.3
> ```
> 
> Then, in the code, I implement a support for arbitrary number of entries in `datasets`:
> 
> ```python
> for d in config.datasets:
>   if d.name.startswith("private"):
>     dss.append(get_fraction(data[d.name], d.fraction_to_select))
> ...
> ```
> 
> I have not found much info in the documentation on interacting with this pattern from terminal, I would like to ask the following questions:
> 
> 1. Is it possible to overwrite from terminal the whole `datasets` block such that the structure in similar and my code will still work?

A lot of this is documented [here](https://hydra.cc/docs/advanced/override_grammar/basic).

```
$ python examples/tutorials/basic/your_first_hydra_app/1_simple_cli/my_app.py  '+datasets=[{name:private, fraction_to_select: 0.2},{foo:10, bar:20}]'
datasets:
- name: private
  fraction_to_select: 0.2
- foo: 10
  bar: 20
```

> 2. Is it possible to keep the default values as above, but overwrite from the terminal, let's say, `fraction_to_select` for dataset `private_A`?

You can do it by index, not by name.
In general, interacting with lists is more limited. If possible represent your config as a dictionary:
```yaml
datasets:
 private_A:
    name: private_A
    fraction_to_select: 0.2
 private_B:
    name: private_B
    fraction_to_select: 0.3
```

This will also enable you to compose datasets much more easily.

> 3. Is it possible to add entries to `datasets` from terminal in addition to `private_A` and `public_B`, e.g. `private_C`?

Not in the current form.
If it was a dictionary would have been able to use the normal composition capabilities of Hydra.
A related feature to this is enabled in Hydra 1.1: [Selecting multiple configs from the same config group](https://hydra.cc/docs/next/patterns/select_multiple_configs_from_config_group).
Note that this lets you compose a dictionary, not a list (even though the input is a list).

> 4. If none of the above is possible, could you, please, recommend an alternative implementation?

I think the best approach is to switch to using a dictionary.
Along with the feature I pointed to, I think you should be covered.
A real-world example of using that feature to do something similar is the [Internal Hydra release tool](https://github.com/facebookresearch/hydra/tree/master/tools/release).
Take a look at the config structure and the readme.
The analog to your datasets there are packages.

**Comment by soupault** [comment]
@omry thank you very much for the detailed reply!

I think I can go forward with the solution you provided in point 1. And it is clear that the recommendations are to switch to using dicts. I assume the returned dicts are ordered, so the modification will not require much effort.

Thanks again for the answers and the references! For some reason, I have been looking through an earlier (pre-1.0) version of the docs indexed by Google.

**Comment by omry** [comment]
dicts are retaining insertion order as of Python 3.6, so the order should be consistent unless the config composition algorithm changes.
