### ISSUE TITLE
[Bug] hydra.errors.MissingConfigException: Could not load datasets/dpr_default.

### ISSUE THREAD

**Issue by cn-boop** [facebookresearch/hydra#1552]
# 🐛 Bug
## Checklist
- [ ] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

** Stack trace/error message **
```
// Paste the bad output here!
```

## System information
- **Hydra Version** :  
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** : 

## Additional context
my version of hydra is 1.0.6, the error occurs

**Comment by jieru-hu** [comment]
@cn-boop pls provide a minimal repro here.

**Comment by omry** [comment]
If you want to report an issue, please fill all the required fields.
