### ISSUE TITLE
[Bug] Unable to Interpolate Config for Hydra Launcher

### ISSUE THREAD

**Issue by Queuecumber** [facebookresearch/hydra#1565]
# 🐛 Bug
## Description

Follow up from Zulip discussion

I'm trying to allow users to define a cluster setting in a top level config group and then use interpolations to copy that config to the hydra/launcher config group, but it fails with the error 

```
Merge error: str is not a subclass of SlurmQueueConf. value: ${cluster}
    full_key: 
    object_type=ExperimentConfig
```

even though the types appear correct. 

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

cluster/test_cluster.yaml
```
name: test
timeout_min: 2160
```

minimal.yaml
```
defaults:
  - experiment
  - cluster: test_cluster
  - override hydra/launcher: submitit_slurm

hydra:
  launcher: ${cluster}
```

minimal.py
```
from dataclasses import dataclass

import hydra
from hydra.core.config_store import ConfigStore
from hydra_plugins.hydra_submitit_launcher.config import SlurmQueueConf


@dataclass
class ExperimentConfig:
    cluster: SlurmQueueConf


cs = ConfigStore.instance()
cs.store(name="experiment", node=ExperimentConfig)


@hydra.main(config_name="minimal", config_path=".")
def main(cfg) -> None:
    print(cfg)


if __name__ == "__main__":
    main()
```

run `python minimal.py --cfg job`

if you comment out the bottom two lines of `minimal.yaml` so that it looks instead like:

```
defaults:
  - experiment
  - cluster: test_cluster
  - override hydra/launcher: submitit_slurm

#hydra:
#  launcher: ${cluster}
```

the script is successful and the `cluster` node seems to have all the correct settings. 

** Stack trace/error message **
```
Merge error: str is not a subclass of SlurmQueueConf. value: ${cluster}
    full_key: 
    object_type=ExperimentConfig
```

This also seems to work if I'm using a custom config, i.e., not a `hydra/` config but something which I defined myself, I can provide an example of this as well.

## Expected Behavior
It should be able to copy that config into the hydra/launchers config group 

## System information
- **Hydra Version** :  1.1.0.dev5
- **Python version** : Python 3.8.2
- **Virtual environment type and version** : venv (not sure of the version)
- **Operating system** : RHEL 7.9

**Comment by omry** [comment]
Thanks, we will take a look.

**Comment by Queuecumber** [comment]
Updated the OP with that info

**Comment by Queuecumber** [comment]
Here's a minimal example of me doing the same thing with my own config nodes (non-hydra/ nodes) and it working, if these are operating slightly differently I can't see it:

cluster/test_cluster.yaml
```
name: test
timeout_min: 2160 # 1.5 days
```

logger/test_logger/yaml
```
name: logger_name
frequency: whatever
```

minimal.yaml
```
defaults:
  - experiment
  - cluster: test_cluster
  - logger: test_logger
  - override hydra/launcher: submitit_slurm

#hydra:
#  launcher: ${cluster}

trainer:
  logger: ${logger}
```

minimal.py
```
from dataclasses import dataclass
from typing import Any

import hydra
from hydra.core.config_store import ConfigStore
from hydra_plugins.hydra_submitit_launcher.config import SlurmQueueConf


@dataclass
class LoggerConfig:
    name: str
    frequency: str
    schema_verification: str = "hello"


@dataclass
class ExperimentConfig:
    cluster: SlurmQueueConf
    logger: LoggerConfig
    trainer: Any


cs = ConfigStore.instance()
cs.store(name="experiment", node=ExperimentConfig)


@hydra.main(config_name="minimal", config_path=".")
def main(cfg) -> None:
    print(cfg.trainer.logger)


if __name__ == "__main__":
    main()
```

Looks the same but if you uncomment the lines in minimal.yaml which set `hydra.logger` you get the crash

**Comment by jieru-hu** [comment]
thanks @Queuecumber 

Could you try the following and see if it is what you what?

```
$ tree .
.
├── cluster
│   └── test_cluster.yaml
├── mini.py
└── mini.yaml

$ cat cluster/test_cluster.yaml 
# @package _global_

hydra:
  launcher:
    name: test
    timeout_min: 2160

$ cat mini.yaml 
defaults:
  - cluster: test_cluster
  - override hydra/launcher: submitit_slurm


$ python mini.py cluster=test_cluster --cfg hydra -p hydra.launcher
# @package hydra.launcher
submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 2160
cpus_per_task: null
gpus_per_node: null
tasks_per_node: 1
mem_gb: null
nodes: 1
name: test
_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
partition: null
comment: null
constraint: null
exclude: null
cpus_per_gpu: null
gpus_per_task: null
mem_per_gpu: null
mem_per_cpu: null
signal_delay_s: 120
max_num_timeout: 0
additional_parameters: {}
array_parallelism: 256
setup: null

```

**Comment by Queuecumber** [comment]
Yeah that works, but that's what I do now (and frankly thats the sensible way to do it) so I knew that would work. 

It's the weird corner case where you try to copy some other node in the config to hydra.launcher using interpolation that is behaving weird. 

Does my minimal example reproduce for you or is it peculiar to my environment somehow?

**Comment by jieru-hu** [comment]
If I understand your example correctly:  you are trying to update the slurm launcher config  with the following, correct?
```
name: test
timeout_min: 2160
```
> Yeah that works, but that's what I do now (and frankly thats the sensible way to do it) so I knew that would work.

Could you paste what you are doing now? My suggestion is different from what you pasted in the description.
In particular, the difference is here
```
$ cat cluster/test_cluster.yaml 
# @package _global_

hydra:
  launcher:
    name: test
    timeout_min: 2160
```

**Comment by Queuecumber** [comment]
> If I understand your example correctly: you are trying to update the slurm launcher config with the following, correct?
> 
> ```
> name: test
> timeout_min: 2160
> ```
Correct but I want to keep it in a top level config group called `cluster` and then update hydra.launcher using interpolation


> > Yeah that works, but that's what I do now (and frankly thats the sensible way to do it) so I knew that would work.
> 
> Could you paste what you are doing now? My suggestion is different from what you pasted in the description.
> In particular, the difference is here
> 
> ```
> $ cat cluster/test_cluster.yaml 
> # @package _global_
> 
> hydra:
>   launcher:
>     name: test
>     timeout_min: 2160
> ```

Sorry the way I am worded that was confusing. I meant that the example you posted mirrors the way I do this in real code so that it doesn't crash. The example I posted reflects how I'd like to do it, but which crashes.

If you copy my example are you able to reproduce?

**Comment by jieru-hu** [comment]
got it. Thanks for clarification. Yes I can repro your example. I will debug and follow up.

**Comment by omry** [comment]
Thanks for reporting @Queuecumber.

Here is a minimal OmegaConf only code reproducing it:
```python
from omegaconf import OmegaConf
from dataclasses import dataclass


@dataclass
class Foo:
    a: int = 10


cfg0 = OmegaConf.structured(
    {
        "hydra": {
            "launcher": Foo,
        },
        "cluster": {"a": 20},
    }
)

cfg2 = OmegaConf.create(
    {
        "hydra": {
            "launcher": "${cluster}",
        }
    },
)

res = OmegaConf.merge(cfg0, cfg2)

print(OmegaConf.to_yaml(res, resolve=True))
```
Having looked at it, I don't think this is an important enough use case to justify any changes at this time.
Fixing this issue, there are other issues behind it. The config merging logic is complicated and this is pushing it to new corners.

While Hydra is very flexible, it is not infinitely flexible and is not meant to support all workflows in existence.

I can think of several more appropriate and supported ways to model what you are trying to do (the one suggested by @jieru-hu  is one of those).

**Comment by Queuecumber** [comment]
I think thats reasonable and what I'm "officially supporting" for this library is actually:

`cluster/vulcan.yaml`
```
# @package _global_
defaults:
 - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    name: ${name} 
    timeout_min: 2160 # 1.5 days
    tasks_per_node:  4
    nodes: 1
    mem_gb: 128
    cpus_per_task: 4
    additional_parameters:
      qos: high
      gres: gpu:gtx1080ti:4
```

but I was a little bit curious why that didnt work, what exactly is the bug that's causing it and why did it work in my case with the `LoggerConfig`? Is it merging the two separately creating config nodes that's the problem?

Side note: these cluster configs are going to get really cool in the next version of omegconf:
```
hydra:
  launcher:
    name: ${name} 
    timeout_min: 2160 # 1.5 days
    tasks_per_node:  ${oc.select:trainer.gpus,1}
    nodes: ${oc.select:trainer.nodes,1}
    mem_gb: ${mm.mul:${.tasks_per_node},32}
    cpus_per_task: 4
    additional_parameters:
      qos: high
      gres: gpu:gtx1080ti:${..tasks_per_node}
``

**Comment by omry** [comment]
What you are officially supporting looks very much like the [Configuring Experiments](https://hydra.cc/docs/next/patterns/configuring_experiments) pattern.
So this approach should be covered well.

> but I was a little bit curious why that didnt work, what exactly is the bug that's causing it and why did it work in my case with the LoggerConfig? Is it merging the two separately creating config nodes that's the problem?

I don't think it actually worked. As of Hydra 1.1, the config composition - for the most part, is not different for the Hydra nodes (with the exception of some high level restrictions unrelated to this).
I did not look closely, but I suspect you didn't actually get any validation in your use case from the dataclass.

**Comment by omry** [comment]
Closing, feel free to followup here if you have additional comments/questions.

**Comment by Queuecumber** [comment]
> I did not look closely, but I suspect you didn't actually get any validation in your use case from the dataclass.

I do get validation actually, but I think this is pretty complex, let me try to summarize what I just did. 

First off you can see the validation by making a small change to `test_logger.yaml`:

```
name: logger_name
frequency: whatever
invalid_field: check
```

this fails with the error `Key 'invalid_field' not in 'LoggerConfig'`

But of course that should fail because we've defined the top level logger package to be of type `LoggerConfig`. What we really want to test is that `trainer.logger` gets validation:

```
@dataclass
class LoggerConfig:
    name: str
    frequency: str
    schema_verification: str = "hello"


@dataclass
class TrainerConfig:
    logger: LoggerConfig


@dataclass
class ExperimentConfig:
    cluster: SlurmQueueConf
    logger: Any
    trainer: TrainerConfig
```

Note that the top level logger can be anything now and only `trainer.logger` is supposed to be the type `LoggerConfig`. This succeeds (it does not error out like setting the `hydra.launcher` field does) **but** it doesn't get any validation (you can set `invalid_field` with no issue and the `schema_verification` field is not set). 

What is a little closer to the situation I was trying to replicate however is something like this:

```
@dataclass
class LoggerConfig:
    name: str
    frequency: str
    schema_verification: str = "hello"


@dataclass
class TrainerConfig:
    logger: LoggerConfig


@dataclass
class ExperimentConfig:
    cluster: SlurmQueueConf
    logger: LoggerConfig
    trainer: TrainerConfig
```

where both the top level `logger` field and the `trainer.logger` field are of type `LoggerConfig` (this should mimic that the top level `cluster` field is of type `SlurmQueueConf` and the `hydra.launcher` field is of type `SlurmQueueConf`). This also **works fine** (no crash) and since the top level `logger` field is now typed, you even get the validation as well.

So I really don't know whats special about `hydra.launcher` that's causing it to crash, but it seems like it's more complicated than expected. I have yet to try the omegaconf example which might shed some light on it.
