### ISSUE TITLE
[Bug] Incorrect wrapper config handling

### ISSUE THREAD

**Issue by topshik** [facebookresearch/hydra#1568]
# 🐛 Bug
## Description
While having two scripts and config file in the same folder, I cannot import a function decorated with `hydra.main`

## Checklist
- [+] I checked on the latest version of Hydra
- [+] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
Tree:
```
.
├── conf.yaml
├── first.py
└── second.py
```
```
# conf.yaml
a: 123
```

```
# first.py
import hydra
from omegaconf import DictConfig


@hydra.main(config_path=".", config_name="./conf.yaml")
def main(config: DictConfig) -> None:
    print(config.a)


def entry():
    main()


if __name__ == "__main__":
    main()
```

```
# second.py
from first import entry

entry()
```

** Stack trace/error message **
```
python first.py
> 123

python second.py
> Traceback (most recent call last):
  File "/Users/topshik/test/hydra-conf-test/second.py", line 3, in <module>
    entry()
  File "/Users/topshik/test/hydra-conf-test/first.py", line 11, in entry
    main()
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/main.py", line 32, in decorated_main
    _run_hydra(
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 346, in _run_hydra
    run_and_report(
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 201, in run_and_report
    raise ex
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/utils.py", line 347, in <lambda>
    lambda: hydra.run(
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 100, in run
    cfg = self.compose_config(
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 505, in compose_config
    self.config_loader.ensure_main_config_source_available()
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 138, in ensure_main_config_source_available
    self.missing_config_error(
  File "/usr/local/anaconda3/envs/p39/lib/python3.9/site-packages/hydra/_internal/config_loader_impl.py", line 112, in missing_config_error
    raise MissingConfigException(
hydra.errors.MissingConfigException: Primary config module is empty.
Python requires resources to be in a module with an __init__.py file
```

## Expected Behavior
I expect both commands `python first.py` and `python second.py` to have the same output `123`. However, it happens only with one of the files.

## System information
OS: macOS 11.2.3 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: version 3.18.3

- **Hydra Version** :  hydra-core==1.0.6
- **Python version** : Python 3.9.2
- **Virtual environment type and version** : conda 4.9.2

## Additional context
Adding `__init__.py` to the same folder does not help. However, changing structure to
```
.
├── my_package
│   ├── __init__.py
│   ├── conf.yaml
│   └── first.py
└── second.py
```
works great. I do not think that such explicit packaging should be obligatory to reuse hydra-decorated functions between python modules.

**Comment by omry** [comment]
We will take a look, but please explain why you need to import entry() in the first place.
`@hydra.main()` functions are not designed to be used as regular functions, they behave differently than regular functions and have many side effects.

Trying to hide it behind a second function does not really make those underlying issues go away.
What are you actually trying to achieve?

**Comment by topshik** [comment]
My use case is the following:

I have two different scripts doing different stuff. One of them has `main()` function decorated with `hydra.main` and can be used as a standalone script. Another one has a flag which sometimes involves most of the logic of the first script.

**Comment by omry** [comment]
You can refactor your code as follows:
```
# Your logic operating on the config
def train(cfg : DictConfig):
  ...
```
first script:
```python
@hydra.main(...):
def main(cfg : DictConfig):
  train(cfg)
```

second script without hydra.main (maybe a unit test, or from a Jupyter notebook):
Using the [Compose API](https://hydra.cc/docs/experimental/compose_api):
```python
def script():
  initialize(...) # initialize Hydra.
  cfg = compose(...) # see the compose API
  train(cfg)
```

**Comment by topshik** [comment]
Thanks, I missed this section in docs! 

That will work, but I still wonder why hydra requires explicit package initialization? Doesn't it follow obsolete Python standards? Isn't it better to allow users to use hydra.main without it, not necessarily forcing them to switch to Compose API?

**Comment by omry** [comment]
Your comment is odd to me:

> That will work, but I still wonder why hydra requires explicit package initialization? Doesn't it follow obsolete Python standards? 

What are you talking about? What explicit package initialization? What Python standards are covering what Hydra is doing?

> Isn't it better to allow users to use hydra.main without it, not necessarily forcing them to switch to Compose API?

You are attempting to use `@hydra.main()` in a way it was not designed to be used.

`@hydra.main` is very much not a normal function.
For example:
1. It changes your working directory.
2. It configures the Python logging
3. It can call the wrapped function multiple times
4. It changes global state.
5. It uses some sophisticated tricks to automatically discover the module of the file containing it, to enable the functionality of the config path relative to the containing file/module.

I do plan to investigate this, but:
1. This is low priority, so it will take time.
2. There is a good chance this is not fixable at all.
3. Even if this is fixed, you will likely have other issues because you are using the API is an unsupported way.

If you want to help, you are very welcome to investigate and send a pull request.
Otherwise I suggest you find a way to not depend on this in the short term because this is not getting fixed soon (if at all).

**Comment by topshik** [comment]
Thanks for detailed response!

**Comment by topshik** [comment]
And as for explicit package initialization, I was speaking about the necessity to add `__init__.py` to the sub directory of the project in my initial commit.

**Comment by omry** [comment]
Hydra is using importlib_resources to load the resources, and this is required to import resources from modules.
The same Hydra app can operate both as a script (`python foo.py`, where the config is loaded using file system API which does not require `__init__.py` and as a module, where the config is loaded using impotlib_resources API that requires the module to be importable.
The correct way to define a Python module is with an `__init__.py`.

[Here](https://github.com/facebookresearch/hydra/issues/719) is some additional context from when this was changed.

I vaguely remember an importlib-resource limitation that prevents it from loading config files from the root module. This could be related to error you are seeing.

In any case, I strongly recommend that you place your configs in a module (there is no need for your script file to be in a module, just the config(s)).
See [this](https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path) for additional motivation.
