### ISSUE TITLE
[Bug] Params with default MISSING value in the Structured Config Schema don't get parsed from the command line

### ISSUE THREAD

**Issue by danielgafni** [facebookresearch/hydra#1572]
# 🐛 Bug
## Description
I'm trying to reproduce the code from [the documencation](https://hydra.cc/docs/next/tutorials/structured_config/defaults) on the defaults list. I want to have a param with no default value (`MISSING`) for my `Structured Config Schema` and also have this param not specified in my `config.yaml` (`???`). I'm doing this because I don't want to get the `???` values for the param when running the script without specifying it, I want to get an error in this case (asking the user to specify the param).

For some reason, currently Hydra does not correctly parse the command line input and is completely missing this param even if it is in fact specified.

## Checklist
- [ x] I checked on the latest version of Hydra.
- [ x] I created a minimal [repo](https://github.com/danielgafni/hydra-structured-config-schema-default-missing-bug) that reproduces the bug.

## To reproduce

`config.yaml`

```yaml
defaults:
  - base_config

param: ???
```

`configs/config.py`

```python
from dataclasses import dataclass, field
from omegaconf import MISSING, DictConfig, OmegaConf
from typing import List, Any
import hydra
from hydra.core.config_store import ConfigStore

defaults = [
    {"param": MISSING},
]


@dataclass
class Config:
    defaults: List[Any] = field(default_factory=lambda: defaults)

    param: str = MISSING


cs = ConfigStore()
cs.store(name="base_config", node=Config)


@hydra.main(config_path="configs", config_name="config")
def main(cfg: DictConfig):
    print(OmegaConf.to_yaml(cfg=cfg))


if __name__ == "__main__":
    main()
```

Now I’m getting this error:
```
╰─❯ python config.py param=foo
You must specify 'param', e.g, param=<OPTION>
Available options:


Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

Am I doing something wrong?

## Expected Behavior
param should be passed to the script

## System information
- **Hydra Version** :  1.1.0.dev5
- **Python version** : 3.7.10
- **Virtual environment type and version** : Poetry version 1.1.6
- **Operating system** : Arch Linux

**Comment by omry** [comment]
Try to define your defaults list only in the yaml file.

**Comment by danielgafni** [comment]
Hmm, but how do I get the type checking and IDE help for the params with missing defaults?

**Comment by omry** [comment]
>  I want to have a param with no default value (MISSING) for my Structured Config Schema

Is this param config group or a config value?
If it's a config group, please create complete example with it and we can discuss it (e.g: I am expecting to see  a file param/foo.yaml or a corresponding config in the config store).
If it's just a config value, it should not be in your Defaults List. read the basic tutorial again to understand the role of the Defaults List.

**Comment by danielgafni** [comment]
Thank you very much! I did read the tutorial again and understood my mistake. I also understood the MISSING + .yaml configs logic. Closing the issue.
