### ISSUE TITLE
[Bug] mismatched input '=' expecting <EOF>

### ISSUE THREAD

**Issue by summelon** [facebookresearch/hydra#1577]
# 🐛 Bug
## Description
Thanks for your great work!

Using hydra with Pytorch Lightning.
when I was overriding pretrained path:
```shell=
python3 main.py basic.pretrained='log/byol/resnet18/cifar10_byol_setting/checkpoints/epoch=999-step=87999.ckpt'
```
The error came out:
`mismatched input '=' expecting <EOF>`

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
- `configs.yaml`:
```yaml
basic:
  pretrained: null
```
- Run:
```shell=
python3 main.py basic.pretrained='log/byol/resnet18/cifar10_byol_setting/checkpoints/epoch=999-step=87999.ckpt'
```
** Stack trace/error message **
```
mismatched input '=' expecting <EOF>
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
It seems that Hydra uses the `=` sign to tokenize each overriding.
Should I adjust this error by changing my checkpoint name? (which is default in PyTorch Lightning)
Or there is any way to fix this?

## System information
- **Hydra Version** :  1.1.0.dev5
- **Python version** : python3.6
- **Virtual environment type and version** : 
- **Operating system** : Ubuntu18.04

**Comment by jieru-hu** [comment]
hi
pls try something like the following

$ python my_app.py  'basic.pretrained=log/byol/resnet18/cifar10_byol_setting/checkpoints/epoch\\=999-step\\=87999.ckpt'

see [here](https://hydra.cc/docs/next/advanced/override_grammar/basic#escaped-characters-in-unquoted-values) for more info :)

**Comment by omry** [comment]
You can include special characters in quoted strings.
You did attempt to quote your value, but you have failed because your shell was intercepting the quotes.
See [this](https://hydra.cc/docs/next/advanced/override_grammar/basic/#working-with-your-shell) for some info about Hydra and the shell.
You basically can quote twice, once for the shell and once for Hydra:

With a dummy app that prints the config:
```shell
# escaping the =:
$ python my_app.py '+a=b\=c'
a: b=c

# quoting the value:
$ python my_app.py '+a="b=c"'
a: b=c
```

You can also use echo on the shell to see what value would be passed to Hydra:
```
$ echo a='b=c'
a=b=c
$ echo 'a="b=c"'
a="b=c"
```

**Comment by summelon** [comment]
That's what I want! Thank you all, guys.

**Comment by richardrl** [comment]
I got this error when using a path with an equals sign in it. Fixed by escaping all equals sign with backslash
