### ISSUE TITLE
[Feature Request] ability to parse args manually

### ISSUE THREAD

**Issue by fogside** [facebookresearch/hydra#1578]
# 🐛 Bug/🚀 Feature Request

I want to be able to control args parsing myself.

## Motivation
Hydra overrides blender argparser and I didn't find the way how to use Hydra with blender (yes, 3d editor).

## Description
I'm not exactly sure that it is bug or feature request. But I will give you some context.
I'm developing some [blender](https://www.blender.org/) scripts in python and they have lots of parameters that I would like to manage with Hydra. Blender has great command line interface which allows to use its inner python. It is also possible to install packages in this blender's python (I installed hydra in it). But it is not possible to use some system python interpreter in blender as it lack specific for blender functions.

Typical use looks like this:
```
blender --background --python python_script.py -- [--any_arguments_for_the_python_script]
```
The problem is that Hydra somehow overrides blender's argparser and blender then does not recognize its argument.
With vanilla Argparse inside my python script I explicitly take args and put into argparser only everything after `--` (this special symbol that blender uses). 
I created `config.yaml` in the same directory and inside the python script Hydra usage looks like:

```python
import hydra
....
@hydra.main(config_name="config")
def hello(cfg):
  print(cfg.some_field)
  ...
  
hello()
```

** Stack trace/error message **
```
/home/fogside/Projects/blender-2.92.0-linux64/blender --background --python blender_dataset_generation.py
Blender 2.92.0 (hash 02948a2cab44 built 2021-02-25 09:31:37)
Read prefs: /home/fogside/.config/blender/2.92/config/userpref.blend
usage: blender [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}]
               [--package PACKAGE] [--run] [--multirun] [--shell-completion]
               [--config-path CONFIG_PATH] [--config-name CONFIG_NAME]
               [--config-dir CONFIG_DIR] [--info]
               [overrides [overrides ...]]
blender: error: unrecognized arguments: --background --python

```
## Expected Behavior
I expected to see printed cfg.some_field.

## System information
- **Hydra Version** :  v1.0.6
- **Python version** : packed with blender 
- **Operating system** : Ubuntu 18.04

**Comment by omry** [comment]
Hello.
This is an interesting use case.
it looks like what is happening is not that Hydra takes over the parameters of blender, but rather that blender does not clean it's own things from sys.argv, and this is confusing `@hydra.main()` which is not designed to be used in this way.

`@hydra.main()` does not (and will not) allow access to the config parser.
What you can do is to use lower level [Compose API](https://hydra.cc/docs/experimental/compose_api) to compose the config and build your own argparse based logic on top.

Once you do that, it's your responsibility to extract the relevant overrides from sys.argv and pass them to the compose() function.

**Comment by omry** [comment]
Closing, feel free to followup here if you have additional comments or questions.
