### ISSUE TITLE
[Feature Request] Add a resolve flag to when using --cfg to output the config

### ISSUE THREAD

**Issue by davidcian** [facebookresearch/hydra#1585]
# 🚀 Feature Request

Add some way to print the resolved configuration (for interpolations) when using the `--cfg` flag in the CLI. 

## Motivation

**Is your feature request related to a problem? Please describe.**

OmegaConf evaluates interpolated values lazily, which is a bummer when using the `--cfg` flag to output the config for debug purposes, since the values just print un-interpolated.

## Pitch

**Describe the solution you'd like**
An extra flag, maybe `--resolve` in the CLI to print the resolved configuration.

**Describe alternatives you've considered**

An alternative is to just use `print(OmegaConf.to_yaml(cfg, resolve=True))` in the code, but it would be better to not clutter the code with such a statement.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes, but I'd need a pointer for where to look in the code.

**Comment by jieru-hu** [comment]
Thanks @davidcian  for the request! We will look into adding this for Hydra 1.1

**Comment by Jasha10** [comment]
FYI I am working on this currently.

**Comment by jieru-hu** [comment]
thanks @Jasha10, I tried to assign the issue to you on GitHub but it won't let me 🤔 , then I ended up clicking the wrong button and accidentally assigned it to myself 😂
