### ISSUE TITLE
[Question] Override syntax on experiment config file

### ISSUE THREAD

**Issue by FrouxBY** [facebookresearch/hydra#1596]
# 🚀 Feature Request

I am not sure wether this is a feature request, or if this is because I didn't find the right way to achieve what I want (or maybe this is a bad idea)

## Motivation

My usecase is training Neural Net, I want to have flexibility to add different number of datasets. Currently Hydra offer all the flexibility I need, but the override syntax and constraints make the experiment.yaml not so much readable in some case

## Pitch

Here is my config structure
```
├── configs
   ├── data
   |     ├── datasets 
   |     |       ├── dataset_1.yaml
   |     |       ├── dataset_2.model
   |     ├─ module_1.yaml 
   |     └─ module_2.yaml
   ├── device
   |     ├── cpu
   |     └── gpu
   ├── experiment.yaml
   │
   └── default.yaml
```
My default.yaml
```
defaults:
  - data: module_1
  - device: cpu
```

my module_*.yaml

```
# @package data

_target_: src.data.module.module_1

default:
  - data.dataset@train_dataset.dataset_1: dataset_1

data_files_root: /path/to/data_files_root
dataset_1_root: /path/to/dataset_1
```
and my dataset_*.yaml
```
# @package data.dataset
name: dataset_1

_target_: src.data.datasets.dataset_1

filename: dataset_1.txt
data_file: ${data.data_files_root}/${.filename}
root_img: ${data.dataset_1_root}

```

So now I am using an experimental.yaml to override and to add some parameters:
Currently I need to use: 

```
defaults:
  - override /data: module_2
  - override /data/datasets@data.train_dataset.dataset_2: dataset_2
  - override /data/datasets@data.train_dataset.dataset_3: dataset_2
  - override /device: gpu

data:
  dataset_2_root: path/to/new_root
  train_dataset:
    dataset_3:
      filename: other_dataset_2.txt
```

However, neither the addition of dataset_2 and dataset_3 are an actual override (train_dataset.dataset_x does not exist in the defaults.yaml config tree), and neither:
```
defaults:
  - override /data: module_2
  - /data/datasets@data.train_dataset.dataset_2: dataset_2
  - /data/datasets@data.train_dataset.dataset_3: dataset_2
  - override /device: gpu
```
or 
```
defaults:
  - /data/datasets@data.train_dataset.dataset_2: dataset_2
  - /data/datasets@data.train_dataset.dataset_3: dataset_2
  - override /data: module_2
  - override /device: gpu
```
is valid or with the expected behaviour,

Finally, the defaults syntax to add group config is separate to the override of the node config of those new group,

Ideally I thought the following syntax or something similar could be nice:
```
defaults:
  - override /data: module_2
  - override /device: gpu

data:
  dataset_2_root: path/to/new_root
 
  train_dataset:
    data.dataset@dataset_2: dataset_2  
    data.dataset@dataset_3: dataset_2  # I define the config group for data.train_dataset.dataset_3
    dataset_3:                         # I now have access to data.train_dataset.dataset_3
      filename: other_dataset_2.txt
```
or
```
defaults:
  - override /data: module_2
  - override /device: gpu

data:
  dataset_2_root: path/to/new_root
 
  train_dataset:
    dataset_2:
      default: data/dataset/dataset_2
    dataset_3:
      default: data/dataset/dataset_2  # I define the config group for data.train_dataset.dataset_3
      filename: other_dataset_2.txt      #   I directly override one config node 
```

## Additional context
I am using Hydra 1.1.0 dev6

Thanks for your input in this edge case

**Comment by omry** [comment]
A config can only have a defaults list as the top level element, so the things you are intuitively expecting are not supported and will not be supported.

> However, neither the addition of dataset_2 and dataset_3 are an actual override (train_dataset.dataset_x does not exist in the defaults.yaml config tree), and neither:

Please simplify your example to something really minimal.
The question is 5 times more complicated than it needs to be and it's really hard to understand what you are doing.

I also suggest that you inspect the output  `--info defaults` to see what Hydra is actually doing.

**Comment by FrouxBY** [comment]
Sorry for the complicated questions,
Everything wasn't clear for me, but the --info flags gave me more insight on what is happening,

I am closing now, and might come with better question later if required,

Thanks
