### ISSUE TITLE
Document HydraContext change

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#1604]
Created an upgrade guide relating to HydraContext, also include  the link in the warning message added here
https://github.com/facebookresearch/hydra/pull/1603

**Comment by omry** [comment]
I don't think it's worth an upgrade page.
You can link to an issue instead with some explanations.
The number of people writing plugins is small and I am expecting them to be able to handle high level instructions without much hand holding.

**Comment by jieru-hu** [comment]
closing, this was address in https://github.com/facebookresearch/hydra/pull/1603

**Comment by jieru-hu** [comment]
makes sense.  reopening this, I will update the error message to make it more actionable

**Comment by jieru-hu** [comment]
right now the warning message is 
```
        Plugin's setup() signature has changed in Hydra 1.1.
        Support for the old style will be removed in Hydra 1.2.
        For more info, check https://github.com/facebookresearch/hydra/pull/1581."""
```

How about something like 
```
        Plugin's setup() signature has changed in Hydra 1.1.
        Support for the old style will be removed in Hydra 1.2.
        If you are the plugin owner, please upgrade your plugin to be compatible.
        For more info, check https://github.com/facebookresearch/hydra/pull/1581."""

```

**Comment by omry** [comment]
Looking at the tests, I did not see the link.
I think editing the linked page to explain both audiences what to do should be good enough, no to change the error.

**Comment by jieru-hu** [comment]
The tests has the link https://github.com/facebookresearch/hydra/blob/f0fd13ed413f953d82b4b86bd29f99c1ffcf65eb/tests/test_hydra_context_warnings.py#L76-L81

I've updated the link with action items for plugin user/maintainer :)

**Comment by omry** [comment]
Which plugin should I upgrade?
Can the error message include the plugin class name?

**Comment by jieru-hu** [comment]
Good point! I will look into it.

**Comment by omry** [comment]
> I've updated the link with action items for plugin user/maintainer :)

Made an edit pass. take a look.

**Comment by jieru-hu** [comment]
lgtm, thanks!
