### ISSUE TITLE
[Bug] pdb support is broken

### ISSUE THREAD

**Issue by LouChao98** [facebookresearch/hydra#1613]
# 🐛 Bug
## Description

In patch #1239, debugger can work with hydra by setting `HYDRA_FULL_ERROR=1` , but pr #1465 breaks it. In #1465, `HydraJobException` is always raised if the job raise an exception, such that debugger will catch `HydraJobException` instead of the original exceptions.

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```python
# mini.py
import hydra

@hydra.main()
def foo(cfg):
    raise Exception

foo()
```
then run `HYDRA_FULL_ERROR=1 python -m pdb -c continue mini.py` in shell.

pdb catch `HydraJobException` in `hydra/core/utils.py`

## Expected Behavior
pdb catch `Exception` in `foo`.

## System information
- **Hydra Version** : 1.1.0dev6
- **Python version** : 3.8.8
- **Virtual environment type and version** : 
- **Operating system** : linux 5.9.10

## Additional context

I think add `if _is_env_set("HYDRA_FULL_ERROR") or is_under_debugger():` in `JobReturn.return_value` can temporarily fix this.
```python
@dataclass
class JobReturn:
    ....

    @property
    def return_value(self) -> Any:
        assert self.status != JobStatus.UNKNOWN, "return_value not yet available"
        if self.status == JobStatus.COMPLETED:
            return self._return_value
        else:
            if _is_env_set("HYDRA_FULL_ERROR") or is_under_debugger():  # add this
                raise self._return_value
            raise HydraJobException(
                f"Error executing job with overrides: {self.overrides}"
            ) from self._return_value
```

**Comment by omry** [comment]
> In patch #1239, debugger can work with hydra by setting HYDRA_FULL_ERROR=1

Thanks for reporting.
#1239 enables pdb support without needing to set HYDRA_FULL_ERROR.
What happens if you do not set it?

**Comment by omry** [comment]
Thanks. #1614 is supposed to fix it.
