### ISSUE TITLE
Nevergrad parametrization with variables not at base level (question) 

### ISSUE THREAD

**Issue by jloveric** [facebookresearch/hydra#1620]
# This a question
I'm using nevergrad and am trying to do parametrization of variables as below.  The variable I want to parameterize is not at the base level, is this the correct way to do things?
```
parametrization:
      mlp:
        n :
          init: 2
          lower : 2
          upper: 6
          integer: true
```
I am getting this error "TypeError: Error instantiating 'hydra_plugins.hydra_nevergrad_sweeper.nevergrad_sweeper.NevergradSweeper' : __init__() got an unexpected keyword argument 'n'" which I believe is a result of this

**Comment by jieru-hu** [comment]
Hi @jloveric,
This is not currently supported for the sweeper. Could you try to promote your config to the a top node? 

If you'd rather have the structure `mlp.n`, maybe look into doing the value assignment inside your application?
For example, something like the following might work:
```
parametrization:
    mlp_n:
       init: 2
```

in your application

```
@hydra.main(config_name="config")
def dummy_training(cfg: DictConfig) -> float:
    cfg.mlp.n = cfg.mlp_n
   ...
```

**Comment by jloveric** [comment]
Thanks @jieru-hu, I'll try that.

**Comment by jloveric** [comment]
Actually, could you use interpolation?  Define variables at the top node and then use mlp.n=${mlp_n}?  I'll try it.

**Comment by jieru-hu** [comment]
@jloveric sorry for the confusion!!

Actually the nested node should be supported
Could you try
```
parametrization:
    mlp.n:
       init: 2
```
and see if it works?


(thanks to @omry who pointed this out to me offline.)

**Comment by jloveric** [comment]
@jieru-hu yes, that works.  Thanks!

**Comment by jieru-hu** [comment]
awesome! closing this issue now. :)
