### ISSUE TITLE
Hydra initialize API

### ISSUE THREAD

**Issue by johnwlambert** [facebookresearch/hydra#1628]
Hi, thanks for the great library. Two questions:

Is there a way to check if hydra has already been initialized, e.g. `hydra.is_initialized()`?

Also, is there a way to present the absolute path to a config, rather than just relative to the caller?

Absolute paths can prevent bugs when using a hydra-reliant package as a dependency.

From the documentation: https://hydra.cc/docs/next/advanced/compose_api/
```python
def initialize(
    config_path: Optional[str] = None,
    job_name: Optional[str] = "app",
    caller_stack_depth: int = 1,
) -> None:
    """
    Initializes Hydra and add the config_path to the config search path.
    config_path is relative to the parent of the caller.
```

**Comment by omry** [comment]
> Hi, thanks for the great library. Two questions:
> 
> Is there a way to check if hydra has already been initialized, e.g. `hydra.is_initialized()`?

What is the use case?
Look at `GlobalHydra.is_initialized()` (It's a singleton, you probably need `GlobalHydra.instance().is_initialized()`.

> Also, is there a way to present the absolute path to a config, rather than just relative to the caller?
> 
> Absolute paths can prevent bugs when using a hydra-reliant package as a dependency.
> 
> From the documentation: https://hydra.cc/docs/next/advanced/compose_api/
> 
> ```python
> def initialize(
>     config_path: Optional[str] = None,
>     job_name: Optional[str] = "app",
>     caller_stack_depth: int = 1,
> ) -> None:
>     """
>     Initializes Hydra and add the config_path to the config search path.
>     config_path is relative to the parent of the caller.
> ```

From the same page:
```python
def initialize_config_dir(config_dir: str, job_name: str = "app") -> None:
    """
    Initializes Hydra and add an absolute config dir to the to the config search path.
    The config_dir is always a path on the file system and is must be an absolute path.
    Relative paths will result in an error.
    :param config_dir: absolute file system path
    :param job_name: the value for hydra.job.name (default is 'app')
    """
```

**Comment by johnwlambert** [comment]
Resolved it -- the real issue was that my hydra .yaml config file wasn't listed in my MANIFEST.in file, so it wasn't being read properly. Thanks!

**Comment by benjaminrwilson** [comment]
Hi @omry, I had a quick, related question. Is there a recommended workflow for two separate applications which use `hydra` in a non-contextual manner? For example, if each application has a global config, what would be the recommended way to handle this (assuming the projects are completely disjoint and have different maintainers)?

**Comment by omry** [comment]
@benjaminrwilson, I am not sure your question is simple would like more clarification about the use case.
Please file a new issue and provide more context.

**Comment by johnwlambert** [comment]
This was the issue I was having -- `hydra` was already initialized from one project, which caused an issue for the second unrelated project.
