### ISSUE TITLE
Create a features matrix comparing to other things out there

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#163]

**Comment by berceanu** [comment]
Well, how about signac.io?

**Comment by omry** [comment]
I am not familiar with this project, but a quick look at their [examples](https://docs.signac.io/en/latest/examples.html) shows that they have a lot of hard coded configuration.

If I had to guess, my guess would be that the two projects are (or can be) complementary.

**Comment by omry** [comment]
Closing this, will reconsider if something similar to Hydra comes along.
