### ISSUE TITLE
Suggested way to access config at multiple places

### ISSUE THREAD

**Issue by brunovollmer** [facebookresearch/hydra#1638]
Hey everybody,

is there a suggested way to access the config at multiple places in a project. Something like @hydra.main() but that does not initialize everything again?

Thanks 
Bruno

**Comment by jieru-hu** [comment]
Hi @brunovollmer 

you will need to add your config to the list of Hydra's searchpath.
checkout this wiki for more info https://hydra.cc/docs/next/advanced/search_path/#internaldocs-banner

If you still have questions after reading the wiki, pls provide a minimal repro so we can help you further.

**Comment by brunovollmer** [comment]
Might be that I don't get the wiki right but my question was what the suggested way is to access the configs in multiple files. 

Given I have a project structure like this: 

main.py
├── conf/
│   ├── config.yaml
├── a/
│   ├── a.py
├── b/
│   ├──b.py

and my main looks like this:
```
@hydra.main(config_path="conf", config_name="config")
def my_app(cfg: DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    my_app()
```

My question now is how can I access the config in file _a.py_ or _b.py_ without having to pass it there from main? Is there a way that is intended by hydra? I can think of a few ways to do it myself but I was wondering of you had any intended way.

Thanks in advance.

**Comment by jieru-hu** [comment]
You need to add the other configs to Hydra's list of search path.  The wiki describes how you would approach this:

basically, you can try to add a `hydra.searchpath` node to the primary config file

```
hydra:
    searchpath:
         pkg://a.a
```

The example uses Yaml files as an example but they should work on struct config as well.  Feel free to upload your example app, I'm happy to modify it and see if it works.

**Comment by brunovollmer** [comment]
But what I want is to access the same config at multiple places

**Comment by jieru-hu** [comment]
@brunovollmer I see, sorry for the misunderstanding!

If you do not want to use Hydra main, you can also check out  the compose API 
https://hydra.cc/docs/next/advanced/compose_api

**Comment by omry** [comment]
@brunovollmer:

You can either pass your config around or use the compose API to compose it again.
