### ISSUE TITLE
Question: how to refer to parent file from composition config

### ISSUE THREAD

**Issue by arisliang** [facebookresearch/hydra#1644]
From the [composition example](https://hydra.cc/docs/intro/#composition-example), we can refer to other yaml files if at the same level, e.g. db folder is the same level as config.yaml.

The question, is it possible to refer to a parent level folder's yaml from config.yaml? 

├── db
│   ├── mysql.yaml
│   └── postgresql.yaml
├── config
│   ├── config_1.yaml
└── my_app.py

For the above example, can `config_1.yaml` refer to `mysql.yaml`?

**Comment by jieru-hu** [comment]
Yes it is possible - this is better support in Hydra 1.1rc (`pip install hydra-core --pre --upgrade`)

for example with the following config structure
```
u$ tree conf
conf
├── config
 │   └── config.yaml
└── db
    ├── mysql.yaml
    └── postgresql.yaml
```

in config.yaml, use the absolute config group path
```
defaults:
  - /db: mysql
```

my_app.py
```
@hydra.main(config_path="conf", config_name="config/config")
def my_app(cfg: DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    my_app()

```

run the app
```
$python my_app.py

config:
  db:
    driver: mysql
    user: omry
    pass: secret
```

here is more info on how to override packages https://hydra.cc/docs/next/advanced/overriding_packages


doc on search path might also help https://hydra.cc/docs/next/advanced/search_path/#internaldocs-banner

**Comment by arisliang** [comment]
Thanks for the example, it works!

**Comment by omry** [comment]
You can eliminate the top level `config` node by overriding the package to global:

```yaml
# @package _global_
defaults:
  - /db: mysql
```

See this for more info:
https://hydra.cc/docs/next/patterns/configuring_experiments
