### ISSUE TITLE
[Feature Request] Ability to override cwd() while still leaving .hydra and run log in hydra output folders

### ISSUE THREAD

**Issue by jpmartineau** [facebookresearch/hydra#1651]
# 🚀 Feature Request

I need to override hydra.run.dir to '.' so that hydra plays well with third party libraries which don't do the hydra.utils.get_absolute_path thing in it's code.

When I do so, all of hydra's output (like run logs and .hydra folder) end up in the cwd instead of hydra's outputs directory.

I'd like to be able to override the cwd while still leaving hydra do its thing with the output directory. In other words, the hydra.run.dir should not (optionally) affect hydra's inner workings.

Does this make sense to you?

**Comment by omry** [comment]
We are planning to give this area some attention in the next version of Hydra.
This is already on the radar, see #910.
