### ISSUE TITLE
[Bug] Overriding of structured config with config

### ISSUE THREAD

**Issue by bonlime** [facebookresearch/hydra#1662]
# 🐛 Bug
## Description
Not really sure that it's a bug, maybe this is a design choice.

The issue is similar to https://github.com/facebookresearch/hydra/issues/1515
Overriding params from CLI works fine but doesn't work if we try to overwrite with another config file. 
The Docs says "Running the experiments from the command line requires prefixing the experiment choice with a +. The experiment config group is an **addition**, not an **override**." but it doesn't provide any way to add new parameters from experiment configs. 

## Checklist
- [ x ] I checked on the latest version of Hydra
- [ x ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

./temp_cfg/bug_test.yaml
```yaml
# @package _global_

defaults:
  - overrides ui: null

ui:
  width: 100
  some_new_arg: 1000
```

./my_app.py
```python
import hydra
from hydra.core.config_store import ConfigStore

from dataclasses import dataclass
from omegaconf import OmegaConf

@dataclass
class UserInterface:
    width: int = 1024

@dataclass
class MyConfig:
    ui: UserInterface = UserInterface()

cs = ConfigStore.instance()
cs.store(name="struct_config", node=MyConfig)

@hydra.main(config_path=".", config_name="struct_config")
def my_app(cfg: MyConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```

This works fine: `python3 my_app.py +ui.some_new_arg=100`
```
ui:
  width: 1024
  some_new_arg: 1000
```

But this doesn't: `python3 my_app.py +temp_cfg=bug_test`
```
Key 'some_new_arg' not in 'UserInterface'
    full_key: ui.some
    reference_type=UserInterface
    object_type=UserInterface
```

## Expected Behavior

It would be nice to have ability to add parameters from experiment configs

## System information
- **Hydra Version** :  1.1.0rc1
- **Python version** : 3.7.6
- **Virtual environment type and version** : None
- **Operating system** : Ubuntu 16.04

**Comment by bonlime** [comment]
Okay, I just realised that Structured Config intentionally doesn't allow adding new fields.
 But it's still confusing that you can add new fields one-by-one but can't add them in bulk

**Comment by omry** [comment]
Hi @bonlime, this is intentional behavior.
Structured Configs are intentionally not allowing new keys to be added via config composition.
There is currently no mechanism to do what you want, and I don't believe we will add one.

If you want to allow arbitrary keys to be composed, the node must node be a Structured Config node.
You have two options:
1. Make ui a plain dict.

```python
@dataclass
class MyConfig:
    ui: Dict[str, Any] = field(default_factory=lambda: {"width": 100}) 
```

2. Not use Structured Configs at all.

Can you share more context why you want to add arbitrary keys to a typed node?

**Comment by bonlime** [comment]
I really like the Structured Configs interface because they're typed and allow writing at least some kind of documentation for parameters (using comments in dataclass code). 

My use-case is as follows: I have several models each with different arguments, which I want to instantiate in code using 
`model = hydra.utils.instantiate(cfg.model)`. 

Yesterday I've come up with a following work-around:
```
@dataclass
class Model:
    _target_: str = 'torchvision.models.resnet18'
    kwargs: Dict = field(default_factory=dict)

...
with open_dict(cfg.model):
    model = hydra.utils.instantiate(cfg.model, **cfg.model.pop("kwargs")
```
But your solution with making it a plain dict looks better and I'll probably use it

**Comment by omry** [comment]
Consider creating a config dataclass per model you want to instantiate.
