### ISSUE TITLE
[Bug] negative list indices in variable interpolation

### ISSUE THREAD

**Issue by vmichals** [facebookresearch/hydra#1674]
# 🐛 Bug
## Description
I'm trying to use variable interpolation to automatically set the input size of one model based on the last layer's size of another model. I tried to index into the list of layers of the input model with index -1 and am getting an `InterpolationKeyError`

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
Using the following `cfg.yaml` and `main.py`, run `python main.py`.

_cfg.yaml_:
```
model:
    encoder:
        hid_channels: [8, 16, 32]
    decoder:
        in_channels: ${model.encoder.hid_channels[-1]}
```

_main.py_:
```
import hydra
from hydra.utils import instantiate

from omegaconf import DictConfig

@hydra.main(config_path=".", config_name="cfg")
def my_app(cfg: DictConfig) -> None:
    model = instantiate(cfg.model)
    import ipdb; ipdb.set_trace()


if __name__ == '__main__':
    my_app()
```

** Stack trace/error message **
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "main.py", line 11, in my_app
    model = instantiate(cfg.model)
  File "/home/vince/dreamerv2venv/lib/python3.8/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 175, in instantiate
    OmegaConf.resolve(config)
omegaconf.errors.InterpolationKeyError: Interpolation key 'model.encoder.hid_channels[-1]' not found

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
The last element of `model.encoder.hid_channels` should be written to `model.decoder.in_channels`.

## System information
- **Hydra Version** :  1.1.0
- **Python version** : 3.8.5
- **Virtual environment type and version** : virtualenv 20.0.17
- **Operating system** : Ubuntu 20.04.2 LTS

**Comment by Jasha10** [comment]
Hi @vmichals,

Thanks very much for the report!

This is an issue with the OmegaConf library that Hydra uses as a backend.

I've filed an issue (https://github.com/omry/omegaconf/issues/755) against the OmegaConf repository, based on your report above. I'm going to close this issue now in favor that one.
