### ISSUE TITLE
[Bug] When using compose API, get error about `Could not override 'hydra/job_logging'. No match in the defaults list.`

### ISSUE THREAD

**Issue by adefossez** [facebookresearch/hydra#1677]
# 🐛 Bug
## Description

I am using the compose API. I just updated to version 1.1. In version 1.0.* everything was working fine.
Now I get the following error:

```
hydra.errors.ConfigCompositionException: In 'config': Could not override 'hydra/job_logging'. No match in the defaults list.
```

Any idea why this is happening and how to solve it ? That would save me a lot of time. thanks :)

**Comment by omry** [comment]
You are going to have to file all the requested information in the bug template.
in particular, Hydra version and a minimal repro.

**Comment by adefossez** [comment]
Bug is resolved. I had to do a monkey patching of the deepcopy method in the previous version of hydra due to the performance issue it had. now this is no longer needed and somehow the old fix was triggering this error.
