### ISSUE TITLE
Ray Tune Sweeper Plugin [Feature Request]

### ISSUE THREAD

**Issue by cn4750** [facebookresearch/hydra#1678]
# 🚀 Feature Request

## Motivation

Continued support for more parameter optimization libraries in sweeper plugins other than Ax, Nevergrad, and Optuna.
[Ray Tune](https://docs.ray.io/en/master/tune/index.html) is a popular hyperparameter tuning library with [integration ](https://docs.ray.io/en/master/tune/api_docs/integration.html#pytorch-lightning-tune-integration-pytorch-lightning)into PyTorch Lightning.
A [Ray launcher plugin](https://hydra.cc/docs/plugins/ray_launcher) is already implemented and would pair nicely with a Ray Tune Sweeper plugin.
[Others ](https://stackoverflow.com/questions/65701661/hydra-parameter-sweeps-in-parallel-e-g-ray-tune)have run into this same issue.

## Pitch

**Describe the solution you'd like**

A Ray Tune Sweeper plugin like that of the Ax/Nevergrad/Optuna Sweeper plugins.

**Describe alternatives you've considered**

Utilizing one of the existing sweeper plugins instead might be reasonable for some, but not for all situations.

**Comment by mayeroa** [comment]
It would be awesome to integrate Ray Tune as a new Sweeper plugin since it integrates nicely with popular hyperparameter tuning libraries such as Optuna & Ax.
Since I work a bit with ray tune and pytorch ligthning, I might help on this issue if necessary.
Is there a plan to integrate Ray Tune?
If so, how can we make the integration as smooth as possible with the existing ray launcher?

**Comment by omry** [comment]
Hi,
At this time we are not considering adding additional first party sweeper plugins to Hydra.
However, you are free to implement and publish your own sweeper plugin.

Note that both Ax and Optuna (and Nevergrad) are supported as first party sweeper plugins already.

**Comment by cn4750** [comment]
> 
> 
> Hi,
> At this time we are not considering adding additional first party sweeper plugins to Hydra.
> However, you are free to implement and publish your own sweeper plugin.
> 
> Note that both Ax and Optuna (and Nevergrad) are supported as first party sweeper plugins already.

Thanks for the quick response. While it is unfortunate that additional first-party sweeper plugins are not being planned at this moment, I understand. Hopefully in the future.

**Comment by omry** [comment]
Thanks for understanding. 
I am closing this as we will not have the cycles to maintain additional first party plugins.

However, we are happy to answer questions and offer guidance to anyone attempting this might have in the Hydra chat.
