### ISSUE TITLE
Is there a way to get the original cwd on the config file?

### ISSUE THREAD

**Issue by czrcbl** [facebookresearch/hydra#1680]
Hi,

I would like to know if there is a way to get the original working directory inside the config file, that normally would be the script folder.
Something like:

```
_target_: torchvision.datasets.mnist.MNIST
root: ${original_cwd}/data/MNIST
download: True
```

I could not find anything about that on the docs.
If it is not possible, is there another way to point in the config to a relative path in regards to the script folder (the original cwd).
I used to do something like `root: ../../../data/MNIST` but that is attached to the hydra subdir config, and would change in case of a multirun.

**Comment by omry** [comment]
Hi.
See https://hydra.cc/docs/0.11/configure_hydra/intro/#runtime-variables

Using `hydra.runtime.cwd` config variable. All Hydra config variables are accessed through the `hydra` resolver, so your syntax is:
```
root: ${hydra:runtime.cwd}/data/MNIST
```

Feel free to send a PR to improve the docs.

**Comment by awhillas** [comment]
AttributeError: module 'hydra' has no attribute 'runtime' :(

**Comment by Jasha10** [comment]
> AttributeError: module 'hydra' has no attribute 'runtime' :(

@awhillas I believe there there is confusion here between the hydra module and the hydra config variable.
