### ISSUE TITLE
Better stack trace when using Launchers

### ISSUE THREAD

**Issue by calebho** [facebookresearch/hydra#1698]
# 🚀 Feature Request

When I'm using a Launcher and my application throws an exception, I should get my application's stack trace instead of Hydra's internal stack trace. 

## Motivation

When debugging my code, I often rely on the stack trace to figure out where things went wrong. Currently, if I use a Hydra Launcher, it is impossible for me to track down the source of an error because my application's stack trace is not preserved.

## Pitch

**Describe the solution you'd like**
Given [this script](https://gist.github.com/calebho/67c86e40b4bab52bd2719163a297c747#file-main-py) and running using `python main.py -m ...`, currently we get
```
Traceback (most recent call last):
  File "/private/home/calebh/miniconda3/envs/hydra-stack-trace-repro/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/private/home/calebh/miniconda3/envs/hydra-stack-trace-repro/lib/python3.8/site-packages/hydra/_internal/utils.py", line 376, in <lambda>
    lambda: hydra.multirun(
  File "/private/home/calebh/miniconda3/envs/hydra-stack-trace-repro/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 139, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/private/home/calebh/miniconda3/envs/hydra-stack-trace-repro/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 161, in sweep
    _ = r.return_value
  File "/private/home/calebh/miniconda3/envs/hydra-stack-trace-repro/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
RuntimeError: boom
```
Instead, I want
```
Traceback (most recent call last):
  File "main.py", line 18, in main
    outer()
  File "main.py", line 22, in outer
    boom()
  File "main.py", line 26, in boom
    raise RuntimeError("boom")
RuntimeError: boom
```

**Describe alternatives you've considered**
Not using launchers at all and launching my Hydra app manually (e.g. using SLURM batch scripts).

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Not at the moment

## Additional context
https://gist.github.com/calebho/67c86e40b4bab52bd2719163a297c747

**Comment by RemyLau** [comment]
Hi, I'm wondering what's the current status of this issue? It would be really great to have the traceback from the actual program. I can try to work on a patch for this if no one else is working on this currently.

**Comment by Jasha10** [comment]
Hi @RemyLau, thanks for offering to work on a patch.
As far as I can tell, this issue is still blocked by [cloudpickle issue #248](https://github.com/cloudpipe/cloudpickle/issues/248) (see Jieru's comment above).

**Comment by jieru-hu** [comment]
hi @RemyLau 

instead of relying on cloudpickle for the stacktrace, maybe try logging the stacktrace directly instead. In Hydra 1.1.2 we've added a new callback for this, https://github.com/facebookresearch/hydra/commit/80c12c0f3bd0c96947f53eb58751c1c15b8dce75

doc on callbacks https://hydra.cc/docs/experimental/callbacks/

**Comment by RemyLau** [comment]
Hi @Jasha10 and @jieru-hu, thank you both so much for the information! And thanks for providing the callback workaround! I'll try to see if I can get the callback printing out the traceback correctly.

**Comment by jieru-hu** [comment]
> Hi @Jasha10 and @jieru-hu, thank you both so much for the information! And thanks for providing the callback workaround! I'll try to see if I can get the callback printing out the traceback correctly.

awesome, yea, give it a try and let me know how it goes. This callback has been tested on our internal slurm cluster and should work as expected.

**Comment by jieru-hu** [comment]
Closing this now since this is a cloudpickle issue. The callback seems like a good alternative solution.
