### ISSUE TITLE
Option for requiring at least one option?

### ISSUE THREAD

**Issue by brijow** [facebookresearch/hydra#1700]
Hi, I apologize if this is very simple question, but I was writing an app that I'd like to have require the user to input at least one of either a task option, or an experiment option. To illustrate, here is a simplified version of my config:

```
# @package _global_

defaults:
  - task: ???
  - experiment: null
```

This works as expected for requiring the user to provide a task, however, I'd like to also allow the user to provide an experiment to run and when doing so not be required to specify a task.

I looked through the documentation but could not figure out how to do it. Thank you in advance for any help.

**Comment by Jasha10** [comment]
Hi @brijow,

I think the easiest way to achieve this would be to use `null` instead of `???` in your config:
```yaml
defaults:
  - task: null
  - experiment: null
```
You can then use the main function in your app to inspect the config supplied by the `@hydra.main` decorator. Perhaps something like this:
```python
import hydra

@hydra.main(config_path="conf", config_name="conf")
def my_app(cfg):
    if not hasattr(cfg, "task") and not hasattr(cfg, "experiment"):
        raise Exception("Specify either a task or an experiment to run.")

if __name__ == "__main__":
    my_app()
```

**Comment by brijow** [comment]
Great, this works for me. Thanks @Jasha10, I'll consider this closed. 👍
