### ISSUE TITLE
[Bug] Set a config value of a group using structured configs

### ISSUE THREAD

**Issue by avril-affine** [facebookresearch/hydra#1705]
# 🐛 Bug
## Description
I'm not sure to tag this as a bug or a feature.
Using structured configs, I'm trying to set a config value within a config group using the `defaults` field. Is this possible? If not, could this be an additional feature?

## Checklist
- [ x] I checked on the latest version of Hydra
- [ x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```
from dataclasses import dataclass, field
from typing import Any, List

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING

@dataclass
class ConfigGroup:
    pass

@dataclass
class A(ConfigGroup):
    x: str = "a"

@dataclass
class B(ConfigGroup):
    x: str = "b"

default_list = [
    {"group/cfg": "B"},
    {"cfg.x": "foo"},  # I'm not sure what should this be?
]
@dataclass
class Main:
    defaults: List[Any] = field(default_factory=lambda: default_list)
    cfg: ConfigGroup = MISSING

cs = ConfigStore.instance()
cs.store(group="group/cfg", package="cfg", name="A", node=A)
cs.store(group="group/cfg", package="cfg", name="B", node=B)
cs.store(name="main", node=Main)

@hydra.main(config_path=None, config_name="main")
def main(cfg: Main):
    print(cfg)
```

** Stack trace/error message **
```
In 'main': Could not find 'cfg.x/foo'
```

## Expected Behavior
I expect the resulting config to be: `{'cfg': {'x': 'foo'}}`

## System information
- **Hydra Version** :  1.1.0 
- **Python version** :  3.7.10

**Comment by omry** [comment]
This is not supported.
You can add another entry to your default list which will override whatever you want to override. You can't override individual values from the defaults list.
