### ISSUE TITLE
when instantiate, make kwargs python object?

### ISSUE THREAD

**Issue by cnut1648** [facebookresearch/hydra#1715]
I was trying to use hydra to instantiate ptrorch optimizer. The optimizer yaml is
```
_target_: torch.optim.Adam
lr: 0.001
betas: [0.9, 0.999]
eps: 1E-08
weight_decay: 1E-4
amsgrad: True
```
and I ran
```python
optim_params = [
        {"params": bn_params, "weight_decay": 0.0},
        {"params": non_bn_params, "weight_decay": optcfg.weight_decay},
    ]
opt = hydra.utils.instantiate(
        optcfg, params=optim_params,
)
```
And I got the error
```
optimizer can only optimize Tensors, but one of the params is omegaconf.dictconfig.DictConfig
```
The error was caused by the internal check of pytorch optimizer, it expects the `params` to be a sequence of python `dict`, however, hydra would change it to a sequence of `omegaconf.dictconfig.DictConfig`, since it would first [ merge `kwargs` to the `config`](https://github.com/facebookresearch/hydra/blob/master/hydra/_internal/instantiate/_instantiate2.py#L173) and then call  [`instantiate_node`](https://github.com/facebookresearch/hydra/blob/master/hydra/_internal/instantiate/_instantiate2.py#L198) 

I am wondering would it be possible to make `DictConfig` and `ListConfig` `kwargs` to be `dict` and `list`, respectively? I am not sure if it would break anything. If it's fine I can submit a PR.

Thanks!

***

Test on
pytorch 1.8.1
hydra 1.1.0rc1

**Comment by Jasha10** [comment]
Hi @cnut1648,

Please take a look at the [parameter conversion strategies](https://hydra.cc/docs/advanced/instantiate_objects/overview#parameter-conversion-strategies) for `hydra.utils.instantiate` -- I think that they will solve your problem.

Try something like this:
```python
opt = hydra.utils.instantiate(
        optcfg, params=optim_params, _convert_="all"  # _convert="partial" should work for your use-case too
)
```

**Comment by cnut1648** [comment]
Thanks @Jasha10! That solves it. Closing this issue now.
