### ISSUE TITLE
Using a config group more than once in experiments

### ISSUE THREAD

**Issue by NinjaAtWork** [facebookresearch/hydra#1720]
Hi
I am trying to define **networkx nodes data** in hydra experiments mode , i need to be able to pre-define less or more node in every experiment.yaml while using one config group more than once.
Docs says if you want to use group more than once then use:
```
defaults:
 - server/db@src: mysql
 - server/db@dst: mysql
```
but how to do this in experiment files?
simply, files looks like this:

config.yaml :

```
defaults:
  - segment : color
```
segment/color.yaml :
```
color_num : 1
```
segment/color2.yaml :
```
color_num : 10
```
experiment/test.yaml :

```
# @package _global_
defaults:
  - override /segment: color2

```

now i want to define (at least) a new config parameter named: `iteration` with defaults from color2.yaml
i need to call some thing like this in main.py : 
`cfg.iteration.color_num`
or better ones:
`cfg.nodes.iteration.color_num`
my try will do nothing or raise:
`assert self.group is not None and self.group != ""`
please pencil me how to do this.
Thanks

**Comment by Jasha10** [comment]
Hi @NinjaAtWork,

Please give this a try.

experiment/test.yaml:
```yaml
# @package _global_
defaults:
  - /segment@iteration: color2
```
The above config will place the `color2` config into the `iteration` package.

at the command line:
```bash
$ python my_app.py +experiment=test  # output from the app is below:
segment:
  color_num: 1
iteration:
  color_num: 10
```

**Comment by NinjaAtWork** [comment]
I tried it at very first but with copy/paste it works like a charm.
My typo for adding space before `@`
Honestly i used to add space before(&after) every `: ` for configs and i add same space for `@` which will raise self.group error. 
Sorry all
