### ISSUE TITLE
Hydra 1.1 when composing a config that is a list at the top level.

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#1724]
Hydra 1.1 raises an error when composing a config if a used config is a ListConfig.

1. Determine behavior in Hydra 1.0
2. If behavior makes sense, allow maintain compatibility, otherwise issue an appropriate error.
Current error:
```python
        if not isinstance(ret.config, DictConfig):
            raise ValueError(
                f"Config {config_path} must be a Dictionary, got {type(ret).__name__}"
            )
```

(Note that the error is reporting the wrong type, should be `type(ret.config)`).

The following should reproduce the issue:

`group/file.yaml`:
```yaml
- a
```

`config.yaml`
```
defaults:
 - group: file
```

**Comment by damian66nowak** [comment]
examples/advanced/ad_hoc_composition/conf/config.yaml
