### ISSUE TITLE
[Feature Request] save runtime overrides

### ISSUE THREAD

**Issue by chris-tkinter** [facebookresearch/hydra#1751]
# 🚀 Feature Request
Hi, thanks for this great library!

I think a feature that can save the runtime overrides would be great. 

## Motivation

One use case is:

Let's say I would like to save model's checkpoint into a folder `ckpt/<wandb-id>` where the id is wandb's run id. 

In my config file I have `ckpt: ./ckpt`, but since `wandb-id` is runtime generated, I have to append id to the checkpoint directory in runtime. Later I would like to restore the config from the previous runs using saved `overrides.yaml` and `config.yaml`, and would like the restored config to have the `wandb-id` in the field `ckpt`, but since it is overridden in the runtime, the restored one would only have `./ckpt`. 

One way is to just save the whole config in the end, and when I would like to restore I can just load the saved config directly. But I feel like it defeats the hydra's methodology that it saves both the config + overrides. I also tried `HydraConfig.get().overrides.task.append` but this is read only

## Pitch

I think an API like this would help
```
HydraConfig.override(key, value)
```
and whenever this is called, it internally updated the saved `overrides.yaml`, so that all the runtime overrides would be tracked.

## Additional context
I am using the hydra version 1.1

**Comment by omry** [comment]
What is a "runtime override"?

**Comment by chris-tkinter** [comment]
By runtime override I mean modifying the config in the runtime not by command line. In the above use case, although I didn't override the `ckpt` field in the command line, I modified it in the runtime (by appending wandb id). However such modification would not be tracked by `overrides.yaml` generated by hydra. Thus I am wondering if it's possible to support this.
