### ISSUE TITLE
Issue a warning if primary config is missing `_self_` and is overriding config values

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#1755]
Hydra 1.1 changed the default composition order and it turned out more disruptive than initially expected.
To help people migrating be aware of the change, we will issue a warning if the primary config is specifying both a Defaults List and config values and the Defaults List is not specifying `_self_.

This warning will be removed in Hydra 1.2.

**Comment by postrational** [comment]
Is it possible to supress this warning in the meanwhile before 1.2 comes out (assuming new app, no hydra 1.0 compatibility needed).

**Comment by Jasha10** [comment]
The warning is raised as a `UserWarning` using python's [`warnings.warn`](https://docs.python.org/3/library/warnings.html#warnings.warn) stdlib function. [Here](https://github.com/facebookresearch/hydra/blob/9cc91b995a0f2bf52d57a3c878721e42c2056995/hydra/_internal/defaults_list.py#L245-L251) is the relevant code in Hydra. You should be able to suppress this by configuring the [`warnings filter`](https://docs.python.org/3/library/warnings.html#warning-filter).

**Comment by francois-rozet** [comment]
We are now at Hydra 1.3.2 and this warning has not been removed.
