### ISSUE TITLE
[Feature Request] Postpone type validation until after recursive instantiation is complete

### ISSUE THREAD

**Issue by rsokl** [facebookresearch/hydra#1759]
# 🚀 Feature Request

By postponing its type validation until after recursive instantiation has been completed, Hydra can permit more descriptive type annotations in structured configs. 

## Motivation

The following code requires that I annotate `Config.x` with `Any`, since I want to use a targeted structured config to populate its field, via recursive instantiation. 

```python
from dataclasses import dataclass, field
from hydra.utils import instantiate

def returns_int() -> int:
    return 1

@dataclass
class InstantiatesToInt:
    _target_: Any = returns_int
        
@dataclass
class Config:
    x:  int = 1

instantiate(Config(x=InstantiatesToInt))  # raises ValidationError: InstantiatesToInt is not a subclass of int
```
If Hydra were to postpone its type validation until after the recursive instantiation is complete, then it would see that the resulting configuration is indeed valid.

The current mode of up-front type validation often forces me to use overly-broad annotations (i.e. `Any`) throughout my configurations and can prevent me from composing configurations.

**Comment by omry** [comment]
Type safety is enabled by OmegaConf, and "postponing it" is not a feature.
if you want to relax OmegaConf type validation, use Any (as you did).

This is not something I am planning to enable.

**Comment by rsokl** [comment]
Gotchya. Thanks for letting me know!

**Comment by rsokl** [comment]
I agree that my proposed solution isn't kosher in terms of static type checking. But it is a shame to have to defer to `Any`, wherever I might want to compose configurations (which is often, since it is such a great feature!).

I wonder if another option would be allow users to disable OmegaConf's type-validation during instantiation. This way I could annotate x as `x: Union[int, Builds[int]]` (where `Builds[Type]` [a generic protocol for a targeted structured config](https://mit-ll-responsible-ai.github.io/hydra-zen/structured_configs.html#hydra-zen-typing)), and thus benefit at least from static type checking.

Of course, OmegaConf could broaden its type-validation to include unions with a DataClass protocol. This would be the best of both worlds, but the devil is in the details here. E.g. it looks like [mypy doesn't yet have support for a DataClass protocol](https://github.com/python/mypy/issues/6568). So this might be a headache.

The current solution – using `Any` – forces me to modify my code, *and* it effectively disables all (runtime and static) type checking for this field. Not to mention that the field becomes more opaque to the user, in terms of the documentation benefits of annotations.

**Comment by omry** [comment]
Yes, using Any is far from perfect. but at the same time runtime type checking is a complicated area and it's hard to come up with something that satisfies all use cases.

Union support is planned in OmegaConf but it will be a while. I am not sure it will help in your use case though.

**Comment by rsokl** [comment]
> runtime type checking is a complicated area and it's hard to come up with something that satisfies all use cases

I totally agree. Would it be feasible to allow users to disable the runtime type-checking?

**Comment by omry** [comment]
You can convert your config to a plain dictionary and then back to OmegaConf.
Something like:
```
cfg = OmegaConf.structured(SomeClass)
cfg2 = OmegaConf.create(OmegaConf.to_container(cfg))
```

**Comment by rsokl** [comment]
Nice. This should have occurred to me. Thank you very much!

**Comment by omry** [comment]
Note that this is not trivial in the context of instantiation because it composes the final config using the inputs provided by the user.
By passing a DictConfig that is not backed by a dataclass in, you lose validation against other user inputs to instantiate.

**Comment by rsokl** [comment]
Thanks for all of the discussion and guidance. It is much appreciated!

**Comment by Jasha10** [comment]
@rsokl your [hydra-zen](https://github.com/mit-ll-responsible-ai/hydra-zen) project looks cool :)

Your use-case reminds me of #1719, which is also related to the interplay between Hydra's instantiate and OmegaConf's structured configs.

I wanted to mention OmegaConf's [custom resolvers](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html), which offer an alternative to using the `_target_` keyword:
```python
OmegaConf.register_new_resolver(name="returns_int", resolver=returns_int)
instantiate(Config(x="${returns_int:}"))
instantiate(Config(x=SI("${returns_int:}")))  # equivalent, but with no mypy failure
```
In the above example, OmegaConf validates that the return-value from `returns_int` of the correct type (`int`, as required by the type annotation in the `Config` class).

**Comment by rsokl** [comment]
Thanks for the tip about using custom resolvers @Jasha10 ! I'll also keep track of #1719 

And thanks for the kind words about hydra-zen :) I am hoping to start to get the word out there to Hydra+ML users soon. It's been really useful for me and my colleagues in our work/research.
