### ISSUE TITLE
can not open https://hydra.cc

### ISSUE THREAD

**Issue by Brodong** [facebookresearch/hydra#1760]
ValueError: Using config_path to specify the config name is not supported, specify the config name via config_name.
See https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes

**Comment by Jasha10** [comment]
Hi @Brodong,
This might be an issue with your internet service provider :P
You can check out the `website` folder in this repository:
https://github.com/facebookresearch/hydra/blob/master/website/docs/upgrades/0.11_to_1.0/config_path_changes.md
has the same information as
https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes

**Comment by omry** [comment]
There is no problem with the website. Ask your ISP if they are blocking it.

**Comment by Brodong** [comment]
> Hi @Brodong,
> This might be an issue with your internet service provider :P
> You can check out the `website` folder in this repository:
> https://github.com/facebookresearch/hydra/blob/master/website/docs/upgrades/0.11_to_1.0/config_path_changes.md
> has the same information as
> https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes
> 
> The other files inside of https://github.com/facebookresearch/hydra/tree/master/website/docs will be useful too.

Thanks!!!!
