### ISSUE TITLE
[Feature Request] Instantiate from string

### ISSUE THREAD

**Issue by TezRomacH** [facebookresearch/hydra#1762]
# 🚀 Feature Request

Add ability to use raw strings with classpath to `hydra.utils.instantiate`.

## Motivation

I want to create objects with `hydra.utils.instantiate` from their string classpath. To do with I need to wrap the string into a dict in format `{"_target_": class_path}`
<img width="697" alt="Screenshot 2021-08-12 at 00 52 28" src="https://user-images.githubusercontent.com/7549587/129108653-3dceae30-94dc-4324-8c9f-deb2a1bbb54f.png">

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

It would be much better to simplify it as 
```python
self.encoder: nn.Module = instantiate(
    "torchvision.models.resnet18",
    pretrained=pretrained,
    progress=progress,
    **kwargs,
)
```

To do this we only need to add an additional check inside `instantiale`:
```python
if isinstance(config, str):
    config = _prepare_input_dict({"_target_": config})
```

if you think it's a nice feature I can make a PR

**Comment by omry** [comment]
Instantiate is designed to work with a config object.
You can pass an empty config and pass the target in the callsite like this:
```python

class MySQLConnection(DBConnection):
    def __init__(self, host: str, user: str, password: str) -> None:
        self.host = host
        self.user = user
        self.password = password

connection = instantiate({}, _target_="my_app.MySQLConnection", host="a", user="b", password="c")
```

**Comment by TezRomacH** [comment]
Does this solution look nice to you? I think it's a bit dirty solution 🤔 

Why not add one simple check inside `instantiate` for string type?

**Comment by omry** [comment]
The API is designed in a certain way. You are trying to use it for a use case it was not designed for.
Feel free to wrap it with your own pristin and pretty version. I do not think this functionality is important enough to justify an API change. Sorry.

**Comment by omry** [comment]
By the way, you can use create your own simpler version based on `hydra.utils.get_class()` as well.
Instantiate is a very complicated and opinionated piece of code which may be doing many things you disagree with.
