### ISSUE TITLE
Parameter Sweeper - call different hydra configs

### ISSUE THREAD

**Issue by catica** [facebookresearch/hydra#1766]
I was trying to run a parameter sweeper (using the Nevergrad Sweeper plugin) and I would like to, besides defining numerical/boolean parameters, test out different loss functions, for instance. 

This is my nevergrad configuration: 
![image](https://user-images.githubusercontent.com/4283843/129350761-f2a35b35-7796-4eda-871c-436683e8c8d9.png)

And this is my config tree-structure: 
![image](https://user-images.githubusercontent.com/4283843/129350964-0a2c008a-4543-4dd4-b02d-9a44dfb2147f.png)

As an example, instead of loading the configuration associated with the _dice.yaml_ , the `cfg` is passing to my main function a `loss_fn:str = 'dice'` . 

Is there a way to make the sweeper use the configuration yaml directly? 

Thanks

**Comment by omry** [comment]
Generally speaking, Hydra sweepers can sweep on config groups and config values.
If you are able to compose the config you need without the sweeper, for example:
```
$ python train.py train/loss_fn=bce
```

You should also be able to sweep over train/loss_fn like:
```
$ python train.py --multirun train/loss_fn=bce,dice
```

How well Nevergrad handles something like this is not clear, but in principle Hydra supports it.
This is not different than that build-in grid search capability in Hydra.

**Comment by catica** [comment]
Hi @omry . 

Thanks for the reply. 

Indeed... Hydra handles this very well... The source of my problem was not that the sweeper was not working but more the syntax I was using. In the pictures I showed above, I was using a dot notation (train.loss_fn) while it should have been a slash notation (train/loss_fn)... 

(As the example you shared)

Thus, and for clarity, I managed to run the Nevergrad sweeping by replacing the Nevergrad configs as below: 

![image](https://user-images.githubusercontent.com/4283843/129412510-c7219ee1-a7c7-4d79-b548-3e10dd1b352a.png)

Maybe it would be good idea to update the documentation of hydra/Nevegrad plugin to illustrate an example similar to this one. Thanks again 👍

**Comment by omry** [comment]
Glad it worked out.
I think the source of your confusion is that you did not understand nested config groups.
Those are described [here](https://hydra.cc/docs/advanced/defaults_list), this is an important page to understand if you use more advanced features of Hydra.

I don't think the documentation of each of the 3 sweepers should cover all the concepts covered in other places of the documentation.

**Comment by omry** [comment]
Feel free to suggest a documentation update via a pull request though!
