### ISSUE TITLE
[CI] hydra_nevergrad_sweeper tests are failing on main branch.

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#1768]
example failure https://app.circleci.com/pipelines/github/facebookresearch/hydra/11235/workflows/273a5296-bebf-4808-8e68-14b9889b63a5/jobs/102829

**Comment by jieru-hu** [comment]
https://github.com/facebookresearch/nevergrad/issues/1208

**Comment by Jasha10** [comment]
Cross reference to PR #1767, which uses a version pin to work around.
Once the nevergrad issue is closed, we should revert the pin.
