### ISSUE TITLE
[Bug] `output_subdir: null` does not work for `multirun`

### ISSUE THREAD

**Issue by nkueng** [facebookresearch/hydra#1773]
# 🐛 Bug
## Description
Disabling the ouput of a `.yaml` file via `hydra.output_subdir: null` works for the standard use-case but not in `multirun`. This still produces an undesired `multirun.yaml`. 

## Checklist
- [x ] I checked on the latest version of Hydra
- [x ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Following the [intro](https://hydra.cc/docs/intro) tutorial should reproduce the issue with the following `conf/config.yaml`:
```
defaults:
  - db: mysql
  
hydra:
  run:
    dir: .
  output_subdir: null
  sweep:
    dir: .
    subdir: .
```
This yields the unwanted `multirun.yaml` in directory `.`.

## Expected Behavior
No output at all.

## System information
- **Hydra Version** :  1.1
- **Python version** :  3.8
- **Virtual environment type and version** : virtualenv
- **Operating system** : Linux Mint 20 Cinnamon

## Additional context
On a side note, the [description](https://github.com/facebookresearch/hydra/blob/2a6cbfaa04c0a5569619d9a01e4dbd6f2e17b1b1/hydra/conf/__init__.py#L147-L148) for `output_subdir` mentiones `None` instead of `null`.

**Comment by Jasha10** [comment]
Hello @nkueng,
Thank you for the bug report!
We will look into it.

**Comment by omry** [comment]
output_dir is controlling the creation of the .hydra directory. `multirun.yaml` is created unconditionally.

**Comment by Jasha10** [comment]
So I guess this is more of a feature request than a bug report...

**Comment by omry** [comment]
Yes, and it's intertwined with #910 and is most likely what the author is really after.

**Comment by Jasha10** [comment]
Good point. I think we should be able to close this issue in favor of #910. @nkueng, is that ok with you?

**Comment by nkueng** [comment]
Thanks for the quick action! Indeed it goes along the lines of #910, but unlike stated there, there is currently no workaround to disable the `multirun.yaml` in 1.1. This is inconsistent in my eyes, as it is possible to disable the same output for a _regualr_ run (as described [here](https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory)). Thus, I am wondering, why the same method does not apply to the mulitrun output.

**Comment by omry** [comment]
You are correct, and there is no workaround for multirun.yaml. Working directory management will get some attention in the next version.

**Comment by nkueng** [comment]
Anyways, thanks for developing such a nice tool! Even if I don't want to use the auto-generated outputs, it's heaps cool! ;)
