### ISSUE TITLE
Filter arguments during object initialization [Feature Request]

### ISSUE THREAD

**Issue by abahnasy** [facebookresearch/hydra#1777]
# 🚀 Feature Request

Filter configuration arguments during object instantiation

## Motivation

when using object instantiation from config file, Hydra passes all arguments to the class constructor. if one of configurations is not defined, it will end up with error `TypeError: __init__() got an unexpected keyword argument 'keyword_arg'`

## Pitch

it would be nice to implement a simple logic to filter the arguments based on the object signature like this one
```
def filter_args(func, keys):
    filtered = {}
    sign = list(signature(func).parameters.keys())
    for k, v in {**keys}.items():
        if k in sign:
            filtered[k] = v
    return filtered
```
instead of modifying the `init()` by adding `kwargs` to accept additional configurations.

**Comment by omry** [comment]
Your config should match the object you are instantiating. Either get Hydra to compose the correct config for you, or clean it up yourself before calling instantiate.
This feature request is in a philosophical conflict with the design of Hydra.
