### ISSUE TITLE
[Bug] Issue loading modules when joblib launcher is configured for multiple CPUs

### ISSUE THREAD

**Issue by harwiltz** [facebookresearch/hydra#1802]
# 🐛 Bug
## Description

I've used the joblib launcher many times, and this is the first time of encountered an issue. I'll preface the rest of this by saying that when `hydra.launcher.n_jobs` is 1, when all else is equal, I experience no issues.

I have a package, let's call it `silly_envs`, that contains some [OpenAI gym environments](https://github.com/openai/gym). The first line in my script is `import silly_envs`, and in `silly_envs/__init__.py` my gym environments are "registered". When I execute my script with multirun and more than one job, an exception is raised saying

```
gym.error.UnregisteredEnv: Error instantiating 'gym.envs.registration.make' : No registered env with id: SillyEnvironment-v0
```

This implies that there must've been an issue importing `silly_envs`. Again, when I run the exact same code from the same context but with only one joblib job, I experience no issues.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

In **`silly_envs/__init__.py`**:

```python
from gym.envs.registration import register

register(
    id="SillyEnv-v0",
    entry_point="silly_envs.silly:SillyEnv",
    max_episode_steps=150
)
```

In **`silly_envs/silly.py`**:

```python
import gym
from gym.spaces import Discrete

class SillyEnv(gym.Env):
    def __init__(self):
        self.observation_space = Discrete(3)
        self.action_space = Discrete(2)
        self.state = 0

    def reset(self):
        self.state = 0
        return self.state

    def step(self, action):
        self.state = (self.state + action) % self.observation_space.n
        done = self.state == 1
        return self.state, 1, done, {}

    def render(self):
        print(self.state)
```

In **`experiment.py`**:

```python
import silly_envs
import gym
import hydra

@hydra.main(config_name="config", config_path=".")
def main(cfg):
    env = hydra.utils.instantiate(cfg.env)
    for _ in range(cfg.sillyness):
        print(env.action_space.n)

if __name__ == "__main__":
    main()
```

In **`config.yaml`**:

```yaml
sillyness: 1

env:
  _target_: gym.make
  _args_:
    - "SillyEnv-v0"

hydra:
  launcher:
    n_jobs: 4

defaults:
  - override hydra/launcher: joblib
```

**Steps**:

1. Write a minimal `setup.py` or for `silly_envs`
2. `(venv) $ pip install gym hydra-core hydra-joblib-launcher`
3. `(venv) $ python setup.py install`
4. `(venv) $ python experiment.py -m sillyness=1,2,3`: This will crash with the exception I wrote above (this is the bug)
5. `(venv) $ python experiment.py -m sillyness=1,2,3 hydra.launcher.n_jobs=1`: This will run without errors.

## System information
- **Hydra Version** :  `1.1.1` (and `hydra-joblib-launcher` version `1.1.5`)
- **Python version** : Tested with `3.8.x` and `3.9.6`
- **Virtual environment type and version** : Virtualenv
- **Operating system** : {Gentoo, Arch} GNU/Linux

**Comment by harwiltz** [comment]
By the way, I'm sorry if I reported this in the wrong place. I realize now that this may also be a `gym` bug.

**Comment by omry** [comment]
One possible workaround is to import gym inside the `@hydra.main` function.

**Comment by harwiltz** [comment]
Thanks, I did end up using a similar workaround  (imported `silly_envs` instead of `gym`).
