### ISSUE TITLE
Reproducing a Hydra run from previous Hydra job configs

### ISSUE THREAD

**Issue by ashleve** [facebookresearch/hydra#1805]
Hi, 

Currently Hydra generates the following logs:
![image](https://user-images.githubusercontent.com/43458894/131483660-c5f2d506-db2c-4d40-aa87-df106e8e4d24.png)

When I want to reproduce the experiment, I can simply load the `config.yaml`:
`python run.py --config-path /logs/runs/.../.hydra --config-name config.yaml`

The problem is, `config.yaml` doesn't contain the hydra logs output paths configuration, which means that after running the line above, the logging path will revert to default.

Is there a workaround for that?

Is it possible to additionally load hydra specific config from some other path with a simple oneliner?

Thanks

**Comment by omry** [comment]
This is not an officially supported workflow.

Try overriding the logging path as well from the command line.
```
python run.py --config-path /logs/runs/.../.hydra --config-name config hydra.run.dir=/logs/runs/.../ 
```

**Comment by Yevgnen** [comment]
@omry 

Hi, how can I load the config with properly formatted placeholders like `${abc.xyz}` in scripts? Can I do this without wrapping another main function? I'm not trying to re-run, but to use the saved output. To instantiate some classes related to the output, I'd like to read the params used saved in `.hydra/config.yaml` but some of them are placeholders.

**Comment by Jasha10** [comment]
@Yevgnen see [OmegaConf.load](https://omegaconf.readthedocs.io/en/latest/usage.html#from-a-yaml-file).

**Comment by Yevgnen** [comment]
```yaml
work_dir: ${hydra:runtime.cwd}
```

@Jasha10  Hi, I tried to load `.hydra/config.yaml` of a run by `OmegaConf.load`, but got the following error when I access the `config.word_dir`

```
UnsupportedInterpolationType: Unsupported interpolation type hydra
    full_key: work_dir
    object_type=dict
```

**Comment by jieru-hu** [comment]
@Yevgnen thank you for trying it out and the repro code. Could you provide a bit more details on what you tried with OmegaConf.load so we can repro? Many thanks

**Comment by jieru-hu** [comment]
reopening, we should look into this and at least provide some documentation on the approach.

**Comment by Jasha10** [comment]
I've had success reproducing the config by using the saved `outputs/.../.hydra/overrides.yaml` file. Specifically, suppose I run `my_app.py` as follows:
```text
$ python my_app.py a=b +c/d=e
```
This produces a file `outputs/.../.hydra/overrides.yaml` with the following contents:
```yaml
- a=b
- +c/d=e
```
This list of overrides can be used to reproduce the config. The following recipe has worked for me:
```python
with hydra.initialize(config_path=config_path):  # same config_path as used by @hydra.main
    recomposed_config = hydra.compose(
        config_name="main",  # same config_name as used by @hydra.main
        overrides=OmegaConf.load("outputs/.../.hydra/overrides.yaml"),
    )
```
There are a few caveats here:
- Currently the `${hydra:...}` resolver cannot be used outside the context of `@hydra.main`. Using `compose` does not play well with the `${hydra:...}` resolver.
- If your config uses non-deterministic resolvers, e.g. to generate a random number or get the current time of day, those resolvers will be run anew (and will probably give different values from the original run). If you need to re-use the values from the initial run, you could try something like this:
`config = OmegaConf.merge(recomposed_config, OmegaConf.load("outputs/.../.hydra/config.yaml"))`

**Comment by jieru-hu** [comment]
how about we jus save  the final composed config of everything related to a job in a separate YAML file (everything including Hydra and the job config, all resolved, no OmegConf syntax in the YAML)  we can also provide an experimental CLI option for rerun an application from that finalized composed config. we will only support single run for now and see how it goes.

**Comment by Jasha10** [comment]
Saving a resolved yaml config (e.g. `outputs/.../.hydra/resolved.yaml`) could certainly be useful! I've just edited the end of my previous comment based on this idea.

That being said, creating `resolved.yaml` could be expensive, e.g. if the user has defined custom resolvers to do some complicated calculation. For this reason, I think it might make sense to have automatic saving of `resolved.yaml` be an opt-in feature (or at least have the option to disable saving `resolved.yaml`).

Another potential complication is that some application use-cases could rely on interpolations or OmegaConf resolvers being *unresolved*, e.g. if the user app wants to call these resolvers at runtime.

For re-running the application, more information is needed than just what is in `resolved.yaml`. The resolved yaml config will not contain typing information. Info about structured config types or enum types cannot be reconstructed from the `resolved.yaml` file. This is why the `compose`+`overrides.yaml` approach is useful.

**Comment by jieru-hu** [comment]
thanks @Jasha10 those are great points! I agree that eagerly resolve *all* configs is not the best way to go -  especially when user applications also plays a role here. 
arguably, we should be able to repro a run if the `task_cfg` and `hydra_cfg` passed into the `task_function` stay the same, the rest will be left up to the user application. I think one lightweight way of enabling this could be pickling `JobReturn`  both before and after the run of user application.
Right now `JobReturn`( which can be very helpful) is not saved anywhere - I think we can enable the *opt in* of this by adding an experimental `CallBack` which dumps the JobReturn for each run. 
The second part of this would providing an experiment CLI option that takes in a JobReturn pickle and single run the application.

**Comment by Jasha10** [comment]
I think that using a `Callback` to pickle the `JobReturn` (and later using a CLI option to load the pickle) sounds like a great idea.
> I think one lightweight way of enabling this could be pickling JobReturn both before and after the run of user application.

To pickle before the run, we might need to change the signature of the [`on_job_start`](https://hydra.cc/docs/next/experimental/callbacks/) hook, since `on_job_start` currently does not accept a `JobReturn` argument.

**Comment by jieru-hu** [comment]
> I think that using a `Callback` to pickle the `JobReturn` (and later using a CLI option to load the pickle) sounds like a great idea.
> 
> > I think one lightweight way of enabling this could be pickling JobReturn both before and after the run of user application.
> 
> To pickle before the run, we might need to change the signature of the [`on_job_start`](https://hydra.cc/docs/next/experimental/callbacks/) hook, since `on_job_start` currently does not accept a `JobReturn` argument.

I think for now we can just pickle the config object instead of a uncomplete JobReturn - that seems like it should be enough (both task and hydra config are included in the `config` object)

**Comment by jieru-hu** [comment]
Hi @ashleve @Yevgnen 
i just created #2098 to address this. It is not a perfect solution but could be useful for what you are trying to achieve.
If you are interested, here is the  [documentation](https://deploy-preview-2098--hydra-preview.netlify.app/docs/next/experimental/rerun/) on this particular issue.

**Comment by addisonklinke** [comment]
I'm see three potential approaches suggested in this thread

1. @ashleve: use the built-in Hydra `--config-path` and `--config-name` flags to point the script to an old config <sup>[[comment]](https://github.com/facebookresearch/hydra/issues/1805#issue-983683196)</sup>
2. @Jasha10: use the Compose API to merge config and overrides  <sup>[[comment]](https://github.com/facebookresearch/hydra/issues/1805#issuecomment-1056311270)</sup>
3. @jieru-hu: use the newly added `--experimental-rerun` flag <sup>[[comment]](https://github.com/facebookresearch/hydra/issues/1805#issuecomment-1069772177)</sup>

I have some questions to better understand the differences between these approaches

1. Do approaches 1 and 2 end up generating the same config object?
2. If the above answer is yes, should approach 1 be preferred whenever `@hydra.main` is applicable? I say that based on this [docs](https://hydra.cc/docs/advanced/compose_api/) recommendation

> Please avoid using the Compose API in cases where @hydra.main() can be used. Doing so forfeits many of the benefits of Hydra (e.g., Tab completion, Multirun, Working directory management, Logging management and more)

3. Is approach 3 only necessary if you want to preserve the original output directory and append to the old log file? Are there other advantages over approaches 1 or 2 that I'm missing? 

Thanks everyone for the clarification!

**Comment by addisonklinke** [comment]
> Approach 1 involves a round-trip through yaml, which does not always capture the original config in full fidelity

Thanks for clarifying this subtle difference - that makes a lot of sense

> Approach 1 always produces the same config even if you refactor your application / input yaml files. This may or may not be desirable.

I'll have to think more about whether this is desirable for my ML experiments. Typically, I would plan to checkout the git commit of the original run before reproducing, in which case there couldn't be any changes to the application code

> I wonder if it would make sense for @hydra.main to expose an overrides parameter so that we could avoid this sys.argv hack...

I agree it could definitely be convenient to officially support that pattern. Worth opening a new issue?

**Comment by npuichigo** [comment]
@Jasha10 For Approach 2, how can we pass the overrides path from command line since we may want the overrides dynamic

**Comment by asimukaye** [comment]
> @Jasha10 For Approach 2, how can we pass the overrides path from command line since we may want the overrides dynamic

@npuichigo I haven't tried it but this: https://github.com/facebookresearch/hydra/issues/1022 seems relevant to your question and might help.

**Comment by bkmi** [comment]
the `compose` + `overrides` looks ok for my purposes, but is there any way to include the `${hydra:...}` resolves in it as well at the current time?
