### ISSUE TITLE
Testing Callbacks

### ISSUE THREAD

**Issue by penguinflys** [facebookresearch/hydra#1812]
# 🚀 Feature Request

Is it possible to test hydra callbacks with pytest?

**Comment by jieru-hu** [comment]
hi @penguinflys  here is the test for callbacks https://github.com/facebookresearch/hydra/blob/main/tests/test_callbacks.py :)

**Comment by omry** [comment]
Testing callbacks is difficult because you need to actually run a Hydra powered process to get the callback to execute. The example from Jieru above shows how we are testing the callbacks logic in the repo.
