### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by assapin** [facebookresearch/hydra#1814]
# 🚀 Feature Request

Looking for a way to instantiate object graphs, where inner objects are managed as part of a config group;
I only found how to do it when inner objects are instantiated inline with the parent object - which means
that I cannot use hydra to override them per run. (This may already be possible and I just didn't manage to find the solution)

Desired state:

config.yaml
```
__target__: models.resnet.ResNetModel
optimizer: adam
```

optimizer/adam.yaml
```
__target__: keras.optimizers.Adam
learning_rate: 0.01
```

## Motivation

Instantiation is a great way to initialize object graphs recursively and directly from yaml.
Config groups are a great way to specify alternative implementations for interfaces that can be composed in experiments.

Supporting the above design pattern will essentially allow the best of both worlds - 
Use Hydra to drive object graph instantiation vs. manually copying config values to constructors - 
While maintaining the ability to swap in implementations of internal components through Hydra's smooth overriding APIs.

**Describe alternatives you've considered**
Right now I need to either:
1. Nest the full object graph in one config file such as the example [here](https://hydra.cc/docs/advanced/instantiate_objects/overview#recursive-instantiation)
2. Use instantiation only for leaf objects

**Comment by assapin** [comment]
Turns out this *is* possible but the syntax is somewhat less intuitive:
config.yaml
```
**defaults:
- optimizer: adam**
_target_: models.resnet.ResNetModel
...

optimizer/adam.yaml
```
optimizer/adam.yaml

_target_: keras.optimizers.Adam
learning_rate: 0.01

**Comment by omry** [comment]
It's intuitive once you realize that instantiate has nothing at all to do with how you composed your config.
Task 1: compose your config.
Task 2: call instantiate on a config node to create an object.
