### ISSUE TITLE
[Feature Request] Add support for the existing `_target_` function args

### ISSUE THREAD

**Issue by bryant1410** [facebookresearch/hydra#1820]
# 🚀 Feature Request

I think it'd be great if, when using `_target_`, the referenced method or class `__init__` function args are automatically supported. By this I mean to treat the arguments (including types, default values, and docstring) from the function/class as if they are arguments specified in a config file (as first-class citizens in some way).

For example, suppose we have this example from the [Instantiate objects docs](https://hydra.cc/docs/advanced/instantiate_objects/overview#simple-usage):

```yaml
optimizer:
  _target_: my_app.Optimizer
  algo: SGD
  lr: 0.01
```

Maybe this `my_app.Optimizer` also has an arg called `eps` with a default value of `1e-8`. Then, we should be able to override it from the CLI with `optimizer.eps=...`. We should be able to somehow get help information for it based on its docstring. And we should be able to also autocomplete based on these.

## Motivation

This is very useful when you instantiate something with lots of args. For example, I find it useful for `Trainer` from PyTorch Lightning, which has a lot of args and default values. It'd be cool to see the default values from the CLI in the help and what they do. It'd be cool to just override the from the CLI without knowing if I declared them or not (I know there's `++` but I think the function/class args should be treated as normal ones). It'd be cool to have CLI autocompletion based on the available `Trainer` args.

Similarly with other types of classes/functions.

## Pitch

The solution I imagine is to somehow parse the available args and docstring from any place in which a `_target_` attribute is used, and treat them as if they are common arguments from the config file.

I have considered as an alternative to declare myself all the arguments a class/function declares. However, this is not maintainable as I have to constantly update them, involves a lot of code/docs repetition, and bloats the config files.

Another alternative when overriding is to just use `++` and check the class/function documentation when using certain configs, knowing in advance how they map to existing ones. This is however far from ideal as mentioned before. It'd be good if any arg worked seamlessly.

**Comment by omry** [comment]
Instantiation operates on the config. To get the behavior you want, you **must** add the relevant parameters to your config.

Once thing you can take a look at that might make this easier is [configen](https://github.com/facebookresearch/hydra/tree/main/tools/configen), an experimental tool used to automatically generate dataclasses that can be used to instantiate objects or call functions based on their signature.

**Comment by omry** [comment]
I am closing as I do not believe what you are suggesting is possible to support.
Feel free to continue discussing there though.
