### ISSUE TITLE
Resuming execution

### ISSUE THREAD

**Issue by jordiae** [facebookresearch/hydra#1822]
Hi, I have tried to search my question in previous issues with no luck. Which is the canonical way of resuming a Hydra execution? Assume that you launch a very long job, and that it crashes in the middle of the execution, and then you want to resume it. To clarify, those would be the steps in my use case:

1. Launch the application normally: python main.py. This generates outputs in outputs/13-09-2021/13:20:00
2. The execution crashes.
3. Relaunch the application, in the same output dir and with the same configuration: python main.py resume_path=outputs/13-09-2021/13:20:00

My application itself takes care of its internal checkpointing etc by saving files in outputs/13-09-2021/13:20:00, but I need to configure Hydra to use the same directory and configuration.

Many thanks in advance.

**Comment by Jasha10** [comment]
Hi @jordiae,

If the creation of your app's config is deterministic, you can re-use the same input yaml files and the same command line arguments with one difference: override the `hydra.run.dir` key (or the `hydra.sweep.dir` key if you are using hydra multirun).

Beware that this will over-write the contents that were previously contained in that output directory (related to https://github.com/facebookresearch/hydra/issues/1817).

For an example, if I run
```
python my_app.py
```
the the directory `outputs/2021-09-14/08-54-10` is created.
When I subsequently run
```
python my_app.py hydra.run.dir=outputs/2021-09-14/08-54-10
```
the same output directory is re-used (overwriting the previous contents).

**Comment by Jasha10** [comment]
Note that issue #1817 contains a proposed behavior change that is relevant for this use-case; it is proposed there that hydra should by default not allow re-use of an output path (in order to prevent accidental overwriting of the pre-existing directory's contents).
This means that in the future it may be necessary to add an extra command-line flag (e.g. #1817 proposed the flag `--allow_overwrite`) in order to achieve your desired behavior.

**Comment by jordiae** [comment]
> Beware that this will over-write the contents that were previously contained in that output directory (related to #1817).

Thanks for your answer, @Jasha10. You meant it will overwrite the fiiles in the directory (not the directory itself) only if my program does indeed write to disk (not append) with a deterministic name, right?

Thanks, @omry!

**Comment by Jasha10** [comment]
> You meant it will overwrite the fiiles in the directory (not the directory itself) only if my program does indeed write to disk (not append) with a deterministic name, right?

Yes, sorry for the lack of precision in my previous answer.
- a pre-existing directory would not be deleted; internally, we are using `pathlib.Path.mkdir` with the `exists_ok=True` keyword argument.
- the files living in the `.hydra` subdirectory, i.e. `config.yaml` and `hydra.yaml` and `overrides.yaml`, *will* be overwritten (though in your use case, the new config should be identical to the old one).
- Log files are appended to. Any file management or output performed by your application can proceed using pre-existing files.

The same is true using multirun mode with the basic sweeper: yaml config files are overwritten, but your app's previous output is not deleted.

**Comment by richardrl** [comment]
Whats the best way to resume model training either same architecture but new optimizer settings?
