### ISSUE TITLE
how to set hydra dont override environment variables in  job env_set  

### ISSUE THREAD

**Issue by jaffe-fly** [facebookresearch/hydra#1835]
~~~
env_set:
      train_data_dir: /codes/audio/AISHELL-1_sample
~~~

in my node ,```train_data_dir```   will sometimes pass through k8s environment variables ,so the yaml env will use if system environment without this variables

**Comment by jieru-hu** [comment]
hi @jaffe-fly 
im not 100% sure what is the question here. Could you provide more details?

It sounds like custom resolver might help here: https://omegaconf.readthedocs.io/en/latest/usage.html#resolvers

**Comment by omry** [comment]
I wouldn't hazard a guess as to what can help because there is no question here.

**Comment by jaffe-fly** [comment]
if the environment variables exist ,copy env name,otherwise,add a new env .so how to set in yaml file?

**Comment by omry** [comment]
I don't understand.

**Comment by jieru-hu** [comment]
@jaffe-fly 
To allow us to  better  you, pls create a minimal repro and explain what is your expected behavior.

**Comment by pixelb** [comment]
omegaconf supports env vars
https://omegaconf.readthedocs.io/en/2.0_branch/usage.html#environment-variable-interpolation

So perhaps something like the following may work:

```
env_set:
      train_data_dir: ${env:train_data_dir,/codes/audio/AISHELL-1_sample}
```

**Comment by Jasha10** [comment]
> So perhaps something like the following may work:

FYI in OmegaConf 2.1 the `${env:...}` resolver has been deprecated in favor of `${oc.env:...}`.
https://omegaconf.readthedocs.io/en/2.1_branch/custom_resolvers.html#oc-env

```
env_set:
      train_data_dir: ${oc.env:train_data_dir,/codes/audio/AISHELL-1_sample}
```
