### ISSUE TITLE
[Bug] Allow additional arguments to structured configs using yaml config files

### ISSUE THREAD

**Issue by ExpectationMax** [facebookresearch/hydra#1836]
# 🐛 Bug
## Description
It is not possible to provide additional arguments to a structured config from a yaml config file.  While this is easily possible using the `+` command line syntax, I cannot find a way to implement similar functionality using a yaml config file.

## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
**minimal_example.py**:
```python
from dataclasses import dataclass
import hydra

class MyClass:
    def __init__(self, **kwargs):
        self.args = kwargs

    def __str__(self):
        return str(self.args)

@dataclass
class MyClassConfig:
    _target_: str = "__main__.MyClass"

@dataclass
class MainConfig:
    the_class: MyClassConfig = MyClassConfig()

cs = hydra.core.config_store.ConfigStore.instance()
cs.store(name="my_class", node=MyClassConfig)
cs.store(name="main_config_base", node=MainConfig)

@hydra.main(config_name="main_config_base", config_path=None)
def main(cfg: MainConfig):
    the_class = hydra.utils.instantiate(cfg.the_class)
    print(the_class)

if __name__ == "__main__":
    main()
```

**minimal_conf.yaml**:
```yaml
defaults:
  - main_config_base
  - _self_

the_class:
  test_arg: 1
```

**Run:**
```bash
# Works perfectly
python minimal_example.py +the_class.test_arg=1
{'test_arg': 1}

# Does not work
python minimal_example.py --config-path . --config-name minimal_conf
Key 'test_arg' not in 'MyClassConfig'                                                                                                                                     
    full_key: the_class.test_arg                                                                                                                                              reference_type=BaseClassConfig                                                                                                                                        
    object_type=MyClassConfig    
```

## Expected Behavior
There should be a way to implement the same behavior of the cli using a config file. I have until now not found out how this could be implemented. Further, as soon as a static configuration is used it is essentially impossible to override `the_class` using yaml config files.

## System information
- **Hydra Version** :  1.1.1
- **Python version** :  3.9.7 
- **Virtual environment type and version** : venv
- **Operating system** : macOS BigSur 11.5.2

**Comment by jieru-hu** [comment]
Hi @ExpectationMax 

I think you are hitting something similar to  this issue https://github.com/facebookresearch/hydra/issues/1351

Pls check it out, Omry provided a detailed explanation and suggested alternatives in the issue. 


in your case, if you update your defaults list to be 
```
defaults:
  - main_config_base
  - _self_
```
it should work as what you expect.

**Comment by ExpectationMax** [comment]
Hi @jieru-hu! Thank you for the hint and direction to solving this. Indeed using 

```
defaults:
  - _self_
  - main_config_base
```
(posting it again here for people who drop by later as there was a typo in your post)

solves the issue. I guess it boils down to what is present in the config first.
If the structured config is present first, then the config file is validated against it. If the config (from the file in form of _self_) is present first and then the config file is loaded the structured config is applied to it. In this case additional fields will not lead to an error.

I think it might be worth mentioning this in the documentation. I guess it is not yet there as the change in behavior was only recently introduced.

Thanks again for the help, I'll close this as the issue is resolved from my side.

**Comment by jieru-hu** [comment]
thanks @ExpectationMax! i edited my answer, sorry for the typo!

we do have documentation on this behavior change in a few places :)  https://hydra.cc/docs/upgrades/1.0_to_1.1/default_composition_order
https://hydra.cc/docs/advanced/defaults_list#composition-order

**Comment by omry** [comment]
A better solution in my opinion is to declare the config node as a Dict, forfeiting type safety for it.
This will allow you to add arbitrary fields to it without restriction from other configs.

```python
@dataclass
class MainConfig:
    the_class: Dict[str, Any] = field(
        default_factory=lambda: {
            "_target_": "__main__.MyClass",
        }
    )
```
