### ISSUE TITLE
how to set muilty value with command?

### ISSUE THREAD

**Issue by jaffe-fly** [facebookresearch/hydra#1838]
```"manifest="${train_data_dir}/train_manifest.json","${train_data_dir}/val_manifest.json","${train_data_dir}/test_manifest.json""```
this not work.

**Comment by Jasha10** [comment]
Please try something like this:
```text
python my_app.py --multirun "manifest=${train_data_dir}/train_manifest.json,${train_data_dir}/val_manifest.json,${train_data_dir}/test_manifest.json"
```

**Comment by jaffe-fly** [comment]
> --multirun

```-multirun```  will  tun three times program, i need run one time program,  in my code  ,a var need a long str like ```"${train_data_dir}/train_manifest.json","${train_data_dir}/val_manifest.json","${train_data_dir}/test_manifest.json"```

**Comment by jieru-hu** [comment]
@jaffe-fly 
pls create a minimal repro and explain what is your expected behavior.

**Comment by Jasha10** [comment]
Here are two options:
1) Use square brackets `[...]` to get a list of strings:
```text
python my_app.py "manifest=[${train_data_dir}/train_manifest.json,${train_data_dir}/val_manifest.json,${train_data_dir}/test_manifest.json]"
```
2) Combine double quotes `"..."` with single quotes `'...'` to get one long string:
```text
python my_app.py "manifest='${train_data_dir}/train_manifest.json,${train_data_dir}/val_manifest.json,${train_data_dir}/test_manifest.json'"
```
