### ISSUE TITLE
[Bug] LexerNoViableAltException: word.p=a|b (error comes from the vertical bar)

### ISSUE THREAD

**Issue by zhaoyanpeng** [facebookresearch/hydra#1843]
hi there,

looks hydra does not support escaping a vertical bar? I checked the doc and it says

> ... by escaping them with a `\`. These characters are: `\()[]{}:=, \t` (the last two ones being the whitespace and tab characters).

any reason for not escaping vertical bar? one of my running parameters is a regex expression, which contains a vertical bar, but I cannot send it in from the command line, e.g, `python main.py word.p=a\|b`

**Comment by Jasha10** [comment]
I can reproduce the issue:
```text
$ cd ~/hydra.git/examples/tutorials/basic/your_first_hydra_app/1_simple_cli/
$ python my_app.py '+foo=ab'
foo: ab

$ python my_app.py '+foo=a|b'
LexerNoViableAltException: +foo=a|b
                                 ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
$ python my_app.py '+foo=a\|b'
LexerNoViableAltException: +foo=a\|b
                                  ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

**Comment by jieru-hu** [comment]
the following works for me:
```
$ python examples/tutorials/basic/your_first_hydra_app/2_config_file/my_app.py '+foo="a|b"'
db:
  driver: mysql
  user: omry
  password: secret
foo: a|b

```

**Comment by zhaoyanpeng** [comment]
thanks @jieru-hu , that works! quoting only the right-hand-side also works: `python main.py word.p='"a|b"'`
