### ISSUE TITLE
[Feature Request] [Submitit-Plugin] Add option to not wait for finished jobs

### ISSUE THREAD

**Issue by jhrmnn** [facebookresearch/hydra#1847]
# 🚀 Feature Request

Add option to not wait for finished jobs.

## Motivation

- With long-running jobs, one typically doesn't want to block their terminal session
- On some clusters, the `sacct` command used by Submitit to monitor jobs might not be available.

## Pitch

A simple configurable option for the plugin should be enough. Right now, I'm using the following one-liner hack, https://github.com/jhrmnn/hydra/commit/3b8f5e330e311090f7174d5d3854d67e8fb29f90, not sure how to best integrate it properly into the code.

**Comment by jieru-hu** [comment]
Hi @jhrmnn 

I think https://github.com/facebookresearch/hydra/issues/692 (support non-blocking launching) is related to your request, this is something we look to support in future releases. 

> With long-running jobs, one typically doesn't want to block their terminal session

Maybe look into solutions like `tmux` for an alternative.

> On some clusters, the sacct command used by Submitit to monitor jobs might not be available.

I think this is more of a Submitit question, so their repo would be a better place for this.

**Comment by jhrmnn** [comment]
Indeed, #692 is a duplicate, sorry about that.

> Maybe look into solutions like tmux for an alternative.

That of course works, but the point here is rather that the monitoring is not really needed.

> I think this is more of a Submitit question, so their repo would be a better place for this.

To a certain degree, yes, but it's also about how the Hydra plugin uses Submitit—if I was using Submitit directly, I would simply never use the watcher that calls `sacct`. When using Submitit via Hydra, I currently don't have that option.
