### ISSUE TITLE
[Bug] Can't reproduce run with installed app

### ISSUE THREAD

**Issue by gphillips-ema** [facebookresearch/hydra#1868]
# 🐛 Bug
## Description

When using an installed hydra app it is not possible to reproduce a run.

In the case of a script you can use the `config-name` and the `config-path` arguments to redirect hydra to use he config.yaml file in the output directory from the original run.  Consider the provided hydra_app_example:

```bash
hydra_app_example $ python hydra_app/main.py app.num2=30
Hello gphillips, 10 + 30 = 40
```
This run produces an output directory in hydra_app_example containing the config constructed by hydra. 

hydra_app_example/outputs/2021-10-26/08-43-50/.hydra/config.yaml
```yaml
db:
  host: localhost
  port: 3306
app:
  user: ${oc.env:USER}
  num1: 10
  num2: 30
```
This config can be reused as follows:
``` bash
hydra_app_example $ python hydra_app/main.py --config-path=/Users/my/abs/path/to/hydra/examples/advanced/hydra_app_example/outputs/2021-10-26/08-43-50/.hydra/
Hello gphillips, 10 + 30 = 40
```
However if you attempted the same using the installed app script you would get a "Primary config module ... not found." error.:
```bash
hydra_app_example $ hydra_app --config-path=/Users/my/abs/path/to/hydra/examples/advanced/hydra_app_example/outputs/2021-10-26/08-43-50/.hydra/
Primary config module 'hydra_app..Users.gphillips.sandbox.hydra.examples.advanced.hydra_app_example.outputs.2021-10-26.08-43-50..hydra' not found.
Check that it's correct and contains an __init__.py file

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```
This error is expected as a result of how `config-path` gets constructed for installed apps.

Trying to set the `hydra.searchpath` argument as recommended in the documentation results in using the config packaged with the installation.
```bash
hydra_app "hydra.searchpath=[file:///Users/my/abs/path/to/hydra/examples/advanced/hydra_app_example/outputs/2021-10-26/08-43-50/.hydra/]"
Hello gphillips, 10 + 20 = 30
```
The app runs, but does not use the config file located at the path provided to `hydra.searchpath`. The same is true when using the `config-dir` argument.
```bash
hydra_app --config-dir=/Users/gphillips/sandbox/hydra/examples/advanced/hydra_app_example/outputs/2021-10-26/08-43-50/.hydra/
Hello gphillips, 10 + 20 = 30
```
## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
Follow instructions in hydra/examples/advanced/hydra_app_example to install hydra_app.

** Minimal Code/Config snippet to reproduce **
```bash
python hydra_app app.num2=30
Hello gphillips, 10 + 30 = 40
```

```bash
python hydra_app --config-path=/abs/path/to/outputs/for/last/run/.hydra/
Hello gphillips, 10 + 30 = 40
```

```bash
hydra_app --config-dir=/abs/path/to/outputs/for/last/run/.hydra/
Hello gphillips, 10 + 20 = 30
```

```bash
hydra_app 'hydra.searchpath=[file:///abs/path/to/outputs/for/last/run/.hydra/]'
Hello gphillips, 10 + 20 = 30
```

## Expected Behavior

All outputs for the above commands should be:
`Hello gphillips, 10 + 30 = 40`
## System information
- **Hydra Version** : 1.1.1  
- **Python version** : 3.7.11
- **Virtual environment type and version** :  conda 4.10.1
- **Operating system** : OSX 10.15.7

## Additional context
This example is framed around reproducing a run, but the problem also inhibits users from providing config files separate from those packaged with the install.

**Comment by jieru-hu** [comment]
hi @gphillips-ema, thanks for listing out all the stuff you've tried! :) 

this is the documentation on how the Hydra CLI is supposed to work  https://hydra.cc/docs/advanced/hydra-command-line-flags/
the fact that `--config-path` worked seems more like a coincidence. :)  Notice in the doc that `--config-dir` is recommended to use for providing extra configuration. 

> Trying to set the hydra.searchpath argument as recommended in the documentation results in using the config packaged with the installation.

`hydra.searchpath` can only be set in a primary config file. In your case, your primary config file cannot be discovered unless Hydra read what's in  `hydra.searchpath`. This creates a "deadlock" situation. The application 
still runs without an exception is because Hydra was able to find a config with the name `config` in your packaged
`conf` folder. This also explains why the config Hydra app reads does not contain the configuration change you made.

> The app runs, but does not use the config file located at the path provided to hydra.searchpath. The same is true when using the config-dir argument.

This is the same case as above, Hydra finds a config named `config` first in `conf` first so it just returns. This is 
because Hydra holds a list of search path and will search for the config going down the list and will return immediately upon the first match.

To further clarify, the following works as expected
```commandline
jieru@jieru-mbp hydra_app_example % hydra_app hydra.run.dir=outputs app.num1=42
Hello jieru, 42 + 20 = 62
jieru@jieru-mbp hydra_app_example % ls -a outputs 
.               ..              .hydra          main.log
jieru@jieru-mbp hydra_app_example % mv outputs/.hydra/config.yaml outputs/.hydra/new_config.yaml
jieru@jieru-mbp hydra_app_example % ls -a outputs/.hydra
.               ..              hydra.yaml      new_config.yaml overrides.yaml
jieru@jieru-mbp hydra_app_example % hydra_app --config-dir outputs/.hydra --config-name new_config
Hello jieru, 42 + 20 = 62
```

**Comment by jieru-hu** [comment]
closing... pls feel free to reopen if needed.
