### ISSUE TITLE
No easy way to provide link to versioned 1.1 Hydra docs

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1871]
It is easy to provide a link to the Hydra docs at version 1.0, e.g. https://hydra.cc/docs/1.0/intro.

When providing links to pages of the version 1.1, however, the version number does not appear in the url, e.g. https://hydra.cc/docs/intro.

When providing such links in e.g. answers to user questions, I fear that the links will become outdated. It would be nice if our website had a way to provide a versioned link for the latest stable version.

**Comment by omry** [comment]
Since 1.1 docs are done, it's a good time to tag a docusaurus version for it. This will enable such links and ensure doc changes are not changing the 1.1 docs.

**Comment by Jasha10** [comment]
> it's a good time to tag a docusaurus version for it.

I've been having trouble with this in PR #1877. We already have versioned docs for v1.1 (i.e. `website/versions.json` has a version 1.1, and `website/versioned_docs/version-1.1` exists with a frozen copy of the docs).

The problem is that there's no way to get a permalink to the v1.1 docs.
According to the table from the docusaurus docs [here](https://docusaurus.io/docs/versioning#directory-structure), this seems to be expected:

Path | Version | URL
-- | -- | --
versioned_docs/version-1.0.0/hello.md | 1.0.0 | /docs/1.0.0/hello
versioned_docs/version-1.1.0/hello.md | 1.1.0 (latest) | /docs/hello
docs/hello.md | current | /docs/next/hello

See that the URL for the latest docs version is `/docs/hello`, and does not contain a version number. In other words, there seems to be no way to make a permalink to our v1.1 docs until after the v1.2 docs have been pinned.

This seems to be related to docusaurus issues filed [here](https://github.com/facebook/docusaurus/issues/1312) and [here](https://docusaurus-2.netlify.app/feature-requests/p/permanent-url-support-for-current-version).
