### ISSUE TITLE
[Feature Request] Better documentation for the search path plugin

### ISSUE THREAD

**Issue by teocasse** [facebookresearch/hydra#1880]
# 🚀 Feature Request

I think better documentation for the search path plugin would be welcome, as it is the only structured way for a framework author to make their configuration accessible via Hydra.

## Motivation

**Is your feature request related to a problem? Please describe.**
I believe the search path plugin functionality should be better documented, as the example is not sufficient for users who are not that familiar with packaging, especially with namespace packages.
## Pitch

**Describe the solution you'd like**
I think that a README that better explain what parts of the code structure and of setup.py are essential in order to package the feature correctly. In particular, it should be clear that the `hydra_plugins` folder is required to be at the top of the project structure in order for that to end up in the namespace where Hydra core looks into.

Moreover, another aspect that I think it is important to highlight is that using the search path plugin to distribute a configuration implicitly require to put all the configuration files in a separate namespace: all the examples on the wiki use a main config file placed _at the root_ of the config path in order to define how the main config is composed from the other config files/groups. However, a framework author must be aware that, if the config path is being appended to the search path, conflicts arising from other entries in the search path should be avoided, and placing a file named `config.yaml` or `main_config.yaml` at the root of the search path will practically guarantee that that file will conflict with another one that the user is using in their downstream application.

**Describe alternatives you've considered**
None in particular. However, regarding the 2nd point I mentioned above (structure of the config path for a framework using SearchPathPlugin), I would like to know if there is any suggested pattern for structuring the configuration. Comparing the Hydra config structure between 0.11 and 1.1 (see https://github.com/facebookresearch/hydra/tree/0.11_branch/hydra/conf and https://github.com/facebookresearch/hydra/tree/1.1_branch/hydra/conf), it seems that this was initially using a yaml file named `hydra.yaml`, and then everything was moved to use structured configs. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Not enough time, unfortunately.

## Additional context
-

**Comment by jieru-hu** [comment]
hi @teocasse thanks for the issue.

We do have some documentations on this topic, we could probably add more details to them. have you checked out the following two pages? (thought i'd mention it just in case)
https://hydra.cc/docs/advanced/search_path
https://hydra.cc/docs/advanced/plugins/develop

**Comment by teocasse** [comment]
Thanks @jieru-hu I had seen the first link but I admittedly didn't see the second, which actually addresses my first point (documentation on the plugin packaging process). I don't see anything obvious missing there, so perhaps it would be sufficient to include a link in the `Config Search Path` page pointing to the `Plugin Development` one, as the first page only includes a link to the example plugin without further explanation.

Do you have any particular suggestion for the second point (i.e. structuring the config directory when distributing configuration through SearchPathPlugin)?

**Comment by jieru-hu** [comment]
@teocasse
We do have some plan on writing a doc for framework owners, tracked here https://github.com/facebookresearch/hydra/issues/1128

in general, it is a  good idea to  provide your configs under a config  group  to  avoid name duplication, using  the config store API as an example here (but should be the  same for yaml files), say your  framework is  `my_framework`, you'd put the `config` under your group to avoid conflicting  with another `config` from another framework.
```
cs.store(name="config", node=MySQLConfig,  group="my_framework")
```

**Comment by teocasse** [comment]
Thank you! Given that the remaining point is already tracked in #1128, I think we can close this ticket :)
