### ISSUE TITLE
[Bug] Override MISSING value in child config

### ISSUE THREAD

**Issue by mayeroa** [facebookresearch/hydra#1881]
# 🐛 Bug
## Description

Hi!

I suspect a bug when I want to create a child structured config (from a parent) and override MISSING values with default containers such as lists or dicts. Maybe the behavior is intended, do not hesitate to confirm. :) 

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```python
from dataclasses import dataclass, field
from typing import Any, Dict, List

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import MISSING


@dataclass
class ParentConfig:
    model_depth: int = MISSING
    model_list: List[int] = field(default_factory=lambda: [5, 6])
    model_list_2: List[int] = MISSING
    model_dict: Dict[str, Any] = MISSING


@dataclass
class ChildConfig(ParentConfig):
    model_depth: int = 5
    model_list_2: List[int] = field(default_factory=lambda: [1, 2, 3])
    model_dict: Dict[str, Any] = field(default_factory=lambda: {'a': 5, 'b': 6})


ConfigStore.instance().store(name='config', node=ChildConfig)


@hydra.main(config_path=None, config_name='config')
def main(cfg) -> None:
    print(cfg)


if __name__ == '__main__':
    main()
```

That code produces the following config:

```shell
{'model_depth': 5, 'model_list': [5, 6], 'model_list_2': '???', 'model_dict': '???'}
```

As we can see, the `model_list_2` and `model_dict` are not properly overridden (`model_depth` is a contrario properly set to `5`) since they remain `MISSING`, even if we use the `ChildConfig` as our primary config.

But if I give to the config store an instantiated config (instead of the class), it works as expected.
Meaning replacing that line:

```python
ConfigStore.instance().store(name='config', node=ChildConfig)
```

into that line:

```python
ConfigStore.instance().store(name='config', node=ChildConfig())
```

produces:

```shell
{'model_depth': 5, 'model_list': [5, 6], 'model_list_2': [1, 2, 3], 'model_dict': {'a': 5, 'b': 6}}
```

Any idea?

## Expected Behavior

I expect that passing either the class or an instance of the primary config should properly set the default values.

## System information
- **Hydra Version** :  1.1.1
- **Python version** : 3.8.11
- **Virtual environment type and version** : MiniConda
- **Operating system** : Linux Mint

**Comment by Jasha10** [comment]
Hi @mayeroa,
Thanks very much for filing this issue! You're correct -- this is a bug. Since the problem lies in the OmegaConf library (rather than in Hydra), I'm going to close this issue in favor of https://github.com/omry/omegaconf/issues/817.

**Comment by mayeroa** [comment]
Ok perfect! thanks @Jasha10 :)
