### ISSUE TITLE
how to initialize the `compose` API with `--config_dir` CLI flag

### ISSUE THREAD

**Issue by aliwumi** [facebookresearch/hydra#1889]
`python my_app.py --config-path=xxx`
the my_app.py import then settings module

and settings.py with code:
```
from hydra import compose, initialize
from omegaconf import OmegaConf

initialize()
settings = compose()
print(OmegaConf.to_yaml(settings))
```

but i got the config is emtpy

**Comment by Jasha10** [comment]
Hi @aliwumi,

The `compose` API does not interact with `sys.argv`.
If you want automatic parsing of your command-line args, use `@hydra.main` instead of `compose`.

If you are using `compose`, you'll need to implement your own command-line logic. I hope that answers your question.
