### ISSUE TITLE
[Feature Request] configuring python libraries using hydra

### ISSUE THREAD

**Issue by youngwoon** [facebookresearch/hydra#1893]
# 🚀 Feature Request

Hydra is a great tool for managing complex and hierarchical configurations. Once I develop a package, I would like to configure this package using hydra (through both configuration files and command line arguments).

For example, project A is using package B. If the package B is using hydra, project A can pass the new configuration to package B, e.g., `python A.py B.var1=10`.

**Comment by jieru-hu** [comment]
hi @youngwoon could you provide a more concrete example of what the feature request would look like?

**Comment by youngwoon** [comment]
Thank you for replying. Here is an example similar to the one in the official documents.

* Python package B is implemented using hydra and the default config is as below:
```
db:
  driver: mysql
  user: omry
  pass: secret
```

* Project A uses package B and tries to configure B's configuration.
```bash
$ python A.py B.db=postgresql B.db.user=abcd B.db.pass=4321
``` 

I hope this conveys the idea of the requested feature.

**Comment by jieru-hu** [comment]
Thanks for the info. I think this kind of depends on exactly how is `B` configured and how is A using B - (ie, is A instantiating a B?)

My feeling is this might already be possible to achieve via Hydra's config group support and instantiation API. Unfortunately I will need more info to give a concrete suggestion :)  For example, what would A.py and B.py looks like? what do their configs look like?

**Comment by Jasha10** [comment]
This seems related in my mind to https://github.com/facebookresearch/hydra/issues/1128.
"How does framework B expose its config to app A?"

**Comment by youngwoon** [comment]
Thanks a lot! I resolved this using SearchPathPlugin!
