### ISSUE TITLE
[Bug?] multirun does not work with hydra.verbose=True

### ISSUE THREAD

**Issue by BenFis** [facebookresearch/hydra#1897]
# 🐛 Bug
## Description
--multirun does not seem to work when using hydra.verbose=True

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
config.yaml:
```
a: 1

hydra:
  verbose: True
```
test.py
```
import hydra


@hydra.main(config_path=".", config_name="config.yaml")
def main(config):
    print(config)


if __name__ == "__main__":
    main()
```
running the command `python test.py -m a=1,2` fails

** Stack trace/error message **
```
Ambiguous value for argument 'a=1,2'
1. To use it as a list, use key=[value1,value2]
2. To use it as string, quote the value: key=\'value1,value2\'
3. To sweep over it, add --multirun to your command line

```

## Expected Behavior
When removing hydra.verbose=True from config.yaml it works as expected:
```
[2021-11-21 14:45:38,189][HYDRA] Launching 2 jobs locally
[2021-11-21 14:45:38,189][HYDRA]        #0 : a=1
{'a': 1}
[2021-11-21 14:45:38,285][HYDRA]        #1 : a=2
{'a': 2}
```

## System information
- **Hydra Version** : 1.1.1
- **Python version** : 3.8
- **Virtual environment type and version** : 
- **Operating system** : Windows 10

## Additional context
Not sure if this is an intended behaviour?

**Comment by Jasha10** [comment]
Hi @BenFis,

Thanks very much for the report. I can reproduce the issue.
