### ISSUE TITLE
overriding the `hydra` config options (logging, working dir) from python - is it possible?

### ISSUE THREAD

**Issue by danielgafni** [facebookresearch/hydra#1903]
# 🚀 Feature Request

Please document overriding the `hydra` config options (logging, working dir) from python if it's possible.

## Motivation

I'm using hydra without the `.yaml` configs. It often takes a lot of time to make them, so I just find it easier to stick with the dataclasses structured configs. I can understand managing the `.yaml` files for an application running in production, but it doesn't make sense for doing research or quickly developing stuff.

However, I can't find a way to override / modify the `hydra` config (like `hydra/hydra_logging` or `hydra/job_logging`. As I understand, this probably can done by importing the original `HydraConf`? 

Anyway, I would really like an official example of how to do it. For example, I want to use `rich` logging, or the `hydra_colorlog` plugin. How can I activate them from python code without using any `.yaml` configs? 

If this is not possible, can it be done with normal `.yaml` configs, but for the `hydra` package only?

Thanks a lot in advance!

**Comment by Jasha10** [comment]
Hi @danielgafni, thanks for opening this issue.

I agree, it would be helpful to add docs with more explanation about python-side config composition.

Here is some info that could be a starting point for such an update to the docs:

## All input configs to Hydra, regardless of the config source, are eventually converted to OmegaConf objects

Under the hood, Hydra uses [OmegaConf](https://omegaconf.readthedocs.io/en/2.1_branch/) as a backend.
All user configs processed by Hydra, whether they originate from a `.yaml` file or from a python `@dataclass` or from a python `dict`,
are eventually converted to OmegaConf object (i.e. an instances of `omegaconf.DictConfig` or `omegaconf.ListConfig`).

The [`pyyaml`](https://pyyaml.org/) library is responsible for converting the
raw `yaml` inputs into python objects (e.g. into `dict` and `list`) before
they are converted to OmegaConf objects.

As a consequence, if you understand how `pyyaml` converts `yaml` files into
python primitives, anything that can be done with a `yaml` file can also be
done with python primitives.

## A Rosetta stone for translating between `.yaml` files, python `dict`, and python `@dataclass`s.

Below is an example of the same app behavior translated into three different implementations.
  - First, a standard implementation using `.yaml` files,
  - Next, an equivalent implementation using python primitives (dicts and lists), and
  - Finally, an implementation that add runtime type-checking using Structured Configs

What the implementations have in common:
  - All three implementations use Hydra's [Colorlog plugin](https://hydra.cc/docs/plugins/colorlog/).
  - All three implementations override the `hydra.run.dir` key as in the [Customizing working directory pattern](https://hydra.cc/docs/configure_hydra/workdir/) doc.
  - All three implementations use the primary config's defaults list to choose a config option (`"mysql"`) from a config group (`"db"`).
  - All three implementations produce below as output when they are run at the command line:
    ```text
    [2021-11-28 21:42:14,012][/home/.../app_using_yaml.py][INFO] - Hello World!
    db:
      user: jasha
      password: secret
    my_setting1: abc
    my_setting2: xyz

    [2021-11-28 21:42:14,013][/home/.../app_using_yaml.py][INFO] - run.dir = ./outputs/custom_run_dir
    ```

#### An example with a `.yaml` file
```python
# app_using_yaml.py

import logging

import hydra
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf

log = logging.getLogger(__file__)


@hydra.main(config_path="config", config_name="main_cfg")
def app(cfg: DictConfig) -> None:
    log.info("Hello World!")
    print(OmegaConf.to_yaml(cfg))

    # Check the `hydra`.run.dir setting
    hydra_cfg = HydraConfig.get()
    log.info(f"run.dir = {hydra_cfg.run.dir}")


if __name__ == "__main__":
    app()
```
```
# config/main_cfg.yaml
defaults:
  - db: mysql
  - _self_
  - override hydra/job_logging: colorlog

hydra:
  run:
    dir: "./outputs/custom_run_dir"

my_setting1: abc
my_setting2: xyz
```
```
# config/db/main_cfg.yaml
user: jasha
password: secret
```
#### An example with python `dict`s
```python
# app_using_primitives.py

import logging

import hydra
from hydra.core.config_store import ConfigStore
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf

cs = ConfigStore.instance()

log = logging.getLogger(__file__)


main_cfg_data = {
    "defaults": [
        {"db": "mysql"},
        "_self_",
        {"override hydra/job_logging": "colorlog"},
    ],
    "hydra": {"run": {"dir": "./outputs/custom_run_dir"}},
    "my_setting1": "abc",
    "mysetting2": "xyz",
}
cs.store(name="main_cfg", node=main_cfg_data)

db_mysql_data = {
    "user": "jasha",
    "password": "secret",
}
cs.store(name="mysql", node=db_mysql_data, group="db")


@hydra.main(config_path=None, config_name="main_cfg")
def app(cfg: DictConfig) -> None:
    log.info("Hello World!")
    print(OmegaConf.to_yaml(cfg))

    # Check the `hydra`.run.dir setting
    hydra_cfg = HydraConfig.get()
    log.info(f"run.dir = {hydra_cfg.run.dir}")


if __name__ == "__main__":
    app()
```
#### An example with python `@dataclass`es
```
# app_using_structured_configs.py

import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List

import hydra
from hydra.core.config_store import ConfigStore
from hydra.core.hydra_config import HydraConfig
from omegaconf import DictConfig, OmegaConf

cs = ConfigStore.instance()

log = logging.getLogger(__file__)


@dataclass
class MainCfgData:
    defaults: List[Any] = field(
        default_factory=lambda: [
            {"db": "mysql"},
            "_self_",
            {"override hydra/job_logging": "colorlog"},
        ]
    )
    hydra: Dict[str, Any] = field(
        default_factory=lambda: {"run": {"dir": "./outputs/custom_run_dir"}}
    )
    my_setting1: str = "abc"
    my_setting2: str = "xyz"


cs.store(name="main_cfg", node=MainCfgData)


@dataclass
class DbMysqlData:
    user: str = "jasha"
    password: str = "secret"


cs.store(name="mysql", node=DbMysqlData, group="db")


@hydra.main(config_path=None, config_name="main_cfg")
def app(cfg: DictConfig) -> None:
    log.info("Hello World!")
    print(OmegaConf.to_yaml(cfg))

    # Check the `hydra`.run.dir setting
    hydra_cfg = HydraConfig.get()
    log.info(f"run.dir = {hydra_cfg.run.dir}")


if __name__ == "__main__":
    app()
```

More information about structured configs can be found
  - in the OmegaConf docs [here](https://omegaconf.readthedocs.io/en/2.1_branch/structured_config.html), and
  - in the Hydra docs [here](https://hydra.cc/docs/tutorials/structured_config/intro/).

Note that with Hydra you are free to mix configs from different config sources.
This means that, within the same app, you can define some of your structured
configs as `yaml` files and others as a python `dict` or `dataclass`.

**Comment by danielgafni** [comment]
Thank you so much for the detailed reply, you helped me a lot!

Another small question: is it possible to configure custom logging this way?

I defied a hydra logging config with `rich`:

```python
@dataclass
class HydraRichLogging:
    handlers: Dict[str, Any] = field(
        default_factory=lambda: {
            "rich": {
                "class": "rich.logging.RichHandler",
                "rich_tracebacks": "true"
            }
        }
    )
    root: Dict[str, Any] = field(
        default_factory=lambda: {
            "root": {
                "handlers": ["rich"],
            }
        }
    )
```

However, I can't pass it to the `defaults` in the main config to override the `hydra/job_logging`:
```python
defaults: List[Any] = field(
        default_factory=lambda: [
            {"override hydra/job_logging": HydraRichLogging()},
        ]
    )
```

```
ValueError: Unsupported item value in defaults : dict. Supported: string or list
```

Is there any way to overcome this issue? Would I have to make a custom plugin like `colorlog`?

Thanks again for the help!

**Comment by danielgafni** [comment]
Actually I can't get any of the custom handlers to work. Here is my config:

```python
@dataclass
class CustomLogging:
    version: int = 1
    formatters: Dict[str, Any] = field(
        default_factory=lambda: {"simple": {"format": "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"}}
    )
    handlers: Dict[str, Any] = field(
        default_factory=lambda: {
            "rich": {"class": "rich.logging.RichHandler", "rich_tracebacks": "true"},
            "console": {"class": "logging.StreamHandler", "formatter": "simple", "stream": "ext://sys.stdout"},
            "file": {
                "class": "logging.FileHandler",
                "formatter": "simple",
                "stream": "${hydra.runtime.output_dir}/${hydra.job.name}.log",
            },
        }
    )
    root: Dict[str, Any] = field(
        default_factory=lambda: {
            "root": {
                "level": "INFO",
                "handlers": ["console"],
            }
        }
    )
    disable_existing_loggers: bool = False

...
cs.store(node=CustomLoggig, name="custom, group="hydra/job_logging")
...
defaults: List[Any] = field(
        default_factory=lambda: [
            {"override hydra/job_logging": "cusom"},
        ]
    )

```
1. I don't get any logs at all
2. The FileHandler can't be configured:
```
omegaconf.errors.InterpolationKeyError: Interpolation key 'hydra.runtime.output_dir' not found
    full_key: hydra.hydra_logging.handlers.file.stream
    object_type=dict
```

**Comment by jieru-hu** [comment]
hi @danielgafni 

1. "${hydra.runtime.output_dir}/${hydra.job.name}.log" is from the latest main branch, if you are using Hydra 1.1, this config is not supported. to find corresponding configs, pls check the 1.1 branch here https://github.com/facebookresearch/hydra/tree/1.1_branch/hydra/conf/hydra/job_logging
2. I'm not sure if the fact that your configs are not working are necessarily due to tyring to add them in Python. I copied your config in a yaml file and could not configure the logger either. How exactly are you trying to use the richhandler? Soemthing like the following seems to be working fine for me (for readability i didn't try to convert them into dataclasses.)
```
version: 1
formatters:
  simple:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
handlers:
  console:
    class: rich.logging.RichHandler
    formatter: simple
  file:
    class: logging.FileHandler
    formatter: simple
    # absolute file path
    filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: false
```
![image](https://user-images.githubusercontent.com/4642412/144095610-3025b8be-298b-4f91-9d09-38e0372b01a3.png)

**Comment by danielgafni** [comment]
@jieru-hu Hey!

1. Well... yeah, obviously :) Idk why I even posted this. Another thing to notice is that am absolute path is required for the `file` handler in `master` and a relative path is required in `1.1`
2. Thank you for correcting my config - for some reason I thought I need to create the `rich` handler separately and use it together with `console`. I understand this has to be one handler now.

But! 

It still doesn't work from python.

It worked for me from the `.yaml` files, but it doesn't python. Here is the dataclass config.

```python
@dataclass
class CustomLogging:
    version: int = 1
    formatters: Dict[str, Any] = field(
        default_factory=lambda: {"simple": {"format": "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"}}
    )
    handlers: Dict[str, Any] = field(
        default_factory=lambda: {
            "console": {"class": "rich.logging.RichHandler", "formatter": "simple", "rich_tracebacks": "true"},
            "file": {
                "class": "logging.FileHandler",
                "formatter": "simple",
                "filename": "${hydra.job.name}.log",
            },
        }
    )
    root: Dict[str, Any] = field(
        default_factory=lambda: {
            "root": {
                "level": "INFO",
                "handlers": ["console", "file"],
            }
        }
    )
    disable_existing_loggers: bool = False
```

Maybe this is a `1.1` issue? I don't have the time now, but will try running the same code in master tomorrow.

**Comment by jieru-hu** [comment]
hey @danielgafni, thank you for trying this out. could you provide a runnable repro (with application code in addition to the python config above)? that'd be easier for us to help debug the issue :)

**Comment by danielgafni** [comment]
@jieru-hu 

here is the [repo](https://github.com/danielgafni/hydra-dataclass-config)

**Comment by jieru-hu** [comment]
thanks @danielgafni for the repo.

there's a typo in your `CustomLogging` class, if you update it to be, it'd work as expected.
```
    root: Dict[str, Any] = field(
        default_factory=lambda: {
            
                "level": "INFO",
                "handlers": ["console", "file"],
            
        }
    )
    disable_existing_loggers: bool = False

```


you can use the Hydra CLI to check for this sort of configuration issue - what i did was comparing the difference of configs between the yaml and dataclass version and spot the difference

```
python config_dataclass.py --cfg hydra -p hydra.job_logging
```
vs
```
python config_yml.py --cfg hydra -p hydra.job_logging
```

then from the output, it is fairly easy to tell the diff :)

**Comment by danielgafni** [comment]
Hey! 

Thank you very much!

I'm very sorry you had to spend your time on my typo. 

I'll use the technique you described from now on if I ever have a config problem again.

**Comment by hiyyg** [comment]
Is it possible to override the logging dir inside the function decorated by `@hydra.main`?

**Comment by omry** [comment]
No. logging is already configured at this stage.
