### ISSUE TITLE
how to make to_absolute_path and get_original_cwd functions work in a subprocess

### ISSUE THREAD

**Issue by byildiz** [facebookresearch/hydra#1904]
## Description
`to_absolute_path` and `get_original_cwd` don't work in subprocesses. The reason is that Hydra seems not initialized in subprocesses.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

**Minimal Code/Config snippet to reproduce**
```python
import hydra
from hydra.utils import get_original_cwd, to_absolute_path
import multiprocessing as mp

def worker():
    print(to_absolute_path('baz'))
    print(get_original_cwd())
    
@hydra.main(config_path='.', config_name='config')
def main(cfg) -> None:
    print(to_absolute_path('foo'))
    print(get_original_cwd())
    p = mp.Process(target=worker)
    p.start()
    p.join()

if __name__ == "__main__":
    main()
```

**Stack trace/error message**
```
/Users/byildiz/Desktop/test_app/foo
/Users/byildiz/Desktop/test_app
/Users/byildiz/Desktop/test_app/outputs/2021-11-27/23-37-30/baz
Process Process-1:
Traceback (most recent call last):
  File "/Users/byildiz/miniconda3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/Users/byildiz/miniconda3/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/byildiz/Desktop/test_app/test.py", line 7, in worker
    print(get_original_cwd())
  File "/Users/byildiz/miniconda3/lib/python3.8/site-packages/hydra/utils.py", line 52, in get_original_cwd
    raise ValueError(
ValueError: get_original_cwd() must only be used after HydraConfig is initialized
```

## Expected Behavior
`to_absolute_path` and `get_original_cwd` should work as expected also in subprocesses.

**Comment by pixelb** [comment]
to_absolute_path() seems to be working for you in your output above?
Can you confirm you're only seeing the issue with get_original_cwd().

I tried to repro this but both functions worked fine with your repro for me

**Comment by byildiz** [comment]
In the main function they work well, but should to_absolute_path('baz') in the worker output the following:
```
/Users/byildiz/Desktop/test_app/baz
```
instead this one:
```
/Users/byildiz/Desktop/test_app/outputs/2021-11-27/23-37-30/baz
```

and for get_original_cwd() should I get:
```
/Users/byildiz/Desktop/test_app
```

instead of a `ValueError`?

**Comment by jieru-hu** [comment]
hi @byildiz the outputs of the helper functiuons are as expected https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/#original-working-directory

as you can see from the error message, if you run in a separate process you'd need to re initialize Hydra, here is an example of from one of our launchers
https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_joblib_launcher/hydra_plugins/hydra_joblib_launcher/_core.py#L24-L42

on the main branch, we've recently added the option to opt out of changing working directory in case that helps your use case, docs can be found here https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory/#disable-changing-current-working-dir-to-jobs-output-dir . Note that this is on the main branch so the feature could be subject to change prior to the next official release.

**Comment by byildiz** [comment]
Hi @jieru-hu, thank you for the reply. Then I need to reinitialize hydra for every subprocesses. One thing I want to ask: how do I make sure to reinitialize hydra to make it use the same output directory that is created by the hydra in the main process?

**Comment by jieru-hu** [comment]
hi @byildiz Hydra actually changes the working directory to the output dir before running your application code, building on top of your application code,
```
import hydra
import multiprocessing as mp
import os

def worker():

    print(f"subprocess working dir: " + os.getcwd())


@hydra.main( config_path='.')
def main(cfg) -> None:
    print(f"main process working dir {os.getcwd()}")
    p = mp.Process( target=worker )
    p.start()
    p.join()


if __name__ == "__main__":
    main()
```

run the application, output as follows
```
main process working dir /Users/jieru/workspace/hydra-fork/hydra/outputs/2021-11-30/11-51-02
subprocess working dir: /Users/jieru/workspace/hydra-fork/hydra/outputs/2021-11-30/11-51-02

```

this sounds like something you'd want?

**Comment by byildiz** [comment]
Thank you @jieru-hu. Yes, I also wanted to initialize hydra in a subprocess  and I managed initialization of hydra with same configuration with the following way from your suggestion at https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_joblib_launcher/hydra_plugins/hydra_joblib_launcher/_core.py#L24-L42:
```python
import os
import logging
from multiprocessing import Process
import hydra
from hydra.utils import get_original_cwd, to_absolute_path
from hydra.core.hydra_config import HydraConfig
from hydra.core.utils import configure_log, setup_globals

def worker(hydra_cfg, cfg):
    # reinitialize hydra
    setup_globals()
    configure_log(hydra_cfg.hydra.job_logging, hydra_cfg.hydra.verbose)
    HydraConfig.instance().set_config(hydra_cfg)

    print(f"main working dir: {os.getcwd()}")
    print(f"main absolute path of baz: {to_absolute_path('baz')}")
    print(f"main original working dir: {get_original_cwd()}")
    log = logging.getLogger('worker')
    log.info('from subprocess')


@hydra.main(config_path='conf', config_name='config')
def main(cfg) -> None:
    print(f"main working dir: {os.getcwd()}")
    print(f"main absolute path of foo: {to_absolute_path('foo')}")
    print(f"main original working dir: {get_original_cwd()}")
    
    log = logging.getLogger('main')
    log.info('from main')

    hydra_cfg = HydraConfig.instance().cfg
    p = Process(target=worker, args=(hydra_cfg, cfg))
    p.start()
    p.join()


if __name__ == "__main__":
    main()
```
and get the following output:
```
main working dir: /Users/byildiz/Desktop/paribubot/outputs/2021-11-30/21-47-23
main absolute path of foo: /Users/byildiz/Desktop/paribubot/foo
main original working dir: /Users/byildiz/Desktop/paribubot
[2021-11-30 21:47:23,926][main][INFO] - from main
main working dir: /Users/byildiz/Desktop/paribubot/outputs/2021-11-30/21-47-23
main absolute path of baz: /Users/byildiz/Desktop/paribubot/baz
main original working dir: /Users/byildiz/Desktop/paribubot
[2021-11-30 21:47:24,652][worker][INFO] - from subprocess
```
The output is what I want.

I only couldn't do singleton state get and set. If I add `singleton_state = Singleton.get_state()` to the main and send it to the worker as a parameter and do `Singleton.set_state(singleton_state)`, I get `AttributeError: Can't pickle local object 'OmegaConf.register_new_resolver.<locals>.resolver_wrapper'`. I couldn't figure this out. Does hydra initialization make a problem without setting singleton state?

**Comment by jieru-hu** [comment]
hi @byildiz 

`multiprocessing`  use pickle behind the scene, which has limited support for complex objects. In this case, it is complaining about a nested function from OmegaConf. To get around this, you can use `cloudpickle`

something like the following should work
```
def worker( cfg, singleton_state):
    # reinitialize hydra
    setup_globals()
    state = pickle.loads(singleton_state)

    Singleton.set_state(state)
    print("from worker")
    print(Singleton.get_state())


@hydra.main( config_path=None)
def main(cfg) -> None:
    print( f"main working dir: {os.getcwd()}" )
    print( f"main absolute path of foo: {to_absolute_path( 'foo' )}" )
    print( f"main original working dir: {get_original_cwd()}" )

    log = logging.getLogger( 'main' )
    log.info( 'from main' )

    singleton_state = Singleton.get_state()
    singleton_state = cloudpickle.dumps(singleton_state)
    p = Process( target=worker, args=( cfg, singleton_state) )
    p.start()
    p.join()


if __name__ == "__main__":
    main()
```

**Comment by byildiz** [comment]
Hi @jieru-hu,

Thank you for the answer. I wish there is an one-liner to reinitialize hydra in a subprocess with the same configuration in the main process. Anyway your suggested code worked like a charm.

> hi @byildiz
> 
> `multiprocessing` use pickle behind the scene, which has limited support for complex objects. In this case, it is complaining about a nested function from OmegaConf. To get around this, you can use `cloudpickle`
> 
> something like the following should work
> 
> ```
> def worker( cfg, singleton_state):
>     # reinitialize hydra
>     setup_globals()
>     state = pickle.loads(singleton_state)
> 
>     Singleton.set_state(state)
>     print("from worker")
>     print(Singleton.get_state())
> 
> 
> @hydra.main( config_path=None)
> def main(cfg) -> None:
>     print( f"main working dir: {os.getcwd()}" )
>     print( f"main absolute path of foo: {to_absolute_path( 'foo' )}" )
>     print( f"main original working dir: {get_original_cwd()}" )
> 
>     log = logging.getLogger( 'main' )
>     log.info( 'from main' )
> 
>     singleton_state = Singleton.get_state()
>     singleton_state = cloudpickle.dumps(singleton_state)
>     p = Process( target=worker, args=( cfg, singleton_state) )
>     p.start()
>     p.join()
> 
> 
> if __name__ == "__main__":
>     main()
> ```

**Comment by byildiz** [comment]
Hi again,
I've just noticed that with this code log message in the worker doesn't appear in the log file nor on the console.

> hi @byildiz
> 
> `multiprocessing` use pickle behind the scene, which has limited support for complex objects. In this case, it is complaining about a nested function from OmegaConf. To get around this, you can use `cloudpickle`
> 
> something like the following should work
> 
> ```
> def worker( cfg, singleton_state):
>     # reinitialize hydra
>     setup_globals()
>     state = pickle.loads(singleton_state)
> 
>     Singleton.set_state(state)
>     print("from worker")
>     print(Singleton.get_state())
> 
> 
> @hydra.main( config_path=None)
> def main(cfg) -> None:
>     print( f"main working dir: {os.getcwd()}" )
>     print( f"main absolute path of foo: {to_absolute_path( 'foo' )}" )
>     print( f"main original working dir: {get_original_cwd()}" )
> 
>     log = logging.getLogger( 'main' )
>     log.info( 'from main' )
> 
>     singleton_state = Singleton.get_state()
>     singleton_state = cloudpickle.dumps(singleton_state)
>     p = Process( target=worker, args=( cfg, singleton_state) )
>     p.start()
>     p.join()
> 
> 
> if __name__ == "__main__":
>     main()
> ```

**Comment by jieru-hu** [comment]
hi @byildiz 

could you try configure the logger in the work?
```
configure_log(hydra_cfg.hydra.job_logging, hydra_cfg.hydra.verbose)

```

**Comment by byildiz** [comment]
Hi @jieru-hu,

Yes, I tried and it works with `configure_log`.

Thanks.
