### ISSUE TITLE
[Bug] BasicLauncher is not being used

### ISSUE THREAD

**Issue by nils-werner** [facebookresearch/hydra#1908]
# 🐛 Bug
## Description

While trying to add functionality to `BasicLauncher` (#1907), I noticed that the class is never actually called.

Apparently, `hydra._internal.core_plugins.basic_launcher.BasicLauncher` is never really used, despite being referenced by `hydra.launcher._target_`.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

 1. `cd examples/tutorials/basic/your_first_hydra_app/1_simple_cli/`
 1. Run `python my_app.py -c hydra` and ensure that `BasicLauncher` is selected
 1. Run `python my_app.py`
 1. It works as expected
 1. Delete the entire class `BasicLauncher` in `hydra/_internal/core_plugins/basic_launcher.py`
 1. Run `python my_app.py`
 1. It still works as expected

## Expected Behavior

After deleting `BasicLauncher`, nothing should work anymore.

## System information
- **Hydra Version** :  latest `main`: 9759f87
- **Python version** : Python 3.7.12 from Homebrew
- **Virtual environment type and version** : `python -m venv`
- **Operating system** : macOS 10.15.7

**Comment by nils-werner** [comment]
Ah, you need to use `-m` to select the launcher, otherwise something else is used.

**Comment by jieru-hu** [comment]
hi @nils-werner.  To call Hydra launcher you'd need multirun mode. We do have plans to re-evaluate this behavior but probably won't happen for the next Hydra release.
