### ISSUE TITLE
Instantiation exception also raises an exception sometimes

### ISSUE THREAD

**Issue by bryant1410** [facebookresearch/hydra#1911]
# 🐛 Bug
## Description

When there's an instantiation exception, raising a chained exception sometimes also fails because it doesn't take an argument:

https://github.com/facebookresearch/hydra/blob/9759f87673be1d41fe33279e1b7980f8efb38b19/hydra/_internal/instantiate/_instantiate2.py#L63-L66

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Try to instantiate an object such that it raises an exception that doesn't take any argument.

## Expected Behavior

Maybe it should try to show another type of exception instead? Or chaining (`from e`).

## System information
- **Hydra Version** :  1.1
- **Python version** : 3.8
- **Virtual environment type and version** : conda 4.11
- **Operating system** : Ubuntu 18.04

**Comment by Jasha10** [comment]
Hi @bryant1410, thanks for reporting this.

Here is a minimal repro:
```python
# module.py
class MyException(Exception):
    def __init__(self):
        """Init method taking no argument"""
        pass

def foo():
    raise MyException
```
```python
# run.py
from hydra.utils import instantiate

instantiate({"_target_": "module.foo"})
```
```text
$ python run.py
Traceback (most recent call last):
  File "/Users/jasha10/hydra.git/hydra/_internal/instantiate/_instantiate2.py", line 62, in _call_target
    return _target_(*args, **kwargs)
  File "/Users/jasha10/hydra_tmp/1911/module.py", line 8, in foo
    raise MyException
module.MyException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jasha10/hydra_tmp/1911/run.py", line 4, in <module>
    instantiate({"_target_": "module.foo"})
  File "/Users/jasha10/hydra.git/hydra/_internal/instantiate/_instantiate2.py", line 180, in instantiate
    return instantiate_node(config, *args, recursive=_recursive_, convert=_convert_)
  File "/Users/jasha10/hydra.git/hydra/_internal/instantiate/_instantiate2.py", line 249, in instantiate_node
    return _call_target(_target_, *args, **kwargs)
  File "/Users/jasha10/hydra.git/hydra/_internal/instantiate/_instantiate2.py", line 64, in _call_target
    raise type(e)(
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by Jasha10** [comment]
I like your proposed idea of exception chaining.
