### ISSUE TITLE
Is it possible to call a hydra wrapped function from a test

### ISSUE THREAD

**Issue by jloveric** [facebookresearch/hydra#1922]
How do I call a function that uses the hydra decorator from a unit test?

I have a function in directory "somedir"
```
@hydra.main(config_path="../config", config_name="some_config")
def some_func(cfg: DictConfig):
    run(cfg)
```
and would like to call "some_config" from a pytest test in a directory "tests".  Currently I have the following pytest in my tests directory
```
def test_some_func():
    some_func()
```
However, when I run the test "pytest tests/test_examples.py I get the error
```
mismatched input 'test_examples.py' expecting ID
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details
```
Has anybody figured out how to do this properly?

**Comment by Jasha10** [comment]
Here are two approaches for your consideration:

---

1. It is possible to pass an argument to functions that have been decorated with `@hydra.main`:
```python
from somedir.app import some_func
from omegaconf import DictConfig

def test_some_func():
    cfg: DictConfig = ...  # compose test-case config here
    assert some_func(cfg) == expected_return_value
```
Note this behavior is different from calling `some_func()` without any arguments, which triggers hydra's command-line parsing of `sys.argv` and is probably not a good idea to do within a `pytest` session. Calling `some_func()` without arguments should usually only happen within an `if __name__ == "__main__"` block.

If you want to test with a config that is based on `some_config.yaml` specifically, you can use the [Compose API](https://hydra.cc/docs/next/advanced/compose_api/) to create the same DictConfig object that `somedir/app.py` were run as a sctipt:
```python
def test_some_func():
    with initialize(config_path="../config"):
        cfg = compose(config_name="some_config", overrides=[])
    assert some_func(cfg) == expected_return
```
See also the [Hydra in Unit Tests](https://hydra.cc/docs/advanced/unit_testing) docs page.

---

2. If you want to test interaction between `some_func` and your `config/some_config.yaml` file, you can run a subprocess:
```python
from somedir.app import some_func
import subprocess, sys

def test_some_func_using_subprocess():
    stdout, stderr = subprocess.Popen(
        args=[sys.executable, "somedir/app.py"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    ).communicate(timeout=10)
    assert stdout.decode() == expected_stdout
    assert stderr.decode() == expected_stderr
```
This is the approach used by many of Hydra's own tests.

**Comment by jloveric** [comment]
Is there a good way to deal with "ValueError: get_original_cwd() must only be used after HydraConfig is initialized"? For now I'll add a try catch around these calls.

**Comment by Jasha10** [comment]
@jloveric, please open a new issue with context or an example about how you are using `get_original_cwd`.
Thanks, Jasha
