### ISSUE TITLE
[Feature Request] Do not run Callback if run wasn't successful

### ISSUE THREAD

**Issue by zakajd** [facebookresearch/hydra#1927]
# 🚀 Feature Request

Hi, thanks for very useful project. 
In my workflow I would like to sync model training logs to remote server once training run is finished. Do so I'm using recently added Callback functionally and roughly follow the documentation guide for S3 sync.

Problem is that sometimes training runs don't finish successfully. They are interrupted, killed or fail in the middle of the training. In that case, I **don't** want the callback code to run and upload the results. Currently `on_job_end` code is always launched.

_How to handle such cases?_

I tried adding config variable like `run_succesful` and modify it at the end of the training, but it doesn't affect the callback behaviour. 

Thanks in advance,
Jamil

**Comment by jieru-hu** [comment]
Hey @zakajd thanks for trying out `Callback`!

`on_job_end` takes in `job_return` variable and you should be able to check if the job succeeded or not in `on_job_end`, JobReturn definition can be found here https://github.com/facebookresearch/hydra/blob/main/hydra/core/utils.py#L242-L250

Would you mind giving that a try?

**Comment by zakajd** [comment]
Thanks for suggestion, it works now!
