### ISSUE TITLE
Is there a way to disable exp_local?

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/hydra#1935]
I'd like to specify my own output path.

**Comment by Jasha10** [comment]
Hi @slerman12,
I'm not sure what you mean by `exp_local`.
Here are two pages from the hydra docs that may be relevant to your question:
[Job Configuration](https://hydra.cc/docs/configure_hydra/job/)
[Output/Working directory example](https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/)
 Feel free to follow up with more detail if your question is not answered by the above.

**Comment by slerman12** [comment]
Got it, sorry
