### ISSUE TITLE
Test against OmegaConf dev version

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1938]
Hydra's CI tests against the latest released version of OmegaConf, currently v2.1.1.

We should add CI testing against the latest (unreleased) commit on OmegaConf's `master` branch.
Related to https://github.com/omry/omegaconf/issues/846.

**Comment by jieru-hu** [comment]
it feels like it could be more helpful if we  test the other way around  - omegaconf changes tested against Hydra main. Since OC is a dependency of Hydra so the other way around would allow us to catch changes in OC that breaks Hydra.

**Comment by Jasha10** [comment]
Hmm, interesting idea!
I think both could be useful -- OmegaConf-side CI for detecting OMC changes that would break Hydra, and Hydra-side CI for detecting Hydra changes that are incompatible with the latest OmegaConf.

**Comment by Jasha10** [comment]
Adding OmegaConf-side CI testing against Hydra would make the projects even more tightly-coupled.
I'm not sure if that's a good thing or a bad thing 😅
