### ISSUE TITLE
[Feature Request] Defining custom resolvers along with SearchPathPlugin

### ISSUE THREAD

**Issue by zaccharieramzi** [facebookresearch/hydra#1943]
# 🚀 Feature Request

I want to be able to define custom `OmegaConf` resolvers, using for example `OmegaConf.register_new_resolver`, alongside my implementation of `SearchPathPlugin`.

## Motivation

Basically I am in a situation where I would like to define submitit plugin customizations in one package, and run hydra with these custom launchers in another repo.
I have managed to define these customizations, and they are working, but now I would like to streamline them a bit more by adding some custom resolvers.
Initially I thought I could add them in the file defining the `SearchPathPlugin` child class, but it didn't work.
You can find the example here: https://github.com/zaccharieramzi/submission-scripts/blob/master/jean_zay/hydra_config/searchpath_config.py#L15

It reads:
```python
# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved
from hydra.core.config_search_path import ConfigSearchPath
from hydra.plugins.search_path_plugin import SearchPathPlugin
from omegaconf import OmegaConf

def qos_from_hours(hours):
    if hours > 20:
        qos = 't4'
    elif hours > 2:
        qos = 't3'
    else:
        qos = 'dev'
    return qos

OmegaConf.register_new_resolver('multiply10', lambda x: x * 10)
OmegaConf.register_new_resolver('qos_from_hours', qos_from_hours)

class JeanZaySearchPathPlugin(SearchPathPlugin):
    def manipulate_search_path(self, search_path: ConfigSearchPath) -> None:
        # Appends the search path for this plugin to the end of the search path
        # Note that foobar/conf is outside of the example plugin module.
        # There is no requirement for it to be packaged with the plugin, it just needs
        # be available in a package.
        # Remember to verify the config is packaged properly (build sdist and look inside,
        # and verify MANIFEST.in is correct).
        search_path.append(
            provider="submission-scripts", path="pkg://jean_zay/hydra_config"
        )
```

And at some point in my config overriding the submitit launcher I would like to have `qos: ${qos_from_hours:hours}` (where `hours` is provided at run time).
I would like to avoid copy-pasting the new resolver definitions in each new package using this conf package.

## Pitch

**Describe the solution you'd like**
I would like to have a class similar to `SearchPluginPath` like `SearchPluginResolver` that allows to define custom resolvers in a package that could be imported anywhere.

**Describe alternatives you've considered**
Of course I could copy-paste the resolvers in each new package or import them in each package, but I would like the packages to be unaware of all SLURM concerns.
I could also resort to not using resolvers which is what I am currently doing.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes, but I think I would need some guidance as it is very unclear to me how `SearchPluginPath` works.

**Comment by Jasha10** [comment]
The resolver should be registered as soon as the `OmegaConf.register_new_resolver` method gets run.
Maybe the method call is not happening at the right time. Could you please add a print statement to your python file (just before the call to `register_new_resolver`) to make sure that the code is getting run?

You can check whether a resolver has been registered by using the [`OmegaConf.has_resolver`](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html#clear-resolvers) method or by checking the `_resolvers` attribute of omegaconf's BaseContainer class:
```python
>>> from omegaconf import OmegaConf
>>> from omegaconf.basecontainer import BaseContainer
>>> BaseContainer._resolvers.keys()
dict_keys(['oc.create', 'oc.decode', 'oc.deprecated', 'oc.env', 'oc.select', 'oc.dict.keys', 'oc.dict.values', 'env'])
>>> OmegaConf.register_new_resolver('multiply10', lambda x: x * 10)
>>> BaseContainer._resolvers.keys()
dict_keys(['oc.create', 'oc.decode', 'oc.deprecated', 'oc.env', 'oc.select', 'oc.dict.keys', 'oc.dict.values', 'env', 'multiply10'])
```

**Comment by zaccharieramzi** [comment]
Yes I verified that the `OmegaConf.register_new_resolver` does not get run with a print statement.

Sorry this was not clear: I am not describing an issue, I am actually requesting a feature similar to `SearchPathPlugin`.
This feature would allow to have custom resolvers defined in installed packages, the same way configurations can be made available via the `SearchPathPlugin` class in an installed package via `'hydra.searchpath=[pkg://installed-package]'`.

I wanted to showcase that it's not possible to do so with the curent `SearchPathPlugin`, because doesn't get executed at the right time (actually I have no idea when the code gets executed).

**Comment by Jasha10** [comment]
Hi @zaccharieramzi, were you able to resolve this issue? I am able to register a resolver from within a hydra plugin using the following minimal setup:
```text
$ tree
.
├── app.py
└── hydra_plugins
    └── mul10.py

1 directory, 2 files
```
```python
# app.py
import hydra
from omegaconf import OmegaConf

@hydra.main(config_path=None)
def my_app(cfg):
    assert OmegaConf.has_resolver("multiply10")

my_app()
```
```python
# hydra_plugins/mul10.py
from omegaconf import OmegaConf

OmegaConf.register_new_resolver('multiply10', lambda x: x * 10)
```

**Comment by zaccharieramzi** [comment]
Hmmm what about a package that's installed not in the same tree structure at all.
My example is this package: https://github.com/zaccharieramzi/jz-hydra-submitit-launcher

I would like to define a custom resolver such that when someones pip installs this package they can use it.

**Comment by Jasha10** [comment]
I see! I believe that the file [`jz_hydra_submitit_launcher/searchpath_config.py`](https://github.com/zaccharieramzi/jz-hydra-submitit-launcher/blob/069a1bdfb22caaf5836f68235f72760d469b1328/jz_hydra_submitit_launcher/searchpath_config.py) is not being discovered by hydra. This means that OmegaConf resolvers in the file are not being registered, and the `SearchPathPlugin` is not usable either.

Hydra's [automatic plugin discovery](https://hydra.cc/docs/next/advanced/plugins/develop/#plugin-discovery-process) relies on using the namespace package "hydra_plugins".

**Comment by zaccharieramzi** [comment]
And in this case, you would put the custom resolver in `searchpath_config.py` or in a different file altogether?

**Comment by Jasha10** [comment]
Putting the custom resolver in `searchpath_config.py`, or any other file under `hydra_plugins` should work too (e.g. `hydra_plugins/jz_hydra_submitit_launcher_plugin/resolvers.py`).

Hydra recursively loads all modules under the `hydra_plugins` namespace package, excepting those modules whose names start with a single leading underscore.

**Comment by zaccharieramzi** [comment]
Makes total sense, thanks @Jasha10  for being so responsive and benevolent!
