### ISSUE TITLE
[Bug?] Changes to the configuration files have an impact on an already launched sweep

### ISSUE THREAD

**Issue by HomoKubrickus** [facebookresearch/hydra#1945]
# 🐛 Bug
## Description
Changes to the configuration files have an impact on an already launched sweep. 

For example, when launching a sweep (using the `--multirun` option) that has 2 jobs, if a configuration file is changed before the second job has started , this second job will use the new version of the configuration file and not the version used when launching the sweep.

I encountered this problem while running machine learning experiments: checking out another branch having different configuration files has an impact on an already running sweep.

Thank you for your work!

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
With the configuration file `config.yaml`:

```yaml
a: 0
b: old
```
And the python script `hydra.py`:
```python
from time import sleep

import hydra


@hydra.main(config_path=".", config_name="config.yaml")
def main(cfg) -> None:
    sleep(10)
    print(cfg)


if __name__ == "__main__":
    main()

```
To reproduce the described behaviour:
- Launch a sweep using this command:
```bash
python hydra.py a=10,20 --multirun
```
- While the first job (`a=10`) is running, change the `config.yaml`to:

```yaml
a: 0
b: new
```
- The output will be:

```
[2022-01-06 11:21:47,228][HYDRA] Launching 2 jobs locally
[2022-01-06 11:21:47,228][HYDRA] 	#0 : a=10
{'a': 10, 'b': 'old'}
[2022-01-06 11:21:57,365][HYDRA] 	#1 : a=20
{'a': 20, 'b': 'new'}
```

## Expected Behavior
Changes to the configuration files don't have an impact on an already launched sweep.  The expected output is:

```
[2022-01-06 11:21:47,228][HYDRA] Launching 2 jobs locally
[2022-01-06 11:21:47,228][HYDRA] 	#0 : a=10
{'a': 10, 'b': 'old'}
[2022-01-06 11:21:57,365][HYDRA] 	#1 : a=20
{'a': 20, 'b': 'old'}
```

## System information
- **Hydra Version** :  1.1.1
- **Python version** : 3.8.5
- **Virtual environment type and version** : 
- **Operating system** :  Ubuntu

**Comment by Jasha10** [comment]
Thanks for pointing this out, @HomoKubrickus!

**Comment by jieru-hu** [comment]
Hi @HomoKubrickus Thanks for the report!

Some more context: 
1) Hydra composed the configs for each job lazily - before launching each job
2) Hydra supports reading configurations from multiple sources, including python packages, files and dataclasses. Hydra queries these config sources at config composition time. Hydra will compose the configs as they are according to the different config sources, regardless of whether they've change between jobs or not.

Generally it is a good idea to not change your code base or configuration sources during experiment running time for reproducibility. In fact, there's existing experiment management solutions that support cloning your environment and launch a new experiment from that. Maybe take a look at those if you want to keep working in your code base while an experiment is running.

I will update our documentation to highlight this to set the right expectations. Thank you!

**Comment by Jasha10** [comment]
After some discussion on this topic, it is not clear whether this is something we will be able to fix.
