### ISSUE TITLE
Question: how to make a hierarchical experiment directory

### ISSUE THREAD

**Issue by yuvalkirstain** [facebookresearch/hydra#1947]
# 🚀 Question

How to launch an experiment while keeping a hierarchical experiment directory? 

## Motivation
I have lots of experiments and I want to store them in a hierarchical manner. When I pass:

```bash
python train.py +experiment=model/dataset
```
Hydra can't find the relevant config. 

I am able to store a flat directory and launch:
```bash
python train.py +experiment=model-dataset
```
but this results in a very messy directory. 

I will appreciate any help!

Thanks :)

**Comment by Jasha10** [comment]
Hi @yuvalkirstain,

Please try this:
```text
python train.py +experiment/model@experiment=dataset
```

**Comment by yuvalkirstain** [comment]
Thank you @Jasha10!

It led to some issues, but `python train.py +experiment/t5_l_lm/dataset@_global_=contract` seems to work fine. 

It would have been great if you had some interactive tutorial, I really like Hydra, but it find it challenging to master.

**Comment by aldopareja** [comment]
I'd appreciate if anyone can show me how this works.
