### ISSUE TITLE
[Bug] submitit launcher: `additional_parameters` cannot be used with local

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#1966]
# 🐛 Bug

In order to allow a parameters that are not yet available in the submitit plugin, there's an `additional_parameters` for `SlurmQueueConf` here:

https://github.com/facebookresearch/hydra/blob/8ebc3ead43b5ebfe51c76ede5ee633a11de5cfc0/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L68

Unfortunately, it cannot be used for `LocalQueueConf`. I suggest to move `additional_parameters` from `SlurmQueueConf` to `BaseQueueConf` so that it can be used for all executors.

As additional context, I would like to use [`stderr_to_stdout`](https://github.com/facebookincubator/submitit/blob/6f9e1f67178b08b050576fe6bc02e4555568128a/submitit/auto/auto.py#L130) in submitit. This is not yet supported by the plugin, which would be ok if we could specify it through `additional_parameters`.

**Comment by Jasha10** [comment]
Hi @YannDubs, would you be willing to submit a PR for this?

**Comment by YannDubs** [comment]
Yes but I looked into it and it seems that `additional_parameters` is actually a slurm specific argument rather than a `**kwargs` that simply redirects arguments to submitit.  

Having a `**kwargs` might be interesting in the future but for now I'd rather just add `stderr_to_stdout` in the submitit plugin. 

Sorry for the confusion I'll open a new issue with PR.
