### ISSUE TITLE
[Feature Request] Allow multiple executions with the same config in multirun

### ISSUE THREAD

**Issue by danielgafni** [facebookresearch/hydra#1969]
# 🚀 Feature Request

Allow multiple job runs with the same config.

## Motivation

Sometimes you need to execute a job multiple times. 
For example, in ML the training can often be unstable. If I want to run it multiple times (for example, to average the results), I need to do something like this right now:

```shell
python script.py lr=0.1,0.1,0.1,0.1,0.1
```

## Pitch

This should be very easy to implement. For example, a `hydra.job.repeat` param can be added. Then it could be used like this:

```shell
python script.py hydra.job.repeat=5 lr=0.1
```

**Comment by Jasha10** [comment]
Hi @danielgafni!
Would a [range sweep](https://hydra.cc/docs/next/advanced/override_grammar/extended/#range-sweep) work for your use-case?
```text
python script.py '+repeat_num=range(5)' lr=0.1
```

**Comment by danielgafni** [comment]
hey @Jasha10 !

Thanks for the suggestion, it looks good! 

I guess the issue is not very important (considering your suggestion).

**Comment by danielgafni** [comment]
There is an issue with this approach: the Optuna sweeper will start optimizing the dummy `repeat_num` hyperparameter. What do you think about this?

**Comment by Jasha10** [comment]
Hmm... Yes, I think you're right that the `range(5)` technique doesn't make sense with the Optuna sweeper.

With optuna, the total number of jobs is constrained by the `hydra.sweeper.n_trials` setting. Does something like this work for your use-case?
```text
python script.py --multirun hydra/sweeper=optuna hydra.sweeper.n_trials=5 lr=0.1
```

**Comment by MM-IR** [comment]
So is it sequentially executed? or creating several processes simultaneously?
