### ISSUE TITLE
Document hydra.utils.{get_class,get_method}

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#1972]
Users would benefit from documentation for the following:
[`hydra.utils.get_class`](https://github.com/facebookresearch/hydra/blob/1cbe86ebecbeb134a3f2041120d57447a7394314/hydra/utils.py#L21)
[`hydra.utils.get_method`](https://github.com/facebookresearch/hydra/blob/1cbe86ebecbeb134a3f2041120d57447a7394314/hydra/utils.py#L32)

**Comment by MaxWolf-01** [comment]
Would be greatly appreciated if this could be doumented!
