### ISSUE TITLE
Need `datetime`-typed field support

### ISSUE THREAD

**Issue by Felix-neko** [facebookresearch/hydra#1973]
Hi folks!

I'm using structured configs (via dataclass). For me it will be really useful to have a couple of `datetime` fields in it, that would be automatically parsed from ISO-formatted string values of corresponding commandline args.

Can you add such feature in future releases?

**Comment by Jasha10** [comment]
Hey!

This issue should be against [OmegaConf](https://github.com/omry/omegaconf), but I'll respond here.

Yaml does [natively support timestamp objects](https://yaml.org/type/timestamp.html), and pyyaml (which is the backend for OmegaConf) parses yaml timestamps as python datetime objects, so this could theoretically be supported.
```python
>>> import yaml
>>> yaml.safe_load("2001-12-15T02:59:43.1Z")
datetime.datetime(2001, 12, 15, 2, 59, 43, 100000, tzinfo=datetime.timezone.utc)
```
That being said, after some discussion surrounding the [recent feature request for `bytes` support](https://github.com/omry/omegaconf/issues/844), I don't feel comfortable committing to this. The main concern is feature bloat.

Could you please repost this issue against OmegaConf? We can then gauge the response from the user community and prioritize / decide whether to move forward.

**Comment by Felix-neko** [comment]
https://github.com/facebookresearch/hydra/issues/1973 -- I've forwared this feature request to OmegaConf, I hope they will support it...
