### ISSUE TITLE
[Issue] Optuna sweep runs sequentially even when setting `n_jobs=2`

### ISSUE THREAD

**Issue by mariomeissner** [facebookresearch/hydra#1974]
# Issue
## Description
Optuna sweep runs sequentially even when setting `n_jobs=2`.
I assume something is wrong on my end regarding the batched job launching...

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro --> Not yet, because I assume I'm missing a simple step. But I will if no quick solution is found.

## To reproduce
Run an Optuna sweep with `n_jobs > 1`.
I run a task with 3 jobs, and `n_jobs=2`, so two jobs should run in parallel and the third should run after that.

I can see the log output "Launching 2 jobs locally" at the beginning, which makes me think that the `n_jobs` has been correctly read. However, those 2 jobs still run sequentially in my terminal. After that, I can see "Launching 1 jobs locally" which means all 3 jobs ran.

## Expected Behavior
Two parallel jobs and a third job once the first two finished.

## Question
What am I missing to make the first two jobs run in parallel? Do I need to configure some special launcher in addition to configuring the `n_jobs` in Optuna Sweeper?

**Comment by Jasha10** [comment]
Hmm... 🤔

Are you using the basic launcher? It runs jobs serially.
The optuna sweeper may pass two jobs at a time to the launcher, but if the launcher cannot parallelize that batch of jobs, then they will run one-after-another.

Try using one of the launcher plugins. For example, using the [Ray Launcher](https://hydra.cc/docs/next/plugins/ray_launcher/):
```yaml
defaults:
  - override hydra/sweeper: optuna
  - override hydra/launcher: ray
  ...
```

**Comment by mariomeissner** [comment]
@Jasha10 

Right, I didn't know about that!

Which launcher would be better suited for this? I want to train several models simultaneously on my local machine (one on each GPU, I have already implemented the GPU ID handling for that).

I'd go for the one requiring the least setup / additional required packages. Would Joblib be better suited for this task?
Ray seems more complicated because I have to initialize a ray cluster first?

**Comment by Jasha10** [comment]
> Is `override hydra/launcher: ray` really all that is required?

Joblib seems sensible for running on a local machine. That being said, `ray` worked for me out of the box :)

**Comment by mariomeissner** [comment]
Thanks again for your help!

**Comment by mariomeissner** [comment]
Unfortunately, both launchers fail for me out of the box.

With ray, I get:
```
Error instantiating 'pytorch_lightning.trainer.trainer.Trainer' : You requested GPUs: [0]
 But your machine only has: []
```

With joblib, I get:
```
  File "/home/meissner/miniconda3/envs/lightning/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 139, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/meissner/miniconda3/envs/lightning/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/optuna_sweeper.py", line 42, in sweep
    return self.sweeper.sweep(arguments)
  File "/home/meissner/miniconda3/envs/lightning/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 241, in sweep
    raise e
  File "/home/meissner/miniconda3/envs/lightning/lib/python3.8/site-packages/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 219, in sweep
    values = [float(ret.return_value)]
  File "/home/meissner/miniconda3/envs/lightning/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
AttributeError: 'Process' object has no attribute 'env'
```

**Comment by mariomeissner** [comment]
For the joblib error, [this issue](https://github.com/pytorch/pytorch/issues/44687) seems related.

**Comment by mariomeissner** [comment]
I managed to make GPUs visible to ray by doing this:
```
hydra:

  launcher:
    ray:
      init:
        num_gpus: 2
      remote:
        num_gpus: 2
```
But now, my jobs still don't run in parallel. They run sequentially.
I'd greatly appreciate any help regarding how to set up ray for parallel GPU training!

**Comment by mariomeissner** [comment]
> For the joblib error, [this issue](https://github.com/pytorch/pytorch/issues/44687) seems related.

Through this solution, I managed to make joblib work. Finally!

**Comment by Jasha10** [comment]
Great, I'm glad you worked it out @mariomeissner!
I wasn't trying to parallelize across GPUs when I said that the launchers worked for me out-of-the-box :P

I assume you used the `DataLoader(..., multiprocessing_context=get_context('loky'))` trick from [this comment](https://github.com/pytorch/pytorch/issues/44687#issuecomment-790842173) to resolve your issue.

**Comment by faroit** [comment]
@mariomeissner i also tried ray, as I couldn't get joblib to work (+didn't want to mess with the dataloader). Turns out it works fine! For a node with 4 gpus you would have to set this up as

```yaml
hydra:
  launcher:
    ray:
      init:
        num_gpus: 4
        local_mode: False
      remote:
        num_gpus: 1
```

also make sure that the lightning trainer is set up correctly to handle 1 gpu

```yaml
trainer:
  devices: 1
  accelerator: gpu
  strategy: null
  auto_select_gpus: true
```

and last but not least, gpus have to set to EXCLUSIVE_MODE to make `auto_select_gpus` work by setting `sudo nvidia-smi -c 3`

@Jasha10 after some tests I can conclude that this runs very stable and spawning is very quick, so I would recommend this to anyone looking for parallel execution on single machines now. Happy to provide a docs PR if thats interesting.

**Comment by GeorgePearse** [comment]
@faroit I'm trying to access the ray dashboard, do you know how to specify the IP for ray via hydra? Training on GCP and assuming I need to run on 0.0.0.0 and then ssh in with port forwarding.

**Comment by nurlanov-zh** [comment]
> @mariomeissner i also tried ray, as I couldn't get joblib to work (+didn't want to mess with the dataloader). Turns out it works fine! For a node with 4 gpus you would have to set this up as
> 
> ```yaml
> hydra:
>   launcher:
>     ray:
>       init:
>         num_gpus: 4
>         local_mode: False
>       remote:
>         num_gpus: 1
>         max_calls: 1
> ```
> 
> Note that `max_calls: 1` is required because the gpu isn't freed quickly enough after the task has finished, thus the training may crash.
> 
> Then, make sure that the lightning trainer is set up correctly to handle 1 gpu
> 
> ```yaml
> trainer:
>   devices: 1
>   accelerator: gpu
>   strategy: null
>   auto_select_gpus: true
> ```
> 
> and last but not least, gpus have to set to EXCLUSIVE_MODE to make `auto_select_gpus` work by setting `sudo nvidia-smi -c 3`
> 
> @Jasha10 after some tests I can conclude that this runs very stable for normal multiruns and spawning is very quick, so I would recommend this to anyone looking for parallel execution on single machines now.
> 
> **Update**: like joblib, it hangs randomly when num_workers is > 0 [ray-project/ray#13407](https://github.com/ray-project/ray/issues/13407)

I have tried this solution. It automatically finds allocated GPUs and runs jobs in parallel. However, after one of the jobs is finished, it does not start a new job. What might be the issue?
