### ISSUE TITLE
[Feature Request] Extend Compose API Initialization Methods to Add Multiple Directories into the Search Path

### ISSUE THREAD

**Issue by AjinkyaIndulkar** [facebookresearch/hydra#2001]
# 🚀 Feature Request

Hey Folks! Since this is my first issue on this repository, I would like to say that this is a great project and has been really helpful for the projects I am working on!

Coming to the feature request, I would like the Compose API to extend the functionality of initialization methods to add multiple config directories to the hydra config search path.

## Motivation

**Is your feature request related to a problem? Please describe.**
Since the current initialization methods only add one config directory to the search path, it tends to reduce flexibility of organising YAML configuration files for complex applications. `initialize_config_dir()` method is helpful to organise all configuration files in one directory but if I want to place the main configuration file in a different directory, hydra is unable to find it. This is obviously due to the parent directory of the main configuration file not included in the search path.

This can also be helpful in unit testing where one would like to keep all their test data in, for example, `tests/configs` and not `configs/` but still access all configurations from `configs/` via the `defaults` key.

## Pitch

**Describe the solution you'd like**
I already have a working solution (which can definitely be refined) for this. This solution can be either packaged in a different method or integrated with existing ones.

My logic:

- create a new search path object `csp` using `create_config_search_path(search_path_dir="configs/")`
- update `csp` to include additional config directories using `csp.prepend()`
- initialise hydra instance with `Hydra.create_main_hydra2(task_name="app", config_search_path=csp)`

**Describe alternatives you've considered**

The above solution is a bit hardcoded but we can either:
- update `config_dir` parameter in `initialize_config_dir()` to accept lists instead of `str`
- use `**kwargs` to handle additional config directories, if provided.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

I would be happy to contribute to this project if my solution is acceptable. I can create a Pull Request within this week.

## Additional context
Unfortunately, I could not find any related issues. Please redirect to the correct issue if this feature request has already been discussed.

**Comment by Jasha10** [comment]
Thanks for the proposal @AjinkyaIndulkar!
I like the idea of `config_dir` being typed as `Union[str, List[str]]`.
I'll bring up this idea at our team meeting to see if there's any feedback.

**Comment by Jasha10** [comment]
@AjinkyaIndulkar, have you tried the pattern from the [Overriding hydra.searchpath config](https://hydra.cc/docs/advanced/search_path/#overriding-hydrasearchpath-config) docs page?
The idea would be to load your primary config (using either `@hydra.main` or `compose`) and then to modify the config search path by overriding `hydra.searchpath` from within that primary config.

Here is the relevant excerpt from the linked docs page:
```yaml
defaults:
  - dataset: cifar10

hydra:
  searchpath:
    - pkg://additonal_conf
    # You can also use file based schema:
    # - file:///etc/my_app
    # - file://${oc.env:HOME}/.my_app
```

The idea for unit tests would be to use compose to load a specified config from `tests/configs` and then add the main `configs` directory to the searchpath from within that test config.

**Comment by AjinkyaIndulkar** [comment]
ah interesting! I was not aware of this. I'll try this out first.

**Comment by AjinkyaIndulkar** [comment]
@Jasha10 the above approach worked but I had to add the absolute path. Is it possible to implement something like this?

```
hydra:
  searchpath:
    - file:///${hydra:runtime.cwd}/configs/
```

Right now, I get:

```
ValueError raised while resolving interpolation: HydraConfig was not set
```

I would like to use the current working directory to define the search path. otherwise, if anyone else wants to use the config file, they'll have to update full path. Is there some way to use `pwd` or `os.getcwd()`?

**Comment by nmichlo** [comment]
I was just about to submit my own feature request, but I found this issue but I see it has now been closed.

I would like to advocate for this enhancement:

> Thanks for the proposal @AjinkyaIndulkar!
> I like the idea of `config_dir` being typed as `Union[str, List[str]]`.
> I'll bring up this idea at our team meeting to see if there's any feedback.

My current project exposes a standard set of configurations. Downstream projects are intended to create their own new configuration directory to override the configs in the standard search path. But it is not easy to control the ordering of items in the search path. (the downstream project should not introduce its own code or plugins). I am not sure if there is an easier way to achieve this?

**Comment by Jasha10** [comment]
Hi @nmichlo,

I have a few questions about your use-case:
- Is your project something that the downstream users would install via a package manager (e.g. pip)?
- Would the downstream users be making the call to `@hydra.main`/`compose`, or is the config composition taking place on your end?

**Comment by nmichlo** [comment]
> * Is your project something that the downstream users would install via a package manager (e.g. pip), with the configuration that you provide being colocated with the installed python package?

The idea is something like this or that it is cloned into a separate directory
- My current very hacky workaround is to manually inject a new `hydra._internal.utils.create_config_search_path` to change the order of the search path. This is done just before @hydra.main is called.

> * Would the downstream users be making the call to `@hydra.main`/`initialize`+`compose`, or is the config composition taking place on your end?

This is taking place on my end. The end-user should not need to worry about these at all. The only thing they do is specify the path to their updated config folder (currently with an environment variable, but a command line option might be better).

**Comment by jieru-hu** [comment]
@nmichlo thanks for the context! Yes, we are aware that search path is might not be very intuitive for some framework use cases. This is something we will look into. 


> The reason I do this instead of using a plugin is because I also want the main/root config file we provide to be able to be overridden too in the search path,

It sounds like you could benefit from allowing your users to use the [Hydra command line](https://hydra.cc/docs/advanced/hydra-command-line-flags/), in particular 
```
--config-path,-cp: Overrides the config_path specified in hydra.main(). The config_path is relative to the Python file declaring @hydra.main().
--config-name,-cn: Overrides the config_name specified in hydra.main().
--config-dir,-cd: Adds an additional config directory to the [config search path](https://hydra.cc/docs/advanced/search_path/).
```
have you taken a look at these?

**Comment by nmichlo** [comment]
I can't believe I missed the `--config-dir` option for the command line. I mistakenly thought it would append not prepend to the search path? Maybe this should be clarified in the docs? I missed the references to that in the code too, but I see it now. This will simplify things a lot. 

It might still be beneficial to somehow allow control of order of everything more easily + allow multiple paths.

**Comment by jieru-hu** [comment]
@nmichlo cool, let us know if you are still experiencing issues with then.

> It might still be beneficial to somehow allow control of order of everything more easily + allow multiple paths.

Yes, agreed. This is one of the areas we will  investigate and improve.

**Comment by nmichlo** [comment]
> @nmichlo cool, let us know if you are still experiencing issues then.

Unfortunately `--config-dir` is still problematic as it does not `prepend` the config directory before the main one as I originally thought, based on lines: https://github.com/facebookresearch/hydra/blob/2a9f18163ad02192cfb05ddbf93edaeb9bf01e20/hydra/_internal/utils.py#L335-L339

It just prepends the search path before the last item being the anchor, which is still after the main search path. Files cannot be overridden this way using this command line option.

**Comment by jieru-hu** [comment]
usually our users use `config-dir` together with "--config-name" to point to a new main config, did you try that?

**Comment by nmichlo** [comment]
I'm sorry, this discussion has extended further than expected. I'm not sure if I should open a new issue?

As for '--config-name' while I could create and specify a new root file, I would still not be able to replace/override existing files in the old/main config directory with files contained in the new/downstream config directory.

One solution to change the search path order could be to swap paths passed to the '--config-path' and '--config-dir', but this is not ideal as the first path needs to be relative, if I'm not mistaken.

**Comment by Jasha10** [comment]
> I'm sorry, this discussion has extended further than expected. I'm not sure if I should open a new issue?

@nmichlo Don't worry about it, this discussion is still on topic.

I looked at the examples ([1](https://github.com/nmichlo/disent/blob/4e2fe384e28f3f65388e82a005137fc70806ba69/experiment/util/hydra_search_path.py#L56-L64), [2](https://github.com/nmichlo/disent/blob/4e2fe384e28f3f65388e82a005137fc70806ba69/experiment/run.py#L485-L488)) you provided in one of your previous comments. My understanding is that users supply the `$DISENT_CONFIG_ROOTS` environment variable to add their config directories to the search path, and that these directories should come earlier in the search path than the `config` directory provided by your library.

Does the following work for you?
```python
# my_app.py
import os

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import DictConfig

cs = ConfigStore.instance()

CONFIG_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "config"))
CONFIG_NAME = "config"

ENV_KEY = "DISENT_CONFIG_ROOTS"
custom_paths = os.environ.get(ENV_KEY, None)
custom_path_list = custom_paths.split(";") if custom_paths else []
custom_path_list.append(CONFIG_PATH)

disent_base_config = {
    "defaults": ["config", "_self_"],
    "hydra": {"searchpath": custom_path_list},
}
cs.store(name="_disent_base_config", node=disent_base_config)

@hydra.main(config_path=None, config_name="_disent_base_config")
def app(cfg: DictConfig) -> None:
    print(cfg)

if __name__ == "__main__":
    app()
```
```text
$ mkdir my_user_conf1
$ mkdir my_user_conf2
$ mkdir config
$ echo "foo: bar" >> config/config.yaml
$ DISENT_CONFIG_ROOTS="my_user_conf1;my_user_conf2" python my_app.py --info=searchpath

Config search path
******************
| Provider                 | Search path                              |
-----------------------------------------------------------------------
| hydra                    | pkg://hydra.conf                         |
| hydra.searchpath in main | file://my_user_conf1                     |
| hydra.searchpath in main | file://my_user_conf2                     |
| hydra.searchpath in main | file:///home/jbss/tmp_hydra/h2001/config |
| schema                   | structured://                            |
-----------------------------------------------------------------------
$ DISENT_CONFIG_ROOTS="my_user_conf1;my_user_conf2" python my_app.py
{'foo': 'bar'}
```
The idea is to store and then load a `_disent_base_config` node that does two things:
- set up the hydra searchpath
- load `config` (which points to your library's `config/config.yaml`, unless a user overrides it with another node called `config`) via the defaults list.

**Comment by Jasha10** [comment]
Given that your library is functioning as a framework for users, [Creating a `SearchPathPlug`](https://hydra.cc/docs/advanced/search_path/#creating-a-searchpathplugin) is probably even more appropriate than the idea from my previous comment.

Here is an example using `SearchPathPlugin`:
```text
$ tree
.
├── config
│   └── config.yaml
├── hydra_plugins
│   └── disent_searchpath_plugin.py
├── my_app.py
├── my_user_conf1
└── my_user_conf2

4 directories, 3 files
```
```python
$ cat my_app.py
# my_app.py

import hydra
from omegaconf import DictConfig

CONFIG_NAME = "config"


@hydra.main(config_path=None, config_name=CONFIG_NAME)
def app(cfg: DictConfig) -> None:
    print(cfg)


if __name__ == "__main__":
    app()
```
```python
$ cat hydra_plugins/disent_searchpath_plugin.py
# hydra_plugins/disent_searchpath_plugin.py

import os

from hydra.core.config_search_path import ConfigSearchPath
from hydra.plugins.search_path_plugin import SearchPathPlugin

CONFIG_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "config"))

ENV_KEY = "DISENT_CONFIG_ROOTS"
custom_paths = os.environ.get(ENV_KEY, None)
custom_path_list = custom_paths.split(";") if custom_paths else []
custom_path_list.append(CONFIG_PATH)
custom_path_list = [os.path.abspath(p) for p in custom_path_list]


class DisentSearchPathPlugin(SearchPathPlugin):
    def manipulate_search_path(self, search_path: ConfigSearchPath) -> None:
        for path in custom_path_list:
            search_path.append(provider="disent-searchpath-plugin", path=path)
```
```text
$ DISENT_CONFIG_ROOTS="my_user_conf1;my_user_conf2" python my_app.py --info=searchpath

Config search path
******************
| Provider                 | Search path                                     |
------------------------------------------------------------------------------
| hydra                    | pkg://hydra.conf                                |
| disent-searchpath-plugin | file:///home/jasha10/tmp_hydra/h2001/my_user_conf1 |
| disent-searchpath-plugin | file:///home/jasha10/tmp_hydra/h2001/my_user_conf2 |
| disent-searchpath-plugin | file:///home/jasha10/tmp_hydra/h2001/config        |
| schema                   | structured://                                   |
------------------------------------------------------------------------------
```

Note that for the above to work, the `hydra_plugins` folder should be a namespace package (see the doc on the [plugin discovery process](https://hydra.cc/docs/advanced/plugins/develop/#plugin-discovery-process).

Further References:
- [example on github](https://github.com/facebookresearch/hydra/tree/1.1_branch/examples/plugins/example_searchpath_plugin)
- [doc on `SearchPathPlugin`](https://hydra.cc/docs/advanced/plugins/overview/#searchpathplugin)

**Comment by nmichlo** [comment]
Thank you for your detailed response @Jasha10, I really appreciate that.

I didn't consider the case for `@hydra.main` when `config_path=None` which would enable the search path plugin or search path modification to work correctly as no `main` search path is added.

I have played around with both solutions and both can be used in my use case, however, there are unfortunately different pros and cons for each.

### Solution 1 - ConfigStore:
- **con**: You can no longer adjust `--config-name` without breaking things, as this must always be `_disent_base_config`. This is quite a big disadvantage for my use case.
- **con**: Both `--config-dir` (**con**) and`--config-path` (**pro**) appends before the search paths setup with the `ConfigStore`. An _advantage for my use case_, but could be a disadvantage for others.
- **pro**: It is contained in the same file, there is no hidden magic that could interfere with other `@hydra.main`s

### Solution 2 - Plugin:
- **con**: The plugin needs to be in the root of a _namespace package_. This is not ideal as this could interfere with other scripts that make use of hydra. One way around this could be to move it into its own directory for example `/_plugin_namespace_/hydra_plugins/disent_searchpath_plugin.py` and then prepend `_plugin_namespace_` to `sys.path` or `PYTHONPATH`. Requiring the `hydra_plugins` directory exists in a _namespace package_ pollutes the directory structure and doesn't directly link itself to the otherwise self-contained script. **[solution]**: A possible solution could be a way to add a `hydra.register_plugin(...)` function or decorator that could be used before `hydra.main` is called.
- **pro**: this plays well with the hydra `--config-name` and `--config-path` command line options, both work and the `--config-path` is given higher priority than the paths added by the plugin.
- **pro**: `--config-dir` is given a lower priority than the search paths added by the plugins, however, this is fine if `--config-path` is changed to allow multiple files and non-relative dirs. We can both prepend and append searchpaths accordingly.

### Already Proposed Solution - Config Paths Lists:
Allow lists to `config_path` and also add list support to `--config-path=...` (and `--config-dir`), separated with commas. But allow non-relative paths too for both.

The solution would look like:
```python3
import hydra

# prepend search paths from `DISENT_CONFIG_ROOTS` separated by ";", before the default config dir.
config_paths = list(map(os.path.abspath, filter(bool, [
    *os.environ.get('DISENT_CONFIG_ROOTS', '').split(';'),
    os.path.abspath(os.path.join(__file__, '..', 'config')),
])))

@hydra.main(config_path=config_paths, config_name='config')
def app(cfg) -> None:
    print(cfg)

if __name__ == "__main__":
    app()
```

- **Pro**: Self-contained
- **Con**: Overriding with `--config-path` requires specifying original default config root again too which would be annoying. It is good it is good that still has `--config-dir` a lower priority.

### Better Solution - `hydra.register_plugin` and Config Paths Lists:

Add both list support to `--config-path`, `--config-dir` and `hydra.main(config_path=[...])`.
Also add plugin registration support directly from python before `hydra.main` possibly with a function/decorator called `hydra.register_plugin` for example.

The solution would look like:
```python3
import hydra
from hydra.plugins.search_path_plugin import SearchPathPlugin

# prepend search paths from `DISENT_CONFIG_ROOTS` separated by ";", before the default config dir.
config_paths = list(map(os.path.abspath, filter(bool, [
    *os.environ.get('DISENT_CONFIG_ROOTS', '').split(';'),
    os.path.abspath(os.path.join(__file__, '..', 'config')),
])))

@hydra.register_plugin()
class DisentSearchPathPlugin(SearchPathPlugin):
    def manipulate_search_path(self, search_path) -> None:
        for path in config_paths:
            search_path.append(provider="disent-searchpath-plugin", path=path)

@hydra.main(config_path=None, config_name='config')
def app(cfg) -> None:
    print(cfg)

if __name__ == "__main__":
    app()
```

- **Pro**: Self-contained
- **Pro**: `--config-path` would now have higher priority
- **Pro**: `--config-dir` would now have lower priority

**Comment by Jasha10** [comment]
Thanks for the detailed proposal @nmichlo. This is good food for thought. I'll get back to you about this.
