### ISSUE TITLE
[Bug] AssertionError in multithread context

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#2010]
I ran into an AssertionError using Hydra with python's `threading` library.

In theory, Hydra is not thread safe. However, we should be able to support using Hydra in a multithread application if Hydra is only used from one thread.

Here is the relevant part of the traceback:
```
An error occurred during Hydra's exception formatting:
AssertionError()
Traceback (most recent call last):
  File "/home/jasha10/miniconda3/envs/pysc/lib/python3.9/site-packages/hydra/_internal/utils.py", line 252, in run_and_report
    assert mdl is not None
AssertionError
```

**Comment by qmpzzpmq** [comment]
same issue

**Comment by Jasha10** [comment]
@qmpzzpmq I've opened PR #2011 to close this issue, would you mind testing it out?

**Comment by Jasha10** [comment]
Unfortunately I forgot how to reproduce this issue. I'll close this now and will reopen it if anyone can post a repro in the future.
