### ISSUE TITLE
Hydra 1.1.2 release

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#2013]
This is a todo-list for the Hydra 1.1.2 release.

#### Adding `_partial_` to Hydra 1.1 branch

Due to popular demand, we are releasing `_partial_` as a feature on `1.1_branch` instead of waiting for the release of Hydra 1.2.
PR #2009 cherry-picked the `_parital_` feature from `main` to `1.1_branch`.

#### Checklist for finalizing the release:
- [x] Update the docs on the *`main`* branch under `website/versioned_docs/version-1.1` with details on `_partial_`. This is the source from which the v1.1 docs on our website get built. The docs should include a note saying that the feature will only be available for Hydra versions >= 1.1.2. (Edit: done by PR [#2128](#2128))
- [x] Create a `_partial_` news file on `main` and `1.1_branch` (done in [#2130](#2130) and [#2131](#2131))
- [x] Other open issues milestoned for 1.1.2:
  - [x] #1786
  - [ ] ~#1830~ (bounced to 1.2.0)
- [x] [`Release`](https://hydra.cc/docs/next/development/release/) Hydra v1.1.2

cc @jieru-hu

**Comment by rsokl** [comment]
Would it be possible to publish a `1.1.2` release candidate on pypi beforehand? It would be great for `hydra-zen` to be able to test its support for `_partial_`.

**Comment by Jasha10** [comment]
@rsokl I have just released Hydra dev versions `1.1.2.dev0` and `1.2.0.dev1`.
