### ISSUE TITLE
Discussion: How to run in silent mode/concurrently

### ISSUE THREAD

**Issue by hminle** [facebookresearch/hydra#2021]
Hi guys,

When using hydra, I need to open a new screen and run python script.
But I want to run multiple scripts at the same time.
So I need to start a python program with hydra in silent mode
something like this:
`python run.py --args &`

But it does not work out.
The logger still prints out on my screen

Do you guys know any way to do it?

Thanks

**Comment by Jasha10** [comment]
Hi @hminle,

This issue is not unique to Hydra.
```text
echo 123456 &
```
^ Using bash shell, the above will still echo even if the job is in the background.

If you are using bash, you can redirect the program's stdout and stderr to a file `output.txt` like so:
```text
python run.py --args > output.txt 2>&1 &
```

**Comment by hminle** [comment]
@Jasha10 Thank you I got it
