### ISSUE TITLE
[Feature Request] configuring experiments in Fairseq!

### ISSUE THREAD

**Issue by yuvalkirstain** [facebookresearch/hydra#2023]
## How can I work with an experiment directory with Hydra + Fairseq?

One of the best patterns in Hydra is [configuring experiments](https://hydra.cc/docs/patterns/configuring_experiments/). However, when I try to configure an experiment in Fairseq by:

1. creating an experiment directory.
2. creating a config file that overrides the main config.
3. calling fairseq-hydra-train +experiment=my_experiment

I get:

```bash
Error merging experiment=my_experiment
Key 'defaults' not in 'FairseqConfig'
        full_key: defaults
        reference_type=Optional[Dict[Union[str, Enum], Any]]
        object_type=FairseqConfig
```

I didn't see an explanation in the docs and will appreciate help :)

btw I raised this issue 30 days ago in Fairseq but they did not answer :(

**Comment by Jasha10** [comment]
Hi @yuvalkirstain,
Could you please post a reproducible example?

**Comment by yuvalkirstain** [comment]
Any attempt to run fairseq with an experiment config that has a default list will fail (I am assuming that the repo is already cloned and the virtual environment is set accordingly to fairseq's readme):

The official example for using hydra with fairseq does not use an experiment config:
```bash
fairseq-hydra-train distributed_training.distributed_world_size=1 \
    dataset.batch_size=2 \
    task.data=data-bin \
    model=transformer_lm/transformer_lm_gpt \
    task=language_modeling \
    optimization.max_update=5000
```
We can try to add one by:
1. add an experiment directory at: `fairseq/config/experiment`
2.  create an experiment config at `fairseq/config/experiment/run.yaml` with:
```bash
# @package _global_
defaults:
    - model: transformer_lm/transformer_lm_gpt
```
3. Run:
```bash
fairseq-hydra-train distributed_training.distributed_world_size=1 \
    dataset.batch_size=2 \
    task.data=data-bin \
    task=language_modeling \
    optimization.max_update=5000 \
    +experiment=run
```

This will fail with:
```
Error merging experiment=run
Key 'defaults' not in 'FairseqConfig'
	full_key: defaults
	reference_type=Optional[Dict[Union[str, Enum], Any]]
	object_type=FairseqConfig
```

**Comment by Jasha10** [comment]
I see. It looks like fairseq has a pin on Hydra: ["hydra-core>=1.0.7,<1.1"](https://github.com/pytorch/fairseq/blob/5551a1995bea28e47b388dc21fe683efee2d53f6/setup.py#L215).

This may be the root of your issue. Hydra 1.0 did support defaults lists in the top-level config, but recursive defaults lists (i.e. defaults lists in non-root-level configs) were not yet supported at that time.

You could try to install Hydra 1.1 together with Fairseq. If you go that route, I'd recommend taking a look at the [migration instructions](https://hydra.cc/docs/next/upgrades/1.0_to_1.1/changes_to_hydra_main_config_path/) for moving from 1.0 to 1.1.

**Comment by yuvalkirstain** [comment]
Indeed it worked, thanks a lot!
