### ISSUE TITLE
Passing model.parameters() to optimizer instantiate raises missing positional argument

### ISSUE THREAD

**Issue by amansouri3476** [facebookresearch/hydra#2028]
Hi, I want to specify the hyperparameters of the optimizer in my config file and instantiate it along with model parameters in my code.

Here's the relevant part in my config:

```
optimizers:
    _target_: torch.optim.Adam
    lr: 0.001
```

And instantiation in the code:

```
params = list(filter(lambda p: p.requires_grad, self.model.parameters()))
optimizer: torch.optim.Optimizer = hydra.utils.instantiate(self.config.optimizers, params)
```

I believe it should work as positional arguments should be passed through to the `_target_` but I get the following error:

```
TypeError: Error instantiating 'torch.optim.adam.Adam' : __init__() missing 1 required positional argument: 'params'
```

Why is this happening? I have tried passing the parameters in a couple ways but didn't succeed.

**Comment by Jasha10** [comment]
Hi @amansouri3476,
Does my [comment here](https://github.com/facebookresearch/hydra/issues/982#issuecomment-1037400220) answer your question?

**Comment by amansouri3476** [comment]
Yes @Jasha10 thank you very much for the help. The problem in my case was that a) I wasn't passing it as a keyword argument (in your comment, one should pass it as `params=model.parameters()`, and b) that `list` wrapping `filter` will cause a problem with optimizer init, so it should be removed. Just putting the edited version for reference here:

```
params = filter(lambda p: p.requires_grad, self.model.parameters())
optimizer: torch.optim.Optimizer = hydra.utils.instantiate(self.config.optimizers, params=params)
```

However, I'd like to ask another question here if you don't mind.

Is there a way where one could pass a **resolved** OmegaConf as a positional argument to an object?
Here's an example.
Suppose I have a model (with corresponding config `config.model` and some `_target_`) and this model has nested objects like optimizer (`config.model.optimizer`) with another `_target_`. Additionally, imagine a scenario where I need to set `_recursive_=False` to prevent the nested objects from being created, so something like this:

`hydra.utils.instantiate(config.model, _recursive_=False)`

When this is called, `config.model` is resolved by OmegaConf in the `__init__` function of model's `_target_`.
What if I want to pass `config.model.optimizer` as a positional argument to `model`, and use that later somewhere else with `instantiate`. If I do something like the following,
`hydra.utils.instantiate(config.model, config.model.optimizer, _recursive_=False)`
 then `config.model.optimizer` will be passed to the `__init__` **without being resolved**, i.e. if `config.model` is structured like this,
```
lr: 0.001

optimizer:
     _target_: torch.optim.Adam
     lr: ${model.lr}
```
then `${model.lr}` won't be resolved and will remain as is, which is undesired. Is there a way to pass nested configs in a resolved way?
So that the following call
`hydra.utils.instantiate(config.model, config.model.optimizer, _recursive_=False)`
gives the init a positional argument with the value
```
{'_target_': torch.optim.Adam,
 'lr': 0.001}
```
and not
```
{'_target_': torch.optim.Adam,
 'lr': ${model.lr}}
```

Please let me know if this is clear. Thanks!

**Comment by Jasha10** [comment]
> then `${model.lr}` won't be resolved and will remain as is, which is undesired.

Why is this undesired?

You can always resolve interpolations by calling [`OmegaConf.resolve`](https://omegaconf.readthedocs.io/en/latest/usage.html#omegaconf-resolve).

**Comment by amansouri3476** [comment]
In my application, I was logging the objects and an unresolved variable caused an `interpolation key {model.lr} unresolved` error. So in general it's not undesired, you're right. `OmegaConf.resolve` addresses this issue.
Thanks for your help @Jasha10 .
I'll close this issue.
