### ISSUE TITLE
[Feature Request] hydra with torch.distributed.launch

### ISSUE THREAD

**Issue by 18445864529** [facebookresearch/hydra#2038]
# 🚀 Feature Request

## Motivation

I want to use hydra with `torch.distributed.launch` for multi-node multi-GPU training. The problem is the `torch.distributed.launch` module will automatically pass a `local_rank` argument to the script thus leading to `unrecognized arguments: --local_rank`. 
In this case, how should I program my customized file accordingly to accept this appended argument?
Currently, it seems command arguments in the format of `--some_argument` will be directly received by hydra.

**Comment by Jasha10** [comment]
The issue is that `@hydra.main` reads from `sys.argv`. Since `torch.distributed` is using `sys.argv` too, there is a conflict.
The most flexible solution is to use the [compose API](https://hydra.cc/docs/advanced/compose_api/).

**Comment by Jasha10** [comment]
Thanks for the insight @jbaczek.

That is a good point about being unable to use a custom launcher without also using a custom sweeper + multirun mode. A feature request r.e. support for custom launching via single-run mode would be most welcome.

**Comment by jbaczek** [comment]
I hit another wall with calling torch distributed as a launcher. Launcher is called in the hydra's main wrapper. I wanted to pass original function to the multiprocessing context. This pickles the function to call together with arguments (btw `OmegaConf.register_new_resolver` is unpicklable because it creates local function in runtime. And this is in a singleton state) and passes it to `Popen`. But here comes the issue: Pickle serializes only metadata about the function and then restores it from a code. But at this point hydra's main wrapper already has overwritten main function, so pickled function does not match function that it tries to restore. Here is a repro:
```
import functools                  
import pickle                     
                                  
def decorate(f):                  
    @functools.wraps(f)           
    def wrapper(*args, **kwargs): 
        print(pickle.dumps(f))    
        return f(*args, **kwargs) 
    return wrapper                
                                  
@decorate                         
def main():                       
    print('A')                    
                                  
if __name__ == '__main__':        
    main()                        
```
I'm still looking into the issue. Any hints on how to solve this are welcome.

**Comment by longmao-yiran** [comment]
you can use --use_env to shield` arguments: --local_rank`

**Comment by jbaczek** [comment]
@Jasha10 I have implemented a working plugin for this. Would you be interested in MR?

**Comment by Jasha10** [comment]
@jbaczek I'd certainly be interested to take a look at the code you've written. I can't promise that we'd merge a PR (I'd have to discuss it with the Hydra team).

**Comment by zhaoedf** [comment]
> Add torchrun launcher plugin #2119

hi, i was wondering if this plugin is available now since i cannot any doc on the hydra website.

**Comment by jieru-hu** [comment]
hi @zhaoedf 
we've added torch run to the contrib folder here https://github.com/facebookresearch/hydra/tree/main/contrib
note that this is not an officially supported Hydra plugin so we may not be able to provide same level support as the official Hydra plugin.

**Comment by zhaoedf** [comment]
> hi @zhaoedf we've added torch run to the contrib folder here https://github.com/facebookresearch/hydra/tree/main/contrib note that this is not an officially supported Hydra plugin so we may not be able to provide same level support as the official Hydra plugin.

since contrib is not available on pypi, does it mean that i need to download the code in the link you provided and manually install it into my conda env?

**Comment by Jasha10** [comment]
@zhaoedf that is correct.

**Comment by zhaoedf** [comment]
for anyone might be interested, you can use --use-env to pass the local_rank param without causing a conflict.
` CUDA_VISIBLE_DEVICES=${GPU} nohup python3 -m torch.distributed.launch --master_port $((GPU + 19020)) --nproc_per_node ${NB_GPU} --use_env $project_path/train_wo_ddp.py`

**Comment by acherstyx** [comment]
I've created an updated version of the hydra-torchrun-launcher plugin at https://github.com/acherstyx/hydra-torchrun-launcher. I've resolved the PicklingError by utilizing [cloudpickle](https://github.com/cloudpipe/cloudpickle). 

Now, this version of the launcher should work exactly like launching with `torchrun`.
