### ISSUE TITLE
Sweep over all options of default with one key

### ISSUE THREAD

**Issue by natolambert** [facebookresearch/hydra#205]
# 🚀 Feature Request

Sweep over all options of default with one key, such as *

## Motivation
This would give us cleaner command line arguments.

## Pitch
Example of a current run in our conf directory:
```
.
├── config.yaml
├── dynamics_model
│   ├── de.yaml
│   ├── d.yaml
│   ├── env.yaml
│   ├── pe.yaml
│   └── p.yaml
```
We could change 
```
python pets/main.py -m env=cartpole dynamics_model=p,pe,d,de random_seed=1,2,3 mode=debug
```
to
```
python pets/main.py -m env=cartpole dynamics_model=* random_seed=1,2,3 mode=debug
```
I'm not sure if this is tractable, but could be fun :). 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))
If I am pointed in the right direction, I could attempt.

**Comment by omry** [comment]
BasicSweeper improvements will come in 1.1.0

**Comment by imanishbarnwal** [comment]
Hello @natolambert, can I take this issue?

**Comment by omry** [comment]
Hi @imanishbarnwal, this is planned for Hydra 1.1. there is some work going on to define a grammar that covers this as well.
See #752 and the linked document.

**Comment by omry** [comment]
https://hydra.cc/docs/next/advanced/override_grammar/extended
