### ISSUE TITLE
[Bug] Regression in `hydra._internal.utils._locate`

### ISSUE THREAD

**Issue by rsokl** [facebookresearch/hydra#2061]
# 🐛 Bug
## Description
[hydra-zen's torch tests](https://github.com/mit-ll-responsible-ai/hydra-zen/blob/main/tests/test_third_party/test_against_torch.py) caught a regression that was introduced in 043ec9b: `hydra._internal.utils._locate` is no longer able to "locate" `torch.tensor`. 

**Edit: this is applicable for PyTorch 1.8.1 and earlier. See my comment later in this thread.**

**Before 043ec9b:**

```python
>>> from hydra._internal.utils import _locate
>>> import torch
>>> _locate("torch.tensor") is torch.tensor
True
```

**After:**
```python
>>> _locate("torch.tensor")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-e8fe6ca69d39> in <module>
----> 1 _locate("torch.tensor")

~\Anaconda3\envs\hydra-zen\lib\site-packages\hydra\_internal\utils.py in _locate(path)
    599     else:
    600         # reject if not callable & not a type
--> 601         raise ValueError(f"Invalid type ({type(obj)}) found for {path}")
    602 
    603 

ValueError: Invalid type (<class 'module'>) found for torch.tensor

**Comment by Jasha10** [comment]
I am not able to reproduce this issue using the latest Hydra commit on the `main` branch.
```python
# repro.py
from hydra.utils import get_method
from hydra.utils import _locate

print(get_method("torch.tensor"))
print(_locate("torch.tensor"))
```
```text
$ python repro.py
<built-in method tensor of type object at 0x10a34d570>
<built-in method tensor of type object at 0x10a34d570>
$ python -c 'import hydra; print(hydra.__version__)'
1.2.0.dev2
$ python -c 'import torch; print(torch.__version__)'
1.10.2
```

**Comment by rsokl** [comment]
Ah, I think the discrepancy is due to a change between PyTorch 1.8.1 (**which I was running when I encountered this**) and later versions.

From PyTorch's release notes:

`import torch.tensor as tensor` is no longer supported (https://github.com/pytorch/pytorch/pull/53424). Instead, use from `torch import tensor`

PyTorch 1.8.1:

```python
>>> import torch.tensor as tensor
>>> torch.tensor(1.)
tensor(1.) 
```

PyTorch 1.9.0:

```python
>>> import torch.tensor as tensor
ModuleNotFoundError: No module named 'torch.tensor'
>>> from torch import tensor
>>> tensor(1.)
tensor(1.)
```

So I do think there is technically a regression here, but it is mainly because `torch.tensor` had some *really* weird  behaviors prior to 1.9.0. I am totally happy to just close this issue; I don't know that `_locate` should accommodate such a bizarre edge care.
