### ISSUE TITLE
cfg_passthrough 

### ISSUE THREAD

**Issue by IshanDindorkar** [facebookresearch/hydra#2064]
Hello,

I am trying to use hydra in an app that is launched using uvicorn with host and port passed as runtime parameters. When hydra see these params, it throws an error - 

uvicorn: error: unrecognized arguments: --host <host_value> --port <port_value>

In hydra.main, I found code in "decorated_main" in which it is checked if cfg_passthrough is not None, it skips parsing runtime parameters. This is what I would like to do. Could you please help me with an example of how I can write code to use "cfg_passthrough" and completely get rid of parsing runtime params for hydra.

Thank you very much in advance for any help/suggestions.

**Comment by Jasha10** [comment]
Hi @IshanDindorkar,

The `@hydra.main` decorator reads from `sys.argv` to parse command line overrides. See the docs on [the compose API](https://hydra.cc/docs/advanced/compose_api/), which does not read from `sys.argv`. Also, have a look at [this issue](https://github.com/facebookresearch/hydra/issues/1964) for discussion on preprocessing `sys.argv` before running `hydra.main`.
