### ISSUE TITLE
[Bug] Hydra instantiate is extremely slow 

### ISSUE THREAD

**Issue by JohnlNguyen** [facebookresearch/hydra#2077]
# 🐛 Bug
## Description

For our use case, we call instantiate more than 1000 times per training loop and it is on the critical path of our code. I did a benchmark on Colab and found that instantiate 1000 objects alone took 23.4 seconds. I tried other convert strategies however we require full object instantiate. Why is instantiate such a heavy call?

## Checklist

- [x] I checked on the latest version of Hydra

- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
https://colab.research.google.com/drive/1Lf0PfVnDpPRW8wMYbf8MYimJH75tBkMP?usp=sharing

## Expected Behavior
instantiate is fast, less than 1s per 1000 calls

## System information
- **Hydra Version** :  1.1.1
- **Python version** : 3.5
- **Virtual environment type and version** : 
- **Operating system** : linux

**Comment by gwenzek** [comment]
```py
from flsim.clients.base_client import Client, ClientConfig
from hydra.utils import instantiate
from omegaconf import OmegaConf

config = ClientConfig()

for _ in range(1000):
	instantiate(config, dataset=None)
```

Flamegraph:

![bench](https://user-images.githubusercontent.com/5920036/157500711-6eb5403f-957c-4362-9ea4-58e962ff0d82.svg)

If you ignore the import time, you see that the `instantiate` call on ClientConfig, will make more call to instantiate.
Overall the code is spending 38% of the time inside `deepcopy.deepcopy`, but beyond that it looks like a death by a thousand paper cut, where each field copy need to go through 4 or 5 function calls.

**Comment by Jasha10** [comment]
Thanks for providing the flamegraph. Using `instantiate` on the critical path is something I have not seen before.

One key question: is the instantiated config the same each time?

If the config is identical each time, I think using the new `_partial_` keyword could provide *significant* speedup. The `_partial_` keyword will be released in Hydra 1.2, and is available for testing via a pre-release:
```
pip install --upgrade hydra==1.2.0.dev1
```

```python
from flsim.clients.base_client import Client, ClientConfig
from hydra.utils import instantiate
from omegaconf import OmegaConf

config = ClientConfig()
config._partial_ = True
factory = instantiate(config)
# factory is an instance of `functools.partial`.
# Calling `factory()` creates a `flsim.clients.Client` instance.

for _ in range(1000):
    client = factory(dataset=None)
    # Calling `factory(foo="bar")` will pass the kwarg `foo="bar"` to `Client.__init__`.	
```

The `_partial_` keyword is documented [here](https://hydra.cc/docs/next/advanced/instantiate_objects/overview/#partial-instantiation).

**Comment by JohnlNguyen** [comment]
Thanks, 

We are not creating the instances of optimizer and lr_scheduler on init. We're creating them later down the line
https://github.com/facebookresearch/FLSim/blob/main/flsim/clients/base_client.py#L216

So this might work for us. Let met try it out.

**Comment by Jasha10** [comment]
Sorry I should have tested this out earlier. I am having success with the following:
```python
factory = instantiate(config, _partial_=True)
```
However, my original suggestion (below) is not working:
```python
config._partial_ = True
factory = instantiate(config)
```

**Comment by JohnlNguyen** [comment]
```python
%%timeit

config = ClientConfig()
factory = instantiate(config, _partial_=True)

[factory(dataset=None) for _ in range(1000)]
10.8 s ± 191 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```


```python
%%timeit

[instantiate(ClientConfig(), dataset=None) for _ in range(1000)]
18.4 s ± 263 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Thanks, I found that partial did help by a factor of 2. Is there anything else we can do to make this even faster? 10s is still really slow.

**Comment by Jasha10** [comment]
Using `_partial_=True`, the `factory` object is an instance of `functools.partial`.
This means writing `factory = instantiate(config, _partial_=True)` is equivalent to the below:
```python
factory = functools.partial(Client, **kwargs)
```
If my understanding is correct, the bottleneck is now `Client.__init__`.
Is `Client.__init__` calling back into Hydra?

**Comment by JohnlNguyen** [comment]
Inside of `Client.__init__`, we initialize the config and construct the OmgaConf object and setting defaults 

Code looks roughly like this
```python
def init_self_cfg(
    component_obj: Any, *, component_class: Type, config_class: Type, **kwargs
) -> None:
    """
    Initialize FL component config by constructing OmegaConf object,
    setting defaults, and validating config.
    """
    cfg = (
        config_class(**kwargs)
        if not hasattr(component_obj, "cfg")
        else component_obj.cfg
    )
    cfg = OmegaConf.create(cfg)  # convert any structure to OmegaConf
    component_class._set_defaults_in_cfg(cfg)  # set default cfg params for this class
    # convert any structure to OmegaConf again, after setting defaults
    cfg = OmegaConf.create(cfg)  # pyre-ignore [6]
    _validate_cfg(component_class, cfg)  # validate the config
    component_obj.cfg = cfg

class Client:
    logger: logging.Logger = Logger.get_logger(__name__)

    def __init__(
        self,
        *,
        dataset: IFLUserData,
        channel: Optional[IdentityChannel] = None,
        timeout_simulator: Optional[TimeOutSimulator] = None,
        store_last_updated_model: Optional[bool] = False,
        cuda_manager: ICudaStateManager = DEFAULT_CUDA_MANAGER,
        name: Optional[str] = None,
        **kwargs,
    ):
        init_self_cfg(
            self,
            component_class=__class__,  # pyre-fixme[10]: Name `__class__` is used but not defined.
            config_class=ClientConfig,
            **kwargs,
        )

        self.dataset = dataset
        self.cuda_state_manager = cuda_manager
        self.channel = channel or IdentityChannel()
        self.timeout_simulator = timeout_simulator or NeverTimeOutSimulator(
            **OmegaConf.structured(NeverTimeOutSimulatorConfig())
        )

        # base lr needs to match LR in optimizer config, overwrite it
        # pyre-ignore [16]
        self.cfg.lr_scheduler.base_lr = self.cfg.optimizer.lr
        self.per_example_training_time = (
            self.timeout_simulator.simulate_per_example_training_time()
        )
```

**Comment by Jasha10** [comment]
Hmm, looking back at the flamegraph posted by @gwenzek above, it seems that a bit more than half of the time in `__init__` is spent calling `init_self_cfg`.
Of the time in `init_self_cfg`, the two calls to `OmegaConf.create` seem to be most significant.

**Comment by Jasha10** [comment]
Taking a close look at `init_self_cfg`, I suspect that the second call to `OmegaConf.create` is unnecessary, since `cfg` is already an OmegaConf object.

**Comment by JohnlNguyen** [comment]
The first call to `OmegaConf.create` is to create a base config that might miss some default values. 

For example, we have the client config as 
```
@dataclass
class ClientConfig:
    _target_: str = fullclassname(Client)
    _recursive_: bool = False
    _partial_: bool = True
    epochs: int = 1  # No. of epochs for local training
    optimizer: LocalOptimizerConfig = LocalOptimizerConfig() <--Base Object class 
```

If the user didn't specify an optimizer then we set the default value for optimizer and call `OmegaConf.create` again
```
    @classmethod
    def _set_defaults_in_cfg(cls, cfg):
        if OmegaConf.is_missing(cfg.optimizer, "_target_"):
            cfg.optimizer = LocalOptimizerSGDConfig()
```

Are you saying that by setting `cfg.optimizer = LocalOptimizerSGDConfig()` is enough and I don't need to call `cfg = OmegaConf.create(cfg)` again?

**Comment by JohnlNguyen** [comment]
Thank you for your help @Jasha10 and @gwenzek ! Closing this issue.
