### ISSUE TITLE
[Bug] hydra-core==1.2.0.dev1 not compatible with omegaconf==2.2.0.dev1 when using poetry

### ISSUE THREAD

**Issue by pedropgusmao** [facebookresearch/hydra#2088]
# 🐛 Bug
## Description
Pre-release `1.2.0.dev1` still depends on omegaconf (>=2.1.0,<2.2.0) and it should probably allow `omegaconf==2.2.0.dev1`.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
**pyproject.toml**:
```
[tool.poetry]
name = "minimal example"
version = "0.1.0"
description = ""
authors = ["John Doe <fake@fake.abc>"]

[tool.poetry.dependencies]
python = "^3.7.12"
omegaconf = "==2.2.0.dev1"
hydra-core = "==1.2.0.dev1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

** Stack trace/error message **
```
Updating dependencies
Resolving dependencies... (0.0s)

  SolverProblemError

  Because hydra-core (1.2.0.dev1) depends on omegaconf (>=2.1.0,<2.2.0)
   and minimal example depends on omegaconf (==2.2.0.dev1), hydra-core is forbidden.
  So, because minimal example depends on hydra-core (==1.2.0.dev1), version solving failed.

  at ~/.local/lib/python3.8/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│ 
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes
```

## System information
- **Hydra Version** :  1.2.0.dev1
- **Python version** :  3.7.12
- **Virtual environment type and version** : pyenv with poetry 
- **Operating system** :  Ubuntu 20.04

## Additional context
Maybe first line in https://github.com/facebookresearch/hydra/blob/main/requirements/requirements.txt needs to be changed to `omegaconf==2.2.*` for hydra-core==1.2.

**Comment by Jasha10** [comment]
Thank you for reporting this @pedropgusmao!
I think the issue is [here](https://github.com/facebookresearch/hydra/blob/00a9536a2b390f396d042dced697d499f5476cde/requirements/requirements.txt#L1) in hydra's `requirements.txt` file. I'll update this shortly...

**Comment by Jasha10** [comment]
`hydra-core==1.2.0.dev2` can now be installed from pypi.
Thanks again @pedropgusmao.
