### ISSUE TITLE
[Bug] Subclassing Launcher throws Mypy error

### ISSUE THREAD

**Issue by d-miketa** [facebookresearch/hydra#2095]
# 🐛 Bug
## Description
I wanted to subclass `Launcher` to create a custom launcher plugin but Mypy is complaining of missing type information.

## To reproduce

Save the following file inside a custom repo which has access to a Hydra 1.1 installation:
https://github.com/facebookresearch/hydra/blob/1.1_branch/examples/plugins/example_launcher_plugin/hydra_plugins/example_launcher_plugin/example_launcher.py

The Mypy error is:
```
Class cannot subclass "Launcher" (has type "Any")
```

## System information
- **Hydra Version** :  1.1
- **Python version** : 3.9.10
- **Virtual environment type and version** : Conda
- **Operating system** : Mac OS 11

## Additional context
This is the same problem in another context: https://stackoverflow.com/questions/49888155/class-cannot-subclass-qobject-has-type-any-using-mypy

**Comment by jieru-hu** [comment]
thanks @d-miketa  for reporting. we will take a look at this.

**Comment by Jasha10** [comment]
@d-miketa are you still seeing this issue?
When I run `mypy` on the file you mentioned, I'm not seeing any errors.
Perhaps it was a mypy bug that has been sorted out.

**Comment by d-miketa** [comment]
Did you run with the flag `--disallow-subclassing-any` (https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-disallow-subclassing-any)? I forgot to mention it in the original post, apologies.
