### ISSUE TITLE
 Specializing config does not work as described in tutorial.

### ISSUE THREAD

**Issue by louismartin** [facebookresearch/hydra#2096]
# 🐛 Bug
## Description
I tried to follow the tutorial for specializing config but it does not seem to work as described:
https://hydra.cc/docs/patterns/specializing_config/

Expected behaviour (tutorial):
```
$ python example.py dataset=cifar10
dataset:
  name: cifar10
  path: /datasets/cifar10
model:
  num_layers: 5
  type: alexnet
```

My repro:
```
$ python example.py dataset=cifar10
dataset:
  name: cifar10
  path: /datasets/cifar10
model:
  num_layers: 7
  type: alexnet
dataset_model:
  model:
    num_layers: 5
```

## Checklist
- [x] I checked on the latest version of Hydra => 1.1.1
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

### Files
example.py
```
import hydra
from omegaconf import DictConfig, OmegaConf

@hydra.main(config_path="conf", config_name="config")
def my_app(cfg : DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```

conf/config.yaml
```
defaults:
  - dataset: imagenet
  - model: alexnet
  - optional dataset_model: ${dataset}_${model}
```

conf/dataset/cifar10yaml
```
name: cifar10
path: /datasets/cifar10
```

conf/dataset/imagenet.yaml
```
name: imagenet
path: /datasets/imagenet
```

conf/model/alexnet.yaml 
```
num_layers: 7
type: alexnet
```

conf/dataset_model/cifar10_alexnet.yaml 
```
model:
  num_layers: 5
  ```

**Bug**:
```
$ python example.py dataset=cifar10
dataset:
  name: cifar10
  path: /datasets/cifar10
model:
  num_layers: 7
  type: alexnet
dataset_model:
  model:
    num_layers: 5
```

**Expected behaviour**:
```
$ python example.py dataset=cifar10
dataset:
  name: cifar10
  path: /datasets/cifar10
model:
  num_layers: 5
  type: alexnet
```

## System information
- **Hydra Version** :  1.1.1
- **Python version** :  3.9.5
- **Virtual environment type and version** : conda 4.10.1
- **Operating system** : ubuntu (devfair)

**Comment by jieru-hu** [comment]
hi @louismartin thanks for trying this out, yes you are correct, in face we do have the header in the example app itself https://github.com/facebookresearch/hydra/blob/1.1_branch/examples/patterns/specializing_config/conf/dataset_model/cifar10_alexnet.yaml

I will update the doc shortly, thanks for catching this

**Comment by jieru-hu** [comment]
hi @jahidhasanlinix - you create your own config.yaml file and pass it to hydra.main. here is an example https://github.com/facebookresearch/hydra/tree/main/examples/tutorials/basic/your_first_hydra_app/3_using_config
