### ISSUE TITLE
[Feature Request] Is this possible to loose the version of antlr4-python3-runtime

### ISSUE THREAD

**Issue by WangCHX** [facebookresearch/hydra#2155]
# 🚀 Feature Request
Since my company is using monorepo (bazel), the version of each package is fixed. Since hydra-core fix the  `antlr4-python3-runtime` to 4.8, my other package which needs 4.9 can't be added into the monorepo. So I am wondering if hydra-core loose the `antlr4-python3-runtime` to something like `>=4.8`. 

## Motivation
same as feature request.

## Pitch
maybe make `antlr4-python3-runtime` >= 4.8 ?

**Comment by Jasha10** [comment]
cc @pixelb

**Comment by pixelb** [comment]
Note antlr-4.9.3 is required for python-3.6 support
