### ISSUE TITLE
[Bug] Link to upgrade guide crashes documentation site

### ISSUE THREAD

**Issue by rsokl** [facebookresearch/hydra#2158]
In `hydra-core==1.2.0dev5`, `basic_launcher` produces the following warning:
```    
/home/runner/work/hydra-zen/hydra-zen/.tox/pre-release/lib/python3.8/site-packages/hydra/_internal/core_plugins
/basic_launcher.py:74: 

UserWarning: Future Hydra versions will no longer change working directory at job runtime by default.
    See https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir for more information.
```

But following the provided URL, https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir , leads to a crash in the docs site:

![image](https://user-images.githubusercontent.com/29104956/164014834-2884356a-bca0-4f37-a787-d4a8829dcbf9.png)

**Comment by Jasha10** [comment]
Thanks for the report! We'll get this fixed shortly.
For now, here's a working link:
https://hydra.cc/docs/next/upgrades/1.1_to_1.2/changes_to_job_working_dir/

**Comment by jieru-hu** [comment]
thanks @rsokl  for reporting! :)

**Comment by vgthengane** [comment]
> Thanks for the report! For now, here's a working link: https://hydra.cc/docs/next/upgrades/1.1_to_1.2/changes_to_job_working_dir/

This link is also not working
