### ISSUE TITLE
add argument so that hydra does not "hijack" the command line and just returns the composed configs

### ISSUE THREAD

**Issue by svenstehle** [facebookresearch/hydra#2177]
# 🚀 Feature Request

Like in [spock-config](https://fidelity.github.io/spock/advanced_features/Keyword-Configs) it would be nice if hydra could be told to not block the command line during execution and just build & compose the config. This is very convenient when testing and debugging with `pytest --pdb` or `python main.py --pdb` for example. Disclaimer: `pytest --pdb` actually seems to work for my current minimal working example, as long as you don't test `main.py` with the hydra decorator pattern. I.e. `python main.py --pdb` does not work.

Example from spock-config

```python
config = SpockBuilder(ModelConfig, DataConfig, SGDConfig, desc=description, config=['./tutorial.yaml'], 
                              no_cmd_line=True)
```

## Motivation

I have run into several problems with hydra in the past when I tried to debug and it is impossible for me to test/fix some functionality sometimes because hydra just blocks the usual command line interface when the `main.py` decorator structure is used during production run-time. Or if you want to test `main.py` itself. If you want to debug, something like this happens: 

```bash
HYDRA_FULL_ERROR=1 python -m src.main --pdb
usage: main.py [--help] [--hydra-help] [--version] [--cfg {job,hydra,all}] [--resolve] [--package PACKAGE] [--run] [--multirun] [--shell-completion]
               [--config-path CONFIG_PATH] [--config-name CONFIG_NAME] [--config-dir CONFIG_DIR]
               [--info [{all,config,defaults,defaults-tree,plugins,searchpath}]]
               [overrides [overrides ...]]
main.py: error: unrecognized arguments: --pdb
```

Please make it more flexible in that regard, we would highly appreciate it.

## Pitch

See above. Something like `no_cmd_line=True` during config building with the `decorator pattern` and the `compose` API.
Or if that does not work, to initialize itself. I don't know about hydras inner workings:

```python
@hydra.main(config_path="conf", config_name="config", no_cmd_line=True)
def hydra_test(cfg: DictConfig):
```

```python
with initialize(config_path="conf", no_cmd_line=True):
        # hydra only composes and returns the cfg with the overrides
        cfg = compose(config_name="config", no_cmd_line=True, overrides=["db=mysql", "db.user=me"])
```

I don't know about any alternatives but I am happy to be pointed to existing workarounds and test them.

## Would you be willing to work on a Pull Request?

Yes... but:
I would not know where to start to work on this or enable this without help or guidance, but I am willing to give it a try or work together with someone on this.

**Comment by Jasha10** [comment]
Hi @svenstehle,
FYI the compose API does not interact with the command line at all. The `hydra.main` function reads `sys.argv`, but `compose` does not.
Also, note it's possible to invoke `pdb` as the main module:
```text
$ python -m pdb -m src.main  # using pdb to run the src.main module
```
```text
$ python -m pdb main.py  # using pdb to run the main.py file
```

**Comment by svenstehle** [comment]
I figured it out:

some tests use the hydra config like this

```python
@pytest.fixture(scope="module")
def prep_hydra_config():
    # context initialization
    with initialize(config_path="../src/conf", job_name="test_app"):
        cfg = compose(config_name="config", overrides=["testing=enabled"])
        yield cfg
```

And others can use it like this without conflicts:

```python
def test_main():
    with initialize(config_path="../../../src/conf", job_name="test_app"):
        cfg = compose(config_name="config", overrides=["testing=disabled"])
        main(cfg)
```

Fixing the scope correctly in the pytest fixture helped, together with 

```python
with initialize(config_path="conf", job_name="test_app"):
```

**Comment by Jasha10** [comment]
> Do you think we can improve the hydra documentation with an example like this so that other users will find it when they want to run their test suite with hydra integration?

Great idea. We can use your notes above to augment the hydra website page on "unit tests".

**Comment by svenstehle** [comment]
You are absolutely right. There it is, I missed it completely! Thanks for pointing it out @Jasha10  :) I think we can close?
