### ISSUE TITLE
[Feature Request] Inline references without using default lists

### ISSUE THREAD

**Issue by dkal-at-meta** [facebookresearch/hydra#2188]
I would like the ability to use inline references without having to use default lists:
Before:
```
config.yaml:
a:
 b:
  c: ...
```
After
```
config.yaml:
a: b

b.yaml:
b:
 c: ...
```

**Comment by Jasha10** [comment]
Hi @dkal-at-meta,
Support for something similar to inlining via [OmegaConf's interpolations](https://omegaconf.readthedocs.io/en/latest/usage.html#variable-interpolation). Is that what you had in mind?

**Comment by dkal-at-meta** [comment]
> Hi @dkal-at-meta, There is support for something similar to inlining via [OmegaConf's interpolations](https://omegaconf.readthedocs.io/en/latest/usage.html#variable-interpolation). Is that what you had in mind?

Yes, that's what I ended up doing, but it would still be nice to have the ability to reference yaml files directly without having to use default lists

**Comment by Jasha10** [comment]
Got it.
I have a partial solution using an [OmegaConf resolver](https://omegaconf.readthedocs.io/en/latest/usage.html#resolvers).

```text
$ tree
├── b.yaml
├── config.yaml
└── omc_demo.py
```
```yaml
# b.yaml
b:
  c: ...
```
```yaml
# config.yaml
a: ${oc_load:b.yaml}
```
```python
# omc_demo.py
from omegaconf import OmegaConf

OmegaConf.register_new_resolver("oc_load", OmegaConf.load)

cfg = OmegaConf.load("config.yaml")
OmegaConf.resolve(cfg)
print(OmegaConf.to_yaml(cfg))
```
```text
$ python omc_demo.py
a:
  b:
    c: '...'
```

This will work with Hydra, but there may be some difficulty with relative paths (e.g. if Hydra causes the working directory to change). With Hydra v1.1, the working directory usually changes to something like `./outputs/2022-05-03/13-46-44`, so you'd need to do `a: ${oc_load:../../../b.yaml}` instead of `a: ${oc_load:b.yaml}`.
```yaml
# config.yaml
a: ${oc_load:../../../b.yaml}
```
```python
# my_app.py
from omegaconf import DictConfig, OmegaConf
import os
import hydra

OmegaConf.register_new_resolver("oc_load", OmegaConf.load)

@hydra.main(config_path=".", config_name="config")
def my_app(cfg: DictConfig) -> None:
    OmegaConf.resolve(cfg)
    print(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    my_app()
```
```text
$ python my_app.py
a:
  b:
    c: '...'
```

**Comment by dkal-at-meta** [comment]
Nice, that's pretty close to what I'm trying to do.
