### ISSUE TITLE
RFC: hydra.compose() decoration

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#219]
Initial API idea:

```python
@hydra.compose(config_path="path/file.yaml", overrides=["foo=bar", "db=mysql"])
def foo(cfg, userarg):
    pass

result = foo(userarg)
```

**Comment by withsmilo** [comment]
It looks good! It seems to be similar to what I had proposed before(#215). What is ‘userarg’? user-defined ArgumentParser, or another something?

**Comment by omry** [comment]
Thanks!
Not quiet the same.
This is a way to access the composition power of Hydra in a regular function call.
User arg is just an example of something else the user is passing to the function (pass through).

**Comment by withsmilo** [comment]
I understood. New ‘hydra.compose’ decorator also seems to be useful in various place. I have a question. Will new decorator return something according to your initial design? As you know, ‘hydra.main’ decorator doesn’t return anything.

**Comment by omry** [comment]
Yes, the new decorator will be able to return results.
In fact, so can the current hydra.main() although nothing is using it as of now.

**Comment by omry** [comment]
Done, this will be available with the next 0.11.0 release candidate.

**Comment by hrchu** [comment]
Glad to see you hear the user voice!

**Comment by omry** [comment]
Actually this is not quiet what you asked for, the compose API does not support anything in the command line.
I am planning on supporting something like what you wanted #274 is implemented.
There is a reasonable workaround for allowing users to specify a config file in the comments there.
