### ISSUE TITLE
[Feature Request] Enable storing git commit hash on launch

### ISSUE THREAD

**Issue by Harimus** [facebookresearch/hydra#2199]
# 🚀 Feature Request
At each launch (normal launch/sweeper) also save the git hash of the current code/commit in `.hydra` folder in the output working directory. 

## Motivation
One thing I really like with hydra is how the full config is available after run in `.hydra/` folder. This makes tracking the *config parameters* on past experiments/runs very easy and a huge relief.

Adding an option to also store a reference to the _code state_ would be a great addition. With the two (hash of commit + config parameters) one could reproduce most experiments by information from the `.hydra` folder alone. 

When people run different branches/versions of a code, the output folder (data/result/used config) might be identical to each other but the code not. When old results needs to be reproduced (after code modification have happened), the hash would also help.

One could ofc do this manually and outside hydra runtime, but would be a cool feature I think!

**Describe alternatives you've considered**
One way is to just do this manually outside hydra runtime, as in 
1. check if there's git/revision control based on current script folder. (`__file__` of the code that have `@hydra.main`)
2. collect the current commit hash/version (example: `subprocess.check_output(['git', 'rev-parse', 'HEAD']).strip()`)
3. store it in `.hydra/` folder.

**Comment by jieru-hu** [comment]
hi @Harimus thanks for the request. This seems like a good use case for Hydra's Callbacks and should be fairly easy to create for your specific use case.
doc on callbacks https://hydra.cc/docs/experimental/callbacks/
example callbacks: https://github.com/facebookresearch/hydra/blob/main/hydra/experimental/callbacks.py

for you specific use case, you could try something like the following (example code, i haven't tested it)

```
class GitSHACallback(Callback):
  def on_run_start(...):
       # compute the git sha
       ...
       # get path to .hydra folder
       hydra_foler = HydraConfig.get().hydra.output_subdir
       commit_sha_file=Path(hydra_foler)/"sha.txt"
       with open(commit_sha_file, "w") as f:
            f.write(...)
```

**Comment by pixelb** [comment]
Yes a use supplied callback seems like the most general solution,
given non git, non committed changes in git, etc.

**Comment by pixelb** [comment]
I think we can close this, given the callback solution

**Comment by Harimus** [comment]
Hi thanks for the reply! (sorry for the late reply!) Yes Hydra callbacks seems sufficient and I didnt know about it before, so I'll try using that!

many thanks! :D

**Comment by jieru-hu** [comment]
@Harimus awesome!  feel free to let us know if you have any feedback/question if you end up using it! :)

**Comment by im-Kitsch** [comment]
Hi, 

I just found a minor issue. When the callback function is called(on_job_start/on_multirun_start), the output folder is not created actually. 

I know that I can manually create it manually. But is the better to initialize log_folder like `.hydra/` ?

Thanks a lot for the good work on hydra.

**Comment by Nielius** [comment]
Starting from [the suggestion](https://github.com/facebookresearch/hydra/issues/2199#issuecomment-1122759769) by @jieru-hu , I wrote this piece of code that I hope will be useful to others to simply copy-paste:

```python
class GitSHACallback(Callback):
    def on_job_start(self, config: DictConfig, **kwargs: Any) -> None:
        hydra_folder = HydraConfig.get().runtime.output_dir
        commit_sha_file = Path(hydra_folder) / "sha.txt"
        with open(commit_sha_file, "w") as f:
            try:
                f.write(subprocess.check_output(["git", "rev-parse", "HEAD"]).decode("utf-8"))
            except subprocess.CalledProcessError:
                warnings.warn("Could not get git commit sha.")
```

@im-Kitsch I believe that the output folder does not exist yet `on_run_start` (or at least it doesn't seem to be in the config object), but it does exist in `on_job_start`, so maybe this piece of code solves your problem?
