### ISSUE TITLE
Modify string in .yaml

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/hydra#2213]
This is unlikely, but would it be possible to modify a string variable in the .yaml itself?

For example, define:

`a_random_string: hello.world`

Now, I want to reference this variable elsewhere in the config except with only the substring following the last period:

`another_variable: ${a_random_string}`

So the above will assign `hello.world` to `another_variable`, but I would like to assign just `"world"`. Is this possible?

**Comment by Jasha10** [comment]
Hi @slerman12,
You can accomplish this with an [OmegaConf resolver](https://omegaconf.readthedocs.io/en/latest/custom_resolvers.html).
```python
# tmp.py
from omegaconf import OmegaConf

yaml_data = """\
a_random_string: hello.world
another_variable: ${get_suffix:${a_random_string}}
"""


def get_suffix_impl(input_: str) -> str:
    if "." in input_:
        return input_.split(".")[-1]
    else:
        return input_


OmegaConf.register_new_resolver("get_suffix", get_suffix_impl)

cfg = OmegaConf.create(yaml_data)

print(cfg.another_variable)
```
```text
$ python tmp.py
world
```

**Comment by slerman12** [comment]
Thanks! Can I just define `OmegaConf.register_new_resolver("get_suffix", get_suffix_impl)` anywhere in the code?

**Comment by Jasha10** [comment]
> Thanks! Can I just define `OmegaConf.register_new_resolver("get_suffix", get_suffix_impl)` anywhere in the code?

Yes, defining it anywhere before you access `cfg.another_variable` will work.
