### ISSUE TITLE
[Bug] Obsolete typing.io import

### ISSUE THREAD

**Issue by srittau** [facebookresearch/hydra#2218]
# 🐛 Bug
## Description

hydra-core 1.2.0 contains two generated files with an obsolete import `from typing.io import TextIO`. The `typing.io` namespace has been deprecated since Python 3.8 and will be removed in Python 3.12. (Cf. python/cpython#92871) The imports can simply be replaced with `from typing import TextIO`:

* hydra/grammar/gen/OverrideLexer.py
* hydra/grammar/gen/OverrideParser.py

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## System information
- **Hydra Version** :  1.2.0
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** :

**Comment by pixelb** [comment]
This was addressed implicitly by the upgrade of antlr from 4.8 to 4.9 (in issue #2155)
which guards the old use of typing.io with a python version check.
