### ISSUE TITLE
Support M1 ARM

### ISSUE THREAD

**Issue by johnnynunez** [facebookresearch/hydra#2220]
# 🚀 Feature Request

Support new M1 device pipeline to select mps device, not GPU?
https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/

**Comment by jieru-hu** [comment]
@johnnynunez  -  a little more context here would be great. Hydra does not depend on Pytorch. What kind of support do you have in mind?

**Comment by johnnynunez** [comment]
> @johnnynunez - a little more context here would be great. Hydra does not depend on Pytorch. What kind of support do you have in mind?

https://github.com/PyTorchLightning/pytorch-lightning/issues/13102
Oh sorry! I see this. So, I close the issue because depends of pytorch
