### ISSUE TITLE
[Bug] Hydra 1.2 introduction breaks downstream tests in detectron2

### ISSUE THREAD

**Issue by sstsai-adl** [facebookresearch/hydra#2224]
# 🐛 Bug
## Description
Detectron2 uses omegaconf which builds upon hydra. Updating the hydra to 1.2 seems to break tests. 

We have a hydra 1.2 vs hydra 1.1 test results here:
hydra 1.2: https://app.circleci.com/pipelines/github/facebookresearch/detectron2/2054/workflows/226048e0-33a0-4736-92e7-ecac81019997
hydra 1.1: https://app.circleci.com/pipelines/github/facebookresearch/detectron2/2059/workflows/8cc6d6a9-207d-4f02-a26e-0e05bdfbe586

## Checklist
- [v] I checked on the latest version of Hydra
- [v] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
For now, we've limited omegaconf package right now to <=2.20 to unbreak things. If we backtrack this fix, https://github.com/facebookresearch/detectron2/commit/32c32e36f7ca49ae4a2ae32bc751c4d837e07ee5 it can be reproduced.  

** Minimal Code/Config snippet to reproduce **

** Stack trace/error message **
```
ex = ConfigAttributeError('ListConfig does not support attribute access\n    full_key: [channels]\n    object_type=list',)
cause = ConfigAttributeError('ListConfig does not support attribute access',)
```
(full list of error can be found here: https://app.circleci.com/pipelines/github/facebookresearch/detectron2/2053/workflows/418077cf-c2e5-4f0b-bf6b-e750252c1de5/jobs/8694/parallel-runs/0/steps/0-106)

## Expected Behavior

Unit tests pass.

## System information
- **Hydra Version** :  
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** :

**Comment by pixelb** [comment]
Even though the pin is on omegaconf I think (through transitive antlr dependencies) this is effectively pinning hydra-core to 1.1
which I inferred from the test runs for your pull request at https://github.com/facebookresearch/detectron2/pull/4251/checks

**Comment by Jasha10** [comment]
I have a hunch that this is related to https://github.com/omry/omegaconf/issues/939.

**Comment by sstsai-adl** [comment]
This is not an issue anymore. @ppwwyyxx has landed a fix( https://github.com/facebookresearch/detectron2/commit/3cc9908ba3301785ec946ae7e37d7091fa1d5045).
