### ISSUE TITLE
[Bug] Optuna sweeper plugin does not support deprecated search space anymore

### ISSUE THREAD

**Issue by MattiasDC** [facebookresearch/hydra#2287]
# 🐛 Bug
## Description
Since Hydra 1.2 usage of hydra.sweeper.search_space is deprecated in favor of hydra.sweeper.params. An upgrade guide and more context is available [here](https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_sweeper_config/).
The search_space usage does give a deprecation warning, but also results in a crash.
This crash was introduced by myself in [this commit](https://github.com/facebookresearch/hydra/commit/0c2af39b155f784329e85cd4212d04e86904b1e8).

## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

I've created a separate branch that contains a unit test that shows the failure [here](https://github.com/MattiasDC/hydra/tree/optuna_sweeper_issue).
```
Traceback (most recent call last):
  File "/home/mattias/git/hydra/.env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/home/mattias/git/hydra/.env/lib/python3.9/site-packages/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/home/mattias/git/hydra/.env/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/mattias/git/hydra/.env/lib/python3.9/site-packages/hydra_plugins/hydra_optuna_sweeper/optuna_sweeper.py", line 54, in sweep
    return self.sweeper.sweep(arguments)
  File "/home/mattias/git/hydra/.env/lib/python3.9/site-packages/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 293, in sweep
    assert self.search_space is None
AssertionError
=== Error executing:
/home/mattias/git/hydra/.env/bin/python3.9 -Werror example/sphere.py --multirun --config-dir=tests/conf --config-name=test_deprecated_search_space hydra.sweep.dir=/tmp/pytest-of-mattias/pytest-0/test_example_with_deprecated_s0 hydra.job.chdir=False hydra.sweeper.n_trials=20 hydra.sweeper.n_jobs=1
```

## Expected Behavior
A deprecation warning should be shown, but then the Optuna sweeper should continue and succeed.

## System information
- **Hydra Version** :  1.2
- **Python version** : 3.9
- **Virtual environment type and version** : venv
- **Operating system** : linux

## Additional context
I can and will create a PR to fix this issue I introduced myself.

**Comment by Jasha10** [comment]
Thanks for working on this @MattiasDC :)
