### ISSUE TITLE
Drop Python 3.6 support

### ISSUE THREAD

**Issue by dolfinus** [facebookresearch/hydra#2304]
# 🚀 Feature Request

How about dropping Python 3.6 support?

## Motivation

**Is your feature request related to a problem? Please describe.**

Python 3.6 reached end of life 23 Dec 2021, and will no longer receive updates and bugfixes

## Pitch

**Describe the solution you'd like**

Let's drop Python 3.6 support from the package and from CI/linters/etc.

**Comment by Jasha10** [comment]
@dolfinus see https://github.com/omry/omegaconf/issues/791.

**Comment by pixelb** [comment]
Note we can monitor python minor version usage at:
https://pypistats.org/packages/hydra-core

**Comment by pixelb** [comment]
Also it's worth noting that python 3.6 is the centos 8 official version, which means longer support than would normally be provided a version

**Comment by dolfinus** [comment]
> Also it's worth noting that python 3.6 is the centos 8 official version

CentOS 8 have a python3.8 package. Also in case of development environment, `pyenv` is a common solution which allows to use any python version user wants without making any changes to list of OS packages.

**Comment by Jasha10** [comment]
It's become onerous to support some CI with python3.6. Mypy no longer has official support for 3.6.
In PR #2472 I disable lints for python3.6. The core tests are still working well enough with 3.6, so I'll leave those intact for now.
