### ISSUE TITLE
Overriding within the same config using a custom OmegaConf resolver

### ISSUE THREAD

**Issue by slerman12** [facebookresearch/hydra#2311]
I have a custom `OmegaConf` resolver called `do_something`.

When I structure my config like this:

```
block1:
     arg1: 1
     arg2: 2

override block1: ${do_something:${block1}}
```

I'm expecting the custom resolver function to be applied to the whole structured config `block1`, but although this doesn't crash, the function does not get applied either.

Am I missing some syntax for overriding in this way?

**Comment by Jasha10** [comment]
The syntax looks correct to me.
Note that custom resolvers are evaluated lazily upon access. This means you won't see the results of running the custom resolver until you access `cfg["override block1"]` (i.e. until one of `cfg.__getitem__` or `cfg.__getattr__` is called with the appropriate key).

**Comment by slerman12** [comment]
Oh, my mistake - I thought `block1` was being "overridden." Like the way defaults are overridden. So I thought block1 itself would be overridden by the `do_something` function.

Is there another way to "override" `block1` as desired? One way I found which I don't completely like is to use two separate blocks:

```
_block1:
     arg1: 1
     arg2: 2

block1: ${do_something:${_block1}}
```

**Comment by Jasha10** [comment]
You can edit `block1` using your custom resolver:
```python
from omegaconf import OmegaConf

def do_something(block):
    block.arg3 = 3
    return "foo"

OmegaConf.register_new_resolver("do_something", do_something)

yaml_data = """\
block1:
     arg1: 1
     arg2: 2

override block1: ${do_something:${block1}}
"""
cfg = OmegaConf.create(yaml_data)

assert cfg.block1 == {"arg1": 1, "arg2": 2}

# accessing causes the resolver to run, modifying block1
assert cfg["override block1"] == "foo"

assert cfg.block1 == {"arg1": 1, "arg2": 2, "arg3": 3}
```
This is technically more of an OmegaConf question than a Hydra one :)

**Comment by slerman12** [comment]
Hmm, this still requires two separate blocks. (`override block1` counts as a separate block, right?)

**Comment by slerman12** [comment]
Never mind, I see what you mean. I'm a bit confused because it resolves from accessing "override block1" (`cfg["override block1"]`) but not from accessing `block1`.

**Comment by Jasha10** [comment]
>  it resolves from accessing "override block1"

Think of it this way: accessing "override block1" is what triggers the `do_something` function to run.

**Comment by slerman12** [comment]
Is there a default override arg in Hydra that already gets accessed right away?

So I can do: `override that_default: ${do_something:${block1}}`

**Comment by Jasha10** [comment]
> Is there a default override arg in Hydra that already gets accessed right away?

Not by default. You can call `OmegaConf.resolve(cfg)`, which will cause all resolvers / interpolations to be resolved.

Using the example I gave above:
```python
...

cfg = OmegaConf.create(yaml_data)
assert cfg.block1 == {"arg1": 1, "arg2": 2}
OmegaConf.resolve(cfg)
assert cfg.block1 == {"arg1": 1, "arg2": 2, "arg3": 3}
```

Another pattern could be to run all of the resolvers stored in a top-level "resolvers" dict inside your config:
```python
from omegaconf import OmegaConf

def do_something(block):
    block.arg3 = 3
    return "foo"

OmegaConf.register_new_resolver("do_something", do_something)

yaml_data = """\
block1:
     arg1: 1
     arg2: 2

resolvers:
    override block1: ${do_something:${block1}}
"""
cfg = OmegaConf.create(yaml_data)

assert cfg.block1 == {"arg1": 1, "arg2": 2}

# run all custom resolvers:
for key in cfg.resolvers:
    cfg.resolvers[key]

assert cfg.block1 == {"arg1": 1, "arg2": 2, "arg3": 3}
```

The approach you proposed above with `block1: ${do_something:${_block1}}` is another good possibility (depending on your use-case).
```yaml
_block1:
     arg1: 1
     arg2: 2

block1: ${do_something:${_block1}}
```

**Comment by slerman12** [comment]
One more thing I tried:

```
block1:
     arg1: 1
     arg2: 2

hydra:
  help:
    template:
      block1: ${do_something:${block1}}
```

This approach would be my favorite, but it gave this error:

Cannot convert 'DictConfig' to string: '{'block1': '${do_something:${block1}}'}'

However, this hacky approach worked:

```
block1:
     arg1: 1
     arg2: 2

hydra:
  run:
    dir: ${do_something:${block1}}
```

(I had to make `do_something` output a path in addition to... doing something).

**Comment by Jasha10** [comment]
Perhaps instead of this:
```yaml
    template:
      block1: ${do_something:${block1}}
```
You could try this:
```yaml
    template: ${do_something:${block1}}
```

**Comment by slerman12** [comment]
Feels hacky (and doesn't seem to work when I tested it). I'll go with:

```
_block1:
     arg1: 1
     arg2: 2

block1: ${do_something:${_block1}}
```
