### ISSUE TITLE
[Bug] Compose order not respected when overriding built-in Hydra config node

### ISSUE THREAD

**Issue by nathanpainchaud** [facebookresearch/hydra#2316]
# 🐛 Bug
## Description

My real use-case is that I want to override some global config options when using a custom config of a launcher (Submitit). I see this as a legitimate use-case, because I want to override some config options related to the computing resources available (e.g. `num_workers`, `gpus`, etc.) from their default values set w.r.t. my local environment.

However, it seems that even if I manually specify an `override hydra/launcher: my_launcher` entry at the very end of my default list (after `_self_`), the global config options set in `my_launcher` are overridden by the default options. I suspect that built-in Hydra config nodes are resolved before user-defined config nodes, and that therefore it's impossible to override global values from built-in Hydra configs. However, as stated in my first paragraph, I think there exists legitimate use-cases for this, because I don't want to have to create a whole new launcher-related config for global values that should be overridden.

I also tried to workaround this issue using a [specialized configuration](https://hydra.cc/docs/patterns/specializing_config/), but the limited interpolation capabilities in the defaults list didn't allow me to interpolate using the `hydra/launcher` choice to specialize a config based on the launcher).

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

Here is the layout of my project:
```shell
my_project/
├── config
│   ├── example.yaml
│   ├── hydra
│   │   └── launcher
│   │       └── my_launcher.yaml
│   └── __init__.py
├── my_app.py
```

And the content of each file:

`example.yaml`:
```yaml
defaults:
  - _self_
  - override hydra/launcher: my_launcher

fizz: 3
buzz: 5
```

`my_launcher.yaml`:
```yaml
# @package _global_

defaults:
  - basic@_group_

hydra:
  launcher:

fizz: 7
```

`my_app.py`:
```python
import hydra
from omegaconf import DictConfig


@hydra.main(version_base=None, config_path="config", config_name="example")
def main(cfg: DictConfig):
    print(cfg)


if __name__ == '__main__':
    main()
```

## Expected Behavior

The global values set in the custom plugin config should be able to override the default values, based on the order in the defaults list.

In the case of the minimal reproducible example above, when launching the application using the command:
```shell
python my_app.py hydra/launcher=my_launcher
```
the output is:
```shell
{'fizz': 3, 'buzz': 5}
```
but I would have expected:
```shell
{'fizz': 7, 'buzz': 5}
```

## System information
- **Hydra Version** :  1.2.0
- **Python version** : 3.10
- **Virtual environment type and version** : conda 4.13.0
- **Operating system** : Linux Ubuntu 18.04

**Comment by ItamarKanter** [comment]
any update on this issue? I'm also experiencing the same behavior   
same scenario,  I want to override some config options related to the computing resources available

**Comment by Jasha10** [comment]
> I suspect that built-in Hydra config nodes are resolved before user-defined config nodes

Yes, this is correct. There is special-casing for the "hydra" namespace.

**Comment by nathanpainchaud** [comment]
@Jasha10 Thanks for confirming it. But I still think that it would be more intuitive if the "hydra" namespace was resolved in the order specified in the defaults list. The current way of doing things feels unintuitive (not to say downright buggy since it doesn't really follow what the defaults list is supposed to do).

**Comment by Jasha10** [comment]
I agree -- the output `{'fizz': 7, 'buzz': 5}` is what I would have expected too, which makes me feel that this issue is appropriately tagged as a "bug".

**Comment by omry** [comment]
Hydra configs groups are - by design - included before user configs. This allows user configs to override them.

**Comment by nathanpainchaud** [comment]
I undestand that Hydra config groups are treated differently and that it is by design. But IMO they should be treated more "normally" when they're being overridden by a user, such as in the example above.

I also disagree that this behavior should be considered "by design", since it then silently overrides the explicit configuration of the defaults list. The fact that the defaults list ordering is not respected should not be treated so lightly (and should be considered a bug), since that's what the user is most likely to understand/care about than the built-in, inflexible resolution order.

**Comment by omry** [comment]
It makes no sense for the launcher config to override the application level config.
You should probably have an application-level config that overrides the application config, and also override the hydra-launcher to my_launcher.

**Comment by nathanpainchaud** [comment]
You say that it makes no sense for the launcher to override the application, but it is entirely possible (and seems intuitive) to use the defaults list to specify that behavior. It just won't be respected during the resolving of the config.

I won't pursue the argument that there IS a logical use-case for built-in config nodes overriding application level config, since we seem to be going in circles. But I would argue that there needs to be a warning/error to warn the user when they put built-in config nodes after _\_self\__ in the defaults list that the application level config will still override these values.

Because regardless of whether it makes sense or not to do that in the end, the way the config is resolved does not follow the most intuitive interpretation of the config based on a strict interpretation of the defaults list.

**Comment by omry** [comment]
You are not putting items into the defaults after `_self_`, you are putting overrides.

Go over the [Defaults List](https://hydra.cc/docs/advanced/defaults_list/) documentation.
An override is changing a previously defined config.
![image](https://user-images.githubusercontent.com/376455/220249856-89f14a4c-2031-4408-a68d-2a5b7de8a9a1.png)

A definition would not have the override keyword.
You cannot define that config because you are not allowed to change the composition order of configs added by other modules (of you omit the override keywork you should get an error message saying something along those lines).
