### ISSUE TITLE
[Feature Request] Supporting Class registries

### ISSUE THREAD

**Issue by vballoli** [facebookresearch/hydra#2325]
# 🚀 Feature Request 

Adding support to class registries as a part of `_target_` during instantiation

Supporting something along the lines of `_target_: framework.class.registry['classname']`. (very crude syntax, can be changed)

## Motivation

When a large number of classes (within and outside a framework) inherit a base class with a registry, it's easier to use by accessing these classes through the class registry.

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes.

**Comment by Jasha10** [comment]
You should be able to achieve lookup in a registry using Hydra's current support for `_target_`. In my MWE below, the function `call_into_registry` looks up the named class in the `REGISTRY` dict and passes through the args and kwargs to that class:
```python
# framework.py

from collections.abc import Callable
from typing import Any

REGISTRY: dict[str, Callable[..., Any]] = {}


def call_into_registry(*args: Any, registered_name: str, **kwargs: Any) -> Any:
    fn = REGISTRY[registered_name]
    return fn(*args, **kwargs)
```
```python
# script.py

from typing import Any

from hydra.utils import instantiate
from omegaconf import OmegaConf

from framework import REGISTRY


class MyClass:
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        """Print out the args and kwargs"""
        print(f"In `MyClass.__init__`: {args=}, {kwargs=}")


REGISTRY["classname"] = MyClass

yaml_data = """
_target_: framework.call_into_registry
registered_name: classname
_args_:
    - a
    - b
    - c
kwarg1: foo
kwarg2: bar
"""

cfg = OmegaConf.create(yaml_data)
instance = instantiate(cfg)
print(f"Got {instance=}")
```
```text
$ python script.py
In `MyClass.__init__`: args=('a', 'b', 'c'), kwargs={'kwarg1': 'foo', 'kwarg2': 'bar'}
Got instance=<__main__.MyClass object at 0x7f2193c6d060>
```

**Comment by vballoli** [comment]
Thanks a lot @Jasha10 ! I have been doing this way, but I wanted to see if there was any interest in providing registry based functionality from hydra and integrate as `_target_` or `_regitsry_`, but yeah this seems good enough for now. Closing this.
