### ISSUE TITLE
Hydra mascot

### ISSUE THREAD

**Issue by snakers4** [facebookresearch/hydra#233]
![image](https://user-images.githubusercontent.com/12515440/66893477-d8cfc880-eff6-11e9-99e2-8729e009bf01.png)

I hesitated whether to report it or not ... but just for lulz, I noticed that your mascot is not a Hydra.

It more resembles a Russian folklore [beast ](https://ru.wikipedia.org/wiki/%D0%97%D0%BC%D0%B5%D0%B9_%D0%93%D0%BE%D1%80%D1%8B%D0%BD%D1%8B%D1%87) Zmey Gorynych.

Hydras (Greek beasts) usually do not have wings.

![image](https://user-images.githubusercontent.com/12515440/66893534-fac94b00-eff6-11e9-8dcf-3bdeea9f5efd.png)

**Comment by omry** [comment]
Thanks @snakers4.
Yes, I am aware that most Hydras are without wings. Other differences is that they are not blue and friendly and usually have more 9 heads.

I am closing this because I like the project mascot despite those imperfections :)
