### ISSUE TITLE
[Feature Request] Request for custom launcher support

### ISSUE THREAD

**Issue by syeehyn** [facebookresearch/hydra#2340]
# 🚀 Feature Request Request for custom launcher support

Our team has own launcher for launching jobs over cloud. 

## Motivation

**Is your feature request related to a problem? Please describe.**

I am trying to find a way to write a hydra [launcher](https://github.com/facebookresearch/hydra/blob/main/hydra/plugins/launcher.py) wraps around our own launcher to launch the job over cloud. 

## Pitch

We want to have some features like following:

in `custom_launcher.py`, we can create our own launcher like

``` python
from hydra.plugins.launcher import Launcher

class CustomLauncer(Launcher):
    def __init__(self) -> None:
        super().__init__()

    def setup(
        self,
        *,
        hydra_context: HydraContext,
        task_function: TaskFunction,
        config: DictConfig
    ) -> None:
        return ...

    def launch(
        self, job_overrides: Sequence[Sequence[str]], initial_job_idx: int
    ) -> Sequence[JobReturn]:
        return ... 

```

in `script.py`, we can plugin our launcher in this way.

``` python
config_store =  ConfigStore.instance()
config_store.store(
        group="hydra",
        name="config",
        node=HydraConf(
            launcher=CustomLauncer()
        ),
        provider="hydra",
    )

```

**Comment by jieru-hu** [comment]
hi @syeehyn thanks for the request. per our offline discussion, implementing a custom launcher and sweeper is supported in Hydra. in your specific case, you might start from configuring BasicSweeper's max_batch_size first :)

**Comment by syeehyn** [comment]
Thanks!

> hi @syeehyn thanks for the request. per our offline discussion, implementing a custom launcher and sweeper is supported in Hydra. in your specific case, you might start from configuring BasicSweeper's max_batch_size first :)
