### ISSUE TITLE
`multirun.yaml` always gets created

### ISSUE THREAD

**Issue by syeehyn** [facebookresearch/hydra#2341]
# 🐛 Bug
## Description
The `multirun.yaml` file still generated with `output_subdir = None`

## Checklist
- [x] I checked on the latest version of Hydra

## To reproduce

script: `main.py`

``` python

import hydra
import dataclasses
from hydra.conf import HydraConf
from hydra.core.config_store import ConfigStore
from hydra.types import RunMode
from omegaconf import DictConfig, OmegaConf

@dataclasses.dataclass
class Config:
    cfg_1: str = "tmp"

config_store = ConfigStore.instance()
config_store.store(
    group="hydra",
    name="config",
    node=HydraConf(
        mode=RunMode.MULTIRUN,
        output_subdir=None,
    ),
    provider="hydra",
)


config_store.store(
    name="my_config",
    node=Config,
)


@hydra.main(
    version_base=None,
    config_name="my_config",
)
def launch(cfg: DictConfig):
    print(OmegaConf.to_yaml(cfg))


if __name__ == "__main__":
    launch()

```

`python main.py`

## Expected Behavior

The `multirun` directory should not be generated.

## System information
- **Hydra Version** :  1.2
- **Python version** :  3.8
- **Virtual environment type and version** :  conda
- **Operating system** :  mac-os

**Comment by jieru-hu** [comment]
hi @syeehyn  -  `multirun.yaml` will always be created. see  discussions in https://github.com/facebookresearch/hydra/issues/1773

If this is critical, we can look into prioritizing this feature request

**Comment by syeehyn** [comment]
> 

Hi @jieru-hu , thanks for taking care about this. It's nice to have this feature, but it's is a trivial thing.
