### ISSUE TITLE
Recursive upcast in config composition

### ISSUE THREAD

**Issue by Sathrovarr** [facebookresearch/hydra#2349]
I'm trying to have worker classes accept a list of arguments they would internally use for further computation, where inheritance thereof makes sense. Say a class `A` has a `query` function, class `B(A)` also has `query` function and accepts same arguments + possibly more.
Let's say `A` has `arg1`, `arg2` for `query`. Then B may have `arg1`, `arg2`, `arg3` for its `query`. I want to encapsulate the arguments belonging to such functions (got multiple such and they have no meaning outside), so that they are part of a same 'package' (i.e. a dict).

The minimal example is as below:

```python
from dataclasses import dataclass
import hydra

from hydra.core.config_store import ConfigStore

@dataclass
class X:
    d: int
    p: int
        
@dataclass
class Y(X):
    q: int
        
@dataclass
class A:
    x: X

@dataclass
class B(A):
    x: Y

cs = ConfigStore.instance()

cs.store(
    'A',
    group = 'foo',
    node = A
)
cs.store(
    'B',
    group = 'foo',
    node = B
)

@hydra.main(config_name='config', config_path="config")
def my_app(cfg):
    pass

my_app()
```

What I then expect to work, is a setup as below:
`foo/fA.yaml`
```yaml
defaults:
    - A

x:
  d: 10
  p: 2
```

`foo/fB.yaml`
```yaml
defaults:
    - fA
    - B

x:
  q: 10
```

, where `A.x` would get upcasted from `X` to `Y` when the entire config is being upcasted to `B`. That never happens, though, so I get `Key 'q' not in 'X'`. In this case I could just comment out `fA`, but it has other defaults I want to have there in my case.

Of course, if I put the `x` in its own folder, established its ConfigStore instances, and included files so that the upcasting would happen on top level, it would work. But that is not quite the use-case here. It's just an encapsulation of parameters that belong to A, B; and I would like the upcast to go alongside the A, B upcasts.

Cheers for any ideas!

Python 3.9.9
Hydra 1.2.0

**Comment by Jasha10** [comment]
The following two changes will do the trick: (1) in `app.py`, do `cs.store("Y", group="foo", node=Y)`, and (2) in `foo/fB.yaml`, insert `Y@x` as the second entry to the defaults list.

```python
# app.py
from dataclasses import dataclass
import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import OmegaConf

@dataclass
class X:
    d: int
    p: int

@dataclass
class Y(X):
    q: int

@dataclass
class A:
    x: X

@dataclass
class B(A):
    x: Y

cs = ConfigStore.instance()
cs.store("A", group="foo", node=A)
cs.store("B", group="foo", node=B)
cs.store("Y", group="foo", node=Y)  # NEW

@hydra.main(config_name="config", config_path="config", version_base=None)
def my_app(cfg):
    print(OmegaConf.to_yaml(cfg))
if __name__ == "__main__":
    my_app()
```
```yaml
# config/foo/fA.yaml
defaults:
    - A
x:
  d: 10
  p: 2
```
```yaml
# config/foo/fB.yaml
defaults:
    - fA
    - Y@x  # NEW
    - B
x:
  q: 10
```
```yaml
# config/config.yaml
defaults:
  - foo: fB
  - _self_
hydra:
  job:
    chdir: false
```
```text
$ python app.py
foo:
  x:
    d: 10
    p: 2
    q: 10
```
---
Now I'll explain how I came up with the above solution.
In your original example, Hydra tries to compose a config that is equivalent to the following:
```python
OmegaConf.merge(  # ConfigKeyError: Key 'q' not in 'X'
    A,
    {"x": {"d": 10, "p": 2}},
    B,
    {"x": {"q": 10}},
)
```
You can confirm this by inspecting the output of `python app.py --info defaults`. The above call to `OmegaConf.merge` raises a `ConfigKeyError`. In fact, the following raises a `ConfigKeyError` too:
```python
OmegaConf.merge(  # ConfigKeyError: Key 'q' not in 'X'
    A,
    {"x": {"d": 10, "p": 2}},
    B,
)
```
Why is this an error? I guess it's because of the way `OmegaConf.merge` works. I'm not sure if this is an OmegaConf bug or if it is desired behavior...
Anyway, the following works:
```python
OmegaConf.merge(  # this is equivalent to my modified version of your original post:
    A,
    {"x": {"d": 10, "p": 2}},
    {"x": Y},
    B,
    {"x": {"q": 10}},
)
```

**Comment by Jasha10** [comment]
I'll close this now as I feel this is more if an OmegaConf issue than a Hydra issue.

**Comment by Jasha10** [comment]
OmegaConf dev version `v2.3.0.dev0` is now [available on pypi](https://pypi.org/project/omegaconf/2.3.0.dev0/). You can install it with `pip install omegaconf==2.3.0.dev0`.

This dev version fixes the underlying OmegaConf issue https://github.com/omry/omegaconf/issues/1003 which means that the workaround from my comment above will no longer be necessary.
