### ISSUE TITLE
[Bug] hydra-nevergrad-sweeper has a requirement on numpy<1.20.0

### ISSUE THREAD

**Issue by ajw1980** [facebookresearch/hydra#2362]
In hydra_nevergrad_sweeper/setup.py:
```
"numpy<1.20.0",  # remove once nevergrad is upgraded to support numpy 1.20
```
I think nevergrad supports numpy > 1.20.0 so I think this requirement should be changed.
https://github.com/facebookresearch/nevergrad/blob/main/requirements/main.txt

**Comment by Jasha10** [comment]
This issue is fixed by PR #2371.
I've published nevergrad sweeper version `1.3.0.dev0` to pypi, which should work with more recent numpy versions. You can install it with `pip install hydra-nevergrad-sweeper==1.3.0.dev0`.
