### ISSUE TITLE
[Feature Request] Allow for non-leading dashes in override keys

### ISSUE THREAD

**Issue by dberenbaum** [facebookresearch/hydra#2363]
# 🚀 Feature Request

Allow for non-leading dashes to appear in override keys. For example:

```
$ python my_app.py +dashed-key=val
LexerNoViableAltException: +dashed-key=val
                                  ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Motivation

See https://github.com/iterative/dvc/issues/8151. We rely on Hydra to enable our users to override parameters from the CLI (and it can enable other great features for our users, like complex configuration and parameter sweeps). However, we have had multiple users complain that converting our CLI overrides to Hydra has broken their use cases when they have dashes in the middle of their parameter keys.

## Pitch

**Describe the solution you'd like**

From #514, it's clear that leading dashes (`--learning-rate=0.1`) are not a feature you want to support. I would like to see support for non-leading dashes so that overrides like `learning-rate=0.1` work.

**Describe alternatives you've considered**

We may be able to find a workaround on our end, but this somewhat defeats the purpose of using Hydra for CLI overrides.

It also seems better to add in Hydra since it has general-purpose value.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Someone on our team (cc @daavoo 😄) can contribute a PR if you are open to it.

## Additional context

N/A

**Comment by Jasha10** [comment]
@dberenbaum I'm wondering if strategic use of quotation marks would make this possible. Could you please try the following?
```text
$ python my_app.py '"+dashed-key"=val'
```
Ref: [CLI override syntax - quoting](https://hydra.cc/docs/1.2/advanced/override_grammar/basic/#quoted-values)

**Comment by Jasha10** [comment]
See the discussion on [PR 2094](https://github.com/facebookresearch/hydra/pull/2094) which is closely related to this feature request.

**Comment by dberenbaum** [comment]
Thanks @Jasha10! I searched the issues but not the PRs, and that one does look like it covers this issue. Since it appears stale, maybe we can try to take it over to get it merged?

**Comment by dberenbaum** [comment]
@Jasha10 Sorry for the delay here. It looks like that #2094 has no outstanding issues to be resolved. Can it be merged along with https://github.com/omry/omegaconf/pull/880?

**Comment by Jasha10** [comment]
Right you are, @dberenbaum. I'm looking into getting those merged now.

**Comment by dberenbaum** [comment]
Thank you @Jasha10!
