### ISSUE TITLE
[Feature Request] Support `argparse` style commandline interface

### ISSUE THREAD

**Issue by ganler** [facebookresearch/hydra#2375]
# 🚀 Feature Request

Can we support the `argparse` style commandline interface? For example, can we have `python app.py --path /some/where` as `python app.py path=/some/where`? In this way, we can have auto-completion for the path while the latter approach is pain for typing paths.

## Motivation

**Is your feature request related to a problem? Please describe.**
No. It's an enhancement to make hydra more user-friendly.

## Pitch

**Describe the solution you'd like**
I don't know the internal about hydra but I think the implementation will be interpretating `sys.argv`.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
I'd like to help with where I can contribute.

**Comment by omry** [comment]
This conflicts with Hydra's own usage of argparse.
If you want tab completion (including paths), you can activate the tab completion support in Hydra (check the docs).

**Comment by ganler** [comment]
@omry Thanks for the reply. However, I am still curious if it is possible to have completion without extra configuration steps? For example, can we tweak the parsing to allow the argument value specified with a space (now is =) so that we can utilize shell path completion. Or can we automatically configure the shell extension during package installation? The hope is that when people ship 'hydraized' cli applications to more end-users, users can easily type things in a way they are familiar with. :-)

**Comment by omry** [comment]
This goes beyond the scope of Hydra itself and is the responsibility of whoever is creating the installation for the user app.
By the way, to make things friendlier for end uses you can create a package with the configs that is executable by running a binary (instead of `python foo.py`).
See the example linked from [here](https://hydra.cc/docs/advanced/app_packaging/).

**Comment by ganler** [comment]
@omry Thanks for the kind instructions!!! I will see if I can make things simple this way. Thanks again!
