### ISSUE TITLE
[Feature Request] Access global multi-run options from subjobs

### ISSUE THREAD

**Issue by janvainer** [facebookresearch/hydra#2398]
# 🚀 Feature Request

Add option to fail if multi-run combinations are duplicit or enable access to global multi-run groups in sub-jobs.

## Motivation

I have to run multi-run for my job, but I have to prevent duplicit argument combinations.
HydraConfig contains only parameters for specific combination. I tried to look up other options how I could accomplish this with hydra. If this feature exists or is doable with he latest master, how can it be done? If not, would it be possible to get this feature in the next hydra version?

## Pitch

**Describe the solution you'd like**
It would be enough for me to have access to global multi-run parameters of the master job.

**Describe alternatives you've considered**
I can read the multirun yaml file and check for duplicate in each of my subjobs. But it is a bit ugly.

**Comment by Jasha10** [comment]
Would using the `on_multirun_start` callback work for your usecase?
See the Hydra docs on the [Callback API](https://hydra.cc/docs/1.2/experimental/callbacks/).

**Comment by janvainer** [comment]
Yes, this would probably help. Thank you!

**Comment by shaunc** [comment]
> global multi-run parameters

@Jasha10 It seems the callback API doesn't give access to configuration?

My application is: if a multi-run fails, it can be that some `.lock` files are left over. In this case, the next run will fail. I would like a hook to check for these, and depending on configuration, either remove them or abort.
