### ISSUE TITLE
`InterpolationKeyError`: Cannot use basic variable interpolation

### ISSUE THREAD

**Issue by jonathanloganmoran** [facebookresearch/hydra#2408]
# 🐛 Bug
## Description
Running into an issue trying to use variable interpolation in the most basic case.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```
### dataset.yaml ###
dataset:
    cwd: ${hydra:runtime.cwd}
    data_dir: ../${cwd}/data
```
```
### From testing_configs.py ###
print(cfg['dataset'].data_dir)
```
which produces the following:
```
...
raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'cwd' not found
```

## Expected Behavior
I expect the path to be correctly printed:
```
/path/to/cwd/data/
```

## System information
- **Hydra Version** :  `1.2.0` / `omegaconf==2.2.3`
- **Python version** : `3.8.13`
- **Virtual environment type and version** : `conda` (used `pip install hydra-core —upgrade`)
- **Operating system** : macOS 12.6

## Additional context
I'm using a `dataclass` spec file with a `ConfigStore` instance. 

#### Side note:
Why do I need the import statement `from folder.file import Dataset` in `testing_configs.py` file? I get a `NameError` otherwise.

**Comment by Jasha10** [comment]
You need to use a relative interpolation (`${.cwd}`) or an absolute interpolation with the full path (`${dataset.cwd}`). See the OmegaConf docs on variable interpolation: https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#variable-interpolation

**Comment by Jasha10** [comment]
> Why do I need the import statement from folder.file import Dataset in testing_configs.py file? I get a NameError otherwise.

Sorry I don't have enough context to answer this question. Feel free to open a discussion topic with more details.

**Comment by jonathanloganmoran** [comment]
> You need to use a relative interpolation (`${.cwd}`) or an absolute interpolation with the full path (`${dataset.cwd}`). See the OmegaConf docs on variable interpolation: https://omegaconf.readthedocs.io/en/2.2_branch/usage.html#variable-interpolation

Okay great, thank you! One other thing, is there a way to evaluate the variable before assigning it to a literal?

In my example, I want to fetch the project root directory (two levels up from `hydra:runtime.cwd) with:
```
### dataset.yaml ###
dataset:
    cwd: ${hydra:runtime.cwd}
    data_dir: [../${.cwd}]/data
```
and get something like:
```
path/to/data
```
where the `/path/to` is the result from evaluating what is inside the brackets.

**Comment by Jasha10** [comment]
Are you saying you want to turn `../${.cwd}` into an absolute path? This can be done using an OmegaConf [custom resolver](https://omegaconf.readthedocs.io/en/2.2_branch/custom_resolvers.html).

**Comment by Jasha10** [comment]
You'll probably need `${.cwd}/../..` to get two levels up, not `../${.cwd}`.

If `${.cwd}` is `/foo/bar/baz` then `${.cwd}/../..` will be equivalent to `/foo/bar/baz/../..` while `../${.cwd}` is equivalent to `..//foo/bar/baz`.

```python
import os

from omegaconf import OmegaConf

OmegaConf.register_new_resolver(
    "abspath", lambda relative_path: os.path.abspath(relative_path)
)

yaml_data = """
### dataset.yaml ###
dataset:
    cwd: /foo/bar/baz
    data_dir_relative: ${.cwd}/../../data
    data_dir_absolute: ${abspath:${.cwd}/../../data}
"""

cfg = OmegaConf.create(yaml_data)
assert cfg.dataset.data_dir_relative == "/foo/bar/baz/../../data"
assert cfg.dataset.data_dir_absolute == "/foo/data"
```

**Comment by jonathanloganmoran** [comment]
That's awesome! Thanks so much for helping me understand this — everything works perfectly!
