### ISSUE TITLE
[Question] How to override hydra config inside the config group?

### ISSUE THREAD

**Issue by namespace-Pt** [facebookresearch/hydra#2411]
### Discussed in https://github.com/facebookresearch/hydra/discussions/2410

<div type='discussions-op-text'>

<sup>Originally posted by **namespace-Pt** October  9, 2022</sup>
Here is my config structure:
- config
  - main
    - default.yaml
- script
  - run.py

In `run.py`:
```
@hydra.main(version_base=None, config_path="../config", config_name="main/default")
def main(config: OmegaConf):
    print(config)

if __name__ == "__main__":
    main()
```
I want to **disable** the `output_subdir` and `logging` of hydra by writing the following in the `default.yaml`:
```
defaults:
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

hydra:
  output_subdir: null
  run:
    dir: .
```

However the code didn't work:
```
hydra.errors.ConfigCompositionException: In 'main/_default': Could not override 'main/hydra/hydra_logging'. No match in the defaults list
```

What's the proper way to do that?
</div>

**Comment by Jasha10** [comment]
See my reply at #2410.
