### ISSUE TITLE
[Feature Request] Compose a new config by using the two existing config

### ISSUE THREAD

**Issue by namespace-Pt** [facebookresearch/hydra#2413]
# 🚀 Feature Request

## Motivation
Here is my config structure:
- config
  - model1.yaml
  - model2.yaml
  - model3.yaml
  - unimodel.yaml
- run.py

Each `modelx.yaml` defines parameters of an individual model, which can be run in `run.py`:
```python
@hydra.main(version_base=None, config_path="config", config_name="modelx")
def main(config: OmegaConf):
    print(config)
```
Now I have a new model type, the `unimodel` that is the combination of arbitrary two models. And I want to compose the config of the `unimodel` by reusing the config in the original config file by adding a package of each one. 

## Pitch
For example, I want to combine `model1` and `model2`, so the `unimodel.yaml` would be:
```
defaults:
  - /model1@x_model
  - /model2@y_model
``` 
and I can override the config of both `x_model`(`model1`) and `y_model`(`model2`) in the command line. 

In the above example, however, the `unimodel.yaml` is fixed so that I can only combine `model1` and `model2`, but I want to combine **arbitrary two models**. Specifically, I can put the following in the command line
```
python run.py --config-name unimodel x_model=model1 y_model=model3 ++x_model.k=v
```
Then hydra would fill the `unimodel.yaml` with `model1@x_model` and `model3@y_model`, and then override the `k` parameter of `model1`.

**Comment by Jasha10** [comment]
Hi @namespace-Pt,

I'd recommend nesting the `model*.yaml` files under a `models` folder, then using the syntax `/models@x_model: model1` in the `unimodel.yaml` defaults list and using `models@x_model=model1` at the command line.

```text
$ tree
.
├── config
│   ├── models
│   │   ├── model1.yaml
│   │   ├── model2.yaml
│   │   └── model3.yaml
│   └── unimodel.yaml
└── run.py

2 directories, 5 files
```
```yaml
 $ cat config/unimodel.yaml
defaults:
  - /models@x_model: model1
  - /models@y_model: model2
```
```text
$ python run.py --config-name unimodel
{'x_model': {}, 'y_model': {}}
$ python run.py --config-name unimodel models@x_model=model3
{'x_model': {}, 'y_model': {}}
$ python run.py --config-name unimodel models@x_model=model3 ++x_model.k=v
{'x_model': {'k': 'v'}, 'y_model': {}}
```

**Comment by namespace-Pt** [comment]
Got it. Thank you.
