### ISSUE TITLE
Returning `ListConfig` instead of `DictConfig`?

### ISSUE THREAD

**Issue by jonathanloganmoran** [facebookresearch/hydra#2417]
# 🐛 Bug
## Description
For some reason, I'm getting back a `list` object (`ListConfig` type?) in only one of my Python script files. Yet, in all others, I get a `DictConfig` type (which I expect). 

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```yaml
### config.yaml ###
defaults:
    dataset: dataset_name
    model: model_name
    ...
```
```yaml
### model_name.yaml ###
param_1: value_1
param_2: value_2
...
```
```yaml
### dataset_name.yaml ###
param_3: value_3
param_4: value_4

nested_keys:
    param_5: value_5 
```

```python
### dataclasses.py ###
from dataclasses import dataclass

@dataclass
class Dataset:
    param_3: type_3
    param_4: type_4

@dataclass
class TFModel:
    param_1: type_1
    param_2: type_2

@dataclass
class MyModel:
    model: TFModel
    dataset: Dataset
```
```python
### my_script.py ###
from dataclasses import MyModel
import hydra
from hydra.core.config_store import ConfigStore
import omegaconf
from omegaconf import DictConfig, OmegaConf

cs = ConfigStore.instance()
cs.store(name='model_config', node=MyModel)
OmegaConf.register_new_resolver(
    'custom_resolver': lambda x: custom_fn(x)
)

@hydra.main(version_base=None, config_path='../configs', config_name='config.yaml')
def main(cfg: MyModel):
    cfg = OmegaConf.create(cfg)
    print(cfg['model'].param_1)
    ...
```
```text
> python3 my_script.py model.param1={VALUE_1} ...
```
** Stack trace/error message **
```text
File "/root/miniconda3/lib/python3.7/site-packages/omegaconf/listconfig.py", line 87, in _validate_get
    "ListConfig indices must be integers or slices, not $KEY_TYPE"
omegaconf.errors.KeyValidationError: ListConfig indices must be integers or slices, not str
    full_key: [model]
    object_type=list
```

## Expected Behavior
I override *some* (not all) of the parameters defined in `model_name.yaml` using the Basic Override Syntax in CLI. These overrides are combined with the other (unmodified) parameters from `model_name.yaml`, then loaded into `my_script.py` as a structured config (`MyModel`). Then, I expect to access `cfg` attributes either by attribute or dictionary style, just like I have done in my other Python files without issue.

Currently, I get back a `list` object of *only* the configs I've overridden in CLI, i.e., `['model.param_1=VALUE_1', ...]` and not any others defined in `model_name.yaml`. Running the same on other Python files in my project results in a structured config `dict` instance, i.e., `cfg = {'model': {VALUE_1, value_2}, 'dataset': {value_3, value_4} ... }`, which is what I expect.

## System information
- **Hydra Version** :  1.2.0
- **Python version** : 3.7.3
- **Virtual environment type and version** : NoVNC
- **Operating system** : Ubuntu 16.04.6 LTS (Xenial)

## Additional context
I am using Basic Override syntax inside a Jupyter Notebook cell, e.g.,
```
!python3 my_script.py model.param_1={VALUE_1} ...
```
When I override params with the above for other Python files, I get back the `MyModel` dict-like object as I would expect.

One other thing, the `main()` function inside `my_script` is called by the [`tf.compat.v1.run()`](https://www.tensorflow.org/api_docs/python/tf/compat/v1/app/run) function wrapper. The wrapper accepts two keyword arguments, a Callable to `main()` and its positional argument (if any), i.e., `tf...run(main=main, argv=argv)`. Right now, I'm not passing it anything (the `sys.modules['__main__'].main` is called by default). 

A workaround I can think of right now would be to use the Hydra [Compose API](https://hydra.cc/docs/advanced/compose_api/) and pass the `cfg` result into the wrapper, i.e., `tf...run(main=__main__, argv=cfg)`. Is there a better way to resolve this?

**UPDATE**: Proposed workaround above doesn't work; TF expects the `argv` to be a list of `absl` flags.

**Comment by jonathanloganmoran** [comment]
Any help on this issue?

**Comment by Jasha10** [comment]
I tried to run the code you posted, though there were some errors in it (e.g. syntax error in `my_script.py`). When I fixed the syntax error and other issues, I did not get the same ListConfig error message that you got. Please provide a full reproducible example. See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips.
