### ISSUE TITLE
[Feature Request] Delete arguments from the CLI

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#242]
# 🚀 Feature Request

Being able to remove config values from the CLI. E.g `python main.py --delete optimizer.lr`

## Motivation

The configuration values can be parameters of an other library, in this case you would like to be able to use the default parameters of the other library without having to keep an updated config file for these defaults (and without having to manually search and type these values). This is especially true for more complex parameters that would be cumbersome to write on a CLI (e.g. a dictionary).

Note that this would not be the same as setting the value to `null`.

**Comment by omry** [comment]
@YannDubs, can you describe a more concrete case where you would need to do this?
Generally speaking, the current approach is to build the configuration from nothing. If you you have something that you don't want there you probably need to make sure it wouldn't be added in the first place.

**Comment by omry** [comment]
Closing, feel free to continue discussing here if you have followup comments.
