### ISSUE TITLE
[Feature Request] Expose `srun_args` from the Submitit Launcher

### ISSUE THREAD

**Issue by Queuecumber** [facebookresearch/hydra#2429]
# 🚀 Feature Request

Submitit allows passing additional options to the `srun` command that it generates using the parameter `srun_args` which is a list of strings. This parameter should also be exposed by the submitit launcher.

## Motivation

For reasons I need to customize my `srun` command a bit but there's no way to do it with the current launcher

## Pitch

I would like to add an option to the `SlurmQueueConf` (https://github.com/facebookresearch/hydra/blob/1.2_branch/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L33) that would forward this parameter

```
srun_args: List[str]
```

and as far as I can tell that's all that should be required

**Are you willing to open a pull request?** 
yes, it should be simple

**Comment by Jasha10** [comment]
> Are you willing to open a pull request?
yes, it should be simple

Go for it!

**Comment by Queuecumber** [comment]
OK I did it
