### ISSUE TITLE
Python 3.11 Support

### ISSUE THREAD

**Issue by johnnynunez** [facebookresearch/hydra#2443]
Yeah! Python 3.11 support please. It should be the default.
Python 3.11 is between 10-60% faster than Python 3.10. On average, we measured a 1.25x speedup on the standard benchmark suite. See Faster CPython for details.
https://docs.python.org/3.11/whatsnew/3.11.html
https://www.phoronix.com/news/Python-3.11-Released

https://github.com/pytorch/pytorch/issues/86566

**Comment by Jasha10** [comment]
Thanks @johnnynunez!
TODO:
- [ ] enable python3.11 in CI pipelines
- [ ] migrate dataclasses to avoid mutable default values (see WIP PR #2418 for context)

**Comment by johnnynunez** [comment]
Amazin results https://www.phoronix.com/review/python-311-performance @Jasha10
