### ISSUE TITLE
[Bug] No outputs directory and no logging when using the Compose API

### ISSUE THREAD

**Issue by fantauzzi** [facebookresearch/hydra#2456]
# 🐛 Bug
## Description
When initializing Hydra with the Compose API (instead of `@hydra.main()`), Hydra doesn't make the `outputs` directory and doesn't do the logging. Also, trying to read `hydra.runtime.output_dir`  results in an exception `omegaconf.errors.MissingMandatoryValue: Missing mandatory value: hydra.runtime.output_dir`

## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
import logging
from logging import info
from hydra import compose, initialize


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)-15s %(message)s")

    initialize(version_base=None, config_path=".")
    params = compose(config_name="params", return_hydra_config=True)
    info(f'Howdy!')
    # print(params.hydra.runtime.output_dir)


if __name__ == '__main__':
    main()
```

** Stack trace/error message **
```
Not applicable.
```

## Expected Behavior
After program completion, there should be, in the current directory, a directory `outputs` with, among other things, the log file. Instead, the `outputs` directory is missing. 

## System information
- **Hydra Version** :  1.2.0
- **Python version** :  3.10.7
- **Virtual environment type and version** :  pyenv 2.3.5 and virtualenv 20.13.0+ds 
- **Operating system** : Ubuntu 22.04.1

## Additional context
Note that if you un-comment line no. 12, and try to access `params.hydra.runtime.output_dir`, you get an exception there:
```
omegaconf.errors.MissingMandatoryValue: Missing mandatory value: hydra.runtime.output_dir
    full_key: hydra.runtime.output_dir
    reference_type=RuntimeConf
    object_type=RuntimeConf
```
Any workaround? How can I have Hydra generate and fill the `outputs` directory, also with the log, while using the Compose API? 

I have tried setting `params.hydra.runtime.output_dir` myself, like in the script below, there is no exception thrown, but still no `outputs` directory and no log are produced.

```
import logging
from logging import info
from pathlib import Path
from hydra import compose, initialize


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)-15s %(message)s")

    initialize(version_base=None, config_path=".")
    params = compose(config_name="params", return_hydra_config=True)
    params.hydra.runtime.output_dir = str(Path.cwd() / 'outputs')  # <== setting params.hydra.runtime.output_dir here
    info(f'Howdy!')
    print(params.hydra.runtime.output_dir)


if __name__ == '__main__':
    main()
```

**Comment by Jasha10** [comment]
This is intended behavior.
The `compose` API is supposed to be a functional interface (in the sense of [functional programming](https://en.wikipedia.org/wiki/Functional_programming)), which means `compose(...)` is supposed to be a ["pure function"](https://en.wikipedia.org/wiki/Pure_function) that does not produce side effects.

**Comment by Jasha10** [comment]
> Also, trying to read hydra.runtime.output_dir results in an exception omegaconf.errors.MissingMandatoryValue: Missing mandatory value: hydra.runtime.output_dir

Yes, the current implementation of `compose` does not populate the `hydra` variable.

**Comment by Jasha10** [comment]
See also [`hydra_zen.launch`](https://mit-ll-responsible-ai.github.io/hydra-zen/generated/hydra_zen.launch.html) for an alternative API that wraps Hydra.
