### ISSUE TITLE
[Bug] Instantiate recursive list with _target_ witch is annotated as dataclass has unexpected behavior

### ISSUE THREAD

**Issue by npuichigo** [facebookresearch/hydra#2504]
# 🐛 Bug
## To reproduce
I want to instantiate a huggingface accelerate for deep learning training, while some of it's argument need [a list of dataclass objects](https://huggingface.co/docs/accelerate/package_reference/accelerator#accelerate.Accelerator.kwargs_handlers) like (https://huggingface.co/docs/accelerate/package_reference/kwargs#accelerate.DistributedDataParallelKwargs)

It's okay outside a list.
```python
In [35]: kwargs = hydra.utils.instantiate({'_target_': 'accelerate.DistributedDataParallelKwargs'})

In [36]: kwargs
Out[36]: DistributedDataParallelKwargs(dim=0, broadcast_buffers=True, bucket_cap_mb=25, find_unused_parameters=False, check_reduction=False, gradient_as_bucket_view=False, static_graph=False)
```

It's not.
```python
In [38]: kwargs = hydra.utils.instantiate([{'_target_': 'accelerate.DistributedDataParallelKwargs'}])

In [39]: kwargs
Out[39]: [{'dim': 0, 'broadcast_buffers': True, 'bucket_cap_mb': 25, 'find_unused_parameters': False, 'check_reduction': False, 'gradient_as_bucket_view': False, 'static_graph': False}]
```

## Expected Behavior
A list of original dataclass object

## System information
- **Hydra Version** :  1.2.0
- **Python version** :  3.8

**Comment by Jasha10** [comment]
Thank you for the bug report @npuichigo!

Note that this behavior happens not only for lists but also for nested dicts:
```python
from dataclasses import dataclass
import hydra
from omegaconf import DictConfig

@dataclass
class MyDataclass:
    ...


# Top-level _target_
obj = hydra.utils.instantiate(
    {"_target_": "__main__.MyDataclass"},
)
assert isinstance(obj, MyDataclass)

# Nested _target_
obj = hydra.utils.instantiate(
    {"nested": {"_target_": "__main__.MyDataclass"}},
)
assert isinstance(obj["nested"], DictConfig)

# _target_ inside list
obj = hydra.utils.instantiate(
    [{"_target_": "__main__.MyDataclass"}],
)
assert isinstance(obj[0], DictConfig)
```

I worry that changing this behavior in Hydra v1.x would be a breaking change, so I'll milestone this issue for v2.0.

**Comment by Jasha10** [comment]
Actually I believe there is a solution for your issue, @npuichigo.
You can pass the `_convert_="object"` flag to `instantiate:
```python
from dataclasses import dataclass

import hydra


@dataclass
class MyDataclass:
    ...


# Top-level _target_
obj = hydra.utils.instantiate({"_target_": "__main__.MyDataclass"}, _convert_="object")
assert isinstance(obj, MyDataclass)

# Nested _target_
obj = hydra.utils.instantiate(
    {"nested": {"_target_": "__main__.MyDataclass"}}, _convert_="object"
)
assert isinstance(obj["nested"], MyDataclass)

# _target_ inside list
obj = hydra.utils.instantiate(
    [{"_target_": "__main__.MyDataclass"}], _convert_="object"
)
assert isinstance(obj[0], MyDataclass)
```
You can also include the `_convert_` key as part of the config itself, e.g. instead of writing `hydra.utils.instantiate({"_target_": "__main__.MyDataclass"}, _convert_="object")` you could write `hydra.utils.instantiate({"_target_": "__main__.MyDataclass", "_convert_": "object"})`.

For reference, see the Hydra docs on [Parameter conversion strategies](https://hydra.cc/docs/1.3/advanced/instantiate_objects/overview/#parameter-conversion-strategies).

**Comment by omry** [comment]
I dislike the inconsistency between instantiating a dataclass target in and out of a list.
IMHO it's worth trying to fix.
