### ISSUE TITLE
[Bug] Relax pin to allow omegaconf 2.3

### ISSUE THREAD

**Issue by weiji14** [facebookresearch/hydra#2510]
# 🐛 Bug
## Description

Just reporting an issue when installing `hydra` with Python 3.11 on conda=forge. Currently, `hydra=1.3.0` is pinned to `omegaconf~=2.2` (>=2.2, <2.3) (see https://github.com/facebookresearch/hydra/blob/v1.3.0/requirements/requirements.txt#L1). Support for Python 3.11 in `hydra` was added in https://github.com/facebookresearch/hydra/issues/2443, but Python 3.11 support was only added in `omegaconf=2.3` (see https://github.com/omry/omegaconf/releases/tag/v2.3.0).

So for Python 3.11 to work properly, the version pinning needs to be relaxed to something like `omegaconf>=2.2` instead.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```bash
mamba create -n temp python=3.11 hydra-core=1.3.0
```

** Stack trace/error message **
```
Encountered problems while solving:
  - package hydra-core-1.3.0-pyhd8ed1ab_0 requires omegaconf 2.2.*, but none of the providers can be installed
```

## Expected Behavior

The installation command should work

## System information
- **Hydra Version** :  1.3.0
- **Python version** : 3.11
- **Virtual environment type and version** : n/a
- **Operating system** : Linux

## Additional context

The unpinning will need to be done first on https://github.com/facebookresearch/hydra, and a patch version (1.3.1?) released, before the change can be propagated to https://github.com/conda-forge/hydra-core-feedstock.

**Comment by Jasha10** [comment]
Excellent, thanks for opening this issue @weiji14.

**Comment by Jasha10** [comment]
Done. Here's [Hydra v1.3.1 on pypi](https://pypi.org/project/hydra-core/1.3.1/).
