### ISSUE TITLE
[Bug?] unexpected override with ConfigStore + `_global_`

### ISSUE THREAD

**Issue by idning** [facebookresearch/hydra#2511]
# 🐛 Bug
## Description
when I using ConfigStore with `_global_` the override is off

## Checklist
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```
$ tree
.
├── a.txt
├── conf
│   ├── config.yaml
│   └── db
│       └── mysql.yaml
└── my_app.py
2 directories, 4 files

```
```python
$ cat my_app.py
#!/usr/bin/env python3

import hydra
from omegaconf import DictConfig, OmegaConf
from dataclasses import dataclass
from hydra.core.config_store import ConfigStore

@dataclass
class PostgresSQLConfig:
    driver: str = "postgresql"
    user: str = "jieru"
    password: str = "secret"

cs = ConfigStore.instance()
# Registering the Config class with the name `postgresql` with the config group `db`
cs.store(name="config", node=PostgresSQLConfig)


@hydra.main(version_base=None, config_path="conf", config_name='config')
def my_app(cfg: DictConfig) -> None:
    print(OmegaConf.to_yaml(cfg))

if __name__ == "__main__":
    my_app()
```

```yaml
$ cat conf/config.yaml
# @package _global_
#
defaults:
  - db: mysql

$ cat conf/db/mysql.yaml
# @package _global_
#
driver: mysql
user: omry
password: secret
```

```
$ ./my_app.py 
sys:1: UserWarning:
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/Users/~/homebrew/lib/python3.10/site-packages/hydra/main.py:90: UserWarning:
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
  _run_hydra(

driver: postgresql
user: jieru
password: secret
```

## Expected Behavior
output should be:
```yaml
driver: mysql
user: omry
password: secret
```

**Comment by Jasha10** [comment]
Hi @idning,

You need to change this:
```python
# Registering the Config class with the name `postgresql` with the config group `db`
cs.store(name="config", node=PostgresSQLConfig)
```
to this:
```python
# Registering the Config class with the name `postgresql` with the config group `db`
cs.store(name="postgresql", group="db", node=PostgresSQLConfig)
```
The error message from your program gives a hint about this:
```
UserWarning:
'config' is validated against ConfigStore schema with the same name.
```
The message is saying that you have two different things stored with the name `'config'` (i.e. there is a file `config.yaml` and also a node `cs.store(name='config', ...)`).

**Comment by idning** [comment]
thanks @Jasha10  this is very helpful!

**Comment by idning** [comment]
another qq, @Jasha10 , how does Hydra determine I have two different things stored in `'config'`, as my actual intention is to override.

also, when I change config.yaml to include a `_self_`, it works as expected:

```
$ cat conf/config.yaml
# @package _global_
#
defaults:
  - _self_
  - db: mysql
```

**Comment by Jasha10** [comment]
> how does Hydra determine I have two different things stored in 'config'

It's a name collision. Calling `ConfigStore.store` is like creating a yaml file dynamically. Hydra is complaining because you're calling `cs.store(name='config', ...)` when there already existed a yaml file named `config.yaml`. You should try to avoid such a name collision.

> also, when I change config.yaml to include a _self_, it works as expected:

Right. If you don't include self, then ([for Hydra >= v1.1](https://hydra.cc/docs/1.3/upgrades/1.0_to_1.1/default_composition_order/)) `_self_` is implicitly included at the end of the defaults list:
```yaml
$ cat conf/config.yaml
# @package _global_
#
defaults:
  - db: mysql
  # If you don't explicitly include _self_, then it is implicitly added
  # to the end of the defaults list
  # - _self_
```
Since the call to `cs.store(name="config", ...)` has the same name as the `config.yaml` yaml file, the `_self_` entry of the `config.yaml` defaults list causes the `PostgresSQLConfig` dataclass to be merged into the composed config.

> my actual intention is to override.

I would recommend using this call to `cs.store`:
```python
cs.store(name="postgresql", group="db", node=PostgresSQLConfig)
```
Then you can switch between `db: postgresql` and `db: mysql` in your `config.yaml` file:
```yaml
$ cat conf/config.yaml
# @package _global_
#
defaults:
  # - db: postgresql
  - db: mysql
```

**Comment by omry** [comment]
>  Hydra is complaining because you're calling cs.store(name='config', ...) when there already existed a yaml file named config.yaml

I don't think adding things to the ConfigStore does such checks.

**Comment by Jasha10** [comment]
It doesn't do such a check. I guess my comment was misleading; I meant that the name collision is causing this issue (though indirectly).

Actually I have an open issue https://github.com/facebookresearch/hydra/issues/2453 to add such a check preventing name collisions.

**Comment by Jasha10** [comment]
Maybe my previous comment was misleading.
The name collision is causing this issue though (as well as the `UserWarning: 'config' is validated against ConfigStore schema with the same name.`)
