### ISSUE TITLE
[Feature Request] Communication between sweeper and main.py

### ISSUE THREAD

**Issue by timruhkopf** [facebookresearch/hydra#2515]
# 🚀 Feature Request

Pass additional (optional) arguments -- perfererably python objects from the sweeper to the main function.

## Motivation

**Is your feature request related to a problem? Please describe.**
We currently are working on a meta-learner for a sweeper, which is supposed to actively guide the main.py model. To do that we would want the sweeper and the main pipeline to be able to communicate directly rather than over the file system; that is 
1. we want to collect the models' experience and return it at the end of their training to the sweeper directly.
2. we would like to provide our meta-learner as an argument to the main function (next to the omegaconf dict).

## Pitch
**Describe the solution you'd like**
Eventually, the sweeper calls the launcher and passes the task function and its hydra context. The BasicLauncher and the SubmititLauncher.__call__ delegate to hydra.core.run_job, which executes the actual task function. 

We would like it to simply pass along additional arguments (next to the config). 

**Describe alternatives you've considered**
There may however be an issue; namely, when submitting jobs on slurm using the executor, we are unsure of how to do this and it likely is not possible to share objects. Is there a good way to do it?

**Comment by Jasha10** [comment]
Hi @timruhkopf,
Thanks for the feature request.
This seems related to issue #1710, where the OP proposed a way for the user's job to access the OptunaSweeper's trial object.

**Comment by timruhkopf** [comment]
Thanks Jasha! 

It is indeed the same issue! Thank you very much. I have been thinking along similar lines for a workaround, but the pointer with the trial config to instantiate the object that I would want to be shared (and loading the weights along with it) is where i was stuck at. 

I actually wouldn't know how to make this a formal connection in hydra, such that this indeed becomes a feature of hydra though. Would love to see a more native way in the future.

But thank you very much for now!
