### ISSUE TITLE
[Feature Request] Use SimpleNamespace for to_container() and to_object()

### ISSUE THREAD

**Issue by raphCode** [facebookresearch/hydra#2524]
# 🚀 Feature Request

Since Python 3.3, the standard library provides [`types.SimpleNamespace`](https://docs.python.org/3/library/types.html#types.SimpleNamespace) which is a container similar to `dict`s, but can be accessed by dot notation.
I would like to have `OmegaConf.to_container()` / `OmegaConf.to_object()` emit instances of `SimpleNamespace` instead of `dict`.

## Motivation

Currently, users of Hydra can convert OmegaConf objects into python `list`s and containers for named keys:
These can be dataclasses / attr classes (in the case of structured configs) or else `dict`s.
This provides speedups of 3 orders of magnitude when accessing an item compared to OmegaConf objects.

In my code, I want to access the config by dot notation, e.g. `config.database.port`.
While this works great for dataclasses / attr classes, it requires a structured config meaning the presence of all keys must be known in advance. All extra keys not present in the structured config are converted to `dict` which must be accessed by subscription: `config["database"]["port"]`

My concrete use case:
In my app, users can provide custom implementations of some functions. These functions may read custom options from the hydra config.
Both the parameter names and nesting levels of these options are completely user-controlled, so there is no way I can use a structured config in advance.

## Pitch

```python
OmegaConf.to_container(cfg, structured_config_mode=omegaconf.SCMode.SIMPLE_NS)
```
If the idea is well received, `OmegaConf.to_object()` could also convert to `SimpleNamespace` by default, but this is a breaking change and not a priority for me.

**Comment by Jasha10** [comment]
Thanks for the feature request, @raphCode.
As the proposed feature doesn't rely on Hydra functionality, I think it would be appropriate to open this against the [omegaconf](https://github.com/omry/omegaconf) repo. Could you please migrate this issue over there?

**Comment by raphCode** [comment]
See https://github.com/omry/omegaconf/issues/1048
