### ISSUE TITLE
[Bug] MissingConfigException cannot be correctly deserialized, due to lack of  missing_cfg_file ctor default

### ISSUE THREAD

**Issue by gazonk** [facebookresearch/hydra#2535]
# 🐛 Bug
## Description
in https://github.com/facebookresearch/hydra/blob/main/hydra/errors.py
the missing_cfg_file parameter of the `MissingConfigException` should be defaulted to `None` since it is optional, otherwise deserialization will fail.
## Checklist
- [x] I checked on latest commit [7bc2b1a] of errors.py (https://github.com/facebookresearch/hydra/commit/7bc2b1ad66da91a12c6158f9413c908b211bff1e) 
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
** Minimal Code/Config snippet to reproduce **
```python
import pickle
import hydra
e = hydra.errors.MissingConfigException("missing", "file")
x = pickle.dumps(e)
y = pickle.loads(x)
```
** Stack trace/error message **
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'missing_cfg_file'
```

## Expected Behavior
successful deserialization:
```
>>> y
MissingConfigException('missing')
```
## System information
- **Hydra Version** :  hydra-core==1.3.1
- **Python version** : Python 3.8.13
- **Virtual environment type and version** : None
- **Operating system** : Ubuntu 22.04.1 LT

## Additional context
This exception was serialized/deserialized when using ray tune.

**Comment by Jasha10** [comment]
Thanks for the bug report, @gazonk! I can reproduce the issue on my local machine.
