### ISSUE TITLE
[Feature Request] Ordered choices for sweeper in config files

### ISSUE THREAD

**Issue by aaronfderybel** [facebookresearch/hydra#2555]
# 🚀 Feature Request

Ordered choices for sweeper in config files

## Motivation

I'd like to have the possibility to have ordered choices in config files to run ML experiments. 
Currently you need to go to command line to type in "tag(ordered, choice(option1, option2))"
When You have different datasets and algorithms you don't want to sample them randomly but instead go over them one by one. 

## Pitch
Currently choices in config files are defined as:

```
db:
  - mnist
  - cifar

```
Maybe something like this could be possible for an ordered choice in config.
```
db:
 1. mnist
 2. cifar
```

Currently i use a nevergrad sweeper custom config file it looks like this:
![image](https://user-images.githubusercontent.com/43145159/213188182-4c58cec3-b371-4737-afb1-28cad004f3bd.png)

When i run the sweeper with 2 jobs it chooses the option isolationforest for model twice. 
Certain options would be handy to only occur once in the sweeper.

**Comment by Jasha10** [comment]
Hi @aaronfderybel,

The nevergrad sweeper is a stochastic sweeper -- it chooses what parameters to run based on an optimizing model.

You should consider using the BasicSweeper instead of nevergrad, especially if your budget is just 2. With the BasicSweeper, each combination of choices will be chosen exactly once.

**Comment by aaronfderybel** [comment]
Hi @Jasha10 ,

I see is there a way to combine different sweepers easily?
Basic sweeper for dataset, algorithm combination and nevergrad for Hyperparameter sweeping?

**Comment by Jasha10** [comment]
No, that's not supported by Hydra's current sweeper implementations.
A few options you have include:
- roll your own sweeper plugin
- Use a loop external to hydra to drive the fixed sweep options (e.g. loop in bash over `{ecod,isolationforest}`) and let Hydra's sweeper focus on the stochastic part of the sweep.

**Comment by aaronfderybel** [comment]
Ok thank you for the feedback, closing this discussion.

**Comment by LukeLIN-web** [comment]
> Ok thank you for the feedback, closing this discussion.

Did you know how to sweep the hyperparameters?  

```
```
ike `model.num_train_worker: range(2, 7)`

**Comment by Jasha10** [comment]
@LukeLIN-web I've opened a new discussion topic: #2528
