### ISSUE TITLE
Hydra ray launcher requirements update

### ISSUE THREAD

**Issue by jccalvojackson** [facebookresearch/hydra#2559]
# 🚀 Feature Request

The requirements of `hydra-ray-launcher` are too restrictive. Please provide wider bounds. In particular, so that is compatible with the latest version of ray and with python 3.10

```
install_requires=[
        "boto3==1.22.6",
        "hydra-core>=1.1.2",
        "ray[default]==1.12.0",
        "aiohttp==3.8.1",
        "cloudpickle==2.0.0",
        "pickle5==0.0.11; python_version < '3.8'",
    ],
```

## Motivation

**Is your feature request related to a problem? Please describe.**

There are multiple issues pointing to this problem #2407 , #2336  and many others

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

**Comment by bryant1410** [comment]
Hey, for what it's worth, I tried relaxing the dependencies, and it just worked for Ray 2 (I used Ray 2.2)! You can try it with:

```bash
pip install git+https://github.com/bryant1410/hydra@ray-2#subdirectory=plugins/hydra_ray_launcher
```

Though I only used the launcher `ray` not `ray_aws`
