### ISSUE TITLE
[Bug] Project dependencies.

### ISSUE THREAD

**Issue by jackokring** [facebookresearch/hydra#2585]
`hydra-core 1.3.1 has requirement antlr4-python3-runtime==4.9.*, but you have antlr4-python3-runtime 4.11.1.`

**Comment by Jasha10** [comment]
@jackokring see #2491.

**Comment by jackokring** [comment]
```
# pip utilities
alias pipfix="(pip check | awk '{print $1}' | xargs pip install --upgrade) && pip check"

# pip upgrade all
alias pipnew="(pip list -o | cut -f1 -d' ' | tr ' ' '\n' | awk '{if(NR>=3)print}' | cut -d' ' -f1 | xargs -n1 pip install -U) && pip check"
```
So `pipfix` in my `.bashrc` managed to fix it. I have one final conflict on `ossfs` but that's not this, so ... closed for now.
