### ISSUE TITLE
[Bug] `hydra.utils.instantiate` converts instantiated objects back to their configs when passing as arguments

### ISSUE THREAD

**Issue by lematt1991** [facebookresearch/hydra#2591]
# 🐛 Bug
## Description
When using `hydra.utils.instantiate`, if I pass an instantiated object from a config as a `kwarg` to `instantiate`, it converts it back to a it's corresponding config.  For example:

```Python
model = hydra.utils.instantiate(model_config)
evaluator = hydra.utils.instantiate(evaluator_config, model=model)
# At this point `evaluator.model` will be `model_config` rather than the instantiated model
```

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

```Python
import hydra
import torch
from omegaconf import OmegaConf
from dataclasses import dataclass

@dataclass
class Model:
    N: int

    def __post_init__(self):
        self.param = torch.nn.Parameter(torch.rand(self.N, self.N))

@dataclass
class Sampler:
    model: Model

    def sample(self, x):
        raise NotImplemented("Sample from the model")

model = Model(5)
sampler_cfg = OmegaConf.create({"_target_": "repro.Sampler"})
sampler = hydra.utils.instantiate(sampler_cfg, model=model)

# At this point `sampler.model` was converted back to it's config format rather than an instantiated model
```

## Expected Behavior
I would expect the argument to get passed in un-changed

**Comment by rsokl** [comment]
Pass `instantiate` the option `_convert_='object'`

```python
>>> hydra.utils.instantiate(sampler_cfg, model=model, _convert_='object')
Sampler(model=Model(N=5))
```

See: https://github.com/facebookresearch/hydra/issues/1719 for explanation

**Comment by lematt1991** [comment]
Thanks @rsokl, that is closer, but still not quite what I'm looking for.  In this case `sampler.model` will be instantiated, but it seems to be converting the model back to it's config and then re-instantiating it.  A slightly modified version of my above example:

```Python
import hydra
import torch
from omegaconf import OmegaConf
from dataclasses import dataclass

@dataclass
class Model:
    N: int

    def __post_init__(self):
        print("Instantiating model!")
        self.param = torch.nn.Parameter(torch.rand(self.N, self.N))

@dataclass
class Sampler:
    model: Model


    def sample(self, x):
        raise NotImplemented("Sample from the model")

model = Model(5)
sampler_cfg = OmegaConf.create({"_target_": "test.Sampler"})
sampler = hydra.utils.instantiate(sampler_cfg, model=model, _convert_="object")

diff = sampler.model.param - model.param
```

`sampler.model.param` is not equal to `model.param` because the model was re-instantiated.  In a real world example this is important if we first did `model.load_state_dict(...)` prior to passing it in to `Sampler`, since if it's re-instantiated then we will lose the pre-trained parameters.

**Comment by rsokl** [comment]
You can avoid this by leveraging hydra's ability to do recursive instantiation. I.e. don't instantiate `Model` ahead of time, instead create a config that will instantiate to `Model(5)` and pass that config to the `model` field of `sampler_cfg`.

Here is a minimal example; sorry for introducing hydra-zen here. It is by no means required, but it makes things a lot less verbose

```python
import hydra
from hydra_zen import builds
from dataclasses import dataclass

@dataclass
class Model:
    N: int

    def __post_init__(self):
        print("Instantiating model!")
        self.param = list(range(self.N))

@dataclass
class Sampler:
    model: Model


    def sample(self, x):
        raise NotImplemented("Sample from the model")

model = builds(Model, 5)
sampler_cfg = builds(Sampler, model=model)
```
```python
>>> sampler = hydra.utils.instantiate(sampler_cfg, model=model, _convert_="object")
Instantiating model!
>>> sampler
Sampler(model=Model(N=5))
```
This is what `sampler_cfg` looks like:
```python
>>> from hydra_zen import to_yaml
>>> print(to_yaml(sampler_cfg))
_target_: __main__.Sampler
model:
  _target_: __main__.Model
  _args_:
  - 5
```

**Comment by omry** [comment]
This is an artifact of using OmegaConf which considers instances of dataclasses config objects.
The solution as mentioned is to use `_convert_=object`, note that this can be specified in the config as well and is documented [here](https://hydra.cc/docs/advanced/instantiate_objects/overview/).
