### ISSUE TITLE
CUDA error: invalid device ordinal when using multirun

### ISSUE THREAD

**Issue by nuomizai** [facebookresearch/hydra#2602]
# CUDA error: invalid device ordinal when using --multirun
## Description
I got the error when I run my code with the multirun mode in hydra, but everything works fine when I remove the multirun config.
Here's what I got when I use the multirun mode:
```
(drqv2) liuchi@omnisky:~/zhaoyinuo/drqv2$ [2023-03-05 14:51:55,069][HYDRA] Submitit 'local' sweep output dir : ./exp_local
[2023-03-05 14:51:55,070][HYDRA]        #0 : device=1 agent=share_encoder_svea seed=0 task=cartpole_swingup
[2023-03-05 14:51:55,074][HYDRA]        #1 : device=1 agent=share_encoder_svea seed=1 task=cartpole_swingup
[2023-03-05 14:51:55,077][HYDRA]        #2 : device=1 agent=share_encoder_svea seed=2 task=cartpole_swingup
Error executing job with overrides: ['device=1', 'agent=share_encoder_svea', 'seed=0', 'task=cartpole_swingup']
Traceback (most recent call last):
  File "/home/liuchi/anaconda3/envs/drqv2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/home/liuchi/anaconda3/envs/drqv2/lib/python3.8/site-packages/hydra/_internal/utils.py", line 376, in <lambda>
    lambda: hydra.multirun(
  File "/home/liuchi/anaconda3/envs/drqv2/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 139, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/home/liuchi/anaconda3/envs/drqv2/lib/python3.8/site-packages/hydra/_internal/core_plugins/basic_sweeper.py", line 161, in sweep
    _ = r.return_value
  File "/home/liuchi/anaconda3/envs/drqv2/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
RuntimeError: Error instantiating 'algos.share_encoder_svea.SVEAAgent' : CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

My command is as follows:
```
python train.py --multirun device=1 agent=share_encoder_svea seed=0,1,2 task=cartpole_swingup
```

My hydra configuring file is as follows:

```
defaults:
  - _self_
  - task@_global_: quadruped_walk
  - agent@_global_: svea
  - override hydra/launcher: submitit_local

hydra:
  sweep:
    dir: ./exp_local
    subdir: ${now:%Y.%m.%d}/${hydra.job.override_dirname}/${seed}
  job:
    config:
      override_dirname:
        exclude_keys:
          - seed
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
```

Does anyone know what's wrong with my configuration/code?

**Comment by Zhylkaaa** [comment]
looking at you launcher config I am assuming you have only one gpu available, which is why device=1 might fail, because it's the second gpu. Maybe in your code you are not setting gpu for non multirun instances. Also check if launcher uses spawn for launching processes instead of fork.

You might consider running with `export CUDA_LAUNCH_BLOCKING=1 && <your script>` to give a bit more context about execution

**Comment by nuomizai** [comment]
> looking at you launcher config I am assuming you have only one gpu available, which is why device=1 might fail, because it's the second gpu. Maybe in your code you are not setting gpu for non multirun instances. Also check if launcher uses spawn for launching processes instead of fork.
> 
> You might consider running with `export HYDRA_FULL_ERROR=1 && <your script>` to give a bit more context about execution
> 
> you can try to run with `CUDA_VISIBLE_DEVICES=<gpu number> python train.py .....` to control which gpu is being used

Thanks for your reply. I have solved my problem.  There are 8 GPUs on my server. Therefore, changing the parameter `gpus_per_node` from 1 to 8 can solve this error report.
