### ISSUE TITLE
[Bug] Update to Hydra website failed to deploy

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#2645]
# 🐛 Bug
## Description

Recent updates to Hydra's website/docs (e.g. in PR #2643) were not successfully deployed to the [hydra.cc](https://hydra.cc) website.

## Details

There is a [`deploy_website.yaml`](https://github.com/facebookresearch/hydra/blob/ef4732da2a6c9422a85906417bd7809800487e2b/.github/workflows/deploy_website.yml) workflow that should result in the [hydra.cc](https://hydra.cc) website being updated after Hydra's `website` code is updated on github.

Recently this deployment has been failing.
For example, see these logs: https://github.com/facebookresearch/hydra/actions/runs/4747524644/jobs/8432544591

Here's the error message:
```text
[INFO] `git commit -m "Deploy website - based on ef4732da2a6c9422a85906417bd7809800487e2b"` code: 0
fatal: could not read Password for 'https://docusaurus-bot@github.com': No such device or address
[INFO] `git push --force origin gh-pages` code: 128
Error:  Running "git push" command failed. Does the GitHub user account you are using have push access to the repository?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

It seems like this is an issue with permissions.

**Comment by omry** [comment]
We will need help from the Meta OSS team here. As far as I remember they own the docusaurus bot.

**Comment by shagunsodhani** [comment]
This should be fixed now via https://github.com/facebookresearch/hydra/pull/2752.
