### ISSUE TITLE
I need to add two config directories to Hydra's search path

### ISSUE THREAD

**Issue by AGI-init** [facebookresearch/hydra#2646]
Adding a config directory via command line is easy with `-cd <path>`.

However, I need to add two paths.

I tried `-cd <path1> <path2>`, but that didn't work. 

Is this possible?

Thanks so much!!

**Comment by omry** [comment]
--config-dir can only add a single directory.
You can leverage hydra.search in your primary config to add multiple elements to the search path.
See [Config Search Path](https://hydra.cc/docs/advanced/search_path/)
