### ISSUE TITLE
[Feature Request] Load Omegaconf dictionary directly from `.hydra` output

### ISSUE THREAD

**Issue by matthewcarbone** [facebookresearch/hydra#2648]
# 🚀 Feature Request

Support for loading the `config` Omegaconf dictionary directly from the `.hydra` directory, without the usual bells and whistles.

## Motivation

I'm creating a pipeline which will require me to reload PyTorch Lightning models from disk. To do this, I really need to get the original Omegaconf dictionary back from the `.hydra` outputs. Specifically, the `.hydra/config.yaml` and `.hydra/overrides.yaml`. It should be possible to parse this manually, and of course you can just load the yaml file directly, but it would be good to have this support.

## Pitch

**Describe the solution you'd like**

```python
# pseudocode
def from_state(path: str) -> omegaconf.DictConfig:
    # `path` is absolute or relative, shouldn't matter 
    config = safe_load(path / "config.yaml")  # <- saved from a hydra run!
    overrides = safe_load(path / "overrides.yaml")
    # ... do hydra magic ...
    return config
```

**Describe alternatives you've considered**

I'm trying to use the usual `initialize` and `compose` API but there are some wacky path issues that I can't seem to figure out. It seems that Hydra is looking for the "primary config" which seems to somehow be relative to the package. Trying absolute paths fails with a specific error that only relative paths are accepted.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

Yes but I don't think I know enough about Hydra (yet!) to do so.

**Comment by matthewcarbone** [comment]
Quick followup: perhaps this isn't quite a Hydra problem? Maybe it's possible to just save the final processed `config.yaml` manually, with all the overrides included, then load it back via Omegaconf and use that with all of the Hydra instantiators... I will play around with this. Nevertheless, I do think exposing the overrides API a bit will be helpful and will streamline the process for re-instantiating objects from the `.hydra/config`s.

**Comment by abuyamin** [comment]
Is this related to [2459](https://github.com/facebookresearch/hydra/issues/2459)?

**Comment by omry** [comment]
Why would oyu need to save this file when Hydra is saving it already as config.yaml?

**Comment by matthewcarbone** [comment]
> Why would oyu need to save this file when Hydra is saving it already as config.yaml?

Because then I would have to deal with implementing Hydra's override syntax to update `config.yaml`, which I'd rather not reinvent.

**Comment by omry** [comment]
Hydra is saving the composed config. The overrides file is just for your information of how it was composed.
There is nothing to reinvent.

**Comment by matthewcarbone** [comment]
Ya you're right. I thought I checked and it wasn't but it indeed is saving the full config with the overrides included. Closing this now as a non issue. Thanks!
