### ISSUE TITLE
[Question] array_parallelism on local machine

### ISSUE THREAD

**Issue by sparisi** [facebookresearch/hydra#2659]
I need to run many jobs on my laptop (with Windows). They are very short but also many. I am using the same script with `submitit` thay I use for longer jobs on a cluster, and `AutoExecutor` works fine: it generates all rubs and starts in parallel all the jobs. I need to limit the number of jobs running in parallel, though, or my laptop crashes. I tried with
`executor.update_parameters(array_parallelism=1)` and `executor.update_parameters(slurm_array_parallelism=1)` but they don't do anything: all my 500 jobs start in parallel and my laptop freezes. 

Is there a way to limit the number of jobs that run in parallel on a local machine that does not use SLURM?

**Comment by odelalleau** [comment]
Might not match your setup exactly, but I believe that when using the `submitit_local` launcher, `tasks_per_node` might be what you need (I haven't tested it though). See doc at https://hydra.cc/docs/plugins/submitit_launcher/ (expand the "Discover the Local Launcher parameters" section).

**Comment by sparisi** [comment]
That worked, thanks!
