### ISSUE TITLE
[Bug] cant pass arg value that contains the char '=' 

### ISSUE THREAD

**Issue by giladw** [facebookresearch/hydra#266]
# 🐛 Bug

when passing argument value that contains the char '=' an error is thrown:
ValueError: too many values to unpack (expected 2)

## To reproduce

python example.py input_path=s3://rawData/year=2019/month=10/day=29/data_raw_joined.parquet 

** Stack trace/error message **
```
  File "/anaconda3/lib/python3.6/site-packages/hydra/_internal/config_loader.py", line 136, in _apply_defaults_overrides
    key, value = override.split("=")```
**Optional video**
If applicable, record a short [video](https://asciinema.org) with to help explain your problem.
You can also 

## Expected Behavior
I expect way to pass an argument that contains '=' in some other way

## System information
- 0.10.0
- macOS

**Comment by omry** [comment]
Hi Gilad,
Thanks for reporting.
This is a pretty simple bug to fix (I think). if you would like to try fixing it I can take a look at a PR.
(Please add tests as well if you do that).

I am traveling so it may take a few weeks before I can fix this).
