### ISSUE TITLE
[Bug] Checkpoint Loading with fairseq-hydra-train

### ISSUE THREAD

**Issue by flckv** [facebookresearch/hydra#2665]
# 🐛 Bug Checkpoint Loading with fairseq-hydra-train
## Description
srun` fairseq-hydra-train`  command to continue pretraining of wav2vec on librispeech following the steps [here](https://github.com/facebookresearch/fairseq/blob/main/examples/wav2vec/README.md#train-a-wav2vec-20-base-model) is not loading any checkpoint 

## To reproduce
I tried to load last checkpoint from sbatch .sh file:

srun fairseq-hydra-train distributed_training.distributed_world_size=4 +optimization.update_freq='[16]' --config-dir /home/flck/fairseq/examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech `--load-checkpoint-on-all-dp-ranks /home/flck/outputs/2023-05-22/07-19-53/checkpoints  `

but I got error:

fairseq-hydra-train: **error**: `unrecognized arguments:` --load-checkpoint-on-all-dp-ranks /home/flck/outputs/2023-05-22/07-19-53/checkpoints

tried also:

-  srun fairseq-hydra-train --run --multirun distributed_training.distributed_world_size=4 +optimization.update_freq='[16]' --config-dir /home/flck/fairseq/examples/wav2vec/config/pretraining --config-name wav2vec2_base_librispeech` --save_dir=/home/flck/outputs/2023-05-22/07-19-53/checkpoints --restore-file /home/flck/outputs/2023-05-22/07-19-53/checkpoints `

- `--restore_file`

with same error `unrecognized arguments`

How to load the checkpoint to continue pertaining? 

## Expected Behavior

load checkpoint to continue pre-training on multi node multi gpu

## System information
- **Hydra Version** :  Hydra 1.0.7
- **Python version** : 3.9.7
- **Virtual environment type and version** : = conda 4.11.0
- **Operating system** : Linux-5.4.204-ql-generic-12.0-19-x86_64-with-glibc2.31

## Additional context
#SBATCH --job-name=ol            # Job name
#SBATCH --output=/home/flck/output_.%A.txt   # Standard output and error log
#SBATCH --nodes=2                   # Run all processes on a single node     2
#SBATCH --ntasks=4                  # Run on a single CPU 4
#SBATCH --mem=128G                   # Total RAM to be used  128G 
#SBATCH --cpus-per-task=8          # Number of CPU cores #--cpus-per-task=8  
#SBATCH --gres=gpu:4                # Number of GPUs (per node) #151966: 4
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH --qos=gpu-8                 # To enable the use of up to 8 GPUs

**Comment by omry** [comment]
You should file this against fairseq.
