### ISSUE TITLE
[Feature Request] Make pydantic.BaseModel and ConfigStore.store() compatible

### ISSUE THREAD

**Issue by stwerner97** [facebookresearch/hydra#2667]
# 🚀 Feature Request Make ``pydantic.BaseModel`` and ``ConfigStore.store()`` compatible

It would be great, if I could store a ``pydantic.BaseModel``  in the ``ConfigStore``, for example, like this:

````python
class MyCustomExperiment(pydantic.BaseModel):
    model: SomeCustomModel
    dataset: SomeCustomDataset
    logging: str = "mlflow"
    lr: float = 1e-3
    

cs = ConfigStore.instance()
cs.store(name="my-custom-experiment", group="experiment", node=MyCustomExperiment)

````
This throws an ``omegaconf.errors.ValidationError: Input class 'MyCustomExperiment' is not a structured config. did you forget to decorate it as a dataclass?`` error. I am aware that ``store()`` works fine when I use the ``@dataclass`` decorator (builtin or pydantic). Still, it would be great to support ``BaseModel``, as these are (in my experience) quite common (and more so than ``pydantic.dataclass`` decorated classes).

## Pitch

**Describe the solution you'd like**
Support for ``pydantic.BaseModel`` in ``ConfigStore.store()``.

**Describe alternatives you've considered**
Using ``@dataclass`` decorators.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by Jasha10** [comment]
@stwerner97 note that the pydantic library exports a `pydantic.dataclasses` library that is similar to the standard library `dataclasses` library.
https://docs.pydantic.dev/latest/usage/dataclasses/
Although Hydra/OmegaConf don't have tests in place to guarantee compatibility, my limited experimentation has shown that the pydantic dataclasses are mostly compatible with Hydra.
See e.g. https://stackoverflow.com/questions/70639556

**Comment by stwerner97** [comment]
Thanks for the response @Jasha10 !

I am aware that ``hydra`` is compatible with ``pydantic.dataclasses`` and have used them together before. At the same time, I don't see a convenient way to use ``hydra`` with an existing codebase build on ``pydantic.BaseModel``.  I don't think we can expect users to refactor their code in such situations, so it would be great to support ``pydantic.BaseModel``.

As far as I know, there is a way to convert a ``pydantic.dataclass`` to a ``pydantic.BaseModel`` with the ``create_pydantic_model_from_dataclass`` method of ``pydantic.dataclasses``, but I am unsure whether this is possible the other way around.

**Comment by omry** [comment]
> I am aware that hydra is compatible with pydantic.dataclasses and have used them together before. At the same time, I don't see a convenient way to use hydra with an existing codebase build on pydantic.BaseModel. I don't think we can expect users to refactor their code in such situations, so it would be great to support pydantic.BaseModel.

Adding a new type of Structured Config is:
1. A feature request for OmegaConf, not Hydra.
2. A major change with a very large testing surface area.
3. Not worth it in this case given the built in dataclass compatibility in pydantic.

I am happy to discuss further but I don't think this will happen.

**Comment by stwerner97** [comment]
Thanks for the insights! :)
