### ISSUE TITLE
command not working 

### ISSUE THREAD

**Issue by abhijeet11yadav** [facebookresearch/hydra#2668]
#hydra -l msfadmin -p /usr/share/wordlists/rockyou.txt 192.168.9.48 -t 32 ssh
Hydra v9.1 (c) 2020 by van Hauser/THC & David Maciejak - Please do not use in military or secret service organizations, or for illegal purposes (this is non-binding, these *** ignore laws and ethics anyway).

Hydra (https://github.com/vanhauser-thc/thc-hydra) starting at 2023-05-31 11:31:47
[WARNING] Many SSH configurations limit the number of parallel tasks, it is recommended to reduce the tasks: use -t 4
[DATA] max 1 task per 1 server, overall 1 task, 1 login try (l:1/p:1), ~1 try per task
[DATA] attacking ssh://192.168.9.48:22/
1 of 1 target completed, 0 valid password found
Hydra (https://github.com/vanhauser-thc/thc-hydra) finished at 2023-05-31 11:31:54

i used -t 32 but hydra is not increasing tasks what i do

**Comment by omry** [comment]
wrong Hydra project.
