### ISSUE TITLE
[Bug] value interpolation does not work in list

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#267]
Value interpolation does not seem to work in list e.g.:

```
chckpnt_dirnames: 
  - ${base_dir}/${model.name}/
  - .
```

Doesn't replace `model.name` and `base_dir`

**Comment by omry** [comment]
Please provide a complete working example that reproduces that. I was not able to reproduce.

**Comment by YannDubs** [comment]
config.yaml:

```
test1: first
test2: second
tests:
  - ${test1}/${test2}
  - ${test1}
```

main.py:

```
@hydra.main(config_path="config.yaml")
def main(args):
    print(args.test1)
    print(args.test2)
    print(args.tests)
```

**Comment by YannDubs** [comment]
Mhhh it actually works but I was thinking of it as a real list:
```
print(args.tests)
print([args.tests[0], args.tests[1]])
print([i for i in args.tests])
```

out:

```
['${test1}/${test2}', '${test1}']
['first/second', 'first']
['${test1}/${test2}', '${test1}']
```

**Comment by omry** [comment]
If you are converting to a list this is no longer an OmegaConf object.

The proper way to convert to a primitive list is to use:
resolved_list = args.tests.to_container(resolve=True)

**Comment by omry** [comment]
Also, why do you even need to convert it to a primitive list?

**Comment by YannDubs** [comment]
Because I'm logging it and wanted to see the interpolated strings (which didn't work when just logging the OmegaConf object)
