### ISSUE TITLE
[Feature Request] Support a way to get the config file chosen via config itself

### ISSUE THREAD

**Issue by kunaltyagi** [facebookresearch/hydra#2691]
# 🚀 Feature Request

Allow support for either:
1. Resolver to find which preset is loaded by hydra
    ```yaml
    # file config/abc_config/nice_name.yaml
    type: ${hydra:this.filename}  # custom resolver, resolves to abc_config/nice_name or just nice_name
    ```
2. Support getting the information via some other means in the compose API

## Motivation

**Is your feature request related to a problem? Please describe.**

I noticed that my team is using `abs_config.material.type`, `xyz_config.loss.type` etc. to give names to presets which are loaded via `xyz_config/loss=blah`. This allows them to just search for `smthg.smthg.type` etc. and get the basic preset used.

I'd love if this was default and not something handled manually.

## Pitch

**Describe the solution you'd like**

One of the following:
* Some override or function which expands to the name of the file
* A way to get this data in an out of band manner and then inject into the config

**Describe alternatives you've considered**

Manually creating this metadata, but sometimes humans forget to change the value or forget to even add it

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
yes

**Comment by kunaltyagi** [comment]
I didn't find any documentation regarding that. I did try it and got an error:
```
File "/REDACTED/lib/python3.10/site-packages/omegaconf/base.py", line 676, in _resolve_node_interpolation
    raise InterpolationKeyError(f"Interpolation key '{inter_key}' not found")
omegaconf.errors.InterpolationKeyError: Interpolation key 'hydra.runtime.choices' not found
```

**Comment by odelalleau** [comment]
> Please note that I'm using the compose API

Oh, it's likely why it doesn't work. I'm not sure if/how it's possible to access this information when using the compose API.

**Comment by kunaltyagi** [comment]
Is it possible to get the `hydra.runtime.choices` using the compose API? I'm assuming it gets generated and is just discarded

**Comment by omry** [comment]
By default, the Compose API does not return the hydra config node.
See [return_hydra_config](https://hydra.cc/docs/advanced/compose_api/#api-documentation).

**Comment by kunaltyagi** [comment]
I feel that I should have seen that. 🤦🏾 

Thanks a lot @omry and @odelalleau
