### ISSUE TITLE
How is it possible to have the slurm launcher run a batch in detached mode?

### ISSUE THREAD

**Issue by alirezakazemipour** [facebookresearch/hydra#2703]
### Discussed in https://github.com/facebookresearch/hydra/discussions/2702

<div type='discussions-op-text'>

<sup>Originally posted by **alirezakazemipour** July  4, 2023</sup>
Hi everyone!
Thank you for your amazing project!
I wanted to know if it's possible to have the functionality of `slurm.sbatch` in submitit launcher so, that after running the program it's run in the background and it's `detached` from the terminal, let's say.</div>

**Comment by odelalleau** [comment]
Currently this is indeed not supported by the submitit launcher, but you should be able to achieve something similar with:
```bash
nohup python my_app.py ... >& /path/to/log &
```
