### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by labombatomba** [facebookresearch/hydra#2712]
# 🐛 Bug Ray launcher plugin passes unrecognized arguments
## Description

Using ray launcher plugin in combination with pytorch lightning seems to crash due to unrecongnized arguments  `hydra.run.dir` and `hydra.job.name` passed to  ray's `default_worker.py` script when using ddp as training strategy.

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** 
```
# launcher config
hydra:
  launcher:
    ray:
      remote:
        num_gpus: 2

# trainer config
trainer:
  strategy: ddp
  accelerator: gpu
  devices: 2
  num_nodes: 1
  sync_batchnorm: True
```
**

** 
[I 2023-07-14 12:24:30,105] A new study created in memory with name: no-name-2af8bbc4-a101-4f6b-946b-643b37bc2fd8
[2023-07-14 12:24:30,106][HYDRA] Study name: no-name-2af8bbc4-a101-4f6b-946b-643b37bc2fd8
[2023-07-14 12:24:30,106][HYDRA] Storage: None
[2023-07-14 12:24:30,106][HYDRA] Sampler: TPESampler
[2023-07-14 12:24:30,106][HYDRA] Directions: ['maximize']
[2023-07-14 12:24:30,582][HYDRA] Ray Launcher is launching 4 jobs, sweep output dir: multirun/2023-07-14/12-24-28
[2023-07-14 12:24:30,582][HYDRA] Initializing ray with config: {'address': None}
2023-07-14 12:24:34,543 INFO services.py:1456 -- View the Ray dashboard at http://127.0.0.1:8265
[2023-07-14 12:24:36,584][HYDRA]        #0 : module.optimizer.lr=0.01923279309285134 datamodule.batch_size=128 trainer=ddp hparams_search=optuna
[2023-07-14 12:24:37,529][HYDRA]        #1 : module.optimizer.lr=0.02771877908879536 datamodule.batch_size=64 trainer=ddp hparams_search=optuna
[2023-07-14 12:24:38,567][HYDRA]        #2 : module.optimizer.lr=0.06837794722369642 datamodule.batch_size=32 trainer=ddp hparams_search=optuna
[2023-07-14 12:24:39,499][HYDRA]        #3 : module.optimizer.lr=0.07730537949907618 datamodule.batch_size=32 trainer=ddp hparams_search=optuna
(_run_job pid=2677859) /home/thogallien/.conda/envs/hydra_ray/lib/python3.9/site-packages/pytorch_lightning/utilities/parsing.py:196: UserWarning: Attribute 'agg_metric' is an instance of `nn.Module` and is already saved during checkpointing. It is recommended to ignore them using `self.save_hyperparameters(ignore=['agg_metric'])`.
(_run_job pid=2677859)   rank_zero_warn(
(_run_job pid=2677859) Trainer already configured with model summary callbacks: [<class 'pytorch_lightning.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
(_run_job pid=2677859) GPU available: True (cuda), used: True
(_run_job pid=2677859) TPU available: False, using: 0 TPU cores
(_run_job pid=2677859) IPU available: False, using: 0 IPUs
(_run_job pid=2677859) HPU available: False, using: 0 HPUs
(_run_job pid=2677859) Initializing distributed: GLOBAL_RANK: 0, MEMBER: 1/2
(_run_job pid=2677859) usage: default_worker.py [-h] --node-ip-address NODE_IP_ADDRESS
(_run_job pid=2677859)                          --node-manager-port NODE_MANAGER_PORT
(_run_job pid=2677859)                          [--raylet-ip-address RAYLET_IP_ADDRESS]
(_run_job pid=2677859)                          --redis-address REDIS_ADDRESS --gcs-address
(_run_job pid=2677859)                          GCS_ADDRESS [--redis-password REDIS_PASSWORD]
(_run_job pid=2677859)                          --object-store-name OBJECT_STORE_NAME
(_run_job pid=2677859)                          [--raylet-name RAYLET_NAME]
(_run_job pid=2677859)                          [--logging-level {debug,info,warning,error,critical}]
(_run_job pid=2677859)                          [--logging-format LOGGING_FORMAT]
(_run_job pid=2677859)                          [--temp-dir TEMP_DIR] [--storage STORAGE]
(_run_job pid=2677859)                          [--load-code-from-local] [--use-pickle]
(_run_job pid=2677859)                          [--worker-type WORKER_TYPE] --metrics-agent-port
(_run_job pid=2677859)                          METRICS_AGENT_PORT
(_run_job pid=2677859)                          [--object-spilling-config OBJECT_SPILLING_CONFIG]
(_run_job pid=2677859)                          [--logging-rotate-bytes LOGGING_ROTATE_BYTES]
(_run_job pid=2677859)                          [--logging-rotate-backup-count LOGGING_ROTATE_BACKUP_COUNT]
(_run_job pid=2677859)                          [--runtime-env-hash RUNTIME_ENV_HASH] --startup-token
(_run_job pid=2677859)                          STARTUP_TOKEN [--ray-debugger-external]
(_run_job pid=2677859) default_worker.py: error: unrecognized arguments: hydra.run.dir="/home/thogallien/git/vsc_demo" hydra.job.name=train_ddp_process_1
**

## System information
- **Hydra Version** :  hydra-core 1.3.2/ hydra-optuna-sweeper 1.2.0/ hydra-ray-launcher 1.2.0
- **Python version** : Python 3.9.17
- **Virtual environment type and version** : conda version : 23.3.1
- **Operating system** : Ubunutu 22.04.1 (5.19.0-45-generic)

## Additional context
- **Pytorch Lightning**: pytorch-lightning  2.0.5

**Comment by addisonklinke** [comment]
@labombatomba did you end up finding a solution here? I have the same issue submitting DDP Lightning jobs to SageMaker (using a simple Hydra launcher I wrote to wrap SageMaker's `Estimator`)
