### ISSUE TITLE
hydra_submitit_launcher: `srun_args` not in `SlurmQueueConf`

### ISSUE THREAD

**Issue by pietrolesci** [facebookresearch/hydra#2719]
https://github.com/facebookresearch/hydra/blob/93f7ac617c34201b602afd6a838ae07658d62888/plugins/hydra_submitit_launcher/hydra_plugins/hydra_submitit_launcher/config.py#L77

Hi there,

I am trying to submit jobs to Slurm using the Submitit plugin. I am running the example in the example from the [docs](https://hydra.cc/docs/plugins/submitit_launcher/) and it seems to be an error with the parameters passed by Hydra to Submitit

```bash
hydra.errors.ConfigCompositionException: In 'config': ConfigKeyError raised while composing config:
Key 'srun_args' not in 'SlurmQueueConf'
    full_key: hydra.launcher.srun_args
    object_type=SlurmQueueConf
```

Any idea what is causing it?

---

Env info

```
- hydra-core==1.3.2
- hydra-submitit-launcher==1.2.0  
- submitit==1.4.5                                             
- python: 3.9.17
 ```

**Comment by DonneyF** [comment]
Came across this issue and found that the addition of `srun_args` to `SlurmQueueConf` came after version 1.2.0, which is still the latest on PyPI.

One can install the latest development version via `pip install "git+https://github.com/facebookresearch/hydra.git#egg=hydra-submitit-launcher&subdirectory=plugins/hydra_submitit_launcher"`
