### ISSUE TITLE
An elegant way to record the git HEAD commit SHA in the hydra.yaml [Feature Request]

### ISSUE THREAD

**Issue by zihaozou** [facebookresearch/hydra#2727]
# 🚀 Feature Request

let hydra automatically record the git HEAD commit SHA in the hydra.yaml if the root dir contains a .git folder.

## Motivation

**Is your feature request related to a problem? Please describe.**
I am trying to implement a git version check for my ML project. I want to save the git commit SHA in a way at the beginning of the run, and every rerun will check the git version and give a warning whenever the git version does not match.

Currently I don't find a good way to record the git SHA non-invasively. 

Here is what I do:
```
def check_git_version(cfg) -> None:
    """Checks if the git version is correct."""
    # save git version to current folder
    current_git_version = git.Repo(get_original_cwd()).head.object.hexsha
    cfg_git_version = cfg.get("git_version")
    if not cfg_git_version:
        log.info("Git version not found in config, skipping git version check...")
    else:
        log.info(
            "Git version found in config, checking if it matches the current git version..."
        )
        if cfg_git_version != current_git_version:
            raise Exception(
                f"Git version mismatch! <cfg.git_version={cfg_git_version}>\n<current_git_version={current_git_version}>\n"
                "Please checkout the correct git version!"
            )
    output_path = HydraConfig.get().run.dir
    OmegaConf.load(Path(output_path) / ".hydra" / "config.yaml")
    with open_dict(cfg):
        cfg.git_version = current_git_version
    OmegaConf.save(cfg, Path(output_path) / ".hydra" / "config.yaml")
    log.info("Git version check passed!")
```

## Pitch

**Describe the solution you'd like**
directly record the git SHA into the hydra.yaml before saving the config: https://github.com/facebookresearch/hydra/blob/93f7ac617c34201b602afd6a838ae07658d62888/hydra/core/utils.py#L179

**Describe alternatives you've considered**
at the `on_run_start` callback, let user optionally return an updated cfg: https://github.com/facebookresearch/hydra/blob/93f7ac617c34201b602afd6a838ae07658d62888/hydra/_internal/hydra.py#L117C25-L117C25

So I can implement a callback by my self to save the git SHA. 

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
Yes

**Comment by odelalleau** [comment]
I think it could make sense to save it within `hydra.runtime`, but I expect that it would get overridden when re-launching with the same config, so I'm not sure how would you achieve what you want much more easily than what you're doing now. But maybe I'm missing something.

Regarding the alternatives, what prevents you from writing an `on_run_start` callback that modifies the config in-place?

**Comment by zihaozou** [comment]
> I think it could make sense to save it within `hydra.runtime`, but I expect that it would get overridden when re-launching with the same config, so I'm not sure how would you achieve what you want much more easily than what you're doing now. But maybe I'm missing something.

Perhaps we should verify if the Git SHA attribute already exists in the configuration? However, I agree that this way may require additional effort.

> Regarding the alternative you mentioned, what prevents you from writing an `on_run_start` callback that modifies the config in-place?

It was my bad. I found that any changes to the config need to be made within the context of `open_dict`. If not, the modifications will fail to take effect and a warning will be raised - a detail I previously ignored.

My code is now working with the callback, but I think that an automatic recording of the Git SHA could be helpful in many contexts.

**Comment by odelalleau** [comment]
> Perhaps we should verify if the Git SHA attribute already exists in the configuration? However, I agree that this way may require additional effort.

It's not clear that it's the best thing to do though. I think there are other use cases where we'd want to know the *current* git commit, not the older one.

> My code is now working with the callback, but I think that an automatic recording of the Git SHA could be helpful in many contexts.

Good to hear you got it to work! :)
