### ISSUE TITLE
[Feature Request]Will hydra support Loguru?

### ISSUE THREAD

**Issue by wjrzm** [facebookresearch/hydra#2735]
# 🚀 Feature Request

## Motivation

When I use the function of printing log, I noticed that hydra can use the output of promised logging, because I usually use more loguru, would like to ask whether it will support loguru?

## Pitch

I hope loguru can be integrated into hydra so that I can use loguru for log printing

## Additional context
https://loguru.readthedocs.io/en/stable/overview.html

**Comment by odelalleau** [comment]
I think it's unlikely to be built-in, but what prevents you from using loguru in your Hydra-powered app?

**Comment by wjrzm** [comment]
> I think it's unlikely to be built-in, but what prevents you from using loguru in your Hydra-powered app?

I can use loguru throughout the file. I want to directly output the content in loguru format in the `outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}` folder, although it is also possible to customize the record format to achieve the same purpose.

**Comment by shagunsodhani** [comment]
Hey @wjrzm! As @odelalleau mentioned, its unlikely that loguru will be built in. I am closing this issue for now but feel free to re-open if you have follow up questions.

**Comment by marawanxmamdouh** [comment]
I see that you'd like to use Loguru for log printing with Hydra. While the provided code is a workaround, it's not necessarily the best practice for integration. However, it does work. You can achieve this behavior by using the following code:

```py
import os
import hydra
from loguru import logger as log

@hydra.main(version_base=None)
def hydra_loguru_init(_) -> None:
    hydra_path = hydra.core.hydra_config.HydraConfig.get().runtime.output_dir
    log.add(os.path.join(hydra_path, "main.log"))
```

**make sure to call the hydra_loguru_init function in the first line of your main function.**

**Comment by mmcdermott** [comment]
You might also be able to just have loguru re-pass all its logs to the normal logging library:

From https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging
```python
 class PropagateHandler(logging.Handler):
    def emit(self, record: logging.LogRecord) -> None:
        logging.getLogger(record.name).handle(record)

logger.add(PropagateHandler(), format="{message}")
```

**Comment by mmcdermott** [comment]
> I see that you'd like to use Loguru for log printing with Hydra. While the provided code is a workaround, it's not necessarily the best practice for integration. However, it does work. You can achieve this behavior by using the following code:
> 
> ```python
> import os
> import hydra
> from loguru import logger as log
> 
> @hydra.main(version_base=None)
> def hydra_loguru_init(_) -> None:
>     hydra_path = hydra.core.hydra_config.HydraConfig.get().runtime.output_dir
>     log.add(os.path.join(hydra_path, "main.log"))
> ```
> 
> **make sure to call the hydra_loguru_init function in the first line of your main function.**

I don't think this actually necessarily works in all cases; it seems like some logs in some nested files don't get caught by this solution, fyi. I'm still debugging, but for folks for whom this is essential, propagating to normal logging might be required.

**Comment by 2catycm** [comment]
> You might also be able to just have loguru re-pass all its logs to the normal logging library:
> 
> From https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging
> 
>  class PropagateHandler(logging.Handler):
>     def emit(self, record: logging.LogRecord) -> None:
>         logging.getLogger(record.name).handle(record)
> 
> logger.add(PropagateHandler(), format="{message}")

Bug encounters
```python
Traceback (most recent call last):
  File "/home/user/program_files/managers/conda/envs/yuequ/lib/python3.10/site-packages/loguru/_handler.py", line 200, in emit
    with self._protected_lock():
  File "/home/user/program_files/managers/conda/envs/yuequ/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/home/user/program_files/managers/conda/envs/yuequ/lib/python3.10/site-packages/loguru/_handler.py", line 114, in _protected_lock
    raise RuntimeError(
RuntimeError: Could not acquire internal lock because it was already in use (deadlock avoided). This likely happened because the logger was re-used inside a sink, a signal handler or a '__del__' method. This is not permitted because the logger and its handlers are not re-entrant.
--- End of logging error ---
```
