### ISSUE TITLE
[Bug] AttributeError: partially initialized module 'hydra' has no attribute 'main' (most likely due to a circular import)

### ISSUE THREAD

**Issue by user529481** [facebookresearch/hydra#2742]
# 🐛 Bug
## Description
Cannot run basic example. I read that it's recommended to run this in a virtual environment but when I try to read the section it just says:
```
This page crashed.
Cannot read properties of undefined (reading 'pathname')
```
Also my project doesn't call for a virtual environment, can it be used without one?

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
```pip install hydra-core --upgrade```

```py
import hydra

@hydra.main(config_path=".", config_name="config")
def run(cfg) -> None:
    print(cfg)
 
if __name__ == '__main__':
    run()
```
./config.yml
```
node:
    a: 1
    b: 2
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "/Users/me/Throwaways/foobar.py", line 1, in <module>
    import hydra
  File "/Users/me/Throwaways/hydra.py", line 3, in <module>
    @hydra.main(config_path='.', config_name='config')
AttributeError: partially initialized module 'hydra' has no attribute 'main' (most likely due to a circular import)
```

## Expected Behavior
Work

## System information
- **Hydra Version** :1.3.2  
- **Python Version** : 3.10
- **Virtual Environment** :  See note above
- **OS** : MacOS 13.5

## Additional context
NA

**Comment by odelalleau** [comment]
Looks like you created your own `hydra.py` files that gets imported instead of the actual `hydra` package.

Regarding

> I read that it's recommended to run this in a virtual environment but when I try to read the section it just says:
> This page crashed.
> Cannot read properties of undefined (reading 'pathname')

Can you clarify where exactly this is happening?

**Comment by shagunsodhani** [comment]
@user293811 Could you please provide more information ?
