### ISSUE TITLE
Notification reminder

### ISSUE THREAD

**Issue by phpmac** [facebookresearch/hydra#2743]
Run through the command line. If successful, is there any function similar to mail notification?

**Comment by odelalleau** [comment]
If you're using the submitit SLURM launcher, you should be able to pass arguments like `--mail-type` or `--mail-user` through the `additional_parameters` config option. Check the [SLURM doc](https://slurm.schedmd.com/sbatch.html) and the [submitit launcher doc](https://hydra.cc/docs/plugins/submitit_launcher/) for more details.

I'm not sure if there are other launchers with similar functionalities, you can look up the docs of Joblib / Ray / RQ to verify.

**Comment by phpmac** [comment]
Installation is complicated, SLURM

**Comment by shagunsodhani** [comment]
There is no builtin function for your use case. However, I have used https://pypi.org/project/notifiers/ in the past. That should work for you too. I am closing the issue for now. Feel free to re-open if you have any followup questions.
