### ISSUE TITLE
[Feature Request] Custom functions for sweepers in extended override syntax

### ISSUE THREAD

**Issue by alfsachin** [facebookresearch/hydra#2745]
# 🚀 Feature Request

Ability to define custom functions for sweepers in Hydra's extended override syntax

## Motivation

I am using hydra as a config system to run trading simulations.  
I'd like to leverage its multirun capabilities to run many instances in parallel over large date ranges. 

## Pitch

Being able to specify date & business date ranges via cmd line in --multirun scenarios, ie:

run_date=drange(20230109, 20230202)
run_date=bdrange(20230109, 20230202)

**Comment by odelalleau** [comment]
Currently a workaround is to define your own script that outputs a comma-separated list of values, then run
```shell
python my_app.py run_date=$(my_script) -m
```

**Comment by alfsachin** [comment]
Very interesting.  This seems very similar to resolvers?  Is it the same thing?

**Comment by odelalleau** [comment]
> Very interesting. This seems very similar to resolvers? Is it the same thing? Could you send me some links to the usage of the feature above (wiki docs or in code)

This is simply using shell features, this has nothing to do with Hydra (https://www.masteringunixshell.net/qa8/bash-how-to-get-result-of-command.html -- I used the `$()` syntax in my example)

**Comment by alfsachin** [comment]
Ahh thanks for this.  This method worked but ended up a bit clunky.  Another work around I found was by writing a custom sweeper and re-using the range function.
