### ISSUE TITLE
[Bug] Tutorial on changing current working directory igves unexpected output

### ISSUE THREAD

**Issue by matteobettini** [facebookresearch/hydra#2748]
# 🐛 Bug
## Description
When running the tutorial here https://hydra.cc/docs/tutorials/basic/running_your_app/working_directory/ I get a different output.

Basically for me `os.get_cwd()` is not changed by hydra.

## Checklist
- [X] I checked on the latest version of Hydra
- [X]  I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
import os
import hydra
from omegaconf import DictConfig

@hydra.main(version_base=None)
def my_app(cfg: DictConfig) -> None:
    print("Working directory : {}".format(os.getcwd()))
```

## Expected Behavior
Working directory : /home/omry/dev/hydra/outputs/2019-09-25/15-16-17

## Actual Behavior
working directory is the one where the script is

**Comment by odelalleau** [comment]
Thanks, the bug is actually that the tutorial needs to be updated: https://hydra.cc/docs/upgrades/1.1_to_1.2/changes_to_job_working_dir/

**Comment by shagunsodhani** [comment]
The code looks [fine](https://github.com/facebookresearch/hydra/blob/main/website/docs/tutorials/basic/running_your_app/3_working_directory.md?plain=1#L68). It seems the website is not deployed properly. Taking a look at it.

**Comment by shagunsodhani** [comment]
This should be fixed now via https://github.com/facebookresearch/hydra/pull/2752. Closing the issue. Feel free to re-open if you have followup questions.
