### ISSUE TITLE
Updating config value in the output/field directory

### ISSUE THREAD

**Issue by sebszyller** [facebookresearch/hydra#2749]
Hydra saves the config in current run's output directory; by default in `.hydra/config.yaml` alongside `hydra.yaml` and `overrides.yaml`.

Those are populated with the config constructed when the script is launched. 
However, there are cases where a config field is populated at runtime of the script, e.g. generate a random seed if not provided by the config/args.

I can write a function that manipulates those files myself but it would be nicer if hydra had a convenience function for overriding a value in the output config. I couldn't find anything in the docs but it doesn't mean there isn't one buried somewhere.

**Comment by odelalleau** [comment]
I doubt there's such a function since the purpose of this file is to dump the config used as input to the program. If you want to save something else, you're likely on your own.

**Comment by shagunsodhani** [comment]
+1 to what @odelalleau mentioned. I am closing the issue for now. Feel free to re-open if you have any follow up questions.
