### ISSUE TITLE
Configure experiments with deeper folder structure for experiments [Feature Request]

### ISSUE THREAD

**Issue by ga92xug** [facebookresearch/hydra#2755]
# 🚀 Feature Request

The configure experiments tab in the doc shows how you can configure experiments https://hydra.cc/docs/patterns/configuring_experiments/. But I don't think deep folder structures in a folder experiments are supported. I can add an experiment only if they are in the folder immediately under experiments if there are deep in the structure it does not work.

## example

`experiments/galaxy10.yaml`
```# @package _global_
defaults:
  - override /training: galaxy10-training
  - override /wandb: default

wandb:
  give_name: final_isic2019
  notes: droout0.0_se0.0`
  ```
  gives the desired output with: `python training/main.py +experiments=galaxy10`
  
  however:

`experiments/foo/galaxy10.yaml`
```# @package _global_
defaults:
  - override /training: galaxy10-training
  - override /wandb: default

wandb:
  give_name: final_isic2019
  notes: droout0.0_se0.0
  ```
  
  referencing this does not work with a slash(/) or a point (.).`python training/main.py +experiments/foo=galaxy10` give me `experiments/nas_common: galaxy10_match_performance` in the cfg.
  
  Am I missing how you can reference deeper folder structures, or is this behavior not supported? This makes a lot of sense in particular for larger projects with a lot of experiments.

**Comment by odelalleau** [comment]
It may be helpful to have a full example illustrating the problem (I don't understand where `nas_common` / `galaxy10_match_performance` are coming from in your example)

**Comment by ga92xug** [comment]
Sorry for the late reply. My initial feature request might have been a bit complicated. What I was aiming at is actually rather simple. Allow nesting in the experiment folder. So imagine this: a large project with 50+ experiments. The experiments are not completely distinct. They allow for a nested structuring. So take the example from the docs:

```
├── config.yaml
├── db
│   ├── mysql.yaml
│   └── sqlite.yaml
├── server
│   ├── apache.yaml
│   └── nginx.yaml
└── experiments
       ├── not_nested.yaml
       ├── group 1
       │  ├── g1_exp1.yaml
       │  └── g1_exp2.yaml
       └── group 2
             ├── g2_general_settings.yaml
             ├── group 2.1
             │  ├── g2.1_exp1.yaml
             │  └── g2.1_exp2.yaml
             ├── group 2.2
             ...
             └── group 2.3
             ...
```
So from my understanding only the experiment not_nested.yaml is supported. I would like to define groups of experiments, with some also having general settings (e.g. g2_general_settings.yaml) that apply for the whole group and some that are only for structuring like group1.

**Comment by odelalleau** [comment]
Someone mentioned elsewhere (can't remember exactly where) that this should work:
```
experiments=group_1/g1_exp1
```
=> would this solve your problem?

**Comment by ga92xug** [comment]
ah thanks!! it does not solve it completely, but I think it is good enough for my purposes. This might be a valuable addition to the docs.
