### ISSUE TITLE
[Question] Overriding nested configs from CLI

### ISSUE THREAD

**Issue by Merlo17** [facebookresearch/hydra#2798]
``Hello, 
I'm new to Hydra and didn't find a place to ask for help, so I hope this is ok. 

I'm currently running some experiments using multiple config groups. This is my directory tree:

```
├── config.yaml
├── experiment
│   ├── linear.yaml
│   ├── quadratic.yaml
│   └── seed_functions
│       ├── linear.yaml
│       └── mixed.yaml
├── logger
│   └── default_logger.yaml
└── model
    ├── base_prompt
    │   ├── basic_image.yaml
    │   ├── basic_text.yaml
    │   └── no_info.yaml
    ├── llama2-7b.yaml
    └── llava1.5-7b.yaml
```

I now want to run a set of experiments testing out different configurations, e.g. linear and mixed seed functions. For reference, the experiment level configs look like this: 
```
defaults:
  - seed_functions: mixed
  - _self_

name: "quadratic"

# Test points
min_points: -100
max_points: 100
num_points: 30
noise_std: 50
tolerance: 2500
```

To run the experiments, I set up a simple bash script to iterate over some values. However, when I try to override the seed functions (e.g. `python3 main.py experiment.seed_functions=linear`), the "linear" part gets picked up as a string, instead of being matched to the appropriate config file. I tried multiple versions of this, for example specifying the full path (/experiment/seed_function/linear), but I couldn't get it working. Am I doing this wrong? How can I set up an experiment iterating over multiple config files?

Thanks for the help.

**Comment by odelalleau** [comment]
Try `experiment/seed_functions=linear` (https://hydra.cc/docs/advanced/override_grammar/basic/#modifying-the-defaults-list)

**Comment by Merlo17** [comment]
Thanks! I missed the distinction between overriding defaults and normal configs!
