### ISSUE TITLE
[Bug] Cannot override a list from cli

### ISSUE THREAD

**Issue by najwalb** [facebookresearch/hydra#2799]
# 🐛 Bug
## Description
One of my hyper-parameters expects a list. I want to override this hyper-param from the command line. When I pass the value in the form 'key=[value1,value2]' as suggested by the error message, I get another error message saying 'zsh: no matches found: key=[value1,value2]' (see attached screenshot).

## Checklist
- [x ] I checked on the latest version of Hydra
- [ x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
Source file `./src/hydra-error.py`:

```
'''
    Sampling from a trained model.
'''
from omegaconf import DictConfig
import hydra

@hydra.main(version_base='1.1', config_path='../configs', config_name=f'default')
def main(cfg: DictConfig):
    print(f'epochs {cfg.general.wandb.checkpoint_epochs}\n')

if __name__ == '__main__':
    try:
        main()
    except Exception as e:
        print("main crashed. Error: %s", e)
```

Config file `./configs/experiment/hydra-error.yaml`:

```
# @package _global_
general:
  wandb: 
    checkpoint_epochs: [5,9] # epoch num for the checkpoint to use (resume/sample from)
```

Default config file under `./configs/default.yaml`:
```
defaults:
    - general : default

hydra:
    job:
        chdir: 'True'
    run:
        dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}

```

** Minimal Code/Config snippet to reproduce **

** Stack trace/error message **
```
// Paste the bad output here!
```

## Expected Behavior
Pass the value of the hyperparam as: general.wandb.checkpoint_epochs=[4,8]

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.11.5
- **Virtual environment type and version** : Conda 23.1.0
- **Operating system** : Mac OS Sonoma 14.1.1

## Additional context
Screenshot of the issue:
<img width="568" alt="Screenshot 2023-11-20 at 12 22 11" src="https://github.com/facebookresearch/hydra/assets/107994360/3eb19b77-5de9-4f5e-b10b-893600d884d5">

**Comment by Jasha10** [comment]
@najwalb try surrounding the argument with quotes.
Instead of this:
```
python3 hydra-error.py +experiment=hydra-error.yaml general.wandb.checkpoint_epochs=[4,8]
```
Try this:
```
python3 hydra-error.py +experiment=hydra-error.yaml 'general.wandb.checkpoint_epochs=[4,8]'
```
See also the docs on [Working with your shell](https://hydra.cc/docs/advanced/override_grammar/basic/#working-with-your-shell)

**Comment by najwalb** [comment]
That worked thanks!
