### ISSUE TITLE
[Bug] Hydra doesn't let me define a `sys.excepthook`.

### ISSUE THREAD

**Issue by kklein** [facebookresearch/hydra#2802]
# 🐛 Bug
## Description
I have been using [this approach](https://stackoverflow.com/a/16993115) to log uncaught exceptions to file for a while. Unfortunately, since using hydra with my custom logging, this doesn't work anymore. The failure mode is silent - the exceptions are simply not logged to file anymore while all other logging messages go through.

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

One can run the following script 

```python
import logging
import sys
from pathlib import Path

import hydra
from omegaconf import DictConfig

logger = logging.getLogger(__name__)


def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return

    logger.exception(
        "Uncaught exception", exc_info=(exc_type, exc_value, exc_traceback)
    )


def setup_logging():
    log_fpath = Path(__file__).parent / "log_w_hydra.txt"
    file_handler = logging.FileHandler(filename=log_fpath)
    logger.addHandler(file_handler)

    sys.excepthook = handle_exception


@hydra.main(version_base=None, config_path="conf", config_name="config")
def my_app(cfg: DictConfig) -> None:
    setup_logging()
    logger.error("Heyho")
    raise RuntimeError("Test unhandled")


if __name__ == "__main__":
    my_app()
```

with an arbitrary hydra config and investigate `"log_w_hydra.txt"`. Running `$ cat log_w_hydra.txt` returns the following:

```
Heyho
```

In other words, the exception has not been logged.

## Expected Behavior
When removing hydra from the script, i.e. running
```python
import logging
import sys
from pathlib import Path

logger = logging.getLogger(__name__)


def handle_exception(exc_type, exc_value, exc_traceback):
    if issubclass(exc_type, KeyboardInterrupt):
        sys.__excepthook__(exc_type, exc_value, exc_traceback)
        return

    logger.exception(
        "Uncaught exception", exc_info=(exc_type, exc_value, exc_traceback)
    )


def setup_logging():
    log_fpath = Path(__file__).parent / "log_wo_hydra.txt"
    file_handler = logging.FileHandler(filename=log_fpath)
    logger.addHandler(file_handler)

    sys.excepthook = handle_exception


if __name__ == "__main__":
    setup_logging()
    logger.error("Heyho")
    raise RuntimeError("Test unhandled")
```
I can investigate `"log_wo_hydra.txt"` and `$ cat log_wo_hydra.txt` does show the exception:

```
Heyho
Uncaught exception
Traceback (most recent call last):
  File "/Users/kevinklein/Code/.../logging_wo_hydra.py", line 29, in <module>
    raise RuntimeError("Test unhandled")
RuntimeError: Test unhandled
```

## System information
- **Hydra Version** :  hydra-core 1.3.2 (pyhd8ed1ab_0)
- **Python version** : 3.11.6
- **Virtual environment type and version** : micromamba 1.4.6
- **Operating system** : macOS 13.4.1

**Comment by odelalleau** [comment]
You'll have to disable Hydra's own error handling by setting `HYDRA_FULL_ERROR=1`

**Comment by kklein** [comment]
This fixed it - thanks a lot! :)
