### ISSUE TITLE
[Question] Can config sources with providers of `command-line` and `main` co-exists? 

### ISSUE THREAD

**Issue by SagiPolaczek** [facebookresearch/hydra#2822]
Hey there!
First - thanks for sharing and maintaining this package - really useful for us!

I have a concrete question that I could not find the answer in the docs:

When looking at the config sources in a run the involve hydra,  can we have the config sources' providers - one with `command-line` and one with `main` in the same time?

Another way asking it, if the following snippet will ever print `"BOOM"`? :)

```python

config_sources = HydraConfig.get()["runtime"]["config_sources"]
config_source = [
      cs for cs in config_sources if cs.get("provider", None) in ["command-line", "main"]
]

if len(config_source) > 1:
     print("BOOM")

```

Any additional explanation regarding the differences between the two - would be great!
(did a little search in the repo, but didn't find it in a reasonable time)

[Just for context - I'm trying to get the `config-path` value at runtime]

Thanks,
Sagi

**Comment by odelalleau** [comment]
I'm not very familiar with this ode but I just checked and yes you can have both when using `--config-dir`.

Using `--config-path` overrides the `"main"` provider.

**Comment by SagiPolaczek** [comment]
Thanks!
Indeed I encountered this scenario as you mentioned.

Not sure if thats an issue or the expected behavior, but calling a script using an entry point results a weird config source with the `"main"` provider:

```
[{'path': 'hydra.conf', 'schema': 'pkg', 'provider': 'hydra'}, {'path': 'path.inside.package', 'schema': 'pkg', 'provider': 'main'}, {'path': '/some/legit/path/to/scipt/that/uses/hydra/script.py', 'schema': 'file', 'provider': 'command-line'}, {'path': '', 'schema': 'structured', 'provider': 'schema'}]
```

Unfortunately I can't provide the real paths, but the point is that using an entry point, the config source with the `"main" ` provider results with `"path"` equals to the path inside the python package with `.` as separators while the config source with `"command-line"` as a provider has the real absolute path.
