### ISSUE TITLE
[Bug] .get() default value doesn't work on blank values in config. (not sure if the is expected or not)

### ISSUE THREAD

**Issue by natephysics** [facebookresearch/hydra#2825]
# 🐛 Bug
## Description
If a property in the config is left blank (let's use "country" for example), when calling cfg.get("country", "Amerika"), I get None despite the default value. 

## Checklist
- [X] I checked on the latest version of Hydra (1.3.2)
- [X] I created a minimal repo: https://github.com/natephysics/hydra_error_report.

## To reproduce
config.yaml:
```
country:
```

my_test.py
```
import hydra


@hydra.main(version_base="1.3", config_path=".", config_name="config.yaml")
def my_app(cfg):
    print(type(cfg.get("country", "Amerika")))


if __name__ == "__main__":
    my_app()
```

`python -m my_test.py` returns NoneType. 

## Expected Behavior
I'd expect it would return the default in this case. But maybe this is a faulty assumption.

## System information
- **Hydra Version** :  1.3.2
- **Python version** : 3.10.12
- **Operating system** : Ubuntu 22.04

**Comment by odelalleau** [comment]
This is not a bug, `cfg.get()` returns the default value when the key does *not* exist in the config. If it exists and has a `None` value (as in your example) then it will return this value.

This behavior is similar to a Python `dict`: `{"country": None}.get("country", "US")` will return `None`.

What you want to achieve would instead be written `"Amerika" if cfg.country is None else cfg.country`.
