### ISSUE TITLE
[Bug] Changing variable in a config group used more than once

### ISSUE THREAD

**Issue by rhajou** [facebookresearch/hydra#2837]
# 🐛 Bug
## Description
I have a config group used more than once in my main config file and I want to change one variable in it
 
## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

```
├--- config.yaml
├── db
   ├--mysql.yaml
   └--sqlite.yaml
   └--postgres.yaml
```
```
# db/mysql.yaml
name: mysql
```
and 

```
# db/sqlite.yaml
name: sqlite
```
and 

```
# server/db/postgres.yaml
name: postgres
```

```
# config.yaml
defaults:
  - db@source: mysql
  - db@destination: sqlite
```

with a simple code as follow, it will work to change the config group assigned to source. 
`python my_app.py db@source=postgres`

But when I try this: `python my_app.py db@source.name=toto` it will get the following error:

** Stack trace/error message **
```
hydra.errors.ConfigCompositionException: Could not override 'db@source.name'.
Did you mean to override one of db@source, db@destination?
To append to your default list use +db@source.name=toto
```

## Expected Behavior
The expected behavior is to use the mysql yaml file but with changed name to `toto`. 
(I simplified the example for clarity)

## System information
- **Hydra Version** :  1.3
- **Python version** : 3.11.2

**Comment by odelalleau** [comment]
I don't think this is a bug.

There are two kinds of command line overrides:
1. Defaults list overrides: used to change which configs to compose
2. Config keys overrides: used to modify the config *after composition*

But (AFAIK) it's not possible to modify a config *before* it is composed.

In the example you provided, the proper syntax would be `python my_app.py source.name=toto` (second type of override above -- note that I didn't test it so let me know if it doesn't work for you).
