### ISSUE TITLE
Selecting multiple configs from a config group using structured configs

### ISSUE THREAD

**Issue by serhez** [facebookresearch/hydra#2859]
# 🐛 Bug
## Description
I am trying to implement the [example given in the docs](https://hydra.cc/docs/patterns/select_multiple_configs_from_config_group/) to select multiple configs from a config group. My use case is that I have experiments where I test a list of methods against a list of benchmarks. Each method and each benchmark has a config class which I manage through hydra. Thus, I would like to configure my experiments through hydra and be able to provide a list of experiment configs and another list of benchmark configs.

To figure this out, I started with a toy example I provide below, which is similar to the example given in the docs; this works. However, when I try to add structured configs it gives me the error `Merge error: B2 is not a subclass of B1.`. I have tried several ways and nothing works. I would like to make structured configs work in this case because I am already using them throughout my whole code-base, which is quite extensive.

Thanks for the help!

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **

`test.py`
```python
from dataclasses import MISSING, dataclass
from typing import Any, List

import hydra
from hydra.core.config_store import ConfigStore
from mloggers import ConsoleLogger


@dataclass(kw_only=True)
class B:
    arg1: int = MISSING
    arg2: str = "default"


@dataclass(kw_only=True)
class B1(B):
    arg1: int = 1
    arg3: str = "default"


@dataclass(kw_only=True)
class B2(B):
    arg1: int = 2
    arg3: str = "default"


@dataclass(kw_only=True)
class C:
    bs: Any = MISSING
    arg1: int = 42


@hydra.main(version_base=None, config_path="test_confs", config_name="test")
def main(config: C) -> None:
    # Setting up loggers
    logger = ConsoleLogger()
    logger.debug(config)


if __name__ == "__main__":
    cs = ConfigStore.instance()
    cs.store(group="bs", name="base_b1", node=B1)
    cs.store(group="bs", name="base_b2", node=B2)
    cs.store(name="base_c", node=C)

    main()
```

`test_confs/test.yaml`
```yaml
---
defaults:
  - bs:
    - b1
    - b2
```

`test_confs/bs/b1.yaml`
```yaml
---
defaults:
  - _self_
  - base_b1

arg1: 1 
arg3: specialB1
```

`test_confs/bs/b2.yaml`
```yaml
---
defaults:
  - _self_
  - base_b2

arg1: 2
arg3: specialB2
```

However, if I don't use the structured configs from the Python config classes, then it works without errors. Like this:

`test_confs/bs/b1.yaml`
```yaml
b1:
  arg1: 1 
  arg3: specialB1
```

`test_confs/bs/b2.yaml`
```yaml
b2:
  arg1: 2
  arg3: specialB2
```

** Stack trace/error message **
```
Merge error: B2 is not a subclass of B1.
```
Only thrown in the first provided versions of `b1.yaml` and `b2.yaml`.

## Expected Behavior
I would like the setup to work also when integrating with the config classes defined in the Python code.

## System information
- **Hydra Version** :  `hydra-core==1.3.2`
- **Python version** :  3.11.7
- **Virtual environment type and version** :  `conda 22.9.0`
- **Operating system** :  MacOS

## Additional context
None.

**Comment by odelalleau** [comment]
I haven't looked at it very closely but this looks very similar to #2849 => can you check if https://github.com/facebookresearch/hydra/issues/2849#issuecomment-1947003107 would help?

**Comment by serhez** [comment]
Apologies for not finding that one! It does indeed solve my issue. Thanks! 😄
