### ISSUE TITLE
[Feature Request] How to replace the config_name in bash.

### ISSUE THREAD

**Issue by gasvn** [facebookresearch/hydra#2868]
Thanks for this great config system.
I am wondering that if it's possible to change the default config_name in bash.

Suppose in python I have
```python
@hydra.main(version_base=None, config_path="../configs", config_name="config1.yaml")
```
Now I want to change config1.yaml to config2.yaml in bash, like this:
```bash
python main.py config_name=config2.yaml
```
Is there a way to do so?

**Comment by SagiPolaczek** [comment]
```
python main.py --config-name=config2
```
Should work.
