### ISSUE TITLE
[Bug] don't support Chinese

### ISSUE THREAD

**Issue by Agoniii** [facebookresearch/hydra#2891]
# 🐛 Bug
## Description
```
  File "/usr/local/lib/python3.10/dist-packages/hydra/core/override_parser/overrides_parser.py", line 96, in parse_overrides
    raise OverrideParseException(
hydra.errors.OverrideParseException: LexerNoViableAltException: prompts=[介绍一下你。]
```

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce

** Minimal Code/Config snippet to reproduce **
```
git clone https://github.com/facebookresearch/hydra
cd hydra/examples/tutorials/basic/your_first_hydra_app/2_config_file
python my_app.py db.user='李明'
```

** Stack trace/error message **
```
LexerNoViableAltException: db.user=李明
                                   ^
See https://hydra.cc/docs/1.2/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

```

## System information
- **Hydra Version** :  1.3.2
- **Python version** :  3.10.12
- **Virtual environment type and version** : 
- **Operating system** :

**Comment by odelalleau** [comment]
This is because your shell consumes the quotes (see https://hydra.cc/docs/advanced/override_grammar/basic/#working-with-your-shell)

Something like `'db.user="李明"' should work.
