### ISSUE TITLE
[Bug] App help takes a lot of time to be generated

### ISSUE THREAD

**Issue by giuliovn** [facebookresearch/hydra#2907]
# 🐛 Bug
## Description
I am not sure this can be called a bug, please suggest a better label if not.

I am using hydra in a project and it helped to manage a huge configuration in a very clean and efficient way.
The problem is that people using it want to have an help in the entrypoint script to be aware at least of the parameters that are commonly overridden from the command line, but generating the help (the default one or with a minimal template I created following [the documentation](https://hydra.cc/docs/configure_hydra/app_help/) takes 1+ minute.

To manage the virtual environment I am using [rye](https://rye.astral.sh/), which creates a `.venv/` directory inside the project.
If I understand well, when generating the help, hydra looks recursively (twice) for all the yaml files from the root of the project, including the `.venv/` directory in my case.

Without understanding much of what happens underneath, sounds like that looking in the hydra configuration files and whatever is defined in the `default_list` should be enough.

## Checklist
- [X] I checked on the latest version of Hydra
- [X] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
1. Clone https://github.com/giuliovn/mario.
2. Follow the instruction in the repo's README.

Running `python main.py --help` takes around 15 seconds, even though the configuration is basically empty.

## Expected Behavior
Be faster, since the config object creation is really fast.
As an alternative, is there a way to bypass hydra's app help and call a custom function?

## System information
- **Hydra Version** :  git+https://github.com/facebookresearch/hydra.git@2e682d84e789d82dd11ab1f329f2dd1966fa6b54
- **Python version** :  3.12
- **Virtual environment type and version** :  rye (uses uv)
- **Operating system** :  Linux

## Additional context
I am installing hydra from main to avoid conflicts with antlr, which is used by another module.

**Comment by odelalleau** [comment]
Indeed that doesn't sound great...

> As an alternative, is there a way to bypass hydra's app help and call a custom function?

Looks like the code calls `hydra.app_help()` => you could try overriding it manually (untested):

```python

@hydra.main()
def main(cfg):
    ...

if __name__ == "__main__":
  hydra.app_help = my_custom_help_function
  main()
```

**Comment by giuliovn** [comment]
Thank you @odelalleau, I think I will go with your approach.
Just in case it will help someone else, I am using structured configs and I am going to turn the config object to a json schema and then probably filter the part that are menat to be overridden.

Something like that:
```python
import hydra
from hydra._internal.hydra import Hydra
from hydra.core.config_store import ConfigStore
from omegaconf import OmegaConf
from pydantic import TypeAdapter
import warnings

from whatever import YourConfig

cs = ConfigStore.instance()
cs.store(
    name="config_class",
    node=YourConfig,
)

@hydra.main(
    version_base=None,
    config_path=".",
    config_name="conf",
)
def main(_cfg: YourConfig):
    print(f"Config:\n{OmegaConf.to_yaml(_cfg, resolve=True)}")

def custom_app_help(*args, **kwargs):
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        schema = TypeAdapter(YourConfig).json_schema()
       # optionally, do stuff with the schema
        print(schema)

if __name__ == "__main__":
    Hydra.app_help = custom_app_help
    main()
```

**Comment by omry** [comment]
Your problem is likely that the config path is at ".".
Hydra help will scan for config groups.
Move your configs to a dedicated conf directory and change the config path.

**Comment by omry** [comment]
Please reopen if moving your if it doesn't help.

**Comment by giuliovn** [comment]
Thanks, indeed moving the root configuration file to a subdirectory make it much faster.
