### ISSUE TITLE
hydra instantiate class with tuple parameters

### ISSUE THREAD

**Issue by hutslib** [facebookresearch/hydra#2918]
how to use hydra instantiate function to create a singleton of a class which has to pass in a parameter with tuple[ float, float, float] type?

example

```
class setcloor():
    color: tuple[float, float, float] = (1.0, 1.0, 1.0)

config:
color: [1.0,1.0,1.0]
do not instantiate this correctly
```

**Comment by Zhylkaaa** [comment]
Have you tried custom omegaconfig resolvers to just cast this list into the tuple? something like `OmegaConf.register_new_resolver("tuple", lambda x: tuple(x))` and in config specify: `color: ${tuple:[1.0,1.0,1.0]}`. 
refer to: https://omegaconf.readthedocs.io/en/2.3_branch/custom_resolvers.html#custom-resolvers

**Comment by hutslib** [comment]
Nice that helps.
