### ISSUE TITLE
[Feature Request] Enable full error output via config

### ISSUE THREAD

**Issue by gfringeli** [facebookresearch/hydra#2923]
# 🚀 Feature Request

Enable full error output via config instead of only by setting environment variable `HYDRA_FULL_ERROR=1`

## Motivation

**Is your feature request related to a problem? Please describe.**
We use a third party that detects failed runs of our Python scripts by checking for uncaught exceptions. However, by default hydra will shadow exceptions by catching them and logging a hydra-specific error message. As this won't lead to an uncaught exception our third party tool won't be able to catch a failed run.
It's possible to get back the uncaught exception by setting environment variable `HYDRA_FULL_ERROR=1`. Unfortunately, this is tedious as it requires either
- setting the environment variable in the execution environment every time a script is run (or at least when the environment is set up), or
- using workarounds like `os.environ.setdefault("HYDRA_FULL_ERROR", "1")` in the scripts themselves.

Related to https://github.com/facebookresearch/hydra/issues/2590

## Pitch

**Describe the solution you'd like**
Set the error output behavior via regular hydra configs, e.g. `hydra.job.full_error`.

**Describe alternatives you've considered**
None

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))
To be decided

## Additional context
None

**Comment by omry** [comment]
Thanks for the suggestion.
This is not possible because the handling of the errors is happening long before the config is available.

**Comment by gfringeli** [comment]
Thanks for your quick reply.
Makes sense. Of course, controlling the error behavior with that config option wouldn't work for anything that happens before the config has been determined. It could be taken into account after having the configs available. But that also does not feel like a nice solution. We will go with setting the environment variable in our scripts for now.

**Comment by rmminusrslash** [comment]
I also ran into this issue. Catching and raising the error is somewhat unexpected. you could log it so that it is not lost, but raising it even if the user wants to catch and treat it should perhaps not be the default?
