### ISSUE TITLE
[Bug] Output directory creation is not atomic

### ISSUE THREAD

**Issue by alexanderwerning** [facebookresearch/hydra#2925]
# 🐛 Bug
## Description
The creation of the output directory is not atomic. If several runs start at exactly the same time, they will share their output directories.
I encountered the problem because the slurm scheduler on my cluster started several jobs simultaneously. Since the checkpoints and log files are in the same versionX directory, it is not clear to me how to determine which belongs to which experiment.

## Checklist
- [x] I checked on the latest version of Hydra
- [ ] I created a minimal repro (See [this](https://stackoverflow.com/help/minimal-reproducible-example) for tips).

## To reproduce
Start several experiment runs simultaneously.

## Expected Behavior
I expect the directory creation operation to be atomic and create exactly one directory per run. The filesystem usually allows this type of operation (I assume mkdir with exist_ok=False would fix this).

## System information
- **Hydra Version** :   1.3.2
- **Python version** :  3.11.3
- **Virtual environment type and version** :  N/A
- **Operating system** :  Linux

**Comment by omry** [comment]
The directory creation cannot be atomic across different jobs and there is nothing Hydra can do about it.
If this is a concern to you, you can [customize the run dir ](https://hydra.cc/docs/configure_hydra/workdir/)to use a higher resolution timestamp.
Check the [strftime format codes table](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)
In particular, you can use `%f` (Microsecond as a decimal number, zero-padded to 6 digits).

Maybe something like this.
```yaml
hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S.%f}
    subdir: ${hydra.job.num}
```
