### ISSUE TITLE
[Feature Request] Add json parsing functions to convert

### ISSUE THREAD

**Issue by jesszzzz** [facebookresearch/hydra#2929]
# 🚀 Feature Request

Add a json_str parser function that takes an object and converts it into a JSON string representation of the object
     

## Motivation

**Is your feature request related to a problem? Please describe.**

Some of our config values are JSON strings that are unstructured to maintain flexibility, eg.
```
@dataclass
SomeConfig:
     metadata: str  # this should be a json-formatted string)
     # other attributes
```

Overriding `metadata` is pretty difficult since there are so many quotes in JSON strings that need to escaped. Being able to specify the object and have the hydra parser convert it into a JSON-formatted string would make this much more convenient.

## Pitch

Enable an override function like `++metadata=json_str({a: 1, b: {c: ['d', 'e']}}` that would set the `metadata` value to the JSON representation of the object (in this case, `'{"a": 1, "b": {"c": ["d", "e"]}}'`)

**Describe alternatives you've considered**
Having `metadata` be `Any` and doing the conversion at runtime, would prefer to do the json conversion as early as possible to reduce having to do it every time the field is accessed.
Passing in a correctly formatted json string, this is just more tedious

**Are you willing to open a pull request?** Yes

**Comment by omry** [comment]
Have you considered using OmegaConf interpolation to convert a node to JSON on access?
In the example below, structured_metadata is the metadata in a dict format (for example) and your own function would take that node and conver it to json:
```python
@dataclass
SomeConfig:
     metadata: str  = "${my_json_converter:${.structured_metadata}}"
     structured_metadata: Optional[Any] = None
     # other attributes

```

**Comment by jesszzzz** [comment]
It's a cool idea, but relies on the tool author to set this up correctly, and the tool consumer to know/find this relationship between `metadata` and `structured_metadata`.  Having a json_str parsing function would give the tool consumer a more consistent experience.

**Comment by omry** [comment]
My position is that it's not useful enough to be included.
