### ISSUE TITLE
Adding class-dir to @hydra.main annotation?

### ISSUE THREAD

**Issue by dbogdoll** [facebookresearch/hydra#2933]
To separate between the source code and the runtime artifacts, I can use the --class-name or -cn on the command line.
But I can't specify this in the hydra.main annotation. Is there a reason why not? How could I achieve this.

Imagine I have my app code put into a docker container (as a wheel or a plain directory with python sources) and I want
to mount the config directory to the docker container. In this case the --class-path which resolves the location of the config
relative to the python file won't help me. In generell outside of rapid prototyping, I don't think its a good idea compute paths
to runtime artifacts from the location of source code files. As depending how I have installed my module, the source code
location is more or less unknown.

**Comment by omry** [comment]
There is no mechanism to provide it to the decoration.
You can also add your config root to the config search path as documented [here](https://hydra.cc/docs/advanced/search_path/).

You can also the environment variable `HYDRA_MAIN_MODULE` to override the detected main module, but this is a bigger hammer and I'd suggest you use the first approach.
