### ISSUE TITLE
Why it must using = to specific value of arguemnts

### ISSUE THREAD

**Issue by MonolithFoundation** [facebookresearch/hydra#2947]
Hi, I have a query regarding Hydra.

It is an excellent library; however, I am somewhat perplexed as to why there must be an '=' for the arguments instead of just a space or support for both.

The confusion lies in the fact that typically, we utilize Hydra in the terminal, correct? For certain terminals, when an '=' is set after the arguments, tab functionality is simply unavailable.

**Comment by omry** [comment]
This is a design decision that is going nowhere.
As for Tab Completion, Hydra [supports](https://hydra.cc/docs/tutorials/basic/running_your_app/tab_completion/) bash, zsh and fish.
