### ISSUE TITLE
[Feature Request] Get the command line info to rerun an entire sweep. 

### ISSUE THREAD

**Issue by yuandong-tian** [facebookresearch/hydra#298]
# 🚀 Feature Request

Get the command line info to rerun an entire sweep. 

## Motivation

Currently .hydra/override.yaml can enable reproduction of a single run but not the entire sweep. It would be ideal if the hydra could record the sweep command in the folder. 

Doing it manually is possible (e.g., by adding some hacks before hydra decorated function). But since the hacky code doesn't know which directory the job would be running, it is a bit awkward to get information saved in that folder. 

## Pitch

Ideally hydra would also have a ./hydra/summary.yaml file in the sweep folder that have all the sweep level information, including the command line.

**Comment by omry** [comment]
From the PR closing this:

The sweep config file contains, among other things, the command line used in the run.
This run:
```
$ python examples/tutorial/3_config_groups/my_app.py -m db=mysql,postgresql hydra/help=default
```
Would result in this in `multirun/.../.../sweep.yaml`:
```yaml
hydra:
  overrides:
    hydra:
    - hydra/help=default
    task:
    - db=mysql,postgresql
```
