### ISSUE TITLE
[Feature Request] Running a script at end of sweep

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#311]
# 🚀 Feature Request

Let the user specify (e.g. in hydra config) a script to run at the end of each sweeps. Usually we run sweeps and then would like to run a script that aggregates the results from all experiments / make plots. It would be handy not to have to do it manually at the end of the sweep.

Additional note : I think that there should also be an additional parameter to say whether this script should run only if there were no errors/timeouts, or whether to do it once all the jobs finished regardless of timeouts.

**Comment by YannDubs** [comment]
Sorry, thinking more carefully this should probably not be implemented in hydra actually, as this can easily be done using `;` or `&&` in bash ...

**Comment by omry** [comment]
I agree that this is probably handled by the user manually (you don't always want to visualize, for example).

There could be user use cases that can benefit from some kind of event mechanism that will allow the user to register hooks for specific events.
for now I am delaying this though, I think once there is an experimentation tracking plugin this will crystallize a bit more.
