### ISSUE TITLE
Add option to not create .hydra in output directory

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#324]
In some cases users are not interested in the generation of config.yaml, hydra.yaml etc.
add an option to opt out.

**Comment by exic** [comment]
I have my applications in docker containers and don't need that either, also I have to say that the whole output directory feature surprised me (especially changing my working directory), since I was only expecting it to do configuration things. So I'd vote to actually make it opt in. :-)

**Comment by omry** [comment]
Hi Jonas,
The working directory feature integrates with other core features like multi-run (where you run your app multiple time with a different configuration with a single command).
I thought hard about this, and while I understand it's surprising it's here to stay :).

Working directory can be fully customized, see [this](https://hydra.cc/docs/configure_hydra/intro).
You can change it to `.` or to `/tmp` for example.

**Comment by exic** [comment]
Yeah I already changed it to `.` to keep my app's behavior, `/tmp` would be better to avoid "pollution" of the main dir, but then I'd probably have to change back to the `get_original_cwd` directory or change all the paths in my program, right?

**Comment by omry** [comment]
I missed your question, sorry.
See [this](https://hydra.cc/docs/tutorial/working_directory#original-working-directory) for ways to access files in the original working directory.

**Comment by benjamindkilleen** [comment]
The automatic output dirs is the **main** reason I use this project, and I especially like the option to set the output_dir to /tmp, for debugging purposes (which I didn't think of until seeing this thread). There are many times I *know* something will fail, but I want to see it's output anyway. This obviously results in many useless output dirs, requiring cleanup.

I could imagine a --debug or --tmp option for hydra that sets this option would be helpful, for people who miss this issue as well as just ease of use.

**Comment by omry** [comment]
Thanks for your feedback @benjamindkilleen.
This capability is not going anywhere. However - in some scenarios automatically changing the cwd to the output directory is 
getting in the way.
I am planning to make things more configurable in that area and in the long term maybe even change the default behavior to not chdir into the output directory (while still allowing it to be easily enabled).

See #910 for general plan in this area (which may yet change, I am still thinking about all this).
