### ISSUE TITLE
[Feature Request] disable output directory

### ISSUE THREAD

**Issue by shacoshe** [facebookresearch/hydra#327]
# 🚀 Feature Request

## Motivation
i am using hydra command line feature to start my web server in more flexible way.
an output directory for each server start is not necessary for web application 

**Is your feature request related to a problem? Please describe.**

## Pitch

i would be nice if i could configure it in my base config. something that will be hidden to the user of my application

hydra: 
    output: false

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

**Comment by omry** [comment]
I already created #324
