### ISSUE TITLE
[Bug] Unable to return any value from main function

### ISSUE THREAD

**Issue by arisliang** [facebookresearch/hydra#332]
# 🐛 Bug

Once marked with @hydra.main, the function always returns None.

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
@hydra.main(config_path='config.yaml')
def main(cfg):
    return 1

if __name__ == '__main__':
    always_none = main()
    print(always_none)   # always print None
```

## Expected Behavior

Expects value to be returned like the usual functions do.

## System information
- Hydra 0.11.2

- Python 3.6.6

- Ubuntu 18.04

**Comment by omry** [comment]
Hi,
It seems like you are trying to use hydra.main in a way it was not designed for.
hydra.main is designed to be use as the app entry point.

Can you share more info on the use case? what are you trying to achieve?

**Comment by omry** [comment]
Can you join the chat to discuss this? it will be easier.

**Comment by arisliang** [comment]
Mainly I try to use hydra as a way to parse configuration (like argparse), then pass the result to other functions.

Intuitively, the app entry point is still a function, so it may be expected to return value. It's a little surprising that it doesn't have that.

**Comment by omry** [comment]
Please join the chat.
https://hydra-framework.zulipchat.com/

**Comment by omry** [comment]
Per our discussion:
This is by design. In multirun that function actually runs multiple times so it's not clear how a value that sometimes represents a single run and sometimes muliple runs can be used.

The general recommendation is to keep all application logic inside the hydra.main() annotated function.

**Comment by fabrizioschiano** [comment]
@omry , I ended up on this issue since I have the same problem. Could you let me understand one thing: why do we need to keep all the logic inside the hydra.main() annotated function? 

Why can't I do something like the following? 

```
# ====================== HYDRA-RELATED IMPORTS ======================
import hydra
from hydra.utils import instantiate
from omegaconf import DictConfig, OmegaConf
# ===================================================================

@hydra.main(config_path="../../conf", config_name="config")
def get_dataset_info(cfg : DictConfig):
    print("cfg.dataset.train_dir: {}".format(cfg.dataset.train_dir))
    print("cfg.dataset.num_classes: {}".format(cfg.dataset.num_classes))
    nc = cfg.dataset.num_classes
    print("num_classes: {}".format(nc))
    return nc

def main(num_classes):
    print("num_classes from main: {}".format(str(num_classes)))

def args_preprocess():
    print("Processing arguments")
    main(get_dataset_info())

if __name__ == '__main__':
    print("\nProcessing arguments and starting main")
    args_preprocess()
```

If I run my program I get

```
Processing arguments and starting main
Processing arguments
cfg.dataset.train_dir: /path_to_dir
cfg.dataset.num_classes: 9
num_classes: 9
num_classes from main: None

```

**Comment by fabrizioschiano** [comment]
Of course, an alternative would be to do:

```
# ====================== HYDRA-RELATED IMPORTS ======================
import hydra
from hydra.utils import instantiate
from omegaconf import DictConfig, OmegaConf
# ===================================================================

def main(num_classes):
    print("num_classes from main: {}".format(str(num_classes)))

@hydra.main(config_path="../../conf", config_name="config")
def args_preprocess(cfg : DictConfig):
    print("cfg.dataset.train_dir: {}".format(cfg.dataset.train_dir))
    print("cfg.dataset.num_classes: {}".format(cfg.dataset.num_classes))
    nc = cfg.dataset.num_classes
    print("num_classes: {}".format(nc))
    print("Processing arguments")
    main(nc)

if __name__ == '__main__':
    print("\nProcessing arguments and starting main")
    args_preprocess()
```

and then I would have:

```
Processing arguments and starting main
Processing arguments
cfg.dataset.train_dir: /path_to_dir
cfg.dataset.num_classes: 9
num_classes: 9
num_classes from main: 9
```

But I would like to understand why the `hydra.main()` is implemented in this way. 

Thanks

**Comment by alvitawa** [comment]
I understand that it is a best practice to do everything inside the hydra main function, but nevertheless there are situations where it is useful to be able to simply return something. For example in my app I have all the logic inside the main function, but I want the result of the main function to be available in the repl after running the script with `python -i`. This is done with:

```
if __name__ == "__main__":
    register_configs()

    cfg, result = main()
```

This way I can play around with the result of the script to check if it is correct or save it if it is good.

However, @hydra.main not returning a function forces me to do this through global variables which is messy. And let's not forget the time it has cost me to figure out why my main function was always returning None. 

I think it is preferable if libraries don't force the user to use them in a particular way but instead allow the user to use the library in the way that is most suitable for his/her application.

I realize I'm being a bit philosophical here but another area in which this manifests is with the custom tracebacks that are provided. It is fortunate that you provide a flag to disable them ('export HYDRA_FULL_ERROR=1') but personally I wonder why a library meant for application configuration also hooks into your error tracebacks (and in the meantime prevents you from using post mortem debugging unless you disable the custom tracebacks).

Anyways, I just wanted to give my experience with hydra with regards to this.

**Comment by alexisthual** [comment]
Here is my use-case:

I'm using a function decorated with `@hydra.main` to launch jobs with submitit.
I would like to return these jobs, because I want to monitor them.
In particular, what I want is to design a pipeline which will call several functions decorated with `@hydra.jobs`, but some of them will be called only after some others have run (which is why I want to access this variable).

Is there a way for me to do this with the way hydra works at the moment? :blush:

**Comment by apple2373** [comment]
# What I wanted to do.
```
import hydra

@hydra.main(config_path="./conf", config_name="main.yaml", version_base="1.3")
def setup_args(args):
    return args

def main(args):
    print("args:", args)

if __name__ == '__main__':
    args = setup_args()
    main(args)
```
But this will print `args: None`...

# What works, but I didn't want to do.
```
import hydra

@hydra.main(config_path="./conf", config_name="main.yaml", version_base="1.3")
def main(args):
    print("args:", args)

if __name__ == '__main__':
    main()
```

# What I end up doing
```
import hydra

def setup_args():
    global args_global
    args_global = None
    @hydra.main(config_path="./conf", config_name="main.yaml", version_base="1.3")
    def hydra_main(cfg):
        global args_global
        args_global = cfg
    hydra_main()
    args = args_global
    del args_global
    return args

def main(args):
    print("args:", args)

if __name__ == '__main__':
    args = setup_args()
    main(args)
```
well, I know hydra is not designed to do this way, but I do want to use this way...

**Comment by odelalleau** [comment]
As @omry and @Jasha10 mentioned, `hydra.main()` isn't actually designed for this (in particular due to multirun which makes the notion of "returned value" a bit fuzzy), and the recommended approach is to use the Compose API if you want a more flexible solution.

That being said, here's a workaround that defines a `hydra_main()` you can use instead of `hydra.main()` to access the returned value(s). You can copy / paste this code snippet as a utility function in your code and it should work out of the box:

```python
mport functools

import hydra


def hydra_main(*args, **kw):

    main = hydra.main(*args, **kw)

    def main_decorator(f):
        returned_values = []

        @functools.wraps(f)
        def f_wrapper(*args, **kw):
            ret = f(*args, **kw)
            returned_values.append(ret)
            return ret

        wrapped = main(f_wrapper)

        @functools.wraps(wrapped)
        def main_wrapper(*args, **kw):
            wrapped(*args, **kw)
            return returned_values[0] if len(returned_values) == 1 else returned_values

        return main_wrapper

    return main_decorator



@hydra_main(config_path="conf", config_name="config", version_base=None)
def setup_args(args):
    return args


def main(args):
    print("args:", args)


if __name__ == '__main__':
    args = setup_args()
    main(args)
```
