### ISSUE TITLE
[Bug] unable to pass additional parameter than cfg in main

### ISSUE THREAD

**Issue by arisliang** [facebookresearch/hydra#333]
# 🐛 Bug

Unable to pass additional parameters than cfg in main function.

## To reproduce

** Minimal Code/Config snippet to reproduce **

```@hydra.main(config_path='config.yaml')
def main_with_param(cfg: omegaconf.DictConfig, count: int):
    return count


if __name__ == '__main__':
    always_none = main_with_param(count=10)
    print(always_none)
```

** Stack trace/error message **
```
// Paste the bad output here!
TypeError: decorated_main() got an unexpected keyword argument 'count'
```

## Expected Behavior

Expects additional parameter to be able to pass along with cfg.

## System information
- Hydra 0.11.2
- Python 3.6.6
- Ubuntu 18.04

**Comment by omry** [comment]
Per our discussion:
This is by design. When using hydra.main(), the only argument that should be passed is the cfg object (which is created by Hydra).
All application logic should be under the hydra.main annotated function.

**Comment by Skylark0924** [comment]
So what's the solution to this situation?


> # 🐛 Bug
> Unable to pass additional parameters than cfg in main function.
> 
> ## To reproduce
> ** Minimal Code/Config snippet to reproduce **
> 
> ```
> def main_with_param(cfg: omegaconf.DictConfig, count: int):
>     return count
> 
> 
> if __name__ == '__main__':
>     always_none = main_with_param(count=10)
>     print(always_none)
> ```
> 
> ** Stack trace/error message **
> 
> ```
> // Paste the bad output here!
> TypeError: decorated_main() got an unexpected keyword argument 'count'
> ```
> 
> ## Expected Behavior
> Expects additional parameter to be able to pass along with cfg.
> 
> ## System information
> * Hydra 0.11.2
> * Python 3.6.6
> * Ubuntu 18.04
> 
> ## Additional context
> Add any other context about the problem here.

**Comment by Jasha10** [comment]
@Skylark0924 I'd recommend one of the following:
- use the [compose API](https://hydra.cc/docs/1.2/advanced/compose_api/)
- use a [`nonlocal`](https://docs.python.org/3/reference/simple_stmts.html#the-nonlocal-statement) variable inside your `@hydra.main`-decorated function.
