### ISSUE TITLE
Enable website versioning

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#343]
See:
https://v2.docusaurus.io/docs/versioning/

**Comment by 3janeAI** [comment]
Are you sure about versioning, based on the disclaimer on the site? https://v2.docusaurus.io/docs/versioning/#️-disclaimer

There's nothing much to do, just invoke the version creation command when needed

**Comment by omry** [comment]
Yes. we can give it a try.

**Comment by omry** [comment]
To access the version from master:
https://hydra.cc/docs/next/intro

We need an easy way for users to change versions.

**Comment by omry** [comment]
@3janeAI, can you help with a simple UI for version selection?
