### ISSUE TITLE
[Question] How to declare required fields?

### ISSUE THREAD

**Issue by exic** [facebookresearch/hydra#348]
Hi, I'm trying out hydra right now because I like having sane defaults and the (java spring-config like) flexibility to configure everything. Looks good so far! :-)

I have a CLI app that has two required fields that need to be provided by the user and can't have defaults. I want to use strict mode, so I declared those in my config file. But if I leave them empty, I get `None` as the value. Is there a way to mark those as required like in argparse and have hydra print usage/help if they are not delivered?

Thanks!

**Comment by omry** [comment]
Hi Jonas,
Thanks for your interest in Hydra!
Do read the documentation of [OmegaConf](https://github.com/omry/omegaconf), it will help you understand what you can do with Hydra.

specifically for your question, you can specify required field with the string `???` (but really, go through the docs :) ).

**Comment by omry** [comment]
Curious, How did you learn about Hydra?

**Comment by exic** [comment]
Thanks for the link to OmegaConf, I remember reading "You don't need a deep understanding of OmegaConf for this tutorial.", maybe I should still have followed that link ;-)

A colleague found Hydra and said it might be of use for us, not sure where he found it though.

**Comment by exic** [comment]
Ok, so I got this to work with `???` :+1: and found that #349 already exists, so that's cool, thanks :-)

Now I'd like to have a base configuration, e. g. to define the `class` for a configuration object only once and then use that. I have different environments, where I use the same DB driver but different hosts/passwords. Is that possible already? This is what I've got:

```
conf
├── config.yaml
├── env
│ ├── default.yaml
│ ├── dev.yaml
│ └── prod.yaml
└── functional.yaml
```

I define the class in `default.yaml`, because it would be duplicated otherwise (more envs are possible, too).

Now I have to pass `env=default env=prod` to make it work correctly, it doesn't work if I declare a default in `config.yaml` (which I reference in my `main.py`) and only set `env=prod`.
Is there a solution to this already?

**Comment by omry** [comment]
Look at the [debugging](https://hydra.cc/docs/tutorial/debugging) section in the tutorial.
What you want to use is the composition trace to understand how your config was actually composed.

Specific answer to your question:
Config groups are mutually exclusive, there can be only one env. and that would be the last env, so prod.
you want to put your scaffolding somewhere else, either in a different config group or in the default.yaml file itself (composition order will show you that it's being composed before the rest of your config group, but after the hydra config groups, allowing you to override hydra from it, but also override it from your config groups.

**Comment by exic** [comment]
Okay cool, that makes some sense and actually works, awesome!

I guess my `env=default env=prod` try only worked by accident, maybe it'd make sense to print a warning if a user tries to use two items of a config group?

**Comment by omry** [comment]
Yes, it does make sense, and it's actually a fairly common mistake.

and btw, I made the wrong suggestion above. when I said "either in a different config group or in the default.yaml" I meant in the config.yaml file itself.
