### ISSUE TITLE
[Feature Request] Override ListConfig in command line argument

### ISSUE THREAD

**Issue by tamuhey** [facebookresearch/hydra#376]
# 🚀 Feature Request

I want to override ListConfig in command line.
For example, I have the below `config.yaml`:
```yaml
foo:
  - bar
  - baz
```

and I want to override `bar`, which is the first element of `foo`, in commend line:

```bash
$ python app.py foo.0=xxx
```

**Comment by omry** [comment]
Hi @tamuhey, did you try this command? I think it should work.
```
$ python app.py foo.0=xxx
```

**Comment by tamuhey** [comment]
It worked!
I'm sorry, I misunderstood something,,

**Comment by omry** [comment]
No worries :)
