### ISSUE TITLE
[Feature Request] Pass run index when performing multi-run

### ISSUE THREAD

**Issue by stepelu** [facebookresearch/hydra#377]
When running a multi-run job (say training the same model with different hyperparameters), it would help to have each DictConfig contain additional data (`hydra.multi_run_id` ?) that allows to identify in which of the multi-runs the code is being executed.
The issue is that as of now resources cannot easily be allocated. 
If for instance we have 4 GPUs available, we would like to have the first run use GPU:0, the second run use GPU:1, ...

**Comment by omry** [comment]
Hi @stepelu, thanks for the request.
This is actually there but not documented in a somewhat internal class. thanks for pointing out this need.
For now, you can access it through the HydraConfig singleton which is not documented and will change in the next major version:

```python
import hydra
from hydra.plugins.common.utils import HydraConfig

@hydra.main(config_path="config.yaml", strict=False)
def experiment(_cfg):
    if "num" in HydraConfig().hydra.job:
        print(HydraConfig().hydra.job.num)
    else:
        print("No job number")


if __name__ == "__main__":
    experiment()
```

I will improve this API for the next major version.

**Comment by omry** [comment]
I have plans of exposing all of the Hydra config to interpolations as an function, so you will be able to do something like:

```yaml
gpu_id: ${hydra:job.num}
```

**Comment by omry** [comment]
By the way, I would be happy to hear more about your use case and context (company/university/what you are using Hydra for etc).
Can you join the [chat](https://hydra-framework.zulipchat.com) and share some details?

**Comment by omry** [comment]
creating a dedicated issue for exposing hydra configuration as described in my comment above.

**Comment by omry** [comment]
see #325

**Comment by agamemnonc** [comment]
Apologies for reviving an old issue.

I am trying to use the Optuna plugin for HPT (using PyTorch with PyTorch-Lightning). I understand that it is possible to use `${hydra:job.num}` to tell PL which GPU to use. In this case, how does one setup the Launcher to use 4 parallel jobs so as to always make use o 4/4 GPUs on a local server? Thanks
