### ISSUE TITLE
[Feature Request] Ensure logging is flushed

### ISSUE THREAD

**Issue by bohoro** [facebookresearch/hydra#378]
# 🚀 Feature Request

Ensure logging is flushed upon completion of a job.

## Motivation

In certain cluster environments, my logging was truncated.  Would like to ensure full logging is flushed to output when a job is complete.

## Pitch

Suggesting something like:
```
logging.shutdown() 
```

**Comment by omry** [comment]
Thanks for suggesting. will include a fix for it with the next major release (there are some big changes underway so it may take a month or two for it to be released).
