### ISSUE TITLE
Hydra client API

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#38]
Create Hydra client API to allow jobs to interact with Hydra.
one immediate need is to allow executed code to find out what is the original working directory is was executed from.

**Comment by giladw** [comment]
is there currently a way to get the original working directory?

**Comment by omry** [comment]
Nothing official, but I am adding something now.

**Comment by omry** [comment]
Closing this one as it's too vague. I will land #252 shorty.
Until this gets into an official version, you can do the same as #252 in your code (but I can't guarantee that HydraConfig() will not be moved or changed, in other words - it's unofficial API).
