### ISSUE TITLE
[Feature Request] Override loaded config file through a command line flag

### ISSUE THREAD

**Issue by tamuhey** [facebookresearch/hydra#386]
# 🚀 Feature Request

I want to pass yaml file instead of parameters like `foo.bar=1 ...` to override default configuration:

```bash
$ python app.py --yaml foo.yaml
```

**Comment by omry** [comment]
Can this file be inside the search path (in the same directory as the config file you specify in @hydra.main() )?

If so, try:

```
conf/
  config.yaml
  experiment/
      exp1.yaml
```

and from the command line:
```
$ python foo.py experiment=exp1
```
This will override your config file with exp1.

**Comment by tamuhey** [comment]
> Can this file be inside the search path (in the same directory as the config file you specify in @hydra.main() )?

No.
I'm creating a cli with hydra, and this use case is for the user, so the config file cannot be placed inside `conf` directory.

**Comment by tamuhey** [comment]
The reason why I use hydra is that the configuration of my cli is a little bit complexed and hydra is suitable for my cli.
This app is closed source now, but will be opened before long. (After opened, I'll tell you that)

**Comment by EtienneDavid** [comment]
Yes it would be definitly helpful to be able to change the config_name from the CLI interface. Hydra sounds super helpful to simplify the architecture of some of my modules but the user should be able to redefine the config from scratch...

**Comment by omry** [comment]
This is more involved than it sounds.
config_path is currently describing both the config search path **relative to the delaring Python file**, and optionally a config file to load from the search path.
There are a few related issues open for allowing some control over the search path from the command line as well this one.
When loading a config file using some command line override, what does it do (if anything) to the search path?

This is also a user facing interface. which means it's not very forgiving to many changes. I want to get this right from the first time.

There are other higher priority issues I am working on. I will get to it.

**Comment by EgorBu** [comment]
Hack that may help you in the meantime
```python
def main(cfg: DictConfig) -> None:
    print(cfg.pretty())


if __name__ =="__main__":
    # add argparser for config location
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--config", default="config.yml", help="Config location.")
    args, left = parser.parse_known_args(sys.argv)
    # remove all argparse arguments from sys.argv
    sys.argv = left
    # use hydra.main directly instead of decorator
    hydra.main(config_path=args.config)(main)()
```

**Comment by omry** [comment]
This is a clean workaround that addresses most of the use cases:

In conf, create a directory called experiment:
```
conf\
  experiment\
    exp1.yaml
    exp2.yaml
```
Each one can specialize the generated config, for example exp1.yaml can be:

exp1.yaml:
```yaml
learning_rate: 0.1
batch_size: 32
```

Now from the command line:
`$ python foo.py experiment=exp1`

There are some use cases where an external config file can be useful, but this should cover a large number of the use cases.

**Comment by jbohnslav** [comment]
Hi there,

I just wanted to +1 for this feature request. My use case is as follows. I have a complex configuration file with lots of details the user will not need to interact with, e.g. optimizers. There are elements, particularly regarding the data and augmentations, that all users will have to customize. 

Default `conf/config.yaml`: 
```
train
  lr: 0.0001
  optimizer: adam
dataset
  name: imagenet
  classes: 
    - tench
    - goldfish
    - great white shark
    - ... etc
augs
  resize: 224
  flip_lr: true
  flip_ud: false
```

`user_config.yaml`: 
```
dataset
  name: not hotdog
  classes:
    - hotdog
    - not hotdog
augs
  resize: 64
  flip_lr: true
  flip_ud: true
```

What I want is to be able to use the following syntax and have Hydra load the default configuration file first, and optionally override with the user's supplied config file:
` python train.py --config user_config.yaml`

Is there a way to do this currently with hydra?

**Comment by omry** [comment]
Please reach out on the chat.

**Comment by SunQpark** [comment]
I'm currently using a workaround for a similar case. 

Default **conf/config.yaml**:
```yaml
user_config: # path to config file to update.
train:
  lr: 0.0001
  optimizer: adam
dataset:
  name: imagenet
  classes: 
    - tench
    ...
```
Then, in the `train.py` you can override hydra config object with [`OmegaConf.merge`](https://omegaconf.readthedocs.io/en/1.4_branch/usage.html#merging-configurations) function when `user_config` is given.
```python
if config.user_config is not None:
    user_config = OmegaConf.load(config.user_config)
    config = OmegaConf.merge(config, user_config)
```

Now, you can use `python train.py user_config=user_config.yaml`

**Comment by gunthergl** [comment]
This comment goes in the direction of @jbohnslav, I think @tamuhey 's question can, but does not have to be connected with it because in this case I assume you can have a userconfig inside the search path. 

```
├── conf
│   ├── config_default.yaml
│   ├── cfgs
│   │   ├── base.yaml
│   │   └── userconfig.yaml
└── my_app.py
```

`config_default.yaml`:
```
defaults:
  - cfgs: base
  - cfgs: userconfig
```
`base.yaml`:
```
db:
  first_param: 1
```
`userconfig.yaml`:
```
db:
  userdefined_param: 2
```

`my_app.py`
```
import hydra
from omegaconf import DictConfig


@hydra.main(config_path="conf/config_default.yaml")
def my_app(cfg: DictConfig) -> None:
    print(cfg.pretty())

if __name__ == "__main__":
    my_app()
```


And the output is:

> db:
  first_param: 1
  userdefined_param: 2

For `multirun`, I added `userconfig2.yaml` inside cfgs:
```
db:
  anotherParam: 2
```
Then start via: 
`python my_app.py cfgs=userconfig,userconfig2 -m`
>[2020-05-16 12:04:38,165][HYDRA] Sweep output dir : multirun/2020-05-16/12-04-38
[2020-05-16 12:04:38,166][HYDRA] Launching 2 jobs locally
[2020-05-16 12:04:38,166][HYDRA] 	#0 : cfgs=userconfig
db:
  first_param: 1
  userdefined_param: 2

>[2020-05-16 12:04:38,246][HYDRA] 	#1 : cfgs=userconfig2
db:
  anotherParam: 2
  first_param: 1


I do not know what happens here exactly but as long as it works..

**Comment by gunthergl** [comment]
I just found that it is sufficient to have the following main config file `config_default.yaml`: 

```
defaults:
  - cfgs: base
  - cfgs: base
```

Then generally, its base and you can overwrite it on the commandline. 

Still, I do not know if there are unwanted side effects.

**Comment by omry** [comment]
@gunthergl, I mentioned this approach in multiple comments above.
This is also documented in the tutorial to some extent [here](https://hydra.cc/docs/tutorial/config_groups).

**Comment by moinfar** [comment]
> #  Feature Request
> I want to pass yaml file instead of parameters like `foo.bar=1 ...` to override default configuration:
> 
> ```shell
> $ python app.py --yaml foo.yaml
> ```

Hi,
I believe the requested feature is a must-have.

By the way, I suggest this workaround:
```
def main(cfg: DictConfig) -> None:
    print(cfg.pretty())

if __name__ == "__main__":
    config_path = "./conf/default.yaml"

    if sys.argv[1].startswith("config="):
        config_path = sys.argv[1].split("=")[-1]
        sys.argv.pop(1)

    main_wrapper = hydra.main(config_path, strict=True)
    main_wrapper(main)()
```

This way you can specify your config file by adding `config=somefile.yaml` at the beginning of your command.

**Comment by omry** [comment]
This requested feature is also a will-have.
Patience.

**Comment by omry** [comment]
This is coming, and by "this", I mean what I am ready to support at this stage:
Hydra 1.0 is splitting the config_path into a config_path and config_name, you can learn about it [here](https://hydra.cc/docs/next/upgrades/0.11_to_1.0/config_path_changes).

This feature is opening up the door for overriding the config name and the config path individually through a simple command line flag.

### Limitations
1. config_name is relative to the search path. this will not work for files in arbitrary locations on the file system.
2. config_path is **overriding** the one in the file, if you override it you will lose access to configs that are relative to your Python file.

I am not planning on doing more than this for 1.0.
If there are concrete uses cases where this is insufficient please open a new issue.

**Comment by omry** [comment]
#874 is coming in Hydra 1.0.0rc3 and will probably address most uncovered use cases.

**Comment by r9y9** [comment]
Wow, `--config-dir` option is exactly what I wanted. It worked perfectly in my use case, where I wanted to allow hydra app users to have custom configurations outside the package path. Looking forward to v1.0.0 release 💯

**Comment by omry** [comment]
Hydra 1.0.0 already has rc2 released which you can  try today (`pip install hydra-core --pre --upgrade`).
You will be able to try --config-dir now by installing from master.

**Comment by npuichigo** [comment]
@omry I think a use case is to reload the configs in .hydra if overriding happened during previous runs.

**Comment by npuichigo** [comment]
@omry

**Comment by omry** [comment]
@npuichigo, please open a separate feature request.

**Comment by dmarx** [comment]
Another workaround option for anyone who needs it: I'm invoking a plugin that adds the user's current working directory to hydra's search path. Depending on how you integrate this into your application, it probably won't override defaults. At least in my use case, it's still preferable to requiring the users to provide the `--config-dir` flag (for now).

```
import os

from hydra.core.config_search_path import ConfigSearchPath
from hydra.plugins.search_path_plugin import SearchPathPlugin

# See also:
# https://hydra.cc/docs/advanced/search_path/#
# https://github.com/facebookresearch/hydra/issues/763

class PyttiLocalConfigSearchPathPlugin(SearchPathPlugin):
    def manipulate_search_path(self, search_path: ConfigSearchPath) -> None:

        local_path = f"{os.getcwd()}/config/"
        logger.debug(local_path)
        search_path.append(
            provider="myframework", path=f"file://{local_path}"
        )
```

**Comment by DuncDennis** [comment]
Hi, 

Inspired by @moinfar's [comment](https://github.com/facebookresearch/hydra/issues/386#issuecomment-631423830), here is another workaround that works perfectly for my use case. 

## Use case

A CLI application, where users can (additionally to cli overwrites) specify a path to a partial external config file, which overwrites values of the default config:

```python main.py --config path/to/external_config.yaml other-hydra-param=123, ...```

The priority of overwrites is: The external_config should overwrite the default_config and the cli-overwrites should overwrite the external config. 

## Workaround
The idea is to merge the external config with the default config, then copy the resulting config as a temporary file into the `conf` folder, and finally tell hydra to use that temporary config. 

Consider this minimal example:
```
conf\
  config.yaml
main.py
external_config.yaml
```

main.py
```
import hydra
from omegaconf import OmegaConf
import tempfile
import sys
import argparse
from pathlib import Path

def main(cfg):
    print(f"Configuration: {cfg}")

if __name__ == "__main__":
    # Load the default config.
    default_config_path = Path(__file__).parent / "conf/config.yaml" # Point to the default config file under conf.
    original_config_parent = default_config_path.parent
    cfg = OmegaConf.load(default_config_path)

    # Simple parser that accepts a config file '--config=path/to/config.yaml'
    parser = argparse.ArgumentParser(add_help=False)
    parser.add_argument("--config", type=str, help="Path to external YAML config file.")
    known_args, unknown_args = parser.parse_known_args()

    # Merge external config with default config if provided
    if known_args.config:
        ext_config = OmegaConf.load(known_args.config)
        cfg = OmegaConf.merge(cfg, ext_config) # MERGE WITH DEFAULT CONFIG
        del sys.argv[1:3] # Remove config argument from sys.argv 

    # CRUCIAL STEP: Save the merged config as a temporary file in the original config directory (conf)
    with tempfile.NamedTemporaryFile(mode="w+", suffix=".yaml", dir=original_config_parent) as tmp:
        tmp_path = Path(tmp.name)
        OmegaConf.save(cfg, tmp_path)
        tmp_config_path = str(tmp_path.parent) 
        tmp_config_name = str(tmp_path.name)
        
        # Start hydra main with temporary config file
        main_wrapper = hydra.main(version_base=None, config_path=tmp_config_path, config_name=tmp_config_name)
        main_wrapper(main)()
```

config.yaml: 
```
defaults:
  - _self_

param1: value1
param2: value2
```

external_config.yaml: 
```
param1: value1_modified 
newparam: newvalue 
```


Now you can do: 

```
# Default
python main.py 
>>> Configuration: {'param1': 'value1', 'param2': 'value2'}

# Partial overwrite with external config
python main.py --config external_config.yaml
>>> Configuration: {'param1': 'value1_modified', 'param2': 'value2', 'newparam': 'newvalue'}

# Partial overwrite with external config + CLI args.
python main.py --config external_config.yaml param1=CLIvalue
>>> Configuration: {'param1': 'CLIvalue', 'param2': 'value2', 'newparam': 'newvalue'}
```
(Run with `hydra-core==1.3.2, python=3.10.19`)

Perhaps there is a more modern workaround, or no workaround is needed anymore?
