### ISSUE TITLE
[Feature Request] Range support in BasicSweeper

### ISSUE THREAD

**Issue by jan-matthis** [facebookresearch/hydra#393]
# 🚀 Feature Request

## Motivation

It'd be great if Hydra's basic sweeper supported range sweeping out of the box.

## Pitch

Provide a simple syntax for range sweeping, e.g.:

- `python foo.py a=1:5` -> `python foo.py a=1,2,3,4,5`
- `python foo.py a=1:10:2` -> `python foo.py a=1,3,5,7,9`

This has been implemented in @BadrYoubiIdrissi's [range-sweeper plugin](https://github.com/BadrYoubiIdrissi/hydra-plugins/blob/master/badr_range_sweeper/hydra_plugins/range_sweeper_badr/range_sweeper_badr.py#L52-L53).

In addition, it might be helpful to disable range sweeping or change the separator char for people who rely on it.

## Additional context

FR following discussion with @omry on Zulip.

**Comment by omry** [comment]
This syntax is consistent with the syntax in the coming [Ax plugin](https://github.com/facebookresearch/hydra/pull/321).

I will look into supporting this in 1.1.0.

**Comment by omry** [comment]
https://hydra.cc/docs/next/advanced/override_grammar/extended
