### ISSUE TITLE
[Feature Request] Support .yml in addition to .yaml for config composition

### ISSUE THREAD

**Issue by tamuhey** [facebookresearch/hydra#398]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

The directory structure of my app looks like:

```
├── db
│   ├── mysql.yml
│   └── postgresql.yml
├── config.yml
└── my_app.py
```

and the `config.yml` is:

```
defaults:
    - db: mysql
```

Running `app.py` raises the error:

```
hydra.errors.MissingConfigException: Could not load db/mysql.yaml
```

Hydra seems to support `.yaml` but not `.yml`.

**Comment by omry** [comment]
Hi @tamuhey, is there a specific case for this? I am not sure supporting .yml files justifies checking for the existence of a file with the second extension if the first one fails.
it also opens up to weird cases where you have both yaml and yml files.

**Comment by tamuhey** [comment]
It's a matter of preference.
Because `.yml` is widely used (e.g. [github actions](https://github.com/features/actions) auto generated file), users sometimes have `.yml` and `.yaml` in same repository if they use hydra.

**Comment by omry** [comment]
I am going to park this one.
I will reconsider if it gets a significant number of votes, for now there does not seem to be a solid enough case here.

The magical support for .yaml is making things more complicated they I would like them to be. I don't want to make things even worse by adding support for .yml files.

**Comment by omry** [comment]
This does not seem to justify the extra complexity, closing.
