### ISSUE TITLE
Adding symlink inside the subdir to job.err file.

### ISSUE THREAD

**Issue by 1nadequacy** [facebookresearch/hydra#40]
When you run a big sweep and some of your jobs fail early, it is usefully to look at the job.err file. The problem is that these files are stored in the sweep root folder, and it is pretty hard to find the corresponding *.err file for a particular jobs. Maybe we can add a symlink to this file and store it in the particular job directory?

**Comment by omry** [comment]
This is an issue against the fairtask plugin which is no longer part of the Hydra repo.
