### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by noklam** [facebookresearch/hydra#402]
# 🐛 Bug

Cannot use integer as dictionary key in the config file.

## To reproduce

** Minimal Code/Config snippet to reproduce **
from omegaconf import OmegaConf
conf = OmegaConf.create( dict([(1, 2), (3, 4)]))
print(conf.pretty())

** Stack trace/error message **
```
  File "C:\ProgramData\Anaconda3\lib\site-packages\omegaconf\dictconfig.py", line 35, in __setitem__
    assert isinstance(key, str)
AssertionError
// Paste the bad output here!
```

## System information
- 
- 
-

**Comment by omry** [comment]
Closes as the proper issues was open against OmegConf.
