### ISSUE TITLE
[Bug] Shell completion does not work as described.

### ISSUE THREAD

**Issue by yycho0108** [facebookresearch/hydra#420]
# 🐛 Bug

Shell completion install script does not work as described in the [documentation](https://hydra.cc/docs/tutorial/tab_completion/).

## To reproduce

In this case I'm invoking a custom [app](https://github.com/yycho0108/DRLND_Core/blob/master/drlnd/app/main.py), but I'm (hopefully) not doing anything peculiar in terms of configuration. The repository can be found in the [link](https://github.com/yycho0108/DRLND_Core) for direct testing, if that would be useful.
I'm adding the full instruction below just in case it will be useful to test it directly:

(Specific for the app, but likely not really required for debugging the issue)
```
# Setup dependencies ...
# python3 -m venv env # Uncomment if working with a virtualenv
# source env/bin/activate
# git clone https://github.com/yycho0108/DRLND_Core.git DRLND_Core
# cd DRLND_Core
# pip3 install -e git+https://github.com/openai/baselines.git
# pip3 install -r requirements.txt
```

And the actually relevant portion here is:
```
$ python drlnd/app/main.py --hydra-help
```

Which shows (only copying the relevant part here):
```
--shell_completion,-sc : Install or Uninstall shell completion:
    Install:
    eval "$(python drlnd/app/main.py -sc install=SHELL_NAME)"

    Uninstall:
    eval "$(python drlnd/app/main.py -sc uninstall=SHELL_NAME)"
```

Then running the command as described:
```
$ eval "$(python drlnd/app/main.py -sc install=bash)"
```

Then `hydra_bash_completion` evaluates to:
```
$ type hydra_bash_completion 
hydra_bash_completion is a function
hydra_bash_completion()
{
    words=($COMP_LINE)
    if [ "${words[0]}" == "python" ]; then
        if (( ${#words[@]} < 2 )); then
            return
        fi
        file_path=$(pwd)/${words[1]}
        if [ ! -f "$file_path" ]; then
            return
        fi
        grep "@hydra.main" $file_path -q
        helper="${words[0]} ${words[1]}"
    else
        helper="${words[0]}"
        true
    fi

    if ! [ -x "$(command -v $helper)" ]; then
        false
    fi

    if [ $? == 0 ]; then
        options=$( COMP_POINT=$COMP_POINT COMP_LINE=$COMP_LINE $helper -sc query=bash)
        word=${words[$COMP_CWORD]}

        if [ "$HYDRA_COMP_DEBUG" == "1" ]; then
            printf "\n"
            printf "COMP_LINE='$COMP_LINE'\n"
            printf "COMP_POINT='$COMP_POINT'\n"
            printf "Word='$word'\n"
            printf "Output suggestions:\n"
            printf "\t%s\n" ${options[@]}
        fi
        COMPREPLY=($( compgen -o nospace -o default -W '$options' -- "$word" ));
    fi
}

COMP_WORDBREAKS=${COMP_WORDBREAKS//=}
COMP_WORDBREAKS=$COMP_WORDBREAKS complete -o nospace -o default -F hydra_bash_completion python
```
The relevant file here is `hydra/_internal/core_plugins/bash_completion.py`.

Here the `helper` string evaluates to the following:
```
helper="python drlnd/app/main.py"
```

So the issue is [this line](https://github.com/facebookresearch/hydra/blob/master/hydra/_internal/core_plugins/bash_completion.py#L38) that causes an early exit:
```
    if ! [ -x "$(command -v $helper)" ]; then
        false
    fi
```

```
helper="python drlnd/app/main.py"
if ! [ -x "$(command -v $helper)" ]; then
    false;
fi
echo $?
>> 1 # == false
```

## Expected Behavior
If I remove the `command -v` check, the script works as expected:
```
$ python drlnd/app/main.py #[TAB]
agent=    agent.    env=      hydra/    hydra.    model=    network=  network.  test.     train.
$ python drlnd/app/main.py train.#[TAB]
train.directory=     train.load=          train.num_env=       
train.enabled=       train.log_period=    train.num_episodes=  
```

## System information
- Hydra Version
```
python3 -c 'import hydra; print(hydra.__version__)'
0.11.3
```
- Python Version
```
$ python3 --version
Python 3.6.9
```
- OS
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
- Shell
```
$ echo $SHELL
/bin/bash
```

**Comment by omry** [comment]
Hi, can you join the chat?

**Comment by yycho0108** [comment]
Summary from the chat conversation:
- The root issue is `command -v python drlnd/app/main.py` printing both `/usr/bin/python` and `drlnd/app/main.py` which affects `-x` check due to there not being a single executable.
- The issue was not reproducible in other machines (would be happy to hear about others).
- It can technically be hacked around via adding a `head -1` ... but the root cause remains unknown.

I'll close the issue until others run into the same problem, thanks for your help @omry.

**Comment by omry** [comment]
Thanks for digging with me into this @yycho0108!
