### ISSUE TITLE
Specifying parameter type (via cmd) for Ax/Nevergrad Plugins

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#437]
Determine how to specify the optimization type per parameters via command-line  for Ax/Nevergrad plugins. (float? int?).

Related to https://github.com/facebookresearch/hydra/issues/302 and https://github.com/facebookresearch/hydra/issues/330

**Comment by omry** [comment]
Let's try to agree on standard command line and configuration structure for the variable definitions for both the Ax and Nevergrad plugins.

**Comment by shagunsodhani** [comment]
Linking to the relevant discussion https://github.com/facebookresearch/hydra/pull/430#discussion_r389033167

**Comment by shagunsodhani** [comment]
I am summarising the onversation so far. In case I missed something relevant, please add it here (the discussion was a little scattered).

Main points to discuss:

* Should cmd always have preference over config? The current consensus seems to be that anything explicitly defined in the cmd should win over config. 
* Should we infer the type from the cmd or require it to be specified explicitly. (ie `3:5` vs `int:3:5`)

@jrapin suggested that we support only range via the cmd for now: 
```
# bounds (min:max)
0:1           # specs are optional, assumed float if int not provided
int:0:1
log:0.001:1 (log 0 somehow means unbounded...)
log:int:0.001:1
int:log:0.001:1 # order of specs does not matter

anything,whatever,something
```

I would build on @jrapin 's suggestion (and include some examples of choice and fixed parameters since Ax supports them currently).

Range Parameters

| Input           | Interpretation                              | Explanation                           |
|-----------------|---------------------------------------------|----------------------------------------|
| 0:1             | float(0):float(1)                           | Numbers are float by default           |
| 0:1.1           | float(0):float(1.1)                         | Numbers are float by default           |
| int:0:1         | int(0):int(1)                               | Numbers are typecasted to int          |
| int:0:1.0       | int(0):int(1)                               | Numbers are typecasted to int          |
| int:0:1.2       | Error                                       | float to int casting loses information |
| log:1:2         | float(1):float(2) Sampling in the log space | Numbers are float by default           |
| log:float:1:2   | float(1):float(2) Sampling in the log space | Numbers are float by default           |
| float:log:1:2   | float(1):float(2) Sampling in the log space | Order of log and float does not matter |
| int:log:1:2     | int(1): int(2) Sampling in the log space    | Numbers are typecasted to int          |
| int:log:1:2     | int(1): int(2) Sampling in the log space    | Order of log and int does not matter   |
| int:log:1.0:2.0 | int(1): int(2) Sampling in the log space    | Order of log and int does not matter   |
| int:log:1.1:2.0 | Error                                       | float to int casting loses information |


Choice Parameters

| Input           | Interpretation                              | Explanation                           |
|-----------------|---------------------------------------------|----------------------------------------|
| 0,1,2             | float(0),float(1),float(2)                           | Numbers are float by default           |
| 0,1.1,2           | float(0),float(1.1),float(2)                       | Numbers are float by default           |
| int:0,1,2         | int(0),int(1),int(2)                               | Numbers are typecasted to int          |
| int:0,1.0,2       | int(0),int(1),int(2)                                | Numbers are typecasted to int          |
| int:0,1.2,2       | Error                                       | float to int casting loses information |

Fixed Parameters

| Input           | Interpretation                              | Explanation                           |
|-----------------|---------------------------------------------|----------------------------------------|
| 0             | float(0)                          | Numbers are float by default           |
| 0.1          | float(0.1)                       | Numbers are float by default           |
| int:0         | int(0)                               | Numbers are typecasted to int          |
| int:0.0       | int(0)                                | Numbers are typecasted to int          |
| int:0.1       | Error                                       | float to int casting loses information |

**Comment by jrapin** [comment]
I mostly agree with this, with a couple of comments:
- `log:float:1:2`: the `float`  specifications seems useless, there is (currently) no case where adding it changing anything.
- there is yet the mixed string/float case to handle in choices. Given the pattern here seems to be "don't cast beyond float when not specified" (which I find safe), I would say that if there is any string in the choices, everything is cast to string

| Input | Interpretation | Explanation |
| --- | --- | --- |
|0,1,2 | float(0),float(1),float(2) | Numbers are float by default |
|0,1.1,2 | float(0),float(1.1),float(2) | Numbers are float by default |
|int:0,1,2 | int(0),int(1),int(2) | Numbers are typecasted to int |
|int:0,1.0,2 | int(0),int(1),int(2) | Numbers are typecasted to int |
|int:0,1.2,2 | Error | float to int casting loses information |
|one,2,three | "one", "2", "three" | strings are contagious |

Which raises a couple of other questions, would we allow:
- `one,int:2,three` to have 2 as an integer?
- `one,float:2,three` to have it as a float? (and making the float spec useful)

My point of view is **no**. Reaching this point it seems much more appropriate to handle this in a user code than in the plugins, since the user code is already handling a mix of very different things.

**Comment by omry** [comment]
> I mostly agree with this, with a couple of comments:
> 
>     * `log:float:1:2`: the `float`  specifications seems useless, there is (currently) no case where adding it changing anything.

I vote for supporting float just for completion.
There also bool which we might need to support. no point in shying from supporting primitive types.
 
>     * there is yet the mixed string/float case to handle in choices. Given the pattern here seems to be "don't cast beyond float when not specified" (which I find safe), I would say that if there is any string in the choices, everything is cast to string. Which adds:
> 
> 
> Input 	Interpretation 	Explanation
> one,2,three 	"one", "2", "three" 	strings are contagious
 
Agreed, let's add this.

> Which raises a couple of other questions, would we allow:
> 
>     * `one,int:2,three` to have 2 as an integer?
> 
>     * `one,float:2,three` to have it as a float? (and making the float spec useful)
>
> My point of view is **no**. Reaching this point it seems much more appropriate to handle this in a user code than in the plugins, since the user code is already handling a mix of very different things.

Yup, let's not add this.

**Comment by jrapin** [comment]
> I vote for supporting float just for completion.

Since float is the default for scalars, I feel it would make the API confusing (Zen of Python:  `There should be one-- and preferably only one --obvious way to do it.` though one could argue that `Explicit is better than implicit.` :D).

I mean, the message is simpler if you just have to say `scalars will always be treated as float but you can modify this behavior by casting them to "int" or "bool"`, than saying `we support "int" "bool" and "float" modifiers, but by default everything is float`. In the second case I would somehow still wonder what `1` is. Do I need to write `float:1`? `1.0`? The fact that `float` exists while not having an actual use case would make me wonder if there's something I did not grasp.

> There also bool which we might need to support. no point in shying from supporting primitive types.

Good point. But would that be `bool:0` or `bool:true`? and what of `bool:1.2` ? :D

**Comment by omry** [comment]
If we are already having int and bool (and maybe str), it would make no sense to keep float out.

generally, I think we should use OmegaConf nodes parse those types somehow, it has all the conversion rules.

See [this](https://github.com/omry/omegaconf/blob/71be77a0db5440d6b0287411bc22f682ea97097b/tests/test_nodes.py#L26-L58).
As an added bonus, it will be consistent with OmegaConf Structured Configs.

**Comment by jrapin** [comment]
> If we are already having int and bool (and maybe str), it would make no sense to keep float out.

Your call, i'm fine with both anyway. And as mentioned I dont much like commandlines anyway, so I'm not the best one to decide^^

**Comment by shagunsodhani** [comment]
Some comments:

* `log:float:1:2` example is included for the sake of completion. While the user is not required to provide it, it is not much work to support it.
* str:1,2,3 would be "1", "2", "3" correct ?

**Comment by omry** [comment]
> 
> 
> Some comments:
> 
>     * `log:float:1:2` example is included for the sake of completion. While the user is not required to provide it, it is not much work to support it.

Is this a question, or are you saying you added it?


>     * str:1,2,3 would be "1", "2", "3" correct ?

Yes, same as [this](https://github.com/omry/omegaconf/blob/71be77a0db5440d6b0287411bc22f682ea97097b/tests/test_nodes.py#L28)

**Comment by shagunsodhani** [comment]
> > Some comments:
> > ```
> > * `log:float:1:2` example is included for the sake of completion. While the user is not required to provide it, it is not much work to support it.
> > ```
> 
> Is this a question, or are you saying you added it?
> 
We should support it for the sake of completion :)

**Comment by shagunsodhani** [comment]
I think we agree on all specification. What would be the best place to put this in ? Maybe a `Optimizer` plugin base class that both Ax and Nevergrad extend ?

**Comment by omry** [comment]
Yes, that's not a bad idea.

Sounds like a good package name.
`hydra-hpo-core`

This does not really need to be a plugin, as much as just a package both plugins can rely on.

**Comment by shagunsodhani** [comment]
what is the right place to put it in the code then? plugins dir ?

**Comment by omry** [comment]
for now we can go a sub directory in the plugins dir, as if it's a plugin. if this becomes common we can rethink.

**Comment by omry** [comment]
I am starting to wrap up issues toward the first 1.0.0 release candidate.

**Comment by omry** [comment]
This is no longer blocking 1.0.

**Comment by omry** [comment]
This is done.
