### ISSUE TITLE
[Feature Request] Allow custom plugings?

### ISSUE THREAD

**Issue by renato145** [facebookresearch/hydra#439]
# 🚀 Feature Request
Allow the possibility to incorporate custom plugings.

## Motivation
It will be nice to allow users to create their own plugings for very specific situations.

## Pitch

**Describe the solution you'd like**
Maybe add a parameter to the custom pluging class, indicating that it is user made.

**Comment by omry** [comment]
Hi @renato145.
You can already do that.

You can learn about plugins [here](https://hydra.cc/docs/advanced/plugins).
There are example plugins [here (next version)](https://github.com/facebookresearch/hydra/tree/master/plugins/examples) and [here (current stable version)](https://github.com/facebookresearch/hydra/tree/0.11_branch/plugins/examples).

I am closing this, feel free to continue asking questions about plugins here or to join the chat and ask.
