### ISSUE TITLE
Resetting the state of GlobalHydra

### ISSUE THREAD

**Issue by chrdiller** [facebookresearch/hydra#440]
Hi,

I am trying to use the pytorch bottleneck profiler (`python -m torch.utils.bottleneck train.py`) which apparently has to run the hydra-decorated main() function twice and results in the error
`AssertionError: GlobalHydra is already initialized`

Is there a way to reset the state of the GlobalHydra singleton manually or another workaround to make the profiler work with hydra?

Thanks

**Comment by omry** [comment]
You can try calling the [clear function](https://github.com/facebookresearch/hydra/blob/0.11_branch/hydra/_internal/hydra.py#L41-L42) at the end of your hydra.main function:

**Comment by chrdiller** [comment]
Ah cool. Had some trouble finding how to actually call this; in the end, `hydra._internal.hydra.GlobalHydra.get_state().clear()` worked.

**Comment by omry** [comment]
Yup.
Note that GlobalHydra is being promoted out of _internal in the next version and will be [here](https://github.com/facebookresearch/hydra/blob/master/hydra/core/global_hydra.py).

**Comment by omry** [comment]
Ah, you are using it wrong (I suspect you are clearing all signletons which may have incidentally been what you want but not what you asked for).

try, in 0.11, try:
`hydra._internal.hydra.GlobalHydra().clear()`

In the next version it will  be:
`hydra._internal.hydra.GlobalHydra.instance().clear()`

**Comment by chrdiller** [comment]
Okay, I also tried those two (I'm on version 0.11.3):  
- `hydra._internal.hydra.GlobalHydra().clear() ` gave me `TypeError: clear() missing 1 required positional argument: 'self'` (which makes sense I guess) and  
- `hydra._internal.hydra.GlobalHydra.instance().clear()` raises `AttributeError: type object 'GlobalHydra' has no attribute 'instance'`

**Comment by chrdiller** [comment]
Ah sorry, `hydra._internal.hydra.GlobalHydra.clear()` doesn't work, `hydra._internal.hydra.GlobalHydra().clear()` does.

Thanks again!

**Comment by omry** [comment]
The above PR will fix this the next major version of Hydra.

**Comment by imilas** [comment]
I ended up here while trying to run hydra (version 1.2.0) inside jupyter notebook. The function that worked for me is: 

hydra.core.global_hydra.GlobalHydra.instance().clear()
