### ISSUE TITLE
[Feature Request] Does it work with ArgumentParser?

### ISSUE THREAD

**Issue by r0f1** [facebookresearch/hydra#443]
Consider this code:

```
# config.yaml
db:
  driver: mysql
  user: omry
  pass: secret
```

```python
# test.py
import hydra
from omegaconf import DictConfig
from argparse import ArgumentParser

@hydra.main(config_path="config.yaml")
def my_app(cfg):
    print(cfg.pretty())

if __name__ == "__main__":
    parser = ArgumentParser()
    parser.add_argument("--verbosity", help="increase output verbosity", action="store_true")
    parser.parse_args()
    my_app()
```
Executing the following command gives an error:
```
>>> python test.py db.user=root
usage: test.py [-h] [--verbosity]
test.py: error: unrecognized arguments: db.user=root
```
Which brings me to my question / feature request? Is it possible to make Hydra work with ArgumentParser? If yes, are there some examples somewhere?

Best, Flo

**Comment by omry** [comment]
Hi @r0f1.
Nope, that is becoming an FAQ.
See #215 for a discussion.

specifically, hydra supports logging verbosity via hydra.verbose (see the docs).
if you want to add something like this you can just add it to you config:

config.yaml
```yaml
verbosity: false
```

and then override with:
`$ python foo.py verbosity=true`
