### ISSUE TITLE
[Bug] setuptools finds and installs tests/ as a top-level package in site-packages/

### ISSUE THREAD

**Issue by bcdarwin** [facebookresearch/hydra#466]

**Comment by omry** [comment]
Hi @bcdarwin, thanks for pointing out. definitely an oversight.
I will fix it for the next version. Is this causing actual issues for you with 0.11.3?

**Comment by bcdarwin** [comment]
No, it's low priority, just noticed it.  Thanks!

**Comment by omry** [comment]
I hate setuptools very much. this was about 2 hours more difficult than it should be.
