### ISSUE TITLE
Use structured config in the Ax plugin

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#469]

**Comment by shagunsodhani** [comment]
One of the parameters have the type as `Optional[Dict[str, Union[str, bool, float, int, None]]]` Specifying this type throws the following error:

```
omegaconf.errors.ValidationError: Unsupported value type : typing.Union[str, bool, float, int, NoneType]
full_key:                                                                                       
reference_type=None                                                                             
object_type=None
```

So I used the type as `Optional[Dict[str, Any]]`

**Comment by omry** [comment]
Unions are not currently supported. This solution is reasonable.

**Comment by shagunsodhani** [comment]
Thanks - I had another question.

Earlier I could unpack a dictconfig just like a dictionary (**config). After adding structured configs, I can not longer do that (which makes sense). Is there a workaround for this limited behavior?

**Comment by omry** [comment]
why not?

**Comment by shagunsodhani** [comment]
It fails mypy check: `hydra_plugins/hydra_ax_sweeper/_core.py:138: error: Argument after ** must be a mapping, not "EarlyStopConfig"`

**Comment by omry** [comment]
You can convert to primitive container or just to tell mypy to shut up with `# type: ignore`

**Comment by shagunsodhani** [comment]
Thats a good point. I wonder if I will lose the type-hint though ie would the attributes (of `EarlyStopConfig`) be marked of type `Any`?

**Comment by omry** [comment]
If you wonder test it. I am not sure which case you are referring to.
you can use reveal_type() to see what type mypy thinks a variable is.
