### ISSUE TITLE
[Bug] %run magic with jupyter notebook

### ISSUE THREAD

**Issue by noklam** [facebookresearch/hydra#481]
# 🐛 Bug

Expect to run hydra in a notebook cell and get realtime output like in Terminal.

Two ways of running a python file in Jupyter
!python (calling the terminal directly) -> but cannot get real time output
%run (Jupyter way of running python file, but does not seems compatible with Hydra directly)

I am expecting this can run `%run runner.py exp_name=abc`

## To reproduce
hydra_tqdm_notebook.py
```
import hydra
@hydra.main(config_path="configs/config.yaml")
def experiment_runner(cfg) -> None:
    from tqdm import tqdm_notebook as tqdm


    for i in tqdm(range(5)):
        import time
        time.sleep(0.02)
        print('helloworld')

if __name__ == "__main__":
    experiment_runner()
```

** Stack trace/error message **
![image](https://user-images.githubusercontent.com/18221871/76141436-2d0b4000-609f-11ea-8b6b-c8111d851d2f.png)

## Expected Behavior

The only difference between `test_hydra_tqdm_notebook.py` and `test_tqdm_notebook.py` is I wrapped it inside the Hydra runner. I expect the output to be the same.
![image](https://user-images.githubusercontent.com/18221871/76141432-2381d800-609f-11ea-9367-bd092c113fbb.png)

## System information
- **Hydra Version** :  
- **Python version** : 
- **Virtual environment type and version** : 
- **Operating system** : 

## Additional context
test_tqdm_notebook.py
```
from tqdm import tqdm_notebook as tqdm
for i in tqdm(range(100)):
    import time
    time.sleep(0.02)
    print('helloworld')
```

**Comment by omry** [comment]
Please edit your bug report to a minimal example to reproduce the problem, will full source code of the runner code and the cell itself.

**Comment by noklam** [comment]
https://github.com/jupyter/notebook/issues/4048 (This issue shows why I want to use %run because I need to get realtime terminal output)

**Comment by omry** [comment]
I will take a look at this, but this is really not a supported mode now.
See the [Compose API page](https://hydra.cc/docs/advanced/compose_api) which is the supported Hydra API for notebooks.

**Comment by omry** [comment]
Your example is a bit convoluted. can you try to minimize it a bit? I am not sure I understand the role of each of the 3 files.

**Comment by noklam** [comment]
![image](https://user-images.githubusercontent.com/18221871/76141305-cc2f3800-609d-11ea-88a2-ec388b7604ff.png)

(I clean up the issue a bit, let's focus only for tqdm_notebook)

To give u some more information. I try to comment out the part that is checking is it calling from notebook. It works when I run for the first time, if I then run again it will throw errors.

![image](https://user-images.githubusercontent.com/18221871/76141314-e1a46200-609d-11ea-83f8-ab1d795c523e.png)
![image](https://user-images.githubusercontent.com/18221871/76141382-9cccfb00-609e-11ea-88eb-d0c193c4d8f6.png)

**Comment by omry** [comment]
Thanks for updating your example and for providing additional context.
It is not likely that I will support `%run`, but I will take a look when I have some time.

Take a look at the compose API I linked above. with some slight refactoring you can use it to compose the config in the Notebook instead of relying on @hydra.main() in the notebook.

**Comment by noklam** [comment]
Sure, I will try using the notebook API instead, thanks!

I like to use a notebook even just for running terminal commands because it cache output and I can log some high-level information for my experiment naturally inside just one notebook. If I need to use the notebook API, all logical code with stay with the config, and I may need 1 notebook for 1 experiment

What I would like to do is something like
## Experiment 1
%run runner exp_name=1
output: accuracy=0.9
## Experiment 2
%run runner exp_name=2
accuracy=0.92

**Comment by omry** [comment]
I understand, but Hydra was never tested using %run, and clearly it does not work.
Hydra is detecting that it's running from within a notebook and behaves differently, however @hydra.main() is designed to run in a regular python process.
there is a lot of magic going on to allow Hydra to auto detect where the config is.

If you really want to run Hydra as a process, use the Python `subprocess` module.
This not do what you want though. I really think the best thing for you to do is to just use the compose API.

`train.py`:
```python
def train(cfg):
  ...

@hydra.main(config_path="config.yaml")
def my_app(_: DictConfig) -> None:
  train(cfg)

if __name__ == "__main__":
    my_app()
```

`notebook`:
```python
import hydra.experimental
from train import train

hydra.experimental.initialize()
cfg = hydra.experimental.compose("config.yaml", overrides=["db=mysql", "db.user=me"])

print(cfg.pretty())
```

**Comment by shaolinkhoa** [comment]
Hi,
It also happened in The Jupyter Lab Terminal:
![image](https://user-images.githubusercontent.com/12138158/77722703-dbb4f780-7031-11ea-8188-ce14ddebf9dd.png)
![image](https://user-images.githubusercontent.com/12138158/77722691-d061cc00-7031-11ea-8a31-7a89294c41a1.png)

**Comment by omry** [comment]
> Hi,
> It also happened in The Jupyter Lab Terminal:
> ![image](https://user-images.githubusercontent.com/12138158/77722703-dbb4f780-7031-11ea-8188-ce14ddebf9dd.png)
> ![image](https://user-images.githubusercontent.com/12138158/77722691-d061cc00-7031-11ea-8a31-7a89294c41a1.png)

I have a fix coming for this issue (%run).
If this does not solve the other problem file a different issue and explain how to reproduce. I have never used Jupyter Lab Terminal.
