### ISSUE TITLE
[Feature Request] How to customize working directory with different configuration

### ISSUE THREAD

**Issue by Johnson-yue** [facebookresearch/hydra#485]
# 🚀 Feature Request

## Motivation
I want to customize working directory depend on model name in config.yaml.
Such as  if I have config.yaml like this:
```
default:
 - data : dataset
 - model: cnn or rnn
 - trainer: cnn
hydra:
  run: 
    dir: outputs/${default.model.name}/XXXX 
```

then , working directory is :  
```
outputs |
        |  cnn | XXXX
or
        |  rnn   | XXXX

```
like this function

**Comment by omry** [comment]
Hi @Johnson-yue,
defaults list is special and is removed from the configuration.
Also, it's a list so you would need to use something un-intuitive like `defaults.1.model`.

You can achieve what you want by adding the name of the model to each of the models, for example:
model/cnn.yaml:
```yaml
model:
  name: rnn
  ...
```

and then using that in your output dir name:
```yaml
hydra:
  run: 
    dir: outputs/${model.name}/XXXX 
```

**Comment by omry** [comment]
Closing for now, feel free to comment if this does not solve your problem.
