### ISSUE TITLE
Frequency

### ISSUE THREAD

**Issue by zairon20** [facebookresearch/hydra#487]
# 🚀 Feature Request

## Motivation

**Is your feature request related to a problem? Please describe.**

## Pitch

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

**Comment by omry** [comment]
Closing. feel free to open a new one and provide actual details if you want anything.
