### ISSUE TITLE
[ax] Ax launched should support initial_job_num

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#488]
https://github.com/facebookresearch/hydra/issues/284#issuecomment-596266565

**Comment by omry** [comment]
I am starting to close Hydra issues toward the first 1.0 release candidate.
Are you planning to start tackling the issues you opened for the Ax launcher?

**Comment by shagunsodhani** [comment]
Will work on it today and provide some update eod.

**Comment by shagunsodhani** [comment]
I think this has been fixed in #527 :)
