### ISSUE TITLE
[Feature Request] Skip certain files during plugin discovery

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#494]
# 🚀 Feature Request

When scanning the plugins directory, certain files should be skipped. 

## Motivation

**Is your feature request related to a problem? Please describe.**

Plugin discovery imports all the modules in the plugins directory. This can slow down Hydra startup. One example is Ax plugin slowing down Hydra #476 

## Pitch

**Describe the solution you'd like**
When scanning plugins, ignore files starting with "_".

**Describe alternatives you've considered**

* We could put certain files outside the plugins directory but that separates the logic that should live together.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

Yes :)

## Additional context

NA

**Comment by shagunsodhani** [comment]
Fixed in https://github.com/facebookresearch/hydra/commit/67a525b84188ea48cf2e22ff9eac9b648eaf5efd

**Comment by omry** [comment]
Next time you can put a "closes #494" in the PR, and it will get closed automatically when it's merged.
