### ISSUE TITLE
[Feature Request] Non-mutually exclusive config groups

### ISSUE THREAD

**Issue by apsdehal** [facebookresearch/hydra#499]
# 🚀 Feature Request

Allow hydra to load multiple configurations in a single compositional block.

## Motivation

For multitasking, one needs to load configurations for multiple datasets. Currently the way hydra is structure, I don't see a clear way of loading multiple configs in a single block.

## Pitch

For e.g. let's say defaults look something like:
```
defaults:
  - dataset:
     - ???
```

and `datasets` folder is something like:
```
conf/
    dataset/
        vqa2.yaml
        textvqa.yaml
```

If I run, `python main.py dataset=vqa2,textvqa`, I should get a final config object something like

```
dataset:
  - vqa2: ...
  - textvqa: ...
```

We have something like this already implemented in Pythia's configuration system which is very close to hydra.

**Are you willing to open a pull request?** No

**Comment by omry** [comment]
Functionally speaking, I think #235 would address this.

In the short term, you can use lower level OmegaConf APIs to do the composition in your code.

Closing as dup, feel free to continue discussing here if you want further discussion.

**Comment by omry** [comment]
The fundamental issue is the options of each config group are mutually exclusive.
maybe I need to introduce a non-mutually-exclusive configuration group.
```
defaults:
  - dataset: a
  - dataset: b
  - dataset: c
```
Your suggestion for nesting there is syntactic sugar on this, and can actually be used to indicate this is one such special config group.

**Comment by omry** [comment]
[Here](https://hydra.cc/docs/next/patterns/select_multiple_configs_from_config_group) are the docs.
This assumes knowledge of [The Defaults List](https://hydra.cc/docs/next/advanced/defaults_list).

**Comment by ysig** [comment]
When I run this:
```
- dataset:
  - imagenet
  - cifar
```

what I will have as an output is not a list of both but rather a merged dictionary of both. This shouldn't be the expected behavior as it violates that stacking means a list. How can I actually have a list?
This can allow me to chain multiple dataset btw

**Comment by Jasha10** [comment]
@ysgi see https://github.com/facebookresearch/hydra/issues/2027 and https://github.com/facebookresearch/hydra/issues/1939.

**Comment by igoradamski2** [comment]
is anyone looking into implementing this? It seems like a very fundamental lack of hydra
