### ISSUE TITLE
Website not pushing

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#506]
fatal: bad object 67a525b84188ea48cf2e22ff9eac9b648eaf5efd

No changes detected in directory website between origin/master and this diff

**Comment by omry** [comment]
Also, can you try to upgrade the website?

**Comment by 3janeAI** [comment]
This error could happen if the revision that was used for the site no longer exists (e.g., force push with a squash). Fixed in #509 

Upgrading is separate, doing in #510
