### ISSUE TITLE
[Feature Request] allow for dashed overrides

### ISSUE THREAD

**Issue by dhpollack** [facebookresearch/hydra#514]
# 🚀 Feature Request

It would be nice if one could use dashed overrides as well as the current non-dashed version

```yaml
arg1: default1
arg2: default2
```

```sh
python app.py arg1=override1 arg2=override2
python app.py arg1=override1 --arg2=override2
python app.py arg1=override1 --arg3=unknown_arg1  # this still fails
```

Some scripts assume that arguments have the preceding dashes and thus breaks if you call hydra scripts.  A notable example is the [pytorch distributed launch script](https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py#L248).  The pytorch example basically invokes multiple runs of the given command with `--local_rank={local_rank}` attached to the command.  So even if you have `local_rank` as an expected variable in your hydra config, it fails because of the formatting of the variable.

## Motivation

I want to use hydra with pytorch distributed training and specifically something like `python -m torch.distributed.launch --nproc_per_node=2 app.py arg1=override1`

## Pitch

I haven't done extensive testing, but I think the following diff on `hydra/_internal/utils.py` would enable this feature.

```
diff --git a/hydra/_internal/utils.py b/hydra/_internal/utils.py
index 7eb38bf0..f23ac64f 100644
--- a/hydra/_internal/utils.py
+++ b/hydra/_internal/utils.py
@@ -148,6 +148,15 @@ def create_config_search_path(search_path_dir: Optional[str]) -> ConfigSearchPat
     return search_path
 
 
+def _convert_dashed_args(unknown_args: List[str]) -> List[str]:
+    new_args = []
+    for arg in unknown_args:
+        while arg.startswith("-"):
+            arg = arg[1:]
+        new_args.append(arg)
+    return new_args
+
+
 def run_hydra(
     args_parser: argparse.ArgumentParser,
     task_function: TaskFunction,
@@ -172,7 +181,8 @@ def run_hydra(
         task_name=task_name, config_search_path=search_path, strict=strict
     )
     try:
-        args = args_parser.parse_args()
+        args, unknown_args = args_parser.parse_known_args()
+        args.overrides += _convert_dashed_args(unknown_args)
         if args.help:
             hydra.app_help(config_name=config_name, args_parser=args_parser, args=args)
             sys.exit(0)
@@ -276,7 +286,9 @@ def get_args_parser() -> argparse.ArgumentParser:
 
 
 def get_args(args: Optional[Sequence[str]] = None) -> Any:
-    return get_args_parser().parse_args(args=args)
+    known_args, unknown_args = get_args_parser().parse_known_args(args=args)
+    known_args.overrides += _convert_dashed_args(unknown_args)
+    return known_args
 
 
 def _strict_mode_strategy(strict: Optional[bool], config_name: Optional[str]) -> bool:
```

**Comment by omry** [comment]
Hi David, thanks for the request.
this is a frequently asked feature, and currently I have no intentions of doing it.

There are a few reasons:

Hydra is making use of --args:
```
$ python test.py  --hydra-help
Hydra (0.11.3)
See https://hydra.cc for more info.

== Flags ==
--help,-h : Application's help
--hydra-help : Hydra's help
--version : show program's version number and exit
--cfg,-c : Show config instead of running [job|hydra|all]
--run,-r : Run a job
--multirun,-m : Run multiple jobs with the configured launcher
--shell_completion,-sc : Install or Uninstall shell completion:
...
```
By disallowing userland apps to use -- for args I avoid name collisions.

2. Scripts that are using argparse are inferior to scripts using Hydra. In general it's not a lot of work to convert them without adding additional functionality, thus enabling hierarchical configuration and composition.
I want to encourage people to make this switch.

3.
For use cases where you are controlling the code launching, you can translate from hydra dashless style to dashed style and call the following main.

4. for use cases where you are controlling the launched code but not the launching code, you can create you on standard argparse app and use hydra.experimental.compose to create the configuration, running the same code executed by the annotated hydra.main (without using hydra.main).

**Comment by omry** [comment]
About torch distributed:
Honestly I did not yet have a chance to try it yes.
Do you know if it supports setting up the rank (and world size) as an environment variable?

**Comment by reactivetype** [comment]
Another use case where -- syntax would be nice to have is for use with MS Visual studio code.

**Comment by dhpollack** [comment]
I'll look into using environmental variables for the torch distributed case as a brief look at the launcher makes it seem like that's possible. I see the disadvantages of allowing the dashes and actually don't like the idea of mixing and matching styles but this was one case where it would be useful. I don't know many other apps where this would be a problem so maybe I'll just bug the pytorch guys to add an option to use Hydra style arguments with their launcher 🤣

**Comment by omry** [comment]
Yes.
For now I am resisting this, it's possible that I will eventually change my mind but as of now I am not planning to allow this.

@teng-li, any thougts about allowing torch distributed to accept non -- parameters as well? :)

**Comment by dhpollack** [comment]
Their script works out of the box if you remove the dashes. That was actually the first thing that I tried. FYI

**Comment by omry** [comment]
> Their script works out of the box if you remove the dashes. That was actually the first thing that I tried. FYI

Oh, looks like it's just forwarding the arguments to environment variables anyway:
https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py#L229-L230

This makes more sense to me.
I don't think there is any action item for the torch team.

Closing.

**Comment by omry** [comment]
@reactivetype :
> Another use case where -- syntax would be nice to have is for use with some editors's launch configuration. For e.g., with MS Visual studio code, we would pass a list of args as follows:
> 
> ```
> args = [ ''--param_1=value1", "--param2=value2"]
> ```

I am not using VSC myself, by traditionally IDEs does not assume getopt style and allow you to pass anything to the app.

**Comment by reactivetype** [comment]
> 3. for use cases where you are controlling the launched code but not the launching code, you can create you on standard argparse app and use hydra.experimental.compose to create the configuration, running the same code executed by the annotated hydra.main (without using hydra.main).

The `compose` api is a pragmatic solution. Thanks.
