### ISSUE TITLE
How to make two apps share config directories

### ISSUE THREAD

**Issue by LinxiFan** [facebookresearch/hydra#516]
I have two app scripts, each has its own config directory (e.g. conf1/ and conf2/). However, they share a number of config groups that I put in sibling directories. For example, the file structure looks like:

```
conf1/
   - config.yaml
   - cnn/
   - trainer/
conf2/
   - config.yaml
   - rnn/
   - trainer/
dataset/
server/
```

main1.py looks like
```python
@hydra.main(config_path='conf1/config.yaml')
def main(cfg):
    pass
```
and main2.py replaces `conf1` -> `conf2` above.

I hope to have the following command line structure:
```
python main1.py cnn=model1 trainer=sgd dataset=imagenet server=gce
python main2.py rnn=model2 trainer=adam dataset=wsj server=aws
```
Could you please advise on the cleanest way to achieve this? Thank you so much!

**Comment by omry** [comment]
You are starting to build a framework.
I recommend that you take a look at example of ConfigSearchPathPlugin [here](https://github.com/facebookresearch/hydra/tree/master/plugins/examples/example_searchpath_plugin).

Feel free to join the chat if you want to chat about this.

**Comment by LinxiFan** [comment]
Thank you so much!
