### ISSUE TITLE
[Bug] Colorlog brokes in master.

### ISSUE THREAD

**Issue by lkhphuc** [facebookresearch/hydra#526]
# 🐛 Bug

Colorlog plugin not working on master.

** Stack trace/error message **
```
MissingConfigException: Could not load hydra/hydra_logging/colorlog, available options:
hydra/hydra_logging:
        default
        disabled
        hydra_debug
```

## System information
- **Hydra Version** : master  
- **Python version** : 3.7

## Additional context
I tried reinstall colorlog with `pip install -U hydra_colorlog` after install hydra from master but it still not working.

**Comment by omry** [comment]
Hi, did you try installing it from master?
`pip install plugins/hydra_colorlog`

**Comment by lkhphuc** [comment]
Haha this is embarassing, yes it fixes that. :))

**Comment by omry** [comment]
happens to the best of us :)

Happy to see you are trying master, it's shaping up nicely and I am hoping to have a release candidate in a few weeks.
keep the bug reports coming!
