### ISSUE TITLE
[Feature Request] Set all loggers log level to DEBUG except hydra

### ISSUE THREAD

**Issue by shaolinkhoa** [facebookresearch/hydra#530]
# 🚀 Feature Request

I want to set the logging to DEBUG level for all my logger except hydra.

## Motivation
So I added a `Config file: hydra/job_logging/custom.yaml` following this [Customizing logging](https://hydra.cc/docs/configure_hydra/logging)
```yaml
hydra:
  # python logging configuration for tasks
  job_logging:
    root:
      level: DEBUG
```

**Is your feature request related to a problem? Please describe.**

It returns error:
```
Traceback (most recent call last):
  File "train.py", line 22, in <module>
    main()
  File "/opt/conda/lib/python3.7/site-packages/hydra/main.py", line 24, in decorated_main
    strict=strict,
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/utils.py", line 174, in run_hydra
    overrides=args.overrides,
  File "/opt/conda/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 86, in run
    job_subdir_key=None,
  File "/opt/conda/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 101, in run_job
    configure_log(config.hydra.job_logging, config.hydra.verbose)
  File "/opt/conda/lib/python3.7/site-packages/hydra/plugins/common/utils.py", line 24, in configure_log
    logging.config.dictConfig(conf)
  File "/opt/conda/lib/python3.7/logging/config.py", line 800, in dictConfig
    dictConfigClass(config).configure()
  File "/opt/conda/lib/python3.7/logging/config.py", line 496, in configure
    raise ValueError("dictionary doesn't specify a version")
ValueError: dictionary doesn't specify a version
```

## Pitch

**Describe the solution you'd like**

I know we can set the `hydra.verbose=[logger_1, logger_2, logger_3]`
But it's time-consuming if I have a lot of loggers.

**Comment by omry** [comment]
That example seems wrong, I will take a look.

This is the full [job logging config](https://github.com/facebookresearch/hydra/blob/master/hydra/conf/hydra/job_logging/default.yaml), see the version?

You have two choices:
1. have a full job logging specification ([working example](https://github.com/facebookresearch/hydra/tree/master/examples/configure_hydra/logging))
2. override the existing job logging specification (which is what you are actually trying to do).

The problem with 2, is that that you are actually replacing the hydra/job_logging with your own custom logging config, so really you are doing 1.

Try this:
Move the logging config override name outside of hydra/job_logging, for example into a log_override group:
```yaml
defaults:
  - log_override: debug
```

`log_override/debug.yaml`:
```yaml
hydra:
  job_logging:
    root:
      level: DEBUG
```

As a side note, you can also just override the log level from the command line (without all of this mess):

```
$ python foo.py hydra.job_logging.root.level=DEBUG
```

**Comment by omry** [comment]
> I know we can set the hydra.verbose=[logger_1, logger_2, logger_3]
But it's time-consuming if I have a lot of loggers.

Another thing:
If your loggers are hierarchical:
- module.logger_1
- module.logger_2
- module.logger_3

You should be able to use
```
hydra.verbose=module
```

**Comment by shaolinkhoa** [comment]
> That example seems wrong, I will take a look.
> 
> This is the full [job logging config](https://github.com/facebookresearch/hydra/blob/master/hydra/conf/hydra/job_logging/default.yaml), see the version?
> 
> You have two choices:
> 
> 1. have a full job logging specification ([working example](https://github.com/facebookresearch/hydra/tree/master/examples/configure_hydra/logging))
> 2. override the existing job logging specification (which is what you are actually trying to do).
> 
> The problem with 2, is that that you are actually replacing the hydra/job_logging with your own custom logging config, so really you are doing 1.

From the [Overview](https://hydra.cc/docs/configure_hydra/intro) and following tutorials, I thought that the customize hydra config will override the existent original hydra configs instead of replacing them.

Thank you for clarifying my misunderstanding.
  
 
> Try this:
> Move the logging config override name outside of hydra/job_logging, for example into a log_override group:
> 
> ```yaml
> defaults:
>   - log_override: debug
> ```
> 
> `log_override/debug.yaml`:
> 
> ```yaml
> hydra:
>   job_logging:
>     root:
>       level: DEBUG
> ```
> 
> As a side note, you can also just override the log level from the command line (without all of this mess):
> 
> ```
> $ python foo.py hydra.job_logging.root.level=DEBUG
> ```

I followed your guides but all the DEBUG loggers from hydra are also printed.


> > I know we can set the hydra.verbose=[logger_1, logger_2, logger_3]
> > But it's time-consuming if I have a lot of loggers.
> 
> Another thing:
> If your loggers are hierarchical:
> 
> * module.logger_1
> * module.logger_2
> * module.logger_3
> 
> You should be able to use
> 
> ```
> hydra.verbose=module
> ```

There are many loggers in different files so I think I will stick with `hydra.verbose=true` at this moment.

**Comment by omry** [comment]
Closing this.
If there is more interest in this feature I can consider adding some kind of support.
