### ISSUE TITLE
[Feature Request] Fish shell tab completion

### ISSUE THREAD

**Issue by binshengliu** [facebookresearch/hydra#549]
# 🚀 Feature Request

Adding completion support for [fish shell](https://fishshell.com/).

## Motivation

**Is your feature request related to a problem? Please describe.**
Nope. This just improves the user experience.

## Pitch

**Describe the solution you'd like**

The solution uses fish's [`complete`](https://fishshell.com/docs/current/#writing-your-own-completions) command to register completion rules. When the user presses TAB, fish will call the underlying script for candidates and do the completion.
```
$ ./test.py -sc install=fish | tee /dev/tty | source
complete -c python3 -n '__fish_seen_subcommand_from ./test.py' -x -a '(/home/bsl/.miniconda3/envs/hydra38/bin/python3 /home/bsl/code/tmp/test.py -sc query=fish --_completion (commandline -cp))'
complete -c test.py -x -a '(/home/bsl/.miniconda3/envs/hydra38/bin/python3 /home/bsl/code/tmp/test.py -sc query=fish --_completion (commandline -cp))'
$ ./test.py -sc uninstall=fish | tee /dev/tty | source
complete -e -c test.py
```
A new global option `--_completion` is added following an [old convention](https://stackoverflow.com/a/20879411/955952). The current command line will be fed into hydra through this option for completion instead of using environment variables. This also leads to the interface change of `CompletionPlugin.query`, but I think it should be reasonable.

**Describe alternatives you've considered**

NA

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))
I did some fiddling with the code. This [branch](https://github.com/binshengliu/hydra/tree/fish-completion) passes the lint checks but I'm not sure what's happening with the tests (on the master branch it fails at `test_completion.py`). I'm okay if you are interested and want to modify the code to your standards. Just hoping this is useful and there's an auto-completion solution for fish.

## Additional context
The effect from my branch.

![Fish completion](https://user-images.githubusercontent.com/441707/79732640-50c8d380-8337-11ea-9144-a27f1cab6932.gif)

There are still three problems I don't know the answers yet.

1. `python script.py` style completion can not be uninstalled from fish. The workaround is to open a new shell.
2. Fish automatically adds a space to args with a dot(`db.` -> `db. `) which requires the user to remove a space then press TAB for further completion. This seems to be a fish's internal limitation.
3. I have no idea how to auto test these features so sorry I can't contribute test cases.

**Comment by omry** [comment]
Hi @binshengliu, this looks nice!
if you want to submit as PR for this and invest more time into getting this to work, I can offer my feedback and guidance on integrating this with the automated shell completion test suite .

**Comment by binshengliu** [comment]
Sure. Please let me know what I need to do.

**Comment by omry** [comment]
Submit a draft PR and I will give you the feedback there.

**Comment by omry** [comment]
> There are still three problems I don't know the answers yet.
> 
>     1. `python script.py` style completion can not be uninstalled from fish. The workaround is to open a new shell.

Why not? how is it different then the one where you run the Python file directly?


>     2. Fish automatically adds a space to args with a dot(`db.` -> `db. `) which requires the user to remove a space then press TAB for further completion. This seems to be a fish's internal limitation.

That is a serious problem, I am not sure this will pass the tests.
Did you reach out on some fish forum/irc thread to discuss this? there could be a way to prevent it.

>     3. I have no idea how to auto test these features so sorry I can't contribute test cases.
I can tell you have to do that over a PR. it will be easier.

**Comment by omry** [comment]
We can [open an issue against fish](https://github.com/fish-shell/fish-shell/issues/new) to discuss this use case. both = and . are special cases for Hydra completion that should not have a space following them.

**Comment by binshengliu** [comment]
> > There are still three problems I don't know the answers yet.
> > ```
> > 1. `python script.py` style completion can not be uninstalled from fish. The workaround is to open a new shell.
> > ```
> 
> Why not? how is it different then the one where you run the Python file directly?

This rule registers new completion for `python` command. Fish can only remove all the rules of `python` or specific options like `-v`, `--verbose`.

> 
> > ```
> > 2. Fish automatically adds a space to args with a dot(`db.` -> `db. `) which requires the user to remove a space then press TAB for further completion. This seems to be a fish's internal limitation.
> > ```
> 
> That is a serious problem, I am not sure this will pass the tests.
> Did you reach out on some fish forum/irc thread to discuss this? there could be a way to prevent it.

They already complete `=` properly because they support `--long-option=LONG_OPTION` style, and I think it's [hard-coded](https://github.com/fish-shell/fish-shell/blob/6ebbe5a4507d906e78a71314256f0abe735ca88f/src/complete.cpp#L200). I'll find some time later to open a discussion.

> 
> > ```
> > 3. I have no idea how to auto test these features so sorry I can't contribute test cases.
> > ```
> 
> I can tell you have to do that over a PR. it will be easier.

I just realized you were using expect for the integration test. I've integrated fish into it.

**Comment by omry** [comment]
awesome, let's move the discussion to the PR.
I will take a look at it later tonight or tomorrow (need to focus on other things).

**Comment by binshengliu** [comment]
No problem. Regarding the extra space issue, it seems one use case is not convincing enough the `.` should be a special case like `=` (https://github.com/fish-shell/fish-shell/issues/6928). I was asking if they'd like to to make it customizable. Otherwise, I don't have better solutions but document it clearly at the moment.

**Comment by omry** [comment]
Thanks. I saw the comment there and this is not something that makes sense for Hydra.
I think we need to explain why, and ask for some more flexibility from Fish.

by the way, please join the [chat](https://hydra-framework.zulipchat.com/#), it will be easier to communicate there.

**Comment by omry** [comment]
This is done. Thanks for your work on this @binshengliu!
