### ISSUE TITLE
Multirun: allow commas in config values set from command-line

### ISSUE THREAD

**Issue by jgehring** [facebookresearch/hydra#573]
Passing `--multirun foo=bar,baz` will result in a sweep over the two specified values for `key`. However, the comma might be used as a part of an actual string value. A simple fix would be to allow introduce an escape character for value splitting, so that e.g. `--multirun foo=bar/,baz` results in a single "bar,baz" value for "foo".

**Comment by omry** [comment]
Thanks @jgehring, this is something I can look at for the next major version.
If you would like to give it a stab I will be willing to review a PR for 1.0 introducing this (along with proper tests).
This should probably go into the BasicSweeper.
