### ISSUE TITLE
[Feature Request] Allow @hydra.main() to take a config object and pass it through

### ISSUE THREAD

**Issue by Darktex** [facebookresearch/hydra#575]
# 🚀 Feature Request

Allow @hydra.main() to take a config and pass it through

**Comment by omry** [comment]
Will look into it.

**Comment by lkhphuc** [comment]
Hi, is this feature the only way to run test of a decorated hydra function?
I have something like this with `run` decorated by `hydra.main`:
```
def test_main():
        experimental.initialize("../cfg/")
        cfg = experimental.compose("../cfg/config.yaml")
        run(cfg)
```
but it is not allowed.

**Comment by omry** [comment]
currently there is no supported way to do it. this feature is exactly about supporting this use case.
