### ISSUE TITLE
Fix Nevergrad sweeper to pass common sweeper tests

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#578]
#576 introduces common sweeper tests that should pass for all Sweeper.
Currently those tests are failing for the Nevergrad  sweeper, please re-enable the tests (commented out in #576) and fix the Nevergrad  sweeper such that they pass.

**Comment by jrapin** [comment]
Is it used anywhere and working? The tests don't even seem to pass when using the basic hydra sweeper

**Comment by omry** [comment]
It does , but not with overriding the function:

[Basuc launcher test](https://github.com/facebookresearch/hydra/blob/master/tests/test_basic_launcher.py#L11-L13) (uses the basic sweeper by default)

[Example sweeper test](https://github.com/facebookresearch/hydra/blob/master/plugins/examples/example_sweeper_plugin/tests/test_example_sweeper_plugin.py#L42-L56
)

I am not seeing an example when I overridden the task_function, so there could still be some issues with that.

**Comment by omry** [comment]
I suggest you wait until @shagunsodhani implements this for the Ax sweeper, no point in both of you trying to make it work at the same time.
Let's see what he ends up with for Ax first.

**Comment by shagunsodhani** [comment]
Yeah I plan to work on it tonight.

**Comment by omry** [comment]
Closing for now. we can revisit what improving testing for optimizing sweepers once they have a common library.
