### ISSUE TITLE
Nevergrad Plugin eval usage

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#579]
The NeverGrad plugin is using eval which is dangerous.
Please see if this can be eliminated (bandit suggests ast.literal_eval as a safer alternative).
```
$ bandit --exclude "./tests/**,./.nox/**" -ll  -r .
[main]  INFO    profile include tests: None
[main]  INFO    profile exclude tests: None
[main]  INFO    cli include tests: None
[main]  INFO    cli exclude tests: None
[main]  INFO    running on Python 3.8.2
229 [0.. 50.. 100.. 150.. 200.. ]
Run started:2020-05-07 19:33:42.950152

Test results:
>> Issue: [B307:blacklist] Use of possibly insecure function - consider using safer ast.literal_eval.
   Severity: Medium   Confidence: High
   Location: ./plugins/hydra_nevergrad_sweeper/build/lib/hydra_plugins/hydra_nevergrad_sweeper/core.py:150
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval
149             if description.startswith(tuple(dir(ng.p))):
150                 param: ng.p.Parameter = eval(  # pylint: disable=eval-used
151                     "ng.p." + description
152                 )

--------------------------------------------------
>> Issue: [B307:blacklist] Use of possibly insecure function - consider using safer ast.literal_eval.
   Severity: Medium   Confidence: High
   Location: ./plugins/hydra_nevergrad_sweeper/hydra_plugins/hydra_nevergrad_sweeper/core.py:150
   More Info: https://bandit.readthedocs.io/en/latest/blacklists/blacklist_calls.html#b307-eval
149             if description.startswith(tuple(dir(ng.p))):
150                 param: ng.p.Parameter = eval(  # pylint: disable=eval-used
151                     "ng.p." + description
152                 )
```

**Comment by jrapin** [comment]
`ast.literal_eval`: The string or node provided may only consist of the following Python literal structures: strings, numbers, tuples, lists, dicts, booleans, and None.

So basically it will not work. Either providing custom parametrization must be dropped or it stays this way. It's pretty safe in the sense that it only accepts strings starting with a specific pattern, and that's only interpreting user provided strings. It's always possible to trick it though, but that would be the user tricking it anyway...

**Comment by omry** [comment]
can you give an example of an accepted usage right now? (in config or command line).

**Comment by jrapin** [comment]
> can you give an example of an accepted usage right now? (in config or command line).

https://hydra.cc/docs/next/plugins/nevergrad_sweeper#custom-parameter

**Comment by omry** [comment]
Okay. let's remove it.
If there is anything not supported by the command line DSL we are converging on we should consider extending it or supporting it via a mechanism that does not directly evaluate used provided code.
