### ISSUE TITLE
referencing files without defaults, dealing with list of files

### ISSUE THREAD

**Issue by sankethvedula** [facebookresearch/hydra#580]
Hi, 

Let's say I have the following config directory.

```
trainer/
 | optim/
    |  sgd.yaml
    |  adam.yaml
          ....
 | models/
     |  unet.yaml
     |  restnet.yaml
          ....
 trainer_config.yaml
```

I would like to compose my ``` trainer_config.yaml ```  as follows:
```
optim: 
 - sgd
 - adam
models:
 - unet
 - resnet
```
I encounter two problems doing this:
1. I see that hydra doesn't let me instantiate paths to files if keys are not listed under ```defaults```. Is there a way to compose configurations from multiple files without using ```defaults``` (the way I mentioned above)?

2. Say to counter this problem I use ```defaults```, then I would like my config to look like:

```
defaults:
  optim:
   - sgd
   - adam
  models:
   - unet
   - resnet

```

since my model contains two sub-models or it uses multiple optimizers. It seems that ```defaults``` does not recognize a list of config files. What is the correct way to configure such a system? Am I missing something? 

Thanks!

**Comment by omry** [comment]
0. reformat your config directory, I can't parse it.

I am loosing you at 

> I would like to compose my trainer_config.yaml as follows:

You are composing a configuration object, not a configuration file.
What do you mean here?

Do you want to compose a single object with all of the choices? both models and both optimizers?
Are you actually going to use both optimizers and both models at runtime in a single run?

I will try to answer after you clarify.

**Comment by sankethvedula** [comment]
Sorry about the unclear formulation! 

Thanks for the clarification about the defaults and for the prompt response! :)

Yes, I would actually like to use both optimizers and both models within a _single_ run.

What seemed natural to me was using the defaults this way:

```
defaults:
  - optim:
      - adam
      - sgd
  - model:
     - resnet
     - unet
```

But it doesn't seem to parse lists of files. What's the correct way to go about such a system?

**Comment by omry** [comment]
Configuration groups are currently mutually exclusive. There is a feature request looking at relaxing this but it's not currently supported.

If you always want to use both, you can just keep them both in a single file and not decompose them into two files.

**Comment by omry** [comment]
See [this](https://hydra.cc/docs/tutorial/config_groups).

What are you actually trying to achieve? Why are you using two optimizers and two models in the same run? is this for GAN, D and G and models?

**Comment by sankethvedula** [comment]
Hi Omry. thanks for the response. The link you've sent is helpful, I'll try to continue this discussion on the Zulip channel -- probably that's a better place to discuss this :)

**Comment by omry** [comment]
@sankethvedula, this link is a part of the basic tutorial.
I strongly suggest that you read the entire thing :)

Closing, feel free to continue this on the chat.
