### ISSUE TITLE
Overwrite default configuration

### ISSUE THREAD

**Issue by isvoboda** [facebookresearch/hydra#582]
My use-case includes predefined configuration of an experiment based on the suggestion from https://github.com/facebookresearch/hydra/issues/386#issuecomment-589586845

I do not know how to redefine the selection of group `model` in `defaults`:

- `conf/config.yaml`
~~~yaml
defaults:
  model: UNetPix
~~~

- `conf/model/UNetPix.yaml`

~~~yaml
model:
  class: models.UNet.UNetPix
    params:
      kwarg1: ...
      kwarg2: ...
~~~

- `conf/model/UNetTC.yaml`

~~~yaml
model:
  class: models.UNet.UNetTC
    params:
      kwarg1: ...
      kwarg2: ...
~~~

I would like to add configuration of an experiment where the UNetTC node replaces the UNetPix.

- `conf/experiment/UNetTC.yaml`

~~~yaml
model: UNetTC # Here I would like to replace UNetPix by UNetTC defined in model/UNetTC.yaml
... # other experiment related configurations
~~~

I can set the model as `model: UNetTC` which resolves to string `UNetTC` but the desired outcome should be the whole node defined in  `models/UNetTC.yaml`.

Is this currently possible?

**Comment by omry** [comment]
The only supported way to override the defaults list when using @hydra.main() is through the command line.
```
python foo.py model=UNetTC
```

I suspect what you really want would be addressed by the potential support for recursive defaults. but this is not something that will happen soon and I still have some questions about it's viability.

See #171 for the info about the task to add recursive detauls.

**Comment by omry** [comment]
An alternative workaround would come once support for an alternative primary config is introduced.
that way you will be able to have a defaults list in your alternative primary config. this is likely be supported before recursive defaults.
