### ISSUE TITLE
Where is hydra_nevergrad_sweeper?

### ISSUE THREAD

**Issue by vict0rsch** [facebookresearch/hydra#601]
# 🐛 Bug

In the docs, it is written that `pip install hydra_nevergrad_sweeper` should allow me to use nevergrad as sweeper (after having installed hydra from master).

This package however does not exist. What's the preferred way to use Nevergrad then? 

Thanks!

**Comment by omry** [comment]
Hi,
The plugin is not yet released as it depends on Hydra 1.0 which is not yet released.
You can install both directly from the repository.
Checkout hydra, and pip install both directories:

```
$ git clone https://github.com/facebookresearch/hydra.git
$ cd hydra
# in your virtual environment:
$ pip install .  # note the trailing '.'
$ pip install plugins/hydra_nevergrad_sweeper
```

**Comment by vict0rsch** [comment]
Thanks!

**Comment by omry** [comment]
By the way:
Both the Ax plugin and the Nevergrad plugin are:
1. Still subject to interface changes.
2. New and may contain bugs and documentation issues.

Please report any issues.

**Comment by vict0rsch** [comment]
I understand, no worries :) thanks for the heads up anyway
