### ISSUE TITLE
Try circleci matrix to speed up CI and simplify ci config

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#610]
1. We ca each plugin in it's own job.
2. We can parameterize Python version instead of having to replicate job config 3 times.

https://circleci.com/blog/circleci-matrix-jobs/

**Comment by omry** [comment]
Some links for dynamic jobs triggering:

[trigger-a-new-pipeline](https://circleci.com/docs/api/v2/#trigger-a-new-pipeline)
[Conditional-steps-in-jobs-and-conditional-workflows](https://support.circleci.com/hc/en-us/articles/360043638052-Conditional-steps-in-jobs-and-conditional-workflows
)
[conditional-workflows](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/conditional-workflows.md)

**Comment by jieru-hu** [comment]
- [ ] parameterize Python version 

- [ ] separate each plugin into its own job.

**Comment by omry** [comment]
see https://circleci.com/docs/api/v2/#trigger-a-new-pipeline , this can be used to dynamically trigger a job per plugin.

**Comment by omry** [comment]
done
