### ISSUE TITLE
multiple use of the same component

### ISSUE THREAD

**Issue by pvnieo** [facebookresearch/hydra#642]
# 🚀 Feature Request

Hi all,

Thanks for the awesome library.

I have a question regarding multiple use of the same component. Let's say that I have two databases configurations (postgre and sql), both are saved under the directory `db`. And in my main `config.yaml`, I want to use the two databases for some application, let's say that I have some information saved in the first database, and other information saved in the second, and  I want my main application to have configuration to access both db.

Is there a way to do this other that creating two folders `db1` and `db2` that have exactly the same configuration files? I think that this solution is against the spirit of Hydra. Maybe giving path to config file along with inferring the path only from the names will be solution
```
db1: db.sql
db2: db.postgre
```
 but I don't think this is supported.

Thank you for you help.

**Comment by omry** [comment]
Hi @pvnieo!
[Hydra 1.0](https://github.com/facebookresearch/hydra/releases/tag/hydra-1.0.0rc1) release candidate was just released a few day ago.

Try using it's new [packages](https://hydra.cc/docs/next/advanced/package_directive) feature.

**Comment by omry** [comment]
Closing as I think this is exactly what you you need. feel free to continue the discussion here or in the chat if you have followup questions.
