### ISSUE TITLE
Using Hydra in jupyter notebook

### ISSUE THREAD

**Issue by ParikaGoel** [facebookresearch/hydra#649]
I am able to use the library in python files. But in the documentation, I can not see how can I use it in notebook. Below is the screenshot of my notebook:

![image](https://user-images.githubusercontent.com/35452780/83865101-fab4c180-a725-11ea-9ff0-7c54d7b2492a.png)

**Comment by omry** [comment]
See the [compose API](https://hydra.cc/docs/next/experimental/compose_api).
