### ISSUE TITLE
Review command line overrides doc page

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#654]
and where it actually belongs (probably advanced)

**Comment by Stonesjtu** [comment]
@omry thanks for open-sourcing such a great tool, it's been really helpful.

Is there a documentation page for CLI interface?  I was planning to implement my own CLI parser before I found it in the `_interal` codebase.

As a new user, I would prefer to see it in `tutorials/basic/your_first_app/config_file`. A note or link would suffice.

**Comment by omry** [comment]
Hi @Stonesjtu!
If you are just getting started, I recommend Hydra 1.0 release candidate.

The docs are [here](https://hydra.cc/docs/next/intro).

Generally, you should get what you need to know by going through the basic tutorial.
The command line interface in 1.0 is richer which it why there is a dedicated page for it:

https://hydra.cc/docs/next/advanced/command_line_overrides

This issues is about improving that page, it's not entirely accurate and it's a bit too dense.

**Comment by omry** [comment]
Judging by the pull request, I think what you actually want is the command line flags for Hydra itself.

try:
```
python foo.py --hydra-help
```

**Comment by omry** [comment]
> Is there a documentation page for CLI interface? I was planning to implement my own CLI parser before I found it in the _interal codebase.

You should not rely on anything internal.
Hydra is also not designed to allow users to extend the argparse command line interface. You should have plenty of flexibility from the general command line support in Hydra.

**Comment by Stonesjtu** [comment]
> Judging by the pull request, I think what you actually want is the command line flags for Hydra itself.
> 
> try:
> 
> ```
> python foo.py --hydra-help
> ```

Exactly! 

Can we add a simple directive such as * You can override the config_name and config_path arguments by passing --config_name xxx to the hydra main file *.

It's better to demonstrate the `hydra-help` interface in the documentation as early as possible.

**Comment by omry** [comment]
--config_path and --config_name are actually FAR less important than you think.
In most cases you shouldn't need them and you should be using composition instead.

I initially considered adding something like this but it did not seem to be worth interrupting the flow of the document for it.

**Comment by omry** [comment]
And by the way:
When you do --help, it tells you about --hydra-help :)

**Comment by Stonesjtu** [comment]
Can you please share a link for *composition* approach

**Comment by omry** [comment]
https://hydra.cc/docs/next/tutorials/basic/your_first_app/config_groups

You can create a group called experiment:
```
experiment/
  exp1.yaml
  exp2.yaml
```
And add it to your defaults list with:
```
python foo.py +experiment=exp1
```

**Comment by omry** [comment]
This is reflecting master, if you want to try it checkout from master.

https://hydra.cc/docs/next/advanced/command_line_syntax
