### ISSUE TITLE
RC releases on conda-forge?

### ISSUE THREAD

**Issue by ToucheSir** [facebookresearch/hydra#667]
# 🚀 Feature Request

Really appreciate the publishing of stable releases on conda-forge! I was wondering if it would be possible to add an RC branch for the upcoming 1.0 release on the relevant feedstocks?

## Motivation

**Is your feature request related to a problem? Please describe.**
Installing the current RC versions of Hydra and OmegaConf break conda's dependency resolution algorithm. This necessitates uninstalling and reinstalling both before and after executing any package management commands.

## Pitch

**Describe the solution you'd like**
Some form of (presumably automated) process for updating the `rc` branches of both OmegaConf and Hydra feedstocks so as to expose conda-compatible pre-releases.

**Describe alternatives you've considered**
Perhaps pulling RC's off of PyPI? I've read that conda-forge does this already for some packages, but not sure if it's applicable for pre-releases.

## Additional context
https://github.com/conda-forge/cfep/blob/master/cfep-05.md

**Comment by omry** [comment]
I am not maintaining the conda release.

can you submit an issue [here](https://github.com/conda-forge/hydra-feedstock)?

**Comment by ToucheSir** [comment]
Ah, I saw your comments on https://github.com/conda-forge/staged-recipes/pull/10545 and assumed you had a hand in the Conda releases as well? Is @mdraw solely responsible for the feedstock then? I'll open an issue on https://github.com/conda-forge/hydra-core-feedstock assuming that's the correct place.

**Comment by omry** [comment]
I can help answer questions or review the code there but I am not the one maintaining the conda packages.
