### ISSUE TITLE
mark plugins as warnings expected so nox will not check for warnings

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#672]
CI shouldnt fail if tests on plugins ares expected to yield warnings

**Comment by omry** [comment]
For most plugins it should. I added this for a reason.

**Comment by omry** [comment]
This could be the answer:
https://docs.pytest.org/en/stable/warnings.html#pytest-mark-filterwarnings

**Comment by omry** [comment]
I think we have a reasonable solution for it.
