### ISSUE TITLE
Save .hydra/*.yaml before task execution

### ISSUE THREAD

**Issue by binshengliu** [facebookresearch/hydra#678]
# 🐛 Bug

Saving the configurations is a really cool idea that helps me check what I actually did. I noticed the save timing is delayed after task execution in the `1.0.0rc1`. I have encountered some scenarios that I think it would be better if the configs are saved earlier.

For example,

1. Tasks may exit accidentally due to bugs. Knowing detailed configurations would be helpful.
2. For time-consuming tasks like ML training which may last for several days, it would be helpful to be able to check the config.yaml. This helps me a lot when I have multiple tasks running but I can't remember the real difference. I do `diff config.yaml`.
3. Some tasks don't need to be finished. The full training may be designed to run 100 epochs but it also happens it's aborted/killed in the middle.

## To reproduce

Default behavior in `1.0.0rc1`.

** Minimal Code/Config snippet to reproduce **
NA

** Stack trace/error message **
NA

## Expected Behavior
NA

## System information
- **Hydra Version** :  1.0.0rc1
- **Python version** : NA
- **Virtual environment type and version** : NA
- **Operating system** : NA

**Comment by omry** [comment]
Is this a change in 1.0?

**Comment by binshengliu** [comment]
It seems this change was introduced in 98128a4d

**Comment by omry** [comment]
Interesting, not sure why I moved it down.
can you send a PR fixing it?

**Comment by binshengliu** [comment]
Yeah sure.
