### ISSUE TITLE
[Feature Request] Document usage without functions (top-level)

### ISSUE THREAD

**Issue by txntxn** [facebookresearch/hydra#688]
# 🚀 Feature Request

Document how to use Hydra without functions

## Motivation

In Jupyter notebooks, you may want access to Hydra configs when you are not within a function. This is because it's easier to test Jupyter scripts where the code is top-level. However, you still want access to Hydra configs.

Please document how to use Hydra when you are not within a function, for example in a Jupyter notebook.

**Comment by omry** [comment]
Hydra 0.11: https://hydra.cc/docs/advanced/compose_api
Hydra 1.0: https://hydra.cc/docs/next/experimental/compose_api

There is an actually Jupyter notebook in the example linked there.
