### ISSUE TITLE
Document instantiate with Structured Configs

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#701]

**Comment by omry** [comment]
@shagunsodhani, done?

**Comment by omry** [comment]
from the reference. classmethod should not have a self, right?

![image](https://user-images.githubusercontent.com/376455/88349903-40ddd880-cd06-11ea-8071-c1d5f4896364.png)

**Comment by shagunsodhani** [comment]
> @shagunsodhani, done?

Doing today :)

**Comment by shagunsodhani** [comment]
Closed in https://github.com/facebookresearch/hydra/pull/821
