### ISSUE TITLE
[Bug] Docs Update

### ISSUE THREAD

**Issue by anthonytec2** [facebookresearch/hydra#703]
# 🐛 Bug

hydra/website/docs/tutorials/structured_config/4_defaults.md

I think in the defaults list that database here should be db

**Comment by omry** [comment]
Thanks @anthonytec2, you are right.

I have an significant update coming to that tutorial. will address that too, but feel free to send a PR fixing that.

**Comment by omry** [comment]
Duplicate (#607)
