### ISSUE TITLE
Evaluate flit for packaging

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#706]
bases content of package on the repo.

https://pypi.org/project/flit/

**Comment by Queuecumber** [comment]
I can highly recommend Poetry although I don't know what the difference is

**Comment by omry** [comment]
Thanks @Queuecumber,
Both flit and poetry does not seem to support build steps.
flit mentions it specifically in the docs and poetry has [this](https://github.com/python-poetry/poetry/issues/1486) issue open without any response for a long time.

Hydra build requires generating the antlr parser. Do you know if a custom build step is possible with poetry?

**Comment by Queuecumber** [comment]
I'm not entirely sure if it's what you're looking for but my library (you can find the full setup at https://gitlab.com/Queuecumber/torchjpeg) has to do a libjpeg build as part of the setup process. 

Poetry let's you specify a custom build script with the "build" option (as far as I can tell this option isn't documented). That script will be invoked during the build of your package and let's you modify the kwargs for a setup call (like in the legacy setup.py) as well as do whatever else you want.

I use it to build libjpeg and then add a c extension build to the setup kwargs. It might be able to do what you need

**Comment by omry** [comment]
I just took a look at both Poetry and Flit:
Flit lacks the ability to work with namespace packages, eliminating it as an option for now (https://github.com/takluyver/flit/issues/370).

Poetry keeps the package version in pyproject.toml, making it incompatible with towncrier (There is no way to get it to pull version from __init__.py like towncrier, flit and other tools (https://github.com/python-poetry/poetry/issues/2614).

**Comment by Queuecumber** [comment]
Yeah I had to solve this for torchjpeg as well, you can call `poetry version <something>` to set the version number in a script so I do that during CI to sync it (in my case to git tags but you could do anything). That being said if setup tools is working for you I don't really see any reason to change it
