### ISSUE TITLE
[Feature Request] TaskSpooler launcher

### ISSUE THREAD

**Issue by pseeth** [facebookresearch/hydra#715]
# 🚀 Feature Request

Task Spooler is a really simple Unix tool that I have used to keep track of jobs, parallelize batch scripts, launch machine learning jobs, and launch long-running jobs (e.g. jupyter lab, tensorboard). I think it's really a clean way to do jobs in succession. Here's the manpage: http://manpages.ubuntu.com/manpages/xenial/man1/tsp.1.html 

It'd be nice if hydra could submit jobs to tsp. Happy to help implement this with some pointers.

## Motivation

The really nice bit about task spooler is that it's global to the user. Any shell you open, task spooler still has the jobs that you launched last time. Each job's log is tailed nicely into tmp files for easy viewing from the terminal (`tsp -t [id]`). Importantly, the fact that it's global makes it really handy to work on a single machine. It means that you can launch jobs as you think of them without overloading the machine. It's also really easy to keep track of all the jobs currently running, even if you lose access to the terminal for some reason by just doing `tsp`, which produces an easy-to-read queue. `tsp` is available via both `brew` and `apt-get` as well as others, making it simple to install and use.

The number of concurrent jobs is easily controlled from anywhere to scale up or down via `tsp -S N` where `N` is the number of concurrent jobs. `N` defaults to 1.

## Pitch

**Describe the solution you'd like**
Make a launcher for task-spooler.

**Describe alternatives you've considered**
JobLib backend is also nice but there's no global state of all the jobs you have launched. I just noticed RQ, which I have tried in the past as well. In the end though, task-spooler is a super clean Unix tool that just works. I wish I knew about it earlier.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md)) Yes, with some pointers on how to make a Launcher plugin. I looked through the other implementations a bit and walked away a little confused. A guide of some kind would be really helpful!

Thanks! I'm just getting started with Hydra myself and so far I quite like it. Nice work!

**Comment by omry** [comment]
Hi @pseeth!
TaskSpooler sounds really nice, I never heard of it.
I'd be happy to help getting you on the right track.

Take a look at the [example launcher](https://github.com/facebookresearch/hydra/tree/master/plugins/examples/example_launcher_plugin), copy it and start hacking.

Feel free to join the chat if you have questions.
