### ISSUE TITLE
Clean up example plugins

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#720]
- [ ] There are some old patterns that should be cleaned up
- [x] Move to examples/plugins (#927)

**Comment by PluckyPrecious** [comment]
Hi @omry can I get a `kind chore` `first timer` Documentation to work on? 🙂

**Comment by omry** [comment]
Hi @PluckyPrecious!
Thanks for your interest, you can take a look at the issues list for [1.0 milestone](https://github.com/facebookresearch/hydra/milestone/4) and pick one that you are comfortable with. If you have questions you can ask on the individual issues.
I marked a few as "good first issues".

This one is not a good intro task because it's not very well defined.
