### ISSUE TITLE
[Bug] ObjectConf with cls Keyword Argument is not Supported on Python 3.6.9

### ISSUE THREAD

**Issue by cgerum** [facebookresearch/hydra#721]
# 🐛 Bug

If one tries to instantiate ObjectConf with cls as a keyword argument python crashes. 

This might be related to #634 and is probably ultimately caused by https://github.com/ericvsmith/dataclasses/issues/155 .

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
Python 3.6.9 (default, May 12 2020, 13:40:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
from hydra.types import ObjectConf 
ObjectConf(cls="Test") 
```

** Stack trace/error message **
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() got multiple values for argument 'cls'

```

## Expected Behavior

```
>>> ObjectConf("Test")
ObjectConf(cls='Test', params={})
```

## System information
- **Hydra Version** :  1.0.0rc1  
- **Python version** : 3.6.9
- **Virtual environment type and version** : pyenv  1.2.18
- **Operating system** : Ubuntu 20.04

**Comment by omry** [comment]
Yeah, as you found I have already submitted a bug about it (I actually totally forgot that I reported it already, good find :) ).
Python 3.6 does not really support dataclasses and OmegaConf is relying on that dataclasses backport package you pointed for that support.

Can you give more context about where you are hitting that problem? is this from the submitit plugin?

**Comment by cgerum** [comment]
Sorry, did not notice that it was you. 

I originally hit it when trying to use the pytorch-lightning example: https://github.com/anthonytec2/pytorch-lightning/pull/2 . 
But now also in the submitit plugin. 

    hydra_submitit_launcher/config.py", line 72, in <module>

    params=LocalParams(),
    TypeError: __new__() got multiple values for argument 'cls'

I will have a look at dataclasses over the weekend, but as there does not seem an obvious solution I can't promise anything..

**Comment by omry** [comment]
The submitit plugin is officially only supporting 3.7+ for another reason as well.

The example from Anthony can be modified to not instantiate the object like this, but it would be a bit messier.
Doing it like this is very clean and the point of that example is to be a clean solid example.

Awesome that you will try to the dataclasses backport.
I am disappointed that so many months after reporting I got no response from the project author.
I hope he will be receptive to a fix if you can figure it out.

**Comment by cgerum** [comment]
For me this is probably another reason to upgrade my python interpreters. 

For the  time being I will use the `sitecustomize.py` workaround in https://gist.github.com/cgerum/20cca9ffa33f3a3ff75cea14b8e9fc9b .

But the only true solutions would probably be renaming the cls parameter. Maybe there is a possibility to keep backwards compatibility on python 3.7+ or dropping support for python 3.6.

**Comment by omry** [comment]
Yeah.
In Hydra 0.11 (stable), the name of this parameter is `class` and I renamed it to `cls` as class is a reserved keyword in Python can you can't have:
```python
@dataclass
class ObjectConf:
  class: str = MISSING
```

It's a bit unfortunate this this conflict is only showing up now so close to Hydra 1.0 release.
I think I can rename it and deprecate `cls` in the same manner.

There is an outstanding open issue about improvements to the instantiate API (#566), which suggests using `_type_`.
Since Instantiate also support functions I think we I can support both `_type_` and `_function_` as valid keywords for the target.

Thoughts?

**Comment by cgerum** [comment]
Well as the API from 0.11 changes anyway, adopting #566   before 1.0 would probably be quite convenient. 

I like the proposed API. Let me know if I can be of further assistance.

**Comment by omry** [comment]
#566 is not making it to 1.0. got to draw the line somewhere. 1.0 has been cooking for more than 6 months.

I am probably going to go with the neutral `_target_` for the field name, which works both for classes and function names.
