### ISSUE TITLE
Update the examples in examples/configure_hydra

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#723]
1. Update them
2. Cover them with tests
3. Mention them in the relevant doc pages.

**Comment by imanishbarnwal** [comment]
Hello @omry, I want to take this issue. Can please elaborate what exactly I need to do. Thank You!!

**Comment by omry** [comment]
Awesome, basically this is a cleanup pass for the examples under the examples directory, in particular examples that are mentioned in the documentation.

All of the documented examples should be tested, and most already are. see tests/test_examples in the repo for what is already there.
For example, this covers examples from the tutorials. but there are some gaps.
Another thing is to add a direct link to each example from the relevant documentation page. 
something similar to the "Example application" link in plugins ([Example](https://hydra.cc/docs/next/plugins/ax_sweeper)).
