### ISSUE TITLE
[Bug] Unable to instantiate classes with non primitive data types

### ISSUE THREAD

**Issue by rohitgirdhar** [facebookresearch/hydra#728]
# 🐛 Bug

Continuing from issue https://github.com/facebookresearch/hydra/issues/650 
I think the fix still doesn't seem to work for me. Here's a MWE that crashes for me, with the current master (0ccc2aad)

## To reproduce

```python
from omegaconf import OmegaConf
import torch
import hydra

data_config = {
    "target": "torchvision.datasets.Kinetics400",
    "params": {
        "root": "/path/to/data",
        "frames_per_clip": 32,
    }
}

config = OmegaConf.create(data_config)
dataset = hydra.utils.instantiate(config, _precomputed_metadata={'a': torch.Tensor([1, 2, 3])})
```

** Stack trace/error message **

```
Error instantiating 'torchvision.datasets.Kinetics400' : Value 'Tensor' is not a supported primitive type
        full_key: _precomputed_metadata.a
        reference_type=Optional[Dict[Any, Any]]
        object_type=dict
omegaconf.errors.UnsupportedValueType: Value 'Tensor' is not a supported primitive type
        full_key: _precomputed_metadata.a
        reference_type=Optional[Dict[Any, Any]]
        object_type=dict
```

## Expected Behavior

It should be able to instantiate the object. While this example is simple (and I could perhaps cast the tensor to list and pass it in), in practice that tensor will be huge and converting it to a primitive lists will be prohibitively slow.

## System information
- **Hydra Version** :  1.0rc1
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Linux

**Comment by omry** [comment]
Thanks for reporting.
I did a cleanup pass in that area and handled this case in #729. let me know if you see anything else.
