### ISSUE TITLE
Clean up instantiate

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#731]
instantiate for classes only
call for callables.
### instantiate
```
foo:
  type: ...
```
```python
object = instantiate(cfg.foo)
```

### call
```
foo:
  callable: ...
```
```python
ret = call(cfg.foo)
```

for backward compatibility, instantiate and call should still support both inputs but issue deprecation warning if the wrong input is specified.

**Comment by shagunsodhani** [comment]
Based on the meeting today, the new goals are:

- `type`/`callable` key will not be introduced.
- `call` and `instantiate` would be aliases.
- Add support for return `None` when config is `None`.
- Improve the documentation:
  -  Split the documentation into two parts: (i) a short description and a longer, more technical version

**Comment by omry** [comment]
Can you create a new task? It seems like it would be better than to repurpose this task.

**Comment by shagunsodhani** [comment]
Closing in favor of https://github.com/facebookresearch/hydra/issues/764
