### ISSUE TITLE
Creating list of configs?

### ISSUE THREAD

**Issue by jgbos** [facebookresearch/hydra#736]
I was wondering if it's possible to do something like this:
```bash
python myapp.py option=[foo,bar]
```

That is, making `option` a list of configurations.

I'd like to also support the basic approach of
```bash
python myapp.py option=foo
```

**Comment by omry** [comment]
please describe what you mean by "list of configurations".
it looks like a list of strings to me.

**Comment by jgbos** [comment]
I'm questioning my own intent now.  I'm not sure the right terminology, but essentially `foo` and `bar` have their own YAML files under the `option` package.  I might want to provide a list of methods to the application.  Not my use case, but maybe this could be providing a list of torchvision transforms.  I think it would be equivalent to this:

```yaml
option:
  - <foo>
  - <bar>
```

On another note, if I had defined `option` as

```yaml
option:
  cls: <method that handles list of methods>
  params:
    fns:
      - <foo>
      - <bar>
```
is there a method to override any parameters in `foo` or `bar` on the command line.  I think the answer is no.

**Comment by omry** [comment]
I see.
This is essentially #499 that I am hoping to tackle with 1.1.

closing as dup.

**Comment by omry** [comment]
@jgbos , I missed your second question:
you can override list variables by using the index as the key:
```
option.cls.params.fns.0=oompa
```
would override <foo>
