### ISSUE TITLE
[Bug] Setting hydra/output_subdir = None still logs .yaml files in a folder called "None"

### ISSUE THREAD

**Issue by numpee** [facebookresearch/hydra#740]
# 🐛 Bug

Basically the title. 
I've disabled hydra/job logging (set default to disabled) and set the output_subdir = None in the hydra.yaml file. 
However, now I get a new folder called None/None where all the config yaml files are stored. I've tried setting it to empty string "", and also null, but none of these seem to work. :(

## Expected Behavior
No generation of new folders at all (to store yaml files)

## System information
- **Hydra Version** :  0.11.3
- **Python version** : 3.5
- **Virtual environment type and version** : virtualenvwrapper
- **Operating system** : Ubuntu 16.0.4

**Comment by omry** [comment]
This is a feature of Hydra 1.0 which is a pre-release now, you will have to upgrade to it (1.0.0rc1 currently).

Note that it requires Python 3.6 and newer.
