### ISSUE TITLE
[Bug] Config search path for hydra apps

### ISSUE THREAD

**Issue by jan-matthis** [facebookresearch/hydra#742]
# 🐛 Bug

For packaged hydra apps, `pkg://` rather than `file://` should be used in the config search path. 

## To reproduce

Install `hydra_app` and run `hydra_app --info`.

## Stack trace/error message

```
Config search path
******************
| Provider | Search path        
--------------------------------------------------------------------------------------------
| hydra    | pkg://hydra.conf  
| main     | file:///Users/jm/Git/hydra/examples/advanced/hydra_app_example/hydra_app/conf 
| schema   | structured:// 
--------------------------------------------------------------------------------------------
```

## Expected Behavior

```
Config search path
******************
| Provider | Search path  
--------------------------------------------------------------------------------------------
| hydra    | pkg://hydra.conf
| main     | pkg://hydra_app.conf
| schema   | structured://
--------------------------------------------------------------------------------------------
```

## System information
- **Hydra Version** :  `master` at `dc8bed5a4d4a0324357f5baeae97962e759cdc6b`
- **Python version** :  `3.7.7`
- **Virtual environment type and version** : `conda`
- **Operating system** :  macOS

## Additional context

Using `pkg://` rather than `file://` would e.g. help with making configurations accessible across machines when using remote launchers where `file://`-based paths may differ.

**Comment by omry** [comment]
how did you install the app? `pip install` or `pip install -e` ?

**Comment by jan-matthis** [comment]
The output above was using `pip install .` from inside `examples/advanced/hydra_app_example/`. 

With `pip install -e .` I'd get `file://path_to_git_repo/examples/...`.

**Comment by omry** [comment]
let me ask it in another way:
if you package a wheel, and pip install it, does it depend on the directory where you packaged it?

try this:
1. package a wheel.
2. move it to /tmp
3. rename the directory
4. install and run the wheel. does it work or not?

**Comment by jan-matthis** [comment]
It will use `file://` to point to the `site-packages` folder (no reference to `/tmp`). However, I would have expected usage of `pkg://` (as done for `hydra` itself). How could that be achieved?

**Comment by omry** [comment]
I would have expected it too, but for some reason the logic detects this as a file run.
feel free to dig into the detection logic to see why. this is low pri for now because it seems to be working fine regardless.

**Comment by omry** [comment]
#750 fixes it but this is sensitive. I may have to revert if it end up causing issues.
