### ISSUE TITLE
how to pass a list as argument?

### ISSUE THREAD

**Issue by SirWyver** [facebookresearch/hydra#743]
Hi there,
what is the syntax to overwrite a config parameter by a primitive list like:
```python
python train.py --gpus='[0,1]'
```
I keep getting an error that it is interpreted as a sweeper override.
```python
'gpus=[0,1]'  is a sweeper override, did you forget to to use --multirun|-m ?
```

**Comment by omry** [comment]
What version are you on?

**Comment by SirWyver** [comment]
I am using Hydra 1.0

**Comment by omry** [comment]
No, you are using master.

**Comment by SirWyver** [comment]
True, you are right. So is it possible?

**Comment by omry** [comment]
It will be possible soon on master, and much more.
https://docs.google.com/document/d/1OELdhAe8jWfNLioqjfRaMcmh56vnzIwUNA0Id9aRIOQ/edit#

This is a regression in master, rc1 should allow that (although it's really partial support).

**Comment by SirWyver** [comment]
great, looking forward to it!

**Comment by omry** [comment]
working on it as we speed, it's a very big change.

**Comment by tnwei** [comment]
For those landing here from Google search, pass lists as arguments like so:
```
foo=[1,2,3]
nested=[a,[b,[c]]]
```

(from the relevant docs page at https://hydra.cc/docs/advanced/override_grammar/basic/#lists)

**Comment by Jasha10** [comment]
Also relevant are Hydra's docs on [Quoted values](https://hydra.cc/docs/1.1/advanced/override_grammar/basic/#quoted-values).
