### ISSUE TITLE
Upgrade to isort 5.0

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#751]

**Comment by omry** [comment]
Marked as good first issue, keep in mind that it could be harder than it sounds.

**Comment by roopeshvs** [comment]
@omry Is this still open? If yes, please elaborate on the pitfall that makes it harder. I would like to work on it.

**Comment by omry** [comment]
Hi @roopeshvs.
Yes, it's still open.
The Hydra repository contains multiple different codebases, in particular the plugins are standalone packages.
This means that the rules to decide if something is a third party dependency changes per plugin.
There is also some generated code which should be excluded from formatting.
give it shot!

**Comment by roopeshvs** [comment]
Would each plugin having its own do .isort.conf with appropriate third party dependencies do the trick?

**Comment by omry** [comment]
Seems reasonable to require it from plugins.

**Comment by vporta** [comment]
@omry I saw this issue and read the isort 5.0+ upgrade docs. It says only one isort config file per project for the new version and more than one will be merged into one. I can open a PR for you to review since I worked on this a bit today

**Comment by omry** [comment]
@vporta, that would be great.
please note that I use nox to drive the linting, and I want to automatically (or almost automatically) discover plugins, tools and examples - as is the case now.

see noxfile.py to understand the current logic.

**Comment by omry** [comment]
done.
