### ISSUE TITLE
[Bug] Empty config raises an AssertionError

### ISSUE THREAD

**Issue by odelalleau** [facebookresearch/hydra#757]
# 🐛 Bug

With a basic Hydra app loading an empty config.yaml, the error message is a bit cryptic (AssertionError)

## To reproduce

** Minimal Code/Config snippet to reproduce **

Run https://github.com/facebookresearch/hydra/blob/master/examples/tutorials/basic/your_first_hydra_app/2_config_file/my_app.py with an empty `config.yaml`

** Stack trace/error message **
```
...
    assert isinstance(obj, (list, dict, str))
AssertionError
```

## Expected Behavior

Either working as if the config was empty, or raising an explicit "Config is empty" error.

## System information
- **Hydra Version** :  1.0.0rc1
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Linux

**Comment by omry** [comment]
This is an OmegaConf bug. moved [here](https://github.com/omry/omegaconf/issues/297).
