### ISSUE TITLE
[Bug] With a List[int] config option (structured config), a single integer is still parsed as an integer

### ISSUE THREAD

**Issue by odelalleau** [facebookresearch/hydra#758]
# 🐛 Bug

Let's say you have a structured config with a single `List[int]` option named `fudge`:

```
@dataclass
class Config(DictConfig):
    fudge: List[int] = field(default_factory=lambda: [])
```

I would expect an error when running `python hydra_basic.py fudge=1`, however it runs fine and `fudge` becomes the integer `1` instead of being a list.

## To reproduce

```
from dataclasses import dataclass, field
from typing import List

import hydra
from hydra.core.config_store import ConfigStore
from omegaconf import DictConfig


@dataclass
class Config(DictConfig):
    fudge: List[int] = field(default_factory=lambda: [])


@hydra.main(config_name="config")
def my_app(cfg: DictConfig) -> None:
    print(cfg.fudge, type(cfg.fudge))


if __name__ == "__main__":
    cs = ConfigStore.instance()
    cs.store(name="config", node=Config)
    my_app()
```

Run `python app.py fudge=1`

** Stack trace/error message **
```
1 <class 'int'>
```

## Expected Behavior
An explicit error should be raised

## System information
- **Hydra Version** :  current master (c82241ce107328894c77e9349f074acac4678af6)
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Linux

**Comment by omry** [comment]
Nice catch.
This is an OmegaConf bug, here is how you reproduce it without Hydra (I suggest you go through the OmegaConf slides to learn more about it if you haven't already (link in the README at https://github.com/omry/omegaconf).

Can you open a new issue for OmegaConf?

Here is how you reproduce this without Hydra:
```
from dataclasses import dataclass, field
from typing import List
from omegaconf import OmegaConf

@dataclass
class Config:
    fudge: List[int] = field(default_factory=lambda: [])

cfg = OmegaConf.structured(Config)

cfg.fudge = 1
```

**Comment by odelalleau** [comment]
Moved to OmegaConf (https://github.com/omry/omegaconf/issues/300) => will close this one
