### ISSUE TITLE
[Bug] Using --help can be very slow

### ISSUE THREAD

**Issue by odelalleau** [facebookresearch/hydra#759]
# 🐛 Bug

Running `python app.py --help` can be very slow, probably because it seems to be scanning all subfolders.

## To reproduce

** Minimal Code/Config snippet to reproduce **

Run https://github.com/facebookresearch/hydra/blob/master/examples/tutorials/basic/your_first_hydra_app/1_simple_cli/my_app.py with `--help` in a folder that has lots of other folders / files in it.

** Stack trace/error message **

Example:

```
my_app is powered by Hydra.

== Configuration groups ==
Compose your configuration from those groups (group=option)

h: config
h/outputs/2020-07-13/05-54-45/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-16-49/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-17-13/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-22-06/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-22-29/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-23-14/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-28-06/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-29-45/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-29-51/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-29-54/.hydra: config, hydra, overrides
i/outputs/2020-07-13/09-31-29/.hydra: config, hydra, overrides
multirun/2020-07-02/16-25-01: multirun
multirun/2020-07-02/16-25-01/0/.hydra: config, hydra, overrides
multirun/2020-07-02/16-25-01/1/.hydra: config, hydra, overrides
multirun/2020-07-02/16-25-01/2/.hydra: config, hydra, overrides
outputs/2020-06-30/09-24-55/.hydra: config, hydra, overrides
outputs/2020-06-30/09-25-56/.hydra: config, hydra, overrides
outputs/2020-06-30/09-26-18/.hydra: config, hydra, overrides
outputs/2020-06-30/09-26-33/.hydra: config, hydra, overrides
outputs/2020-06-30/09-30-21/.hydra: config, hydra, overrides
outputs/2020-06-30/09-30-26/.hydra: config, hydra, overrides
outputs/2020-06-30/09-34-27/.hydra: config, hydra, overrides
outputs/2020-06-30/10-31-57/.hydra: config, hydra, overrides
outputs/2020-06-30/10-35-32/.hydra: config, hydra, overrides
outputs/2020-06-30/10-38-02/.hydra: config, hydra, overrides
outputs/2020-06-30/12-47-27/.hydra: config, hydra, overrides
outputs/2020-06-30/12-47-56/.hydra: config, hydra, overrides
outputs/2020-06-30/13-25-31/.hydra: config, hydra, overrides
outputs/2020-06-30/13-25-42/.hydra: config, hydra, overrides
outputs/2020-06-30/13-45-40/.hydra: config, hydra, overrides
outputs/2020-06-30/13-49-22/.hydra: config, hydra, overrides
outputs/2020-06-30/13-49-34/.hydra: config, hydra, overrides
... (there are more in my folder)

== Config ==
Override anything in the config (foo.bar=value)

{}


Powered by Hydra (https://hydra.cc)
Use --hydra-help to view Hydra specific help
```

## Expected Behavior
A quick help message not cluttered by lots of irrelevant data

## System information
- **Hydra Version** :  master (c82241ce107328894c77e9349f074acac4678af6)
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Linux

**Comment by omry** [comment]
Do you add your current working directory to the search path?

This is the expected behavior. You should keep only configs in your config search path. in some simple cases the config directory overlaps with your code directory, but even in those cases you should have a module:

```
module/
   app.py
   config.yaml

$ python module/app.py
```

**Comment by odelalleau** [comment]
Ok I understand the reason now, it's because `.` is in the default config search path. I agree that in most cases the folder containing your script shouldn't contain a lot of files / sub-folders (and otherwise that you should store your configs elsewhere). In my case this happened because I was just testing stuff in a temporary location. It's definitely something you can avoid easily in practice but that's going to happen to other people who are just getting started with Hydra and may not understand what is happening.
Hopefully people running into this problem will search about it and find this issue, then just change their config path :) Otherwise, a potential "fix" could be to try and detect such situations to warn the user if the help can't be displayed after e.g. 10s because it's scanning tons of files.

**Comment by omry** [comment]
Yeah, if this becomes a repeating issue I will think about detecting it.
it's not so simple because there are multiple config sources and some of them can potentially be slower (if they are making a network call to list/get the config, as an example).
No such ConfigSources exists right now, but the abstraction is there and will be used.
