### ISSUE TITLE
[Feature Request] Automatic output redirection to files

### ISSUE THREAD

**Issue by odelalleau** [facebookresearch/hydra#760]
# 🚀 Feature Request

It could be handy for Hydra to provide a way to automatically redirect all stdout / stderr to files.

## Motivation

It's common to either (i) run jobs locally whose output is manually redirected with >& some_log for inspection, or (ii) run jobs on a cluster whose output is redirected to some files by the cluster management system.
If Hydra took care of it no manual step would be required and all output files could be in a consistent location regardless of how the job was run.

## Pitch

**Describe the solution you'd like**

`python my_app.py hydra/autologs=1` or something similar.

**Describe alternatives you've considered**

Current alternatives are those listed in "Motivation"

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

Not sure at this point as it's unclear to me how easy / difficult this would be.

**Comment by omry** [comment]
Thanks, I will look into it for a future version.
This may be a tricky one to achieve. If your application is launching a subprocess you will likely need to redirect it's output somehow yourself (possibly to the stdout and stderr of the current process).

**Comment by jan-matthis** [comment]
[`capturer`](https://pypi.org/project/capturer/) could be useful for this. The docs also include a discussion of design choices and alternatives.

**Comment by omry** [comment]
Thanks @jan-matthis. This can be useful if there is a way to enable it as a plugin, I don't think this functionality deserves an additional dependency.
Such a plugin might be possible in the near future though.

**Comment by omry** [comment]
The approach Hydra takes to logging is that you should be using the Python logging system (by default, the configuration includes logging to a file in the generated output directory).
I don't think something like this makes sense for Hydra. It seems very tricky and this has not came up as a significant pain point in the ~year since this issue was created.

Closing. Feel free to followup if you want to discuss further.
