### ISSUE TITLE
[Bug] Defaults Populated Structured Config

### ISSUE THREAD

**Issue by anthonytec2** [facebookresearch/hydra#768]
# 🐛 Bug

I am trying to create a top level structured configuration which is used to check my config.yaml.  At the moment, I cannot get the defaults to be populated and correctly working will null initializers. I created a sample of this here: https://github.com/anthonytec2/hydra/commit/38b94c57928f50f9f5ec196346dd445b5f96094c. Thing works when assigning defaults to be field(default_factory=lambda: defaults), but fails when assigned to MISSING. 

## To reproduce

** Stack trace/error message **
```
Cannot iterate a missing ListConfig
	full_key: defaults
	reference_type=List[Any]
	object_type=list
```

## System information
- **Hydra Version** :   1.0.0rc2
- **Python version** : 3.7.7
- **Virtual environment type and version** : 
- **Operating system** : Ubuntu 18.04

**Comment by omry** [comment]
Please create a zip file with a minimal rero. (app.py, and the relevant yaml config file).

**Comment by anthonytec2** [comment]
[struct.zip](https://github.com/facebookresearch/hydra/files/4922498/struct.zip)
