### ISSUE TITLE
[Bug] @hydra.main() does not preserve the function's return value

### ISSUE THREAD

**Issue by odelalleau** [facebookresearch/hydra#769]
# 🐛 Bug

Wrapping a function with `hydra.main()` makes it lose its return value.

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
import hydra

@hydra.main()
def my_app(cfg):
    return 0

if __name__ == "__main__":
    print(my_app())
```

** Stack trace/error message **
The above code prints `None` instead of `0`.

## Expected Behavior
I'd expect @hydra.main() to return the original return value.

One typical use case is when we want to exit the program with specific return codes indicating success / failure:

```
@hydra.main()
def my_app(cfg):
    ...
    return 0 if success else 1

if __name__ == "__main__":
    sys.exit(my_app())
```

## System information
- **Hydra Version** :  1.0.0rc1
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.7.10
- **Operating system** : Linux

**Comment by omry** [comment]
@hydra.main is not your average function.
The underlying may actually be executing multiple times in the case of multirun. in addition, @hydra.main will be configuring your logging, change your working directory, parse your command line and more.

When using `@hydra.main`, all your logic should be inside your function. your `__main__` stanza should contain just that call.

**Comment by odelalleau** [comment]
Ah, yes, multirun makes it harder to handle in a generic way.

**Comment by omry** [comment]
I also don't want to encourage people to start using it as a regular function because it has so many side effects.
```
@hydra.main(...)
def foo(cfg):
   return 10

# look ma! math!
assert foo() + foo() ==  20
```
