### ISSUE TITLE
[Feature Request] Detect missing arguments in multirun before actually launching the job(s)

### ISSUE THREAD

**Issue by odelalleau** [facebookresearch/hydra#776]
# 🚀 Feature Request

With `--multirun`, fully validate the config (in particular for potentially missing arguments) of all jobs before launching them.

For instance, with the following script:

```
from dataclasses import dataclass

import hydra
from hydra.core.config_store import ConfigStore

from omegaconf import MISSING


@dataclass
class MySQLConfig:
    host: str = MISSING
    port: int = 3306


cs = ConfigStore.instance()
# Registering the Config class with the name 'config'.
cs.store(name="config", node=MySQLConfig)


@hydra.main(config_name="config")
def my_app(cfg: MySQLConfig) -> None:
    print(f"Host: {cfg.host}, port: {cfg.port}")


if __name__ == "__main__":
    my_app()
```

==> the following command line would fail before submitting anything to SLURM (while currently it doesn't): `python my_app.py hydra/launcher=submitit_slurm -m`

## Motivation

When launching with `--multirun` on a cluster for instance, it can take a long time (several hours) before these jobs actually start. If there is a missing argument it's best to know about it immediately rather than wait for the job to start.

## Pitch

**Describe the solution you'd like**

I'd like Hydra to run a validation pass on the config before running each job with `--multirun`, and fail immediately if any job has a missing argument (or any other config issues, for that matter -- I discovered this issue with missing arguments but I don't know if some other checks might be delayed as well).

**Describe alternatives you've considered**

Wait until the job is launched :)

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

No

**Comment by omry** [comment]
Since the sweeper determines what jobs to run, it's not obviously doable.
as an example, the optimizing sweepers are driving an optimization loop and you don't know the jobs it will launch in advance.

Let me think about it, it might be a feature request for individual sweepers (that will need to compose the config to see they succeed).

**Comment by odelalleau** [comment]
Oh ok, I haven't played with sweepers yet. But couldn't you validate the job config provided by the sweeper before launching the job on the cluster? (I'm assuming the sweeper runs locally and outputs jobs to be run on the cluster, but I may be totally wrong)

**Comment by omry** [comment]
which job? if the sweeper is generation jobs dynamically and it needs to run one job to generate the next?

**Comment by omry** [comment]
For simple sweepers it could be done, for optimizing sweepers like Ax and Nevergrad, not so much.

**Comment by odelalleau** [comment]
> which job? if the sweeper is generation jobs dynamically and it needs to run one job to generate the next?

Sure in that case you can’t do anything until the first job has completed. But Hydra could at least crash before the second one is queued on the cluster (if its config is invalid).

**Comment by odelalleau** [comment]
Also I expect that many failure cases can be caught just by validating the first job's config, so even just this partial check could be useful already.

**Comment by omry** [comment]
I will try to improve this a bit for 1.0.

**Comment by omry** [comment]
I don't think composing the first config is a good proxy for anything meaningful.  I don't want a system that sometimes works and sometimes not depending input order.

**Comment by odelalleau** [comment]
> I don't think composing the first config is a good proxy for anything meaningful. I don't want a system that sometimes works and sometimes not depending input order.

Fair enough. In that case the alternative of launching only valid jobs and displaying an error for jobs that are skipped due to invalid configs would already be very useful, and (at least in theory) should work regardless of the sweeper logic.
