### ISSUE TITLE
Commandline interpolation by indexing lists

### ISSUE THREAD

**Issue by senthilps8** [facebookresearch/hydra#789]
I recently switch to using the master branch due to #748 .
It looks like the commandline syntax has changed and it doesn't seem possible to do interpolation by indexing lists (or I couldn't figure it out).

For example, for a config containing:
```
listconf: [2,3]
newlistconf: [3,4]
```

In v0.11, I could do `python main.py newlistconf.0=\${listconf.0}`
But now, on master, this throws the following error:
```
Error parsing override 'newlistconf.0=${listconf.0}' : extraneous input '.0' expecting '='
```

Even `python main.py newlistconf=\${listconf.0}`, throws the following error:
```
Error parsing override 'newlistconf=${listconf.0}' : mismatched input '{' expecting <EOF>
```

Can you let me know if there's a new syntax for doing this? I couldn't figure it out from [https://github.com/facebookresearch/hydra/blob/master/hydra/grammar/Override.g4](url)

Thanks!

**Comment by omry** [comment]
Thanks for reporting. I will take a look.
