### ISSUE TITLE
Hydra returns empty config for .yml files.

### ISSUE THREAD

**Issue by terraflops1048576** [facebookresearch/hydra#80]
Hydra produces an empty config when the file has a .yml extension as opposed to a .yaml extension.

A minimal reproduction is here:
hydra_test.py
```
import hydra
class A:
    def __init__(self, **kwargs):
        print(kwargs)


@hydra.main('./config_test.yml')
def main(cfg):
    print(cfg)
    print(cfg.obj_test)
    print("ASDFASDFASDFAFSD")
    hydra.utils.instantiate(cfg.obj_test)


if __name__ == '__main__':
    main()
```

config_test.yml / config_test.yaml
```
obj_test:
  class: hydra_test.A
  params:
    a: 123
    b: 421
```

Put both of these files into the same folder and run with `python hydra_test.py`

**Comment by omry** [comment]
Hi @terraflops, I am probably going to drop support for .yml files in the next version.
This is getting in the way on something else which is fairly complicated.
