### ISSUE TITLE
[Feature Request] Sweep over files

### ISSUE THREAD

**Issue by charleswilmot** [facebookresearch/hydra#804]
# 🚀 Feature Request

## Motivation

It would be super convenient to autonomously replace wildcards like when using the multirun functionality:
```
python script.py --multirun path=../results/*/checkpoints/* explore=True,False
```
Would then apply the script on all files matched twice, once with explore=True, once with explore=False

**Comment by omry** [comment]
You can achieve this through interpolation, note that I single quote the path so it won't get interpreted by the shell.

```
python examples/tutorials/basic/your_first_hydra_app/1_simple_cli/my_app.py --multirun '+path=../results/${explore}/checkpoints/${explore}' +explore=True,False
```

Please note that by default when printing a configuration with pretty() interpolations are not resolved, so it will look like this didn't work.
you can print with cfg.pretty(resolve=True), or alternatively you can access the actual field and print it.
```diff
 @hydra.main()
 def my_app(cfg: DictConfig) -> None:
-    print(cfg.pretty())
+    print("path:", cfg.path)
```

```
python examples/tutorials/basic/your_first_hydra_app/1_simple_cli/my_app.py --multirun hydra/hydra_logging=disabled '+path=../results/${explore}/checkpoints/${explore}' +explore=True,False
path: ../results/True/checkpoints/True
path: ../results/False/checkpoints/False

```
