### ISSUE TITLE
[Feature Request] Add support for some features from gin-config

### ISSUE THREAD

**Issue by roytseng-tw** [facebookresearch/hydra#805]
# 🚀 Feature Request

Support some features in [gin-config](https://github.com/google/gin-config)
- Passing functions, classes, and instances ("configurable references") as a config node for `instantiate`
- Configuring the same function in different ways ("scopes")

This way, hydra will be super powerful. 

## Motivation

For example when instantiate an optimizer, net parameters to be optimized are passed as an argument.
Hope to specify which parameters to be passed in the config file. 

## Pitch

Take gin-config code for example
- python code
```python
@gin.configurable
class DNN(nn.Module):
    def __init__(num_layers):
         ...

@gin.configurable
def get_parameter(net):
    return net.parameters()

gin.external_configurable(torch.optim.Adam)

@gin.configurable
def trainer(optim1, optim2):
    ...
```

- gin config file
```
dnn1/DNN.num_layers = 5
dnn2/DNN.num_layers = 10 

dnn1/get_parameter.net = @dnn1/DNN
dnn2/get_parameter.net = @dnn2/DNN

torch.optim.Adam.lr = 0.01
dnn1/torch.optim.Adam.params = @dnn1/get_parameter()
dnn2/torch.optim.Adam.params = @dnn2/get_parameter()

trainer.optim1 = @dnn1/torch.optim.Adam
trainer.optim2 = @dnn2/torch.optim.Adam
```

## Additional context
More detailed description about gin-config
https://github.com/google/gin-config/blob/master/docs/index.md

**Comment by omry** [comment]
Hi Roy,
Thanks for the suggestion.
Hydra takes a different approach where the user is responsible for passing your configuration around and using it appropriately.
I don't subscribe to the idea of automatically binding configuration with code, I think it's causes more problems than it's worth.
There are some problems the gin-config approach is creating, for example - what do you do when you want to configure two instances of the same class with two different configs - that does not have solutions I find elegant enough in gin.
This is a very basic use case in my opinion and should not require the use case for any advanced features (as is the case with gin: I believe gin scopes are handling it).

I am happy to continue the discussion in the Hydra chat (I am actually interested in learning about gin-config from a proficient user). But I don't believe Hydra will ever take this approach.
