### ISSUE TITLE
[Feature Request] Instantiate objects that require positional-only arguments

### ISSUE THREAD

**Issue by NTL-Remi** [facebookresearch/hydra#808]
# 🚀 Feature Request

Hello,
I propose to add the ability to specify positional-only arguments for object instantiation.

## Motivation

**Is your feature request related to a problem? Please describe.**
Since Python 3.8, and more precisely [PEP 570](https://www.python.org/dev/peps/pep-0570/), it is possible to define functions that forbid passing arguments by name.
From what I have seen from the [docs](https://hydra.cc/docs/next/patterns/instantiate_objects/instantiate_objects_reference) and the code ([call()](https://github.com/facebookresearch/hydra/blob/650cfc8ae2ac124e43cf78fff9f0d90daed8c74b/hydra/utils.py#L22), [_instantiate_class()](https://github.com/facebookresearch/hydra/blob/650cfc8ae2ac124e43cf78fff9f0d90daed8c74b/hydra/_internal/utils.py#L478) and [_get_kwargs()](https://github.com/facebookresearch/hydra/blob/650cfc8ae2ac124e43cf78fff9f0d90daed8c74b/hydra/_internal/utils.py#L543)) it is only possible to assign a dict-like structure to the `params` key in the YAML file, that will end up being passed as `**kwargs`, so there is currently no way to give positional-only arguments through config files.

## Pitch

**Describe the solution you'd like**
Replacing the `params` key by `args` and  `kwargs`, taking respectively  a list and a dict.
This will be breaking existing code, so maybe keep `params` as an alias to `kwargs`.
I leave open the question of whether the pass-through `args` should append, prepend or override the config `args`.

**Describe alternatives you've considered**
On the user side, wrapping each class or function that needs it in an adapter class/function that takes the same arguments but without the positional-only restriction.
I can see that getting tedious, and it kind of defeats PEP 570 's purpose.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md)) <= _btw, this link from the template is broken_
Maybe, if I have time.

**Comment by shagunsodhani** [comment]
Thanks for the feature request. One problem I see is that we support Python 3.6 and 3.7 as well while position arguments are only supported since Python 3.8

**Comment by remisphere** [comment]
Well 3.6 and 3.7 still accept positional arguments, they are just not **mandatorily** positional.
So regarding the python version, there is no backward compatibility problem.

**Comment by remisphere** [comment]
Sorry, I am the same person, just answering from another account ><

**Comment by shagunsodhani** [comment]
Oops :) I think I misunderstood the motivation. I assumed that you were requesting support for "positional-only" parameters.

**Comment by remisphere** [comment]
No, but from what I understand of the code, it is currently not possible to instantiate objects that have an `__init__` with positional-only arguments.

**Comment by omry** [comment]
Thanks for the feature request.
The surface area of the instantiate method is already quite large and I am not sure this is worth the added complexity. Especially given that we plan to make the surface area even larger by supporting recursive instantiation (#566).

One workaround that you can employ now which is to use a static or class method as a factory, that will delegate the parameters appropriately for the underlying method.

I am going to keep it as a wishlist item, but this is not something that is likely to be added in the near future.
If this item gets many upvotes I may reconsider.

**Comment by omry** [comment]
Let's put a timeout of 12 months on this feature request. if there is no significant interest in 12 months I will close this.
