### ISSUE TITLE
[Feature Request] Saving Ax optimization result

### ISSUE THREAD

**Issue by jgbos** [facebookresearch/hydra#810]
# 🚀 Feature Request

I have found it useful to save out the optimization state of Ax for loading the trial results and the model fit to the data using

```python
ax_client.save_to_json_file()
```

The same command will also provide snapshots during the optimization.

## Motivation

**Is your feature request related to a problem? Please describe.**

No problem, just a way to add more information for the user.

## Pitch

**Describe the solution you'd like**

In `_core.py` of the plugin the command above can be added in the `sweep` method both in the trial loop and before exit.  Although this will save the file in the original working directory.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../CONTRIBUTING.md))

Yes, I can do that if you want.  Need to solve the save location though.

**Comment by jgbos** [comment]
This might be related to #468

**Comment by shagunsodhani** [comment]
I think it can be saved in the [output directory](https://hydra.cc/docs/next/configure_hydra/workdir).

**Comment by omry** [comment]
@jgbos, can you give more info about how you want to use this information?
Also, the optimization is iterative and the intermediate state is changing constantly. Are you just interested in the latest state or all of them?

**Comment by omry** [comment]
I believe Ax supports different backends for storing the optimization state, we should be able to allow configuring it. would that work?

**Comment by jgbos** [comment]
I'm new to Ax so learning, but currently just generating the plots as shown here:

https://ax.dev/tutorials/gpei_hartmann_service.html

It's useful to see what the model learned.

I haven't played with the snapshots it saves out, but the overall optimization takes a while to run.  I could look at the snapshot to see the current state.  

Also, I haven't tested this idea, is it possible to resume an optimization from a saved snapshot?

**Comment by jgbos** [comment]
Yes, I was thinking it could just be configurable if you wanted it.

**Comment by shagunsodhani** [comment]
> I believe Ax supports different backends for storing the optimization state, we should be able to allow configuring it. would that work?

Another possibility is that the user can register a function that is called at the start/end of the optimization process. Something along the lines of `setup` and `teardown` in pytest.

**Comment by omry** [comment]
> > I believe Ax supports different backends for storing the optimization state, we should be able to allow configuring it. would that work?
> 
> Another possibility is that the user can register a function that is called at the start/end of the optimization process. Something along the lines of `setup` and `teardown` in pytest.

This is something that will be possible with Lyfecycle plugins once they are added. but I don't think it's a good solution here. it's more for plugin authors than for end users.

**Comment by omry** [comment]
> Also, I haven't tested this idea, is it possible to resume an optimization from a saved snapshot?

Not currently.

**Comment by jgbos** [comment]
Oh sorry, I know the plugin doesn't support continuing from a snapshot, I just wasn't sure if Ax supported it.  If it does, that's a reason to save out the snapshot.

**Comment by omry** [comment]
That is a question for the Ax project.
Even if it did, it does not automatically means Hydra would support it too.

**Comment by jgbos** [comment]
Agreed, just providing a possible justification for saving the snapshot, not that I'm asking you to support continuing from a snapshot!  Obviously I can update the plugin for my personal needs (that's what I'm currently doing).  Just thought this might be a good feature for other users.

Go ahead and close this if it's beyond the scope of your project.

**Comment by omry** [comment]
Thanks for suggestion @jgbos. Your feedback is valued.
At this point the plugin is not yet mature and there are some changes planned. I prefer to hold off any additional features until we are on stable ground.

There are less obvious considerations at play as well:
1. Hydra is offering an interface for multiple optimizers (two at this time, probably more later). From a UX perspective it's best to try to keep them similar unless the deviation really justifies it. (this is related to the changes I mentioned above).
2. This seems like a half baked idea at this stage, as you pointed out there would be more concrete value if and when the the plugin can support automatic resume. but to be honest - something like this would be much better served by Ax itself (and should be enabled via the plugin).

I think it's good that you are tweaking the plugin,  If you have found some really valuable feature feel free to file an issue for it.

**Comment by omry** [comment]
closing for now..

**Comment by 2timesjay** [comment]
@jgbos @omry To answer some Ax Qs: Ax saves the complete history of the experiment, so that could be used for visualization purposes. Our API supports resuming at the most recent step and it would be a small extension to support resuming from any step. 

The save/load API (which includes that @jgbos found above but is more extensive if you need sqlalchemy integration) is the main mechanism we use for this.

We're happy to help support extending the plugin.

**Comment by jgbos** [comment]
@2timesjay Great! I haven't had a need to resume optimization yet, but I can see it in my future.  Right now the `json` file is good enough for what I need (mainly just load into a notebook and generate the plots and look at the experiments)  

To resume, do you just need to load in the snapshot before launching the job?

**Comment by omry** [comment]
Revisiting this during the HPO output audit: this request is related to the common sweeper result contract tracked in https://github.com/facebookresearch/hydra/issues/468. Ax-specific persistence should not be added independently of that design. If optimizer state, or a reference to backend state, belongs in Hydra's result surface, it should be specified there across HPO sweepers.
