### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by binh-vu** [facebookresearch/hydra#813]
# 🚀 Feature Request

Don't capture exception when running hydra application in debug mode in pycharm.

## Motivation

When developing algorithm, I often use debug mode in Pycharm, which stops the program right in the place where the exception is thrown. This makes debugging super easy and pleasing.

Right now, when encounters error, hydra kill the program using `sys.exit(1)`. It will be better if instead of exit the program, hydra re-throws the exception so the debugger can catch it. If the exception isn't catched, then the program exit as normal.

## Pitch

**Describe the solution you'd like**

It will be better if instead of exit the program, hydra re-throws the exception so the debugger can catch it. If the exception isn't catched, then the program exit as normal.

**Comment by omry** [comment]
Hydra is doing very specific exception handling. I absolutely do not want to let the exception fly to the shell.
Please try on 1.0.0rc2 or master to see what I am talking about. Generally Hydra error handling improved dramatically from 0.11.

Happy to continue the discussion here but I am not planning on doing it.

**Comment by binh-vu** [comment]
If you don't want to let the exception fly to the shell, we can check if the code is running in debug mode and re-throw the exception in that case (see [here](https://stackoverflow.com/questions/38634988/check-if-program-runs-in-debug-mode)). That will be better for people debugging the code (as they don't have to modify anything).

I am happy to submit a PR for that if you don't have time to do that. I think the only line that needs to be modified is `run_and_report` function in utils.py

**Comment by omry** [comment]
Sure, submit a PR and we can discuss over the code.
by the way: try to give meaningful titles to issues :)

**Comment by leonweber** [comment]
For anyone else coming here from  a google search:
`HYDRA_FULL_ERROR=1 ` allows the debugger to break at the exception when Hydra is used.

**Comment by WarmongeringBeaver** [comment]
I personally can't manage to have `breakpoint()`s caught when using the VSCode debugger, even when passing

```json
"pythonArgs": [
    "-Xfrozen_modules=off"
],
"env": {
    "HYDRA_FULL_ERROR": "1"
}
```
to `launch.json`.

Is there anything else needed? @omry
