### ISSUE TITLE
Speed up CircleCI mac os tests. 

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#817]
They are very slow, twice as time needed than Linux. :( 

Response from CircleCI:

The linux OS you are referring to is a Docker container, which uses a very base minimal version of a Linux image, as well as the dependencies you would normally need to run. Docker images can be multiple times faster than macOS or machine executors.

A macOS executor is a virtual machine that will spin up on request and contains a large amount of software for convenience when testing on macOS. We do expect macOS jobs to run slower than Docker jobs. I would ask that you investigate the testing framework for flags or variables that can be set to increase the speed or parallelism of the running test.

**Comment by omry** [comment]
probably not worth the effort now that we can split the CI job into parallel pipelines automatically.
