### ISSUE TITLE
[Bug] With compose API, there is no `HydraConfig`

### ISSUE THREAD

**Issue by turian** [facebookresearch/hydra#828]
# 🐛 Bug

I am using the compose API within a Jupyter notebook. However, there is no `HydraConfig` even after there is a `GlobalHydra`. (I want to use `HydraConfig.get().runtime.cwd`.)

## To reproduce

** Minimal Code/Config snippet to reproduce **

```
from hydra.experimental import compose, initialize

# global initialization
initialize(config_path="conf")
cfg = compose(config_name="config")
print(cfg.pretty())

from hydra.core.hydra_config import HydraConfig
assert HydraConfig.initialized()
```

** Stack trace/error message **
```
AssertionError
```

## Expected Behavior

I would expect that using the compose API, we could still access HydraConfig.

## System information
- **Hydra Version** : 1.0.0rc1 
- **Python version** : 3.7.7
- **Virtual environment type and version** : n/a
- **Operating system** : OSX

**Comment by omry** [comment]
This is not a bug.

runtime.cwd is only populated during a real Hydra run and will not be available in compose (what is the runtime.cwd for a compose anyway?).

The compose API now supports [returning the Hydra config](https://hydra.cc/docs/next/experimental/compose_api#api-documentation) which can help here, but it does still not (and will not) initialize the HydraConfig singleton:
A singleton does not play well with the ad-hoc nature of compose.

You can override things from the overrides list:

```python
compose(config_name="config", return_hydra_config=True, overrides=["hydra.runtime.cwd=."])
```

If you have access of the Hydra config via 
```
foo: ${hydra:bar}
```
you can override it in compose above to something like: `foo=${hydra.bar}'.
