### ISSUE TITLE
[Bug] example notebook on binder failed to build.

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#831]
# 🐛 Bug
to reproduce, click on launch binder link from the doc
https://hydra.cc/docs/next/advanced/jupyter_notebooks

stack trace from the binder console:
```
Building wheels for collected packages: hydra-core, antlr4-python3-runtime, PyYAML
  Building wheel for hydra-core (PEP 517): started
  Building wheel for hydra-core (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /srv/conda/envs/notebook/bin/python3.7 /srv/conda/envs/notebook/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpff7xyxzh
       cwd: /tmp/pip-req-build-rzr0b1rr
  Complete output (10 lines):
  running bdist_wheel
  running build
  running build_py
  running clean
  Generating parsers with antlr4
  running antlr
  Generating parser for Python3: ['java', '-jar', '/tmp/pip-req-build-rzr0b1rr/build_helpers/bin/antlr-4.8-complete.jar', '-Dlanguage=Python3', '-o', '/tmp/pip-req-build-rzr0b1rr/hydra/grammar/gen/', '-Xexact-output-dir', '-visitor', '/tmp/pip-req-build-rzr0b1rr/hydra/grammar/Override.g4']
  ===================================================================================
  | Unable to generate parsers: [Errno 2] No such file or directory: 'java': 'java' |
  ===================================================================================
  Building wheel for antlr4-python3-runtime (setup.py): started
  Building wheel for antlr4-python3-runtime (setup.py): finished with status 'done'
  Created wheel for antlr4-python3-runtime: filename=antlr4_python3_runtime-4.8-py3-none-any.whl size=141230 sha256=2addf0aa9b23342c36310e9e5291623a456acc78f2a2890851cadddd92ffc18b
  Stored in directory: /tmp/pip-ephem-wheel-cache-uzsoqfww/wheels/ca/33/b7/336836125fc9bb4ceaa4376d8abca10ca8bc84ddc824baea6c
  Building wheel for PyYAML (setup.py): started
  Building wheel for PyYAML (setup.py): finished with status 'done'
  Created wheel for PyYAML: filename=PyYAML-5.3.1-cp37-cp37m-linux_x86_64.whl size=393762 sha256=717fe48e2428266d08347c411d935a6c5ce495bd2b1067214e31bc2be89058c3
  Stored in directory: /tmp/pip-ephem-wheel-cache-uzsoqfww/wheels/5e/03/1e/e1e954795d6f35dfc7b637fe2277bff021303bd9570ecea653
Successfully built antlr4-python3-runtime PyYAML
Failed to build hydra-core
ERROR: Could not build wheels for hydra-core which use PEP 517 and cannot be installed directly
Removing intermediate container 13bba172cf7d
The command '/bin/sh -c ${KERNEL_PYTHON_PREFIX}/bin/pip install --no-cache-dir .' returned a non-zero code: 1
  ----------------------------------------
  ERROR: Failed building wheel for hydra-core
```

![Screen Shot 2020-07-28 at 12 35 18 PM](https://user-images.githubusercontent.com/4642412/88712581-cda1e100-d0ce-11ea-9b56-efdfc613791b.png)

**Comment by omry** [comment]
Looks like it does not have java there, which is now required to generate the antlr grammar.
we should either find a way to install it or otherwise move to a different service that allow it.

**Comment by omry** [comment]
can you reach out to then [here](https://binder.works/request-help) and see if there is a way to get Java there?

**Comment by shagunsodhani** [comment]
Just a fyi, I tried running it on colab. The url was well-formed: `https://colab.research.google.com/github/facebookresearch/hydra/blob/master/examples/jupyter_notebooks/compose_configs_in_notebook.ipynb` (more [here](https://colab.research.google.com/github/googlecolab/colabtools/blob/master/notebooks/colab-github-demo.ipynb). But it could not access `cloud_app` dir (in `with initialize(config_path="cloud_app/conf"):`).

**Comment by omry** [comment]
We can chat about collab, I tried and I don't think it's really checking-out the repo in your link. (try !ls and see that the config files are not there).

**Comment by shagunsodhani** [comment]
Ohh that is right. It does not have access to the files

**Comment by shagunsodhani** [comment]
I see a couple of workarounds while using binder: 

1. Put a separate requirements.txt in [`binder`](https://mybinder.readthedocs.io/en/latest/faq.html#can-i-put-my-configuration-files-outside-the-root-of-my-repository) folder. This file installs the latest hydra version from pip. I think this is the least disruptive option.

2. Using a docker file as described [here](https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html).

3. Make a separate repo for examples. `hydra/examples`

**Comment by omry** [comment]
cool, 1 sounds very reasonable to me. let's do it.

**Comment by shagunsodhani** [comment]
Do not know how to test on CI. for now, I tested locally.
