### ISSUE TITLE
[Bug] In some cases list with whitespace fails to parse

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#836]
Example:
```
$ python examples/tutorials/structured_configs/1_minimal/my_app.py '+param=[[a, 1, 2], [b, 2, 3]]'
no viable alternative at input '[[a, 1, 2], [': +param=[[a, 1, 2], [b, 2, 3]]
                                                                   ^
```

**Comment by nehalmamgain** [comment]
FYI, this issue still happens in Hydra `1.1.0`

**Comment by jieru-hu** [comment]
hi @nehalmamgain 
 could you try this 'param=[string1, string2]'

more tips on how to do commandline override can be found here https://hydra.cc/docs/next/advanced/override_grammar/basic/

**Comment by nehalmamgain** [comment]
@jieru-hu Hi, that results in the same error.
```
hydra.errors.OverrideParseException: no viable alternative at input '[string1,'
```
Only 'param=["string1","string2"]' (without whitespace) works.

**Comment by jieru-hu** [comment]
thanks for trying it out @nehalmamgain 
i'd suggest checking out the debugging tips in the doc I linked above. this is highly shell dependent.

**Comment by nehalmamgain** [comment]
@jieru-hu Thanks! I don't think the override or debugging section covers (removal of) whitespaces though.
I feel like this GH issue might be the only way for struggling users to find out.

**Comment by benrhodes26** [comment]
Bump. I hit this same error, and it's hard to avoid as the hydra override is auto-generated (by weights and biases)
