### ISSUE TITLE
[Bug] Quick start guide on Colab

### ISSUE THREAD

**Issue by Ceceu** [facebookresearch/hydra#839]
# 🐛 Bug

Unable to run a quick start guide on Colab.

## To reproduce

Just run this [Colab](https://colab.research.google.com/drive/11AF7sQW3A5xdL6hVf0NL_8-ke4iuxsAd?usp=sharing) example

** Stack trace/error message **
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-b7ef6b9d7e46> in <module>()
      7 
      8 if __name__ == "__main__":
----> 9     my_app()

2 frames
/usr/local/lib/python3.6/dist-packages/hydra/main.py in decorated_main()
     22                     task_function=task_function,
     23                     config_path=config_path,
---> 24                     strict=strict,
     25                 )
     26             except KeyboardInterrupt:

/usr/local/lib/python3.6/dist-packages/hydra/_internal/utils.py in run_hydra(args_parser, task_function, config_path, strict)
    143     config_dir, config_file = split_config_path(config_path)
    144     strict = _strict_mode_strategy(strict, config_file)
--> 145     task_name = detect_task_name(calling_file, calling_module)
    146     search_path = create_automatic_config_search_path(
    147         calling_file, calling_module, config_dir

/usr/local/lib/python3.6/dist-packages/hydra/_internal/utils.py in detect_task_name(calling_file, calling_module)
     71             task_name = calling_module
     72     else:
---> 73         raise ValueError()
     74 
     75     return task_name

ValueError: 
```

## Expected Behavior
1. Was expected that config.yaml is loaded automatically when I run my application;
2. the output should be like:
```python
$ python my_app.py
db:
  driver: mysql
  pass: secret
  user: omry
```

**Comment by omry** [comment]
This not supported and will not be supported.
@hydra.main() does many things that are incompatible with Jupyter notebooks.

What you can do, is to use the [Compose API](https://hydra.cc/docs/next/experimental/compose_api) inside your notebook to create a config object and call your @hydra.main() function with it (or any other function).

**Comment by omry** [comment]
Here is an [example notebook](https://github.com/facebookresearch/hydra/tree/master/examples/jupyter_notebooks).
The binder link is broken right now, but you should be able to check-out the repo and run it locally after you pip install the checked out repo.
