### ISSUE TITLE
[Bug] `HydraConfig.get().run.dir` different from actual cwd

### ISSUE THREAD

**Issue by SunQpark** [facebookresearch/hydra#840]
# 🐛 Bug

I discovered that `HydraConfig.get().run.dir` returns wrong working directory, when it is called some seconds after the initialization. It seems like the time-formatter in the `hydra.run.dir` is being evaluated when HydraConfig.get() is first called, not when hydra is being initialized. 

## To reproduce
```python3
import time
from pathlib import Path
import hydra
from hydra.utils import get_original_cwd
from hydra.core.hydra_config import HydraConfig


@hydra.main(config_path='conf/', config_name='db')
def main(_):
    actual_cwd = Path.cwd()
    print(actual_cwd.relative_to(get_original_cwd()))
    # outputs/2020-07-31/16-27-21

    time.sleep(3)

    hydra_cwd = HydraConfig.get().run.dir
    print(hydra_cwd)
    # outputs/2020-07-31/16-27-24 -> this should be same as above

if __name__ == '__main__':
    # pylint: disable=no-value-for-parameter
    main()
```

## Expected Behavior
written in code abobe

## System information
- **Hydra Version** :  1.0.0rc1
- **Python version** : 3.7.7
- **Virtual environment type and version** : 
- **Operating system** : Ubuntu 18.04.3 LTS

**Comment by omry** [comment]
Thanks. please test on latest Hydra 1.0 (rc2 or master).

**Comment by omry** [comment]
Can you explain why you are accessing hydra.run.dir here instead of just using `os.getcwd()` or better yet just rely on the fact that your cwd is allocated and unique and save relative files?

**Comment by SunQpark** [comment]
> Can you explain why you are accessing hydra.run.dir here instead of just using `os.getcwd()` or better yet just rely on the fact that your cwd is allocated and unique and save relative files?

Because I wanted to print cwd as **relative path** and doing so with `os.getcwd()` or `Path.cwd()` needed extra step (converting it to relative path).

I'll test on latest version and comment again.

**Comment by SunQpark** [comment]
It works OK on `1.0.0rc2`. Thanks
