### ISSUE TITLE
Plugin commands start with a $ which is copied when using the `copy` button.

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#846]
# 🐛 Bug
## Description

Plugin commands start with a $ which is copied when using the `copy` button. We should remove the $ from the command.

## Checklist
- [ x] I checked on the latest version of Hydra
- [ x] I created a minimal repro

## To reproduce

https://hydra.cc/docs/next/plugins/ax_sweeper - try the copy button to copy the installation command

Happens for most other plugins as well.

## System information
NA

## Additional context
NA

**Comment by omry** [comment]
Reading the title of your issue left me scratching my head for a minute trying to understand what plugins commands are referring to and what copy button there is in Hydra.

Documentation is sometimes showing the output of the shell. in those cases I think it makes sense to include a $ to make it clear that this is happening in the shell.
Specifically a pip install command is just a command the user should copy and we can definitely omit the $ there.
