### ISSUE TITLE
passing config file to a class initialization

### ISSUE THREAD

**Issue by a-z-e-r-i-l-a** [facebookresearch/hydra#847]
I would like to pass a config file to a class and so far tried this:

```
class SomeClass(object):

    @hydra.main(config_path=config.yaml, strict=True)
    def __init__(self, args):
        self.args = args

    def func():

if __name__ == "__main__":
    L = SomeClass()
    L.func()
```

However this gives the error:` TypeError: decorated_main() takes 0 positional arguments but 1 was given`. Is there a different way that I can do this?

**Comment by omry** [comment]
This is not how you use @hydra.main().
If this works, it's completely by accident.

Please use it as documented in the [basic tutorial](https://hydra.cc/docs/next/tutorials/basic/your_first_app/config_file) (and use Hydra 1.0).

You are free to pass the cfg object (or any sub node to your class once you have it:
```python
calss SomeClass:
  def init(self, cfg):
    ...

@hydra.main(config_name="config")
def main(cfg):
  SomeClass(cfg)
```
