### ISSUE TITLE
[Bug] Local submitit launcher can't fetch JobEnvironment

### ISSUE THREAD

**Issue by calebho** [facebookresearch/hydra#849]
# 🐛 Bug
## Description
Calling `submitit.JobEnvironment()` raises an exception with `hydra/launcher=submitit_local`

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce

Directory structure:
```
.
├── foo.py
└── foo.yaml
```
Contents:
```yaml
defaults:
  - hydra/launcher: submitit_local
```
```python
import hydra
import submitit


@hydra.main(config_name="foo")
def main(cfg):
    submitit.JobEnvironment()


if __name__ == "__main__":
    main()
```

** Stack trace/error message **
```
$ HYDRA_FULL_ERROR=1 python foo.py
Traceback (most recent call last):
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/_internal/utils.py", line 336, in <lambda>
    overrides=args.overrides,
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 109, in run
    job_subdir_key=None,
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/hydra/core/utils.py", line 123, in run_job
    ret.return_value = task_function(task_cfg)
  File "foo.py", line 7, in main
    submitit.JobEnvironment()
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/submitit/core/job_environment.py", line 37, in __new__
    return plugins.get_job_environment()
  File "/private/home/calebh/miniconda3/envs/bench-detectron2/lib/python3.7/site-packages/submitit/core/plugins.py", line 82, in get_job_environment
    f"Could not figure out which environment the job is runnning in. Known environments: {', '.join(envs.keys())}."
RuntimeError: Could not figure out which environment the job is runnning in. Known environments: slurm, local, debug.
```

## Expected Behavior
Should not throw

## System information
- **Hydra Version** : 
    ```
    $ pip list | grep hydra
    hydra-core              1.0.0rc2
    hydra-submitit-launcher 1.0.0rc4
    ```
- **Python version** : 3.7.7
- **Virtual environment type and version** : conda 4.8.3 
- **Operating system** : Ubuntu 18.04.3

**Comment by omry** [comment]
cc @jrapin.

Looks like we forgot to test submitit_local ?

**Comment by jrapin** [comment]
Actually local works fine (just added a test to make sure the example works, but local is what was tested all the time since we cannot test on slurm...), but there is something weird somewhere:
in this example, with `python foo.py` it seems submitit launcher is not picked up. However if you run `python foo.py -m` it works just fine. Is there any reason for it?
Once this is clearer, we need to update the doc accordingly

**Comment by omry** [comment]
Ah yes. Launchers are only used in multirun.

I am thinking about allowing launchers in regular runs as well, but it will not happen in Hydra1.0.

**Comment by jrapin** [comment]
in the meantime could it raise an error then if not using multirun?

**Comment by omry** [comment]
Raise an error when a user user Hydra without multirun?

**Comment by omry** [comment]
@calebho , mind sharing what you are trying to get out the JobEnvironment?
by accessing it from the code you add a hard dependency on Submitit, which will make it harder to switch to other launchers.

**Comment by calebho** [comment]
Yeah I'm trying to get the number of GPUs I requested since I'm using Hydra to wrap another CLI which takes the number of GPUs per node as an option. I was hacking around, so I know I can work around this by putting that in my config and using interpolation to set the value in the launcher parameters

**Comment by omry** [comment]
taking this to an offline chat.

**Comment by GUIMINLONG** [comment]
I also have this problem ? how can I avoid this

**Comment by GUIMINLONG** [comment]
Any one have sugesstion on how to solve this problem? I also have this problem when try to reproduce a project, but have no idea about how solve it.
Thanks

**Comment by odelalleau** [comment]
> Any one have sugesstion on how to solve this problem? I also have this problem when try to reproduce a project, but have no idea about how solve it. Thanks

Are you enabling multirun with `-m`?

**Comment by GUIMINLONG** [comment]
> 



> > Any one have sugesstion on how to solve this problem? I also have this problem when try to reproduce a project, but have no idea about how solve it. Thanks
> 
> Are you enabling multirun with `-m`?

Thanks for your help. It was solved.  Its my first time use hydra.   
Very appreciate
