### ISSUE TITLE
[Submitit]: Setting environment variables from launcher 

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#853]
# 🚀 Feature Request

It would be nice to be able to set environment variables from Submitit launcher.

Right now it's possible (but a bit hacky) in submitit (https://github.com/facebookincubator/submitit/issues/10) but I think it should also be possible from the launcher. The simplest way would be to add a parameter `setup` for slurm launcher.

Usecase: I'm training pytorch models using a distributed backend and need to set the flag "NCCL_DEBUG=INFO" to see actual errors in the code rather than NCCL errors.

@jrapin

**Comment by omry** [comment]
Can you explain what environment variables you want to set and what do you mean by "from the Submitit launcher"?
did you see [env_set](https://hydra.cc/docs/next/configure_hydra/job#hydrajobenv_set)?

**Comment by YannDubs** [comment]
`env_set` seems to be what I was looking for. There's no reason I was saying "from the submitit launcher", I just didn't know you could do it directly from hydra!

Thanks

**Comment by omry** [comment]
Great :)
