### ISSUE TITLE
[Bug] Cannot add a value to hydra.job.set_env from the command line.

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#854]
# 🐛 Bug
## Description
I cannot add a append a config value for the hydra configuration (hydra installed from source)

## To reproduce

**Minimal Code/Config snippet to reproduce**

```
python main.py +hydra.job.env_set.WANDB_NOTES="X"
```

**Stack trace/error message**
```
Error merging override +hydra.job.env_set.WANDB_NOTES="X"
Key 'WANDB_NOTES' is not in struct
	full_key: hydra.job.env_set.WANDB_NOTES
	reference_type=Dict[str, str]
	object_type=dict
```

## Additional context
- I don't have the issue with `+` on non hydra config
- if I add `hydra.job.env_set.WANDB_NOTES=""` in the config then I can correctly override the value (without `+`)

## System information
- **Hydra Version** :  1.0.0rc2
- **Python version** : 3.8.5
- **Operating system** : Ubuntu 18.04.3 LTS

**Comment by omry** [comment]
Thanks for reporting. for now set it in your config.
