### ISSUE TITLE
Evaluating possibility of call/instantiate based parameters of target

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#855]
This can use logic similar to Functions.eval()

**Comment by shagunsodhani** [comment]
Didnt understand it :) Could you explain a bit

**Comment by omry** [comment]
It's a bit early to explain, this is a reminder for me to look at this. post 1.0.
Take a look at #825.

**Comment by omry** [comment]
Will revisit later. Definitely not for 1.1.
