### ISSUE TITLE
[Bug] autocompletion is not working if PATH environment has `.` in the list

### ISSUE THREAD

**Issue by thoth291** [facebookresearch/hydra#858]
# 🐛 Bug
## Description
Basically when you install it for that terminal it is not working.
So I did comparison with my MacOS installation (all the same versions of hydra and stuff) and got that the difference in behavior comes from `command` tool.
Here is how it reacts on working side (on my mac):
```shell
$ command -v python simple.py
/path/to/bin/python
```
And how it reacts in CentOS:
```shell
$ command -v python simple.py
/path/to/bin/python
./simple.py
```
## Expected Behavior
I was able to fix it by replacing this in the autocompletion installation script:
```bash
 if ! [ -x "$(command -v $helper)" ]; then
        false
 fi
```
to this one:
```bash
cmd=($(command -v $helper))
if ! [ -x "${cmd[0]}" ]; then
        false
fi
```

## System information
- **Hydra Version** :  1.0.0rc3
- **Python version** : 3.8.3
- **Virtual environment type and version** : conda, 4.8.3
- **Operating system** : CentOS7
- **Bash Version** : 4.2.46(2)

**Comment by omry** [comment]
Can you address this question at KDE?

**Comment by thoth291** [comment]
@omry , I've tried all possible versions of centos I had access to (from 7.x-8.x) - they all was behaving as your script would expect. I need to dig dipper to see what exactly going on in our systems - it might be some discrepancy between builtin tools. I'll check with systems team and will come back to you.
Thanks!

**Comment by omry** [comment]
Thanks for digging.

**Comment by thoth291** [comment]
@omry , I tracked it down to 2 possible workarounds.
In some systems when you have "." in the PATH - it will interpret your second argument as yet another executable and will report it - that's why I'm getting 2 lines.
But if I use system-wide (not shell-wide) command: return of `which command` - then my experience is regular and not depends on PATH having `.`.
I discussed it with some systems people and they told me that some other clusters in national labs will have the say issue - since their setup is similar to ours.
So I would suggest to change bash autocompletion script using the setup mentioned above or using this method:
```bash
COMMAND=$(which command)
if ! [ -x "$($COMMAND -v $helper)" ]; then
     false
fi
```
It should fix the issue and make it working for everyone regardless of their system settings.

**Comment by omry** [comment]
Nice find.
Feel free put up a pull request. Try to include tests that are testing for this scenario.

**Comment by thoth291** [comment]
```
Try to include tests that are testing for this scenario.
```
That won't be possible on other than CentOS, I guess... But I will try.
**Which solution do you prefer?**, @omry .
My last one gives an extra call to do - `which` -  that should not be terribly slower, but it's still an extra call.

**Comment by omry** [comment]
Looks like it has nothing to do with Centos:

```
omry@Coronadev:~/dev/hydra$ lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
omry@Coronadev:~/dev/hydra$ export PATH=.:$PATH
omry@Coronadev:~/dev/hydra$ command -v python setup.py 
/home/omry/miniconda3/envs/hydra38/bin/python
./setup.py
```

> Which solution do you prefer?

I see only one solution proposed. which are the two solutions?

**Comment by thoth291** [comment]
```bash
cmd=($(command -v $helper))
if ! [ -x "${cmd[0]}" ]; then
        false
fi
```

**Comment by omry** [comment]
I still see only one solution propsed.

**Comment by thoth291** [comment]
I guess I was not clear enough.
One in the description:
```bash
cmd=($(command -v $helper))
if ! [ -x "${cmd[0]}" ]; then
        false
fi
```
And one over here: https://github.com/facebookresearch/hydra/issues/858#issuecomment-672097063
```bash
COMMAND=$(which command)
if ! [ -x "$($COMMAND -v $helper)" ]; then
     false
fi
```

**Comment by omry** [comment]
The second one looks cleaner, but without tests I have no idea if they are equal.

**Comment by thoth291** [comment]
There are equal and the tests (of their equality) are outside of the scope of Hydra, I guess. So I can see if I will be able to push some code - this is really 2-lines change of code PR - small but powerfull.
Please note that the second solution will do an extra system call - which might slow down autocompletion for a few microseconds.

**Comment by thoth291** [comment]
I just found out that when path has `.` and your python script is executable (`chmod +x simple.py`) then even using system command will not help you to avoid issues - so I will go with the first solution - interpreting return as an array and grab the first element of it.

**Comment by omry** [comment]
sounds good.
