### ISSUE TITLE
Update the Ax Plugin to use the new OverridesParser 

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#870]
Followup for #752.
Hydra 1.0.0rc3 introduces new command line grammar that supports advanced sweeprs.
You can read about it [here](https://hydra.cc/docs/next/advanced/override_grammar/extended).

The Ax sweeper should use hydra.core.override_parser.overrides_parser.OverridesParser to parse the command line to take advantage of new grammar.

You can see simple usage example in the [Example Sweeper Plugin ](https://github.com/facebookresearch/hydra/blob/master/plugins/examples/example_sweeper_plugin/hydra_plugins/example_sweeper_plugin/example_sweeper.py#L73-L94) and in the [Basic Sweeper Plugin](https://github.com/facebookresearch/hydra/blob/master/hydra/_internal/core_plugins/basic_sweeper.py#L107-L121).

**Comment by shagunsodhani** [comment]
I can take it up :)

**Comment by shagunsodhani** [comment]
Closed in https://github.com/facebookresearch/hydra/commit/108af1aec8ef86d752f46ec4c5542ee64fd80412
