### ISSUE TITLE
Update the Nevergrad Plugin to use the new OverridesParser 

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#871]
Followup for #752.
Hydra 1.0.0rc3 introduces new command line grammar that supports advanced sweeprs.
You can read about it [here](http://localhost:3000/docs/next/advanced/override_grammar/extended).

The Nevergrad Sweeper should use hydra.core.override_parser.overrides_parser.OverridesParser to parse the command line to take advantage of new grammar.

You can see simple usage example in the [Example Sweeper Plugin ](https://github.com/facebookresearch/hydra/blob/master/plugins/examples/example_sweeper_plugin/hydra_plugins/example_sweeper_plugin/example_sweeper.py#L73-L94) and in the [Basic Sweeper Plugin](https://github.com/facebookresearch/hydra/blob/master/hydra/_internal/core_plugins/basic_sweeper.py#L107-L121).

**Comment by omry** [comment]
cc @shagunsodhani , @jrapin , @jieru-hu : Anyone wants this one?

**Comment by jieru-hu** [comment]
> cc @shagunsodhani , @jrapin , @jieru-hu : Anyone wants this one?

i'll take this :)

**Comment by omry** [comment]
Not blocking Hydra 1.0

**Comment by jieru-hu** [comment]
the plugin is released, closing :)
