### ISSUE TITLE
command line is incorrectly removing whitespace in primitives

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#873]
```commandline
$ python foo.py "+x=a b c"
```
results in:
```yaml
x: abc
```

because the grammar is ignoring whitespace outside of quoted strings and there is a concatenation phase for primitives.

**Comment by omry** [comment]
cc @odelalleau

**Comment by odelalleau** [comment]
I'll take it

**Comment by omry** [comment]
can you assign to yourself?

**Comment by odelalleau** [comment]
> can you assign to yourself?

No, looks like I don't have permission for that

**Comment by shagunsodhani** [comment]
@odelalleau needs to be added to the repo. I dont recall the procedure for this but had the same problem when I started working on Hydra.
