### ISSUE TITLE
[Bug]: Nevergrad sweeper does not work with integers if there are less than 6 choices

### ISSUE THREAD

**Issue by YannDubs** [facebookresearch/hydra#881]
Nevergrad sweeper complains if it has less than 6 values to sweep over in a range (e.g. `lower: 1` `upper:3`) and asks to use a list instead (`ValueError: For integers with 6 or fewer values, use a choice instead`). But if you use a list with integers it does not work because it assumes that choices contain only strings:

![Screen Shot 2020-08-15 at 7 42 39 PM](https://user-images.githubusercontent.com/24327668/90323444-84a3b680-df2f-11ea-8d77-1ce82ab9c7c6.png)

Line where the first error is raised: https://github.com/facebookresearch/hydra/blob/0e001afb2a55275b6f7dc33e79035dbf3a797c00/plugins/hydra_nevergrad_sweeper/hydra_plugins/hydra_nevergrad_sweeper/core.py#L178
Hydra Version: 1.0.0rc2

Of course I can give a string and then convert in my code, but it would probably be better to solve it differently? For example sliently treating it as a list without raising the first error ? Or at least to say in the raised error that you have to use a list and convert the str to int in your own code ? Not sure what is the best way..

**Comment by omry** [comment]
This is going to be changed dramatically soon anyway.
we will be sure to test this case when we change it.
Take a look at the [Extended grammar syntax for a sneak preview](https://hydra.cc/docs/next/advanced/override_grammar/extended

cc @shagunsodhani

**Comment by omry** [comment]
@YannDubs, please provide a minimal repo.
