### ISSUE TITLE
[Bug] trying to use the mandatory attribute according to tutorial

### ISSUE THREAD

**Issue by Alexfinkelshtein** [facebookresearch/hydra#895]
# 🐛 Bug
Hi, thanks for Hydra, seem like a perfect solution for me from reading the docs. especially the instance features

I'm trying to run some basic stuff to get familiar with Hydra, and when I'm trying to use the MISSING required attribute it crashes.

## Checklist
- [x] I checked on the latest version of Hydra (the recommended one from the README)

- [x] I created a minimal repro

It is demonstrated in the following notebook:

https://colab.research.google.com/drive/1fsWCyEiZCntZarBjcc8VUgYG14C6K0DT?usp=sharing

** Stack trace/error message **
```
RecursionError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/omegaconf/dictconfig.py in __getattr__(self, key)
    294 
--> 295             return self._get_impl(key=key, default_value=DEFAULT_VALUE_MARKER)
    296         except Exception as e:

1438 frames
RecursionError: maximum recursion depth exceeded

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
KeyError: '_content'
```

## Expected Behavior
creating an instance

## System information
- **Hydra Version** :  1.0
- **Python version** : COLAB
- **Virtual environment type and version** :  COLAB
- **Operating system** : COLAB

**Comment by omry** [comment]
Please open your collab privacy.

**Comment by Alexfinkelshtein** [comment]
thanks!
1. my bad.. I think it would be helpful if imports are added as a context for the docs
2. in my use case I will be mainly instantiating them myself.. is there a fundamental reason it would be wrong? or just less optimized by design for this use case 
3. I am not sure with respect to what you mentioned this
4. isn't it used in the docs examples?

thanks again!
