### ISSUE TITLE
[Ax-Plugin] Switch back to the usage of "." in place of "_"

### ISSUE THREAD

**Issue by shagunsodhani** [facebookresearch/hydra#913]
> > I abandoned the idea of compact keys in OmegaConf. This is a good chance to switch back to the more intuitive usage of dot and not _ to separate the path element in keys:
> > ```yaml
> >       params:
> >         banana.x:
> >           type: range
> >           bounds: [-5, 5]
> > ```

_Originally posted by @omry in https://github.com/facebookresearch/hydra/pull/912#issuecomment-679236669_

**Comment by omry** [comment]
Not blocking Hydra 1.0.

**Comment by deethereal** [comment]
Hello! How can I override `banana.x` through CLI? hydra returns me `Could not override 'params.banana.x' .Key 'banana' is not in struct`

**Comment by omry** [comment]
banana.x=10

**Comment by deethereal** [comment]
That will raise `KeyError banana`

**Comment by omry** [comment]
No. The config should contain a banana.x field, and it [does](https://github.com/facebookresearch/hydra/blob/main/plugins/hydra_ax_sweeper/example/conf/config.yaml#L6-L9).

**Comment by deethereal** [comment]
I think I misunderstand the example. Is it possible to have a key with name, contains ".". For example it is common practice for confluent_kafka package. Is it possible to override such key?
For example, if I have a following config:
```yaml
params:
  a: 10
  b: 12
  c.x: abc
  ```
I can not override it with `python main.py params.c.x=aaa`
It raise              
```
Could not override 'params.c.x'.
To append to your config use +params.c.x=aaa
Key 'c' is not in struct
    full_key: params.c
    object_type=dict
```

**Comment by omry** [comment]
No, this is not supported.
Hydra interprets `.` as a key separator. there is no mechanism to change this behavior.

**Comment by deethereal** [comment]
Thanks for your answer!
