### ISSUE TITLE
[Bug] AttributeError: module 'hydra' has no attribute 'main'

### ISSUE THREAD

**Issue by paantya** [facebookresearch/hydra#919]
# 🐛 Bug
## Description
AttributeError: module 'hydra' has no attribute 'main'

## Checklist
- [x] I checked on the latest version of Hydra
- [x] I created a minimal repro

## To reproduce

```
import hydra
from omegaconf import DictConfig

@hydra.main(config_path="config", config_name="config", strict=False)
def run(cfg: DictConfig) -> None:
    print(cfg)

if __name__ == '__main__':
    run()
```

```
    @hydra.main(config_path="config", config_name="config", strict=False)
AttributeError: module 'hydra' has no attribute 'main'
```

## Expected Behavior
Just works

## System information
Hydra: hydra-core-1.0.0rc4
OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: 9.1.85
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.0
[conda] Could not collect

**Comment by omry** [comment]
you already opened one issue about this. you probably did not install correctly. let's keep the discussion on the other issue.

**Comment by hforharsh** [comment]
This error still exist post reinstallation, is there a resolution for this.

**Comment by omry** [comment]
Yes. install Hydra per the instructions in the website, instead of taking a guess at `pip install hydra`.

**Comment by natoucs-datagen** [comment]
Currently having this issue [while running the vanilla example](https://hydra.cc/docs/tutorials/basic/your_first_app/simple_cli) although I did install `hydra-core` (1.0.5) and not `hydra`.
macOS Mojave.

**Comment by omry** [comment]
Please file a new issue with exact repro instructions, including a new conda or virtualenv environment.

**Comment by engrmz** [comment]
> Yes. install Hydra per the instructions in the website, instead of taking a guess at `pip install hydra`.

I had the same problem, I solved it by reinstalling hydra using the command (link. [click](https://pypi.org/project/hydra-core/))
`pip install hydra-core --upgrade`
