### ISSUE TITLE
Overwrite string containing equal signs from command line

### ISSUE THREAD

**Issue by skmatz** [facebookresearch/hydra#938]
# 🚀 Feature Request

Allow overwriting string containing equal signs from the command line.

## Motivation

Currently, we will get an error when trying to overwrite a value from the command line as follows.

```sh
> python main.py foo.bar="baz=qux"

See https://hydra.cc/docs/next/advanced/override_grammar/basic for details
```

## Pitch

I don't know the specifics, but it may be possible to deal with it by updating the parser.

**Are you willing to open a pull request?** (See [CONTRIBUTING](../../CONTRIBUTING.md))

I'm sorry, but I can't do it now.

**Comment by omry** [comment]
Your shell is intercepting the `=`:

try this:
```
python main.py 'foo.bar="baz=qux"'
```

Read about working with your shell [here](https://hydra.cc/docs/advanced/override_grammar/basic#working-with-your-shell).
