### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Chizkiyahu** [facebookresearch/hydra#949]
# 🐛 Bug
## Description
When I try to open the Hydra in Jupyter Notebooks with Binder and get error **404** 

## To reproduce
go to [hydra/examples/jupyter_notebooks/](https://github.com/facebookresearch/hydra/tree/e46b09b888df23eee6a84180659d8ae591d34bde/examples/jupyter_notebooks#jupyter-notebooks) and click the Binder button 

```
404 : Not Found
You are requesting a page that does not exist!

```

## Expected Behavior
the page open with no errors 

## Additional context
the [link](https://mybinder.org/v2/gh/facebookresearch/hydra/e46b09b888df23eee6a84180659d8ae591d34bde) working but is open the root git folder  and not specific file [hydra/examples/jupyter_notebooks/compose_configs_in_notebook.ipynb](https://github.com/facebookresearch/hydra/blob/master/examples/jupyter_notebooks/compose_configs_in_notebook.ipynb)

**Comment by omry** [comment]
Thanks for reporting, I corrected the link. please try again.

**Comment by Chizkiyahu** [comment]
the new link not working (try in Incognito mode)
the correct link is https://mybinder.org/v2/gh/facebookresearch/hydra/master?filepath=examples%2Fjupyter_notebooks%2Fcompose_configs_in_notebook.ipynb

**Comment by omry** [comment]
oops.
