### ISSUE TITLE
Add jinja2 to requirements for configen

### ISSUE THREAD

**Issue by romesco** [facebookresearch/hydra#960]
## System information
- **Hydra Version** :  master
- **Python version** : 3.8
- **Virtual environment type and version** : conda w/ pip
- **Operating system** : 16.0.4

**Comment by omry** [comment]
configen got it's own setup.py and it has jinja.

**Comment by omry** [comment]
Until it's ready and published, the plan is that you install it from the Hydra repo with `pip install tools/configen`.

**Comment by romesco** [comment]
👍
