### ISSUE TITLE
[Bug] Cannot use overrides containing '%' character

### ISSUE THREAD

**Issue by another-pjohnson** [facebookresearch/hydra#962]
# 🐛 Bug
## Description
I am unable to override a value that contains the '%' character without doing special quoting around the override

## To reproduce

```
import hydra

@hydra.main()
def foo(*args, **kargs):
    pass

foo()
```

** Minimal Code/Config snippet to reproduce **
```
python test.py +bar=/path/to/pattern_%r.bin
```

** Stack trace/error message **
```
LexerNoViableAltException: +bar=/path/to/pattern_%r.bin
                                                 ^
See https://hydra.cc/docs/next/advanced/override_grammar/basic for details

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

## Expected Behavior
bar's value should be set to "/path/to/pattern_%r.bin".

## System information
- **Hydra Version** :  1.0.0
- **Python version** : 3.7.7
- **Virtual environment type and version** : 
- **Operating system** : 

## Additional context
Similar error to: Issue #798.

**Comment by omry** [comment]
Thanks for reporting, will take a look.

**Comment by pringshia** [comment]
Any plans on also allowing the `@` symbol?

```
 LexerNoViableAltException: mephisto.provider.requester_name=example@example.com
                                                                    ^
```

**Comment by omry** [comment]
There are no such plans, but if you file a but report I can look at it.

**Comment by pringshia** [comment]
> There are no such plans, but if you file a but report I can look at it.

Done here: #1074
