### ISSUE TITLE
Move deploy-website action from circleCI to github

### ISSUE THREAD

**Issue by jieru-hu** [facebookresearch/hydra#973]
## Motivation

We want to move our github token  back to github instead of saving it in circleCI.

## Action items
- [x] Create github action to deploy webiste in master first with the actual deployment part commented out first (just to make sure the github action run as expected) https://github.com/facebookresearch/hydra/pull/974/files
- [x] Create github token secret in github actions. 
- [x] Remove deploy-website step from CircleCI, enable it in github. #979
- [x] remove github token from circleCI

**Comment by jieru-hu** [comment]
closing. All todo items done.

**Comment by omry** [comment]
Good job :)
