### ISSUE TITLE
[Feature Request] @dataclass `__post_init__` for config validation

### ISSUE THREAD

**Issue by Jasha10** [facebookresearch/hydra#981]
# 🚀 Feature Request

The `__post_init__` hook called by the `__init__` function defined in `dataclasses` can be used for post-processing or validation of configuration information.

## Motivation

One possible use case for the `__post_init__` hook defined in [PEP 557 -- Data Classes](https://www.python.org/dev/peps/pep-0557/) is the validation of configuration data. Here is an example:
```
# post_init_example.py
from dataclasses import dataclass

@dataclass
class MySQLConfig:
    host: str = "localhost"
    port: int = 3306
    def __post_init__(self):
        assert 7000 < self.port < 99999

cfg = MySQLConfig()
```
When running this file, we get an assertion error because the port number is outside the allowable range:
```
jbss@rig1:~$ python post_init_example.py
Traceback (most recent call last):
  File "post_init_example.py", line 10, in <module>
    cfg = MySQLConfig()
  File "<string>", line 5, in __init__
  File "post_init_example.py", line 8, in __post_init__
    assert 7000 < self.port < 99999
AssertionError
```

However, when the `MySQLConfig` class is used in a `@hydra.main` app, the validation code from `__post_init__` does not get run:
```
# post_init_example2.py, adapted from Hydra docs
from dataclasses import dataclass

import hydra
from hydra.core.config_store import ConfigStore

@dataclass
class MySQLConfig:
    host: str = "localhost"
    port: int = 3306
    def __post_init__(self):
        assert 7000 < self.port < 99999

cs = ConfigStore.instance()
# Registering the Config class with the name 'config'.
cs.store(name="config", node=MySQLConfig)

@hydra.main(config_name="config")
def my_app(cfg: MySQLConfig) -> None:
    print(cfg)

if __name__ == "__main__":
    my_app()
```

```
jbss@rig1:~$ python post_init_example2.py
{'host': 'localhost', 'port': 3306}
```
No `AssertionError` was triggered. This may be unexpected behavior for users who are familiar with the normal behavior of the `@dataclass` decorator.
## Pitch

**Describe the solution you'd like**

In the type signature for the `my_app` function above, the type hint for the `cfg` argument is `MySQLConfig`, but at runtime the type of `cfg` is `omegaconf.dictconfig.DictConfig`. What if there were the option to have hydra return a bona fide instance of `MySQLConfig`, so that `assert isinstance(cfg, MySQLConfig)` is true within the body of the `my_app` function? If the option were available to work with instances of the user-defined dataclass, rather than instances of `DictConfig`, clients could make use of methods defined on their custom config dataclass, including but not limited to the `__post_init__` method that is automatically called upon dataclass initialization.

**Describe alternatives you've considered**

1) One alternative is to use keyword expansion to convert the parsed `DictConfig` object into a `MySQLConfig` object:

        cfg = MySQLConfig(**cfg)  # convert DictConfig -> MySQLConfig

    This **does not** play well with nested config structures, e.g. if `MySQLConfig` has a field that is another (different) dataclass.

2) Another alternative is to employ the [dacite](https://github.com/konradhalas/dacite) library to convert the `DictConfig` object into an instance of `MySQLConfig`: after calling `import dacite` and `import omegaconf`, the following definition of `my_app` can be used to achieve the desired effect:

        @hydra.main(config_name="config")
        def my_app(cfg0: omegaconf.DictConfig) -> None:
            cfg1: typing.Dict = omegaconf.OmegaConf.to_container(cfg0)
            cfg2: MySQLConfig = dacite.from_dict(data_class=MySQLConfig, data=cfg1)
            ...

    The `MySQLConfig.__init__` and `MySQLConfig.__post_init__` functions get called when `dacite.from_dict` creates the `MySQLConfig` instance. To be clear, this alternative involves a three-step procedure: (1) use hydra to parse the `DictConfig` object, (2) use omegaconf's `to_container` to get a native python container, and (3) use `dacite` to parse the python container as a `MySQLConfig` instance. This alternative **does** work with nested dataclass structures; it is the solution that I am using currently.

3) Of course, there are other packages besides hydra for parsing configuration/settings directly into a dataclass, e.g. [argparse-dataclasses](https://pypi.org/project/argparse-dataclasses/0.1.3/) or the [SimpleParsing](https://github.com/lebrice/SimpleParsing) package. Would be nice if hydra supported this feature though.

**Are you willing to open a pull request?**
I think some brainstorming would be required regarding the API for this feature. How would the user indicate whether they want a `DictConfig` or a `MySQLConfig` object? Perhaps a keyword argument could be exposed by the `@hydra.main` decorator or by the `hydra.core.config_store.ConfigStore` class? There are some edge cases to consider too, such as how to handle cases of mixed config (e.g. yaml config mixed with dataclasses). 

At this point the `hydra` project seems fairly tightly coupled to the `omegaconf` project. I'm not sure how easy it would be to implement this feature or where to start. The `dacite` solution mentioned above continues to be useful. Nevertheless, I am creating this issue to share the idea with others...

**Comment by omry** [comment]
Thanks for the thoughtful feature request @Jasha10.
This feature request should be against OmegaConf and not Hydra, but I can respond here.

`__post_init__` depends on Structured Configs method support in OmegaConf. Currently methods are not supported and it's something I will consider for a later OmegaConf version.

The use cases you are describing will be addressed by omegaconf#131.
post_init method feels a bit too powerful for my liking, it allows raising of unexpected exceptions and also potentially changing the object in breaking ways.
Another thing here is that the self for such a method would not be the dataclass instance but the DictConfig instance, which in turn means this is not really a normal post_init (although for most purposes it can written normally).

Please file this against OmegaConf, I will consider this if and when method support is added to it.

If you want to chat about feel free to join the Hydra chat.

**Comment by OhadRubin** [comment]
Hey, since OmegaConf added this feature, this can be added to hydra now.

**Comment by Jasha10** [comment]
Hi @OhadRubin,
This is now implemented on the OmegaConf side by the [`OmegaConf.to_object`](https://omegaconf.readthedocs.io/en/latest/usage.html#omegaconf-to-object) method.
On the hydra side, usage would look something like this:
```python
@hydra.main(...)
def app(_cfg: DictConfig):
    cfg: MyDataclass = OmegaConf.to_object(_cfg)  # turn DictConfig into dataclass instance, causing `MyDataclass.__post_init__` to be run
    ...
```

**Comment by OhadRubin** [comment]
Yeah that's what I did, but I think it's reasonable to assume that if someone is using dataclass as a config, then that person would assume __post_init__ would be triggered without this workaround.

**Comment by Jasha10** [comment]
One might assume that, but it's not the case :)
When hydra creates a structured config, no dataclass is instantiated. You have to instantiate it yourself using `to_object` if you want to use the dataclass methods.

**Comment by OhadRubin** [comment]
No, but what I'm saying is maybe it's worthwhile to add this to the documentation.

**Comment by Jasha10** [comment]
Aah yes, good idea.

**Comment by ramshi236** [comment]
here is my implementation for incorporating the post_init method while preserving the schema validation that hydra offers  :


```python
from dataclasses import dataclass, fields, MISSING
from typing import List, Optional, Dict, Callable, Union
from functools import partial, wraps
import hydra
from hydra.core.config_store import ConfigStore

from hydra import initialize, compose
from omegaconf import DictConfig, OmegaConf, SCMode
from fastcore.meta import delegates
import dacite


def _invoke_post_init(node_obj, cfg: DictConfig) -> DictConfig:
    """
    if the cfg dataclass have a __post_init__ method then:
        - first, we convert the DictConfig object to a python dict
        - second, we're using the dacite from_dict() function that fill a dataclass object (node_obj) 
                with kwargs from the python dict
        - last, we convert the dataclass object to a DictConfig object (we have to return a DictConfig object 
                because of the hydra.main decorator)
    Args:
        node_obj:the dataclass object to call __post_init__ method
        cfg: the loaded dictConfig object

    Returns: DictConfig

    """
    cfg_dict: Dict = OmegaConf.to_container(cfg)
    cfg_obj: node_obj = dacite.from_dict(data_class=node_obj, data=cfg_dict)
    cfg_dict_config: DictConfig = OmegaConf.create(cfg_obj)
    return cfg_dict_config


def _decorator_with_args(node_obj, node_obj_base_name: Optional[str] = None, invoke_post_init: bool = True) -> Callable:
    """
    single purpose decorator that adds logic encapsulated in my_logic function, calling it with DictConfig, 
        before the hydra.main decorator function.
    Args:
        node_obj: the dataclass object which validate the schema of the loaded DictConfig
        node_obj_base_name: Optional string to register the base name of the node_obj 
            (this name should be in the yaml file under default)
        invoke_post_init: boolean that issues the post-init object method on the frash loaded cfg DictConfig object
    Returns: A function that process the cfg DictConfig before the hydra.main decorator
    """

    def _mydecorator(func: Callable) -> Callable:
        # inspiration : https://github.com/facebookresearch/hydra/issues/981
        @wraps(func)
        def my_logic(cfg: DictConfig):

            if node_obj_base_name is not None:
                cs = ConfigStore.instance()
                cs.store(name=node_obj_base_name, node=node_obj)

            if invoke_post_init and hasattr(node_obj, "__post_init__"):
                cfg = _invoke_post_init(node_obj=node_obj, cfg=cfg)

            assert isinstance(cfg, DictConfig), "the logic in my_logic have to return DictConfig only"

            return func(cfg)  # pass cfg to decorated function

        return my_logic

    return _mydecorator


def hydra_call_main(node_obj, node_obj_base_name=Optional[str], invoke_post_init: bool = True,
                    config_path: Optional[str] = None, config_name: Optional[str] = None, **kwargs):
    """
    decorator function composed with _decorator_with_args logic and arguments and the hydra main function (in that order)
    Args:
        node_obj: the dataclass object which validate the schema of the loaded DictConfig
        node_obj_base_name: string to register the base name of the node_obj 
            (this name should be in the yaml file under default),
         if not specified then the register_config will not be called and the DictConfig will not be validated
        invoke_post_init: boolean that issues the post-init object method on the frash loaded cfg DictConfig object
        config_path: The config path, a directory relative to the declaring python file.
                        If config_path is None no directory is added to the Config search path
        config_name: The name of the config (usually the file name without the .yaml extension)
    Returns: the decorated function
    """
    hydra_dec = hydra.main(config_path=config_path, config_name=config_name, **kwargs)
    my_dec = _decorator_with_args(node_obj=node_obj, node_obj_base_name=node_obj_base_name,
                                  invoke_post_init=invoke_post_init)

    def real_decorator(func):
        return hydra_dec(my_dec(func))

    return real_decorator

def load_cfg(yaml_cfg_name: str, config_path: str, node_obj,return_hydra_config:bool=False, invoke_post_init: bool = True
             , **kwargs_to_override_list) -> DictConfig:
    """
    Args:
        yaml_cfg_name: only the name of the yaml file without the *.yaml extension
        config_path: currently points to the config path for decorated function DictConfig
        node_obj: the dataclass object which validate the schema of the loaded DictConfig
        return_hydra_config: True to return the hydra config node in the result
        invoke_post_init: calling __post_init__ method for the cfg object
        hydra_override_list : hydra overide list in overwrite format see :https://hydra.cc/docs/1.0/advanced/override_grammar/basic/

    Returns: a DictConfig obj which is like a python dict but can access values like a class (dict_cfg["stam"]=dict_cfg.stam)

    """
    with initialize(version_base=None, config_path=config_path):
        cfg = compose(config_name=yaml_cfg_name,return_hydra_config=return_hydra_config,
                      overrides=hydra_override_list(node_obj=node_obj, **kwargs_to_override_list))
    if invoke_post_init:
        cfg = _invoke_post_init(node_obj=node_obj, cfg=cfg)
    return cfg




```



 a simple use case will be : 


```yaml
# valid_song.yaml
defaults:
  - song_base_class
  - _self_

song_name: Tribute
artist: Tenacious D
lyric: this_is_the_best_song_in_the_world

```
```python

@dataclass
class SongCfg:
    song_name: str = MISSING
    artist: str = MISSING
    lyric: str = "NEED TO PUT LYRICS"
    descriptor: Optional[str] = None

    def __post_init__(self):
        self.descriptor = f"song name : {self.song_name}'\n' artist : {self.artist}'\n' lyric : {self.lyric}"

@hydra_call_main(node_obj=SongCfg,node_obj_base_name="song_base_class",
                 version_base=None, config_path="../conf/example_config/songs/", config_name="valid_song")
def example_fused_decorator_function(cfg:DictConfig):
    cfg_dict = OmegaConf.to_container(cfg)
    print(cfg_dict["descriptor"])

conf_path = f"../conf/example_config/"
example_cfg = load_cfg("valid_song",conf_path,SongCfg)
example_fused_decorator_function(example_cfg)
# >>"song name : valid_song'\n' artist : this is a valid artist'\n' lyric : this is a valid lyric"
```

**Comment by BeeGass** [comment]
> One might assume that, but it's not the case :) When hydra creates a structured config, no dataclass is instantiated. You have to instantiate it yourself using `to_object` (or maybe `hydra.utils.instantiate`) if you want to use the methods, including the `__post_init__` method.
> 
> Do you have a use-case that makes it difficult to call `OmegaConf.to_object`?

Can I ask why this is not the case? This seems like a pretty obvious assumption to make. Perhaps there could be a flag set that allows for this behavior.
