### ISSUE TITLE
Instantiate: Support annotation of passthrough values

### ISSUE THREAD

**Issue by omry** [facebookresearch/hydra#982]
When instantiating PyTorch optimizers, the params cannot be a part of the configuration.
It is a tensor that is only available at runtime.
To enable instantiating of optimizers, instantiate supports passthrough:
```python
optimize = instantiate(cfg.optimizer, params=model.parameters())
```

Since it's not possible to annotate params as a Tensor in dataclasses used for Structured Configs, there is no way to declare that params is a required value.

The idea is to add support for marking such parameters as MISSING. if the type is incompatible the can be annotated as Any:
```python
@dataclass
class AdamConf:
  params: Any = MISSING
  lr: float = 1.0
```

**Comment by amansouri3476** [comment]
Can I ask for an example of how you define cfg.optimizer?
I've tried to achieve a similar thing but I'm having a hard time. I don't want to hardcode optimizer into my application code, so in my config file I have something like this:

```
optimizer:
       _target_: torch.optim.Adam
       lr: 0.001
```
And in my code I do 
```
optimize = instantiate(cfg.optimizer, params=model.parameters())
```
But it's not passed as positional argument and raises the error  `missing positional argument 'params'`.
Would it be possible that you share a minimal working example corresponding to your snippet above?

**Comment by Jasha10** [comment]
Hi @amansouri3476,

The following is working for me with the latest version of Hydra:
```python
# my_app.py
import hydra
from hydra.utils import instantiate
from torch import nn

model = nn.Linear(3, 3)

@hydra.main(config_path=".", config_name="config")
def app(cfg):
    print(cfg)
    print(instantiate(cfg.optimizer, params=model.parameters()))

if __name__ == "__main__":
    app()
```
# config.yaml
optimizer:
       _target_: torch.optim.Adam
       lr: 0.001
```yaml
```text
$ python my_app.py
{'optimizer': {'_target_': 'torch.optim.Adam', 'lr': 0.001}}
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0
)
```

If you want to use structured config, you can do it like this:
```python
# my_app.py
from dataclasses import dataclass
from typing import Any
from omegaconf import MISSING
import hydra
from hydra.core.config_store import ConfigStore
from hydra.utils import instantiate
from torch import nn

cs = ConfigStore.instance()

@dataclass
class OptimizerSchema:
    _target_: str = MISSING
    params: Any = MISSING
    lr: float = 0.001

cs.store(name="optimizer_schema", node=OptimizerSchema)

model = nn.Linear(3, 3)

@hydra.main(config_path=".", config_name="config")
def app(cfg):
    print(cfg)
    print(instantiate(cfg.optimizer, params=model.parameters()))

if __name__ == "__main__":
    app()
```
```yaml
# config.yaml
defaults:
  - optimizer_schema@optimizer
  - _self_

optimizer:
       _target_: torch.optim.Adam
```
```text
$ python my_app.py
{'optimizer': {'_target_': 'torch.optim.Adam', 'params': '???', 'lr': 0.001}}
Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.001
    weight_decay: 0
)
```

**Comment by amansouri3476** [comment]
Yes @Jasha10 thanks, I could make it work with this example as well. However, it's interesting that one cannot pass the params as a positional argument and they need to be named. I'm not sure why exactly is this so, but it's fine! Thank you, I can close the issue.
